INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('02487-603', '4307', 'F', 'SONIA MARIA MARTINEZ PENITENTE', '2014-09-18', 0, 'Kazakhstan', 'sonia.maria.martinez.penitente@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('83802-553', '6505', 'M', 'CLAUDIO BARBOSA DOS SANTOS', '2014-08-14', 1, 'Sierra Leone', 'claudio.barbosa.dos.santos@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('35683-575', '9445', 'M', 'DILMA DE SOUZA', '2014-09-15', 1, 'Brazil', 'dilma.de.souza@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('22191-220', '3869', 'F', 'JULIO APARECIDO DE SOUZA', '2014-11-27', 0, 'Chad', 'julio.aparecido.de.souza@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('55601-907', '4355', 'M', 'RAMIRO VEDOVATO', '2014-06-07', 0, 'Thailand', 'ramiro.vedovato@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('08194-273', '4450', 'M', 'OBADIAS MARCAL DE OLIVEIRA', '2014-08-24', 1, 'St. Kitts & Nevis', 'obadias.marcal.de.oliveira@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('69602-590', '6914', 'M', 'CLEODETE CANOLA DE CAMPOS', '2014-02-15', 0, 'Cape Verde', 'cleodete.canola.de.campos@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('58124-788', '2069', 'M', 'ANGELA APARECIDA BERNEGOZZE', '2014-01-19', 1, 'Serbia', 'angela.aparecida.bernegozze@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('91193-419', '4440', 'F', 'AUGUSTA ALVES DOS SANTOS', '2014-08-10', 1, 'Tunisia', 'augusta.alves.dos.santos@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('24350-411', '0375', 'M', 'CARLOS SERGIO URBANIN', '2014-05-03', 1, 'Kyrgyzstan', 'carlos.sergio.urbanin@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('82171-700', '1661', 'M', 'FRANCISCA MARIA SILVA COSTA', '2014-12-06', 1, 'Costa Rica', 'francisca.maria.silva.costa@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('63425-692', '4812', 'M', 'MARIA TEREZINHA ROCHA DE SOUZA', '2014-02-24', 0, 'Guatemala', 'maria.terezinha.rocha.de.souza@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('83972-292', '5574', 'F', 'GLAUBER DA COSTA ARRUDA', '2014-04-10', 0, 'Equatorial Guinea', 'glauber.da.costa.arruda@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('07989-598', '0232', 'M', 'PAULO TEIXEIRA DE ABREU', '2014-01-20', 1, 'Ukraine', 'paulo.teixeira.de.abreu@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('53097-885', '0275', 'F', 'HELOIZA ALMEIDA DOS SANTOS', '2014-02-22', 0, 'The Netherlands', 'heloiza.almeida.dos.santos@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('24140-909', '2668', 'F', 'MARIA DO CARMO JERONIMO SILVA', '2014-11-21', 0, 'Seychelles', 'maria.do.carmo.jeronimo.silva@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('04894-372', '7916', 'M', 'MARLENE SANTANA MARTINS', '2014-05-17', 0, 'Austria', 'marlene.santana.martins@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('37777-799', '6054', 'M', 'AUGUSTA ALVES DOS SANTOS', '2014-01-26', 1, 'Canada', 'augusta.alves.dos.santos@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('72989-093', '9409', 'F', 'ADAIL BANDINELLE DE MORAES', '2014-03-01', 1, 'Georgia', 'adail.bandinelle.de.moraes@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('95761-809', '7244', 'M', 'BENJAMIM GAUNA', '2014-03-06', 0, 'Fiji', 'benjamim.gauna@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('15375-008', '2293', 'F', 'LUIZ FERNANDO DA SILVA AMORIM', '2014-11-02', 1, 'Korea North', 'luiz.fernando.da.silva.amorim@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('97941-888', '6236', 'F', 'WILSON CONCEICAO DE MIRANDA', '2014-12-21', 0, 'Iraq', 'wilson.conceicao.de.miranda@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('84398-544', '1144', 'M', 'MARLENE SANTANA MARTINS', '2014-06-14', 0, 'Norway', 'marlene.santana.martins@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('17307-815', '5458', 'M', 'CLEODETE CANOLA DE CAMPOS', '2014-02-28', 1, 'Colombia', 'cleodete.canola.de.campos@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('15655-896', '0963', 'M', 'MARGARETH VIRGINIA DE REZENDE MEHLMANN', '2014-01-18', 1, 'Kenya', 'margareth.virginia.de.rezende.mehlmann@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('29982-936', '1861', 'M', 'ALICE FERNANDES DE OLIVEIRA', '2014-10-13', 1, 'Brunei', 'alice.fernandes.de.oliveira@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('28928-668', '7351', 'F', 'JOSE EVALDO DA SILVA', '2014-05-05', 1, 'France', 'jose.evaldo.da.silva@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('88079-043', '1350', 'F', 'ADENILTON JOSE DE MIRANDA', '2014-07-28', 1, 'United Arab Emirates', 'adenilton.jose.de.miranda@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('19178-540', '0076', 'M', 'LOURIVAL ROSA GUIMARAES', '2014-10-31', 1, 'Thailand', 'lourival.rosa.guimaraes@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('86050-857', '7296', 'M', 'JOANA ANTUNES', '2014-11-24', 1, 'Paraguay', 'joana.antunes@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('02336-932', '5988', 'F', 'MARIA HILDA MACHADO', '2014-04-20', 0, 'Portugal', 'maria.hilda.machado@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('62597-336', '5653', 'F', 'MARIA DAIANE DE ARAUJO SOUZA', '2014-02-05', 0, 'Korea South', 'maria.daiane.de.araujo.souza@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('91479-421', '8802', 'M', 'JOSE RIBAMAR BEZERRA SA', '2014-07-01', 0, 'Gabon', 'jose.ribamar.bezerra.sa@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('84959-431', '9413', 'M', 'ALCEU DOS SANTOS', '2014-05-08', 0, 'Indonesia', 'alceu.dos.santos@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('82512-569', '8792', 'F', 'JOANA ANTUNES', '2014-11-24', 1, 'Luxembourg', 'joana.antunes@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('59493-607', '2721', 'M', 'ELISABETE ROMERO NOBRE LEAL', '2014-11-13', 0, 'Latvia', 'elisabete.romero.nobre.leal@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('70311-534', '0202', 'F', 'JOSE RIBAMAR BEZERRA SA', '2014-03-24', 1, 'Bahamas', 'jose.ribamar.bezerra.sa@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('25729-656', '4376', 'F', 'JOSE RIBAMAR BEZERRA SA', '2014-09-22', 0, 'Georgia', 'jose.ribamar.bezerra.sa@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('48109-613', '7973', 'F', 'MIGUEL VENCESLAU MACIEL DE CAMPOS', '2014-05-06', 1, 'Marshall Islands', 'miguel.venceslau.maciel.de.campos@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('09005-510', '8856', 'F', 'WANDERSON COSMO DE ARAUJO', '2014-01-25', 0, 'Nauru', 'wanderson.cosmo.de.araujo@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('76900-389', '4564', 'M', 'ALIETE FRANCISCA PRATES', '2014-08-09', 1, 'Tanzania', 'aliete.francisca.prates@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('97991-671', '8693', 'M', 'ELISABETE ROMERO NOBRE LEAL', '2014-01-14', 0, 'Latvia', 'elisabete.romero.nobre.leal@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('49143-667', '4980', 'M', 'IROCIDES APARECIDA FERREIRA', '2014-06-30', 1, 'Norway', 'irocides.aparecida.ferreira@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('26043-764', '6302', 'M', 'ALICE FERNANDES DE OLIVEIRA', '2014-02-19', 0, 'Turkey', 'alice.fernandes.de.oliveira@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('24494-286', '0618', 'M', 'CORNELIO DIAS DUARTE', '2014-09-22', 1, 'Vatican City (Holy See)', 'cornelio.dias.duarte@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('67455-922', '6380', 'F', 'ALICE FERNANDES DE OLIVEIRA', '2014-11-21', 0, 'United Arab Emirates', 'alice.fernandes.de.oliveira@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('43623-064', '8712', 'M', 'JOAO MAURILIO DA SILVA', '2014-10-05', 1, 'Guinea', 'joao.maurilio.da.silva@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('74363-950', '8280', 'F', 'DILMA DE SOUZA', '2014-01-28', 1, 'Lesotho', 'dilma.de.souza@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('92731-992', '1875', 'F', 'LAURA SEBASTIANA GURGEL', '2014-09-03', 1, 'Mauritania', 'laura.sebastiana.gurgel@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('67798-190', '1742', 'M', 'HELIO SAMBATTI', '2014-07-16', 0, 'Greece', 'helio.sambatti@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('57398-236', '7887', 'F', 'ANTONIO INACIO RODRIGUES', '2014-06-27', 1, 'Liechtenstein', 'antonio.inacio.rodrigues@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('92342-472', '3363', 'F', 'ALDIVINA REIS FERNANDES', '2014-07-18', 1, 'Guatemala', 'aldivina.reis.fernandes@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('67074-377', '0081', 'M', 'MARIA DO CARMO JERONIMO SILVA', '2014-02-08', 1, 'France', 'maria.do.carmo.jeronimo.silva@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('28981-372', '1091', 'F', 'JOSE EVALDO DA SILVA', '2014-10-08', 1, 'Estonia', 'jose.evaldo.da.silva@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('31933-403', '8255', 'M', 'MARCONI GEORGE RIBEIRO DA SILVA', '2014-04-26', 1, 'Djibouti', 'marconi.george.ribeiro.da.silva@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('20418-864', '7900', 'M', 'ALCEU DOS SANTOS', '2014-07-22', 0, 'Japan', 'alceu.dos.santos@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('86442-388', '8801', 'F', 'MARIA TEREZINHA ROCHA DE SOUZA', '2014-12-02', 1, 'Egypt', 'maria.terezinha.rocha.de.souza@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('41264-520', '1251', 'F', 'SOLANGE APARECIDA DO PRADO DA CRUZ', '2014-06-19', 0, 'Bhutan', 'solange.aparecida.do.prado.da.cruz@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('56379-689', '1603', 'F', 'MARIA DAIANE DE ARAUJO SOUZA', '2014-02-28', 0, 'Lithuania', 'maria.daiane.de.araujo.souza@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('35172-446', '9148', 'F', 'CLEUSA FERREIRA MACIEL', '2014-12-27', 1, 'Angola', 'cleusa.ferreira.maciel@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('31332-336', '9749', 'F', 'QUITERIA LOURENCO DE LIMA', '2014-05-31', 0, 'Azerbaijan', 'quiteria.lourenco.de.lima@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('06596-267', '0033', 'M', 'OLGA PEREIRA', '2014-05-18', 1, 'Bhutan', 'olga.pereira@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('46141-100', '8925', 'M', 'BEATRIZ PEREIRA LIMA', '2014-11-09', 0, 'Antigua & Barbuda', 'beatriz.pereira.lima@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('03558-933', '1190', 'F', 'JUEL PRUDENCIO BORGES', '2014-12-07', 0, 'Haiti', 'juel.prudencio.borges@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('61590-141', '3227', 'M', 'SEBASTIANA BENEDITA DA COSTA', '2014-06-13', 0, 'Nauru', 'sebastiana.benedita.da.costa@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('90908-128', '8384', 'M', 'KLEBER MAGALHAES FERREIRA', '2014-11-29', 0, 'Israel', 'kleber.magalhaes.ferreira@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('71928-053', '0543', 'F', 'RITA IRACI ALMEIDA DA SILVA', '2014-10-19', 0, 'Mauritius', 'rita.iraci.almeida.da.silva@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('23349-428', '6742', 'M', 'MARILEIA NUNES DE OLIVEIRA', '2014-06-29', 1, 'Bulgaria', 'marileia.nunes.de.oliveira@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('42064-997', '5728', 'M', 'ALDEIR ALEX ALVES LIMA', '2014-03-11', 1, 'Honduras', 'aldeir.alex.alves.lima@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('56537-084', '5618', 'M', 'BENEDITO AMBROSIO DA COSTA', '2014-07-05', 0, 'Niger', 'benedito.ambrosio.da.costa@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('26687-376', '2670', 'F', 'MARCONI GEORGE RIBEIRO DA SILVA', '2014-03-05', 0, 'Haiti', 'marconi.george.ribeiro.da.silva@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('97642-438', '6952', 'M', 'ABIGAIL DA SILVA LARA', '2014-07-21', 1, 'Samoa', 'abigail.da.silva.lara@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('92311-464', '0976', 'F', 'ALBERTO FEIZAR CARDOSO ABDALA', '2014-10-11', 0, 'Ireland', 'alberto.feizar.cardoso.abdala@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('12857-417', '1454', 'M', 'DORILDA ALVES DE CARVALHO', '2014-03-16', 0, 'Egypt', 'dorilda.alves.de.carvalho@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('91811-319', '4713', 'F', 'ANA ALVES LUCIANO', '2014-08-20', 1, 'Thailand', 'ana.alves.luciano@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('84337-185', '5700', 'M', 'DAVINA PEREIRA DE SALES', '2014-05-17', 0, 'Taiwan', 'davina.pereira.de.sales@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('27805-574', '5547', 'F', 'VIOLINDO DE SOUZA', '2014-08-15', 1, 'San Marino', 'violindo.de.souza@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('88179-062', '6602', 'M', 'MARIA ELENA ALVES', '2014-10-02', 1, 'Nigeria', 'maria.elena.alves@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('44445-537', '2709', 'F', 'EDIR DIAS DE CARVALHO', '2014-03-20', 1, 'Czech Republic', 'edir.dias.de.carvalho@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('02480-681', '5317', 'F', 'MIGUEL VENCESLAU MACIEL DE CAMPOS', '2014-03-28', 0, 'Bosnia & Herzegovina', 'miguel.venceslau.maciel.de.campos@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('50375-077', '4491', 'M', 'WANDERSON COSMO DE ARAUJO', '2014-05-21', 1, 'Bosnia & Herzegovina', 'wanderson.cosmo.de.araujo@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('17225-500', '0432', 'F', 'MARIA DO CARMO JERONIMO SILVA', '2014-09-18', 0, 'Switzerland', 'maria.do.carmo.jeronimo.silva@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('96005-558', '4692', 'F', 'AURELINDA BATISTA DA SILVA', '2014-04-26', 0, 'Cyprus', 'aurelinda.batista.da.silva@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('99284-668', '7041', 'F', 'VIOLINDO DE SOUZA', '2014-04-02', 0, 'Slovakia', 'violindo.de.souza@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('84103-082', '3026', 'M', 'MARIA ELENA ALVES', '2014-08-10', 1, 'Italy', 'maria.elena.alves@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('50356-299', '0903', 'M', 'AURELINDA BATISTA DA SILVA', '2014-02-25', 0, 'Grenada', 'aurelinda.batista.da.silva@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('07763-287', '3023', 'M', 'EDIO JUSTO BORGES', '2014-12-25', 0, 'Oman', 'edio.justo.borges@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('11614-485', '5940', 'M', 'MARIA ALVES SUTIL', '2014-10-06', 1, 'Slovenia', 'maria.alves.sutil@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('22546-514', '2074', 'M', 'LAURA SEBASTIANA GURGEL', '2014-01-25', 0, 'Benin', 'laura.sebastiana.gurgel@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('36735-378', '7009', 'M', 'ELISABETE ROMERO NOBRE LEAL', '2014-01-04', 1, 'Iran', 'elisabete.romero.nobre.leal@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('45145-280', '6067', 'M', 'ELZA LIMA DE SOUZA MANSANO', '2014-06-30', 1, 'Guinea-Bissau', 'elza.lima.de.souza.mansano@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('63560-562', '1729', 'M', 'ATAIDE DIAS DE MOURA', '2014-09-16', 0, 'Morocco', 'ataide.dias.de.moura@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('38656-718', '1156', 'F', 'AURELINDA BATISTA DA SILVA', '2014-09-02', 0, 'Iraq', 'aurelinda.batista.da.silva@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('40843-051', '0036', 'M', 'ALICE FERNANDES DE OLIVEIRA', '2014-02-09', 0, 'Sudan', 'alice.fernandes.de.oliveira@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('12698-795', '8060', 'M', 'AMERICO FRANCISCO DA SILVA', '2014-02-10', 0, 'Vanuatu', 'americo.francisco.da.silva@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('28277-976', '2866', 'F', 'VILMA VITORIA DE SOUZA MESSA', '2014-04-18', 1, 'Zimbabwe', 'vilma.vitoria.de.souza.messa@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('64458-013', '2031', 'M', 'KLEBER MAGALHAES FERREIRA', '2014-08-12', 1, 'Egypt', 'kleber.magalhaes.ferreira@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('41482-345', '3338', 'F', 'MARCONI GEORGE RIBEIRO DA SILVA', '2014-11-10', 0, 'Switzerland', 'marconi.george.ribeiro.da.silva@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('43369-725', '8249', 'F', 'MARIA ELENA ALVES', '2014-04-21', 1, 'Kiribati', 'maria.elena.alves@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('26482-974', '8091', 'M', 'ILZA XAVIER DE LIMA ARAUJO', '2014-12-11', 0, 'Gambia', 'ilza.xavier.de.lima.araujo@yahoo.com');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LUIZA ROTTLISBERGER SILVA', '2014-07-08', '2014-04-05', 0, 0, 'luiza.rottlisberger.silva@hotmail.com', 'luiza.rottlisberger.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ELOIR CARLOS FIRMINO', '2014-07-10', '2014-06-16', 1, 1, 'eloir.carlos.firmino@fb.com', 'eloir.carlos.firmino');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ELZA LIMA DE SOUZA MANSANO', '2014-07-08', '2014-01-24', 0, 0, 'elza.lima.de.souza.mansano@fb.com', 'elza.lima.de.souza.mansano');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('SUELY DA SILVA CAVALCANTI', '2014-07-07', '2014-05-21', 0, 0, 'suely.da.silva.cavalcanti@fb.com', 'suely.da.silva.cavalcanti');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('AUGUSTA ALVES DOS SANTOS', '2014-07-07', '2014-06-20', 1, 1, 'augusta.alves.dos.santos@hotmail.com', 'augusta.alves.dos.santos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARILEIA NUNES DE OLIVEIRA', '2014-07-06', '2014-02-17', 1, 0, 'marileia.nunes.de.oliveira@gmail.com', 'marileia.nunes.de.oliveira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ALICE FERNANDES DE OLIVEIRA', '2014-07-11', '2014-02-07', 1, 0, 'alice.fernandes.de.oliveira@fb.com', 'alice.fernandes.de.oliveira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MIGUEL JOAQUIM SILVA', '2014-07-01', '2014-05-17', 0, 0, 'miguel.joaquim.silva@fb.com', 'miguel.joaquim.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ELISABETE ROMERO NOBRE LEAL', '2014-07-01', '2014-04-28', 0, 1, 'elisabete.romero.nobre.leal@hotmail.com', 'elisabete.romero.nobre.leal');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ROSILENE ALMEIDA DA SILVA', '2014-07-13', '2014-03-13', 0, 1, 'rosilene.almeida.da.silva@fb.com', 'rosilene.almeida.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MIGUEL VENCESLAU MACIEL DE CAMPOS', '2014-07-07', '2014-05-21', 0, 0, 'miguel.venceslau.maciel.de.campos@gmail.com', 'miguel.venceslau.maciel.de.campos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('NEIZA MARIA LEITE DA SILVA', '2014-07-01', '2014-04-10', 1, 0, 'neiza.maria.leite.da.silva@fb.com', 'neiza.maria.leite.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('QUITERIA LOURENCO DE LIMA', '2014-07-04', '2014-01-06', 1, 1, 'quiteria.lourenco.de.lima@fb.com', 'quiteria.lourenco.de.lima');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ALICE DE SOUZA MIRANDA', '2014-07-13', '2014-04-13', 0, 0, 'alice.de.souza.miranda@fb.com', 'alice.de.souza.miranda');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LUIZA ROTTLISBERGER SILVA', '2014-07-03', '2014-06-05', 0, 1, 'luiza.rottlisberger.silva@gmail.com', 'luiza.rottlisberger.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LUIZ LOPES DA SILVA', '2014-07-04', '2014-03-29', 1, 1, 'luiz.lopes.da.silva@gmail.com', 'luiz.lopes.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ELZA LIMA DE SOUZA MANSANO', '2014-07-02', '2014-05-17', 1, 1, 'elza.lima.de.souza.mansano@fb.com', 'elza.lima.de.souza.mansano');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('RUZINO ANTUNES DA SILVA', '2014-07-08', '2014-05-07', 0, 1, 'ruzino.antunes.da.silva@hotmail.com', 'ruzino.antunes.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('EUSTAQUIA PRIETO', '2014-07-02', '2014-04-23', 0, 0, 'eustaquia.prieto@hotmail.com', 'eustaquia.prieto');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JORGE TETSUO TAIRA', '2014-07-09', '2014-05-05', 0, 1, 'jorge.tetsuo.taira@gmail.com', 'jorge.tetsuo.taira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ROSILENE ALMEIDA DA SILVA', '2014-07-07', '2014-06-04', 0, 0, 'rosilene.almeida.da.silva@gmail.com', 'rosilene.almeida.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('IROCIDES APARECIDA FERREIRA', '2014-07-03', '2014-04-29', 1, 0, 'irocides.aparecida.ferreira@gmail.com', 'irocides.aparecida.ferreira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('CARLOS SERGIO URBANIN', '2014-07-03', '2014-06-08', 1, 1, 'carlos.sergio.urbanin@fb.com', 'carlos.sergio.urbanin');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JOANA ANTUNES', '2014-07-05', '2014-05-07', 1, 1, 'joana.antunes@hotmail.com', 'joana.antunes');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LOURENCO DIAS', '2014-07-09', '2014-03-30', 1, 0, 'lourenco.dias@gmail.com', 'lourenco.dias');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LUIZ FERNANDO DA SILVA AMORIM', '2014-07-13', '2014-03-15', 1, 1, 'luiz.fernando.da.silva.amorim@gmail.com', 'luiz.fernando.da.silva.amorim');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LAURA SEBASTIANA GURGEL', '2014-07-13', '2014-06-06', 1, 0, 'laura.sebastiana.gurgel@gmail.com', 'laura.sebastiana.gurgel');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LUIZ FERNANDO DA SILVA AMORIM', '2014-07-10', '2014-04-26', 0, 1, 'luiz.fernando.da.silva.amorim@gmail.com', 'luiz.fernando.da.silva.amorim');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('EUZEBIO DA SILVA CEZAR', '2014-07-08', '2014-03-18', 0, 1, 'euzebio.da.silva.cezar@gmail.com', 'euzebio.da.silva.cezar');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ALIETE FRANCISCA PRATES', '2014-07-13', '2014-01-09', 1, 1, 'aliete.francisca.prates@hotmail.com', 'aliete.francisca.prates');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ANA PAULA FIGUEIREDO DA ROCHA', '2014-07-11', '2014-06-04', 1, 1, 'ana.paula.figueiredo.da.rocha@fb.com', 'ana.paula.figueiredo.da.rocha');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARCIA DA SILVA OLIVEIRA', '2014-07-07', '2014-05-09', 1, 0, 'marcia.da.silva.oliveira@gmail.com', 'marcia.da.silva.oliveira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('NADIACUIABANO KUNZE', '2014-07-11', '2014-06-23', 1, 1, 'nadiacuiabano.kunze@gmail.com', 'nadiacuiabano.kunze');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARIA DAIANE DE ARAUJO SOUZA', '2014-07-01', '2014-05-15', 1, 0, 'maria.daiane.de.araujo.souza@fb.com', 'maria.daiane.de.araujo.souza');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JOAQUIM BORGES RODRIGUES', '2014-07-07', '2014-05-05', 1, 1, 'joaquim.borges.rodrigues@gmail.com', 'joaquim.borges.rodrigues');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('IVANI DO NASCIMENTO VALENTIM', '2014-07-07', '2014-02-04', 0, 1, 'ivani.do.nascimento.valentim@fb.com', 'ivani.do.nascimento.valentim');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('NADIACUIABANO KUNZE', '2014-07-11', '2014-06-12', 1, 0, 'nadiacuiabano.kunze@gmail.com', 'nadiacuiabano.kunze');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ELISABETE ROMERO NOBRE LEAL', '2014-07-09', '2014-01-05', 0, 0, 'elisabete.romero.nobre.leal@fb.com', 'elisabete.romero.nobre.leal');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JUEL PRUDENCIO BORGES', '2014-07-06', '2014-03-28', 1, 1, 'juel.prudencio.borges@fb.com', 'juel.prudencio.borges');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARIA LOURENCO ARISTIDES', '2014-07-07', '2014-04-16', 0, 1, 'maria.lourenco.aristides@fb.com', 'maria.lourenco.aristides');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('NEIVA OBERGER FERREIRA', '2014-07-04', '2014-01-29', 0, 1, 'neiva.oberger.ferreira@fb.com', 'neiva.oberger.ferreira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ADELSON LUIZ DA SILVA', '2014-07-02', '2014-01-27', 1, 1, 'adelson.luiz.da.silva@fb.com', 'adelson.luiz.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LUIZ FERNANDO DA SILVA AMORIM', '2014-07-07', '2014-03-22', 1, 1, 'luiz.fernando.da.silva.amorim@gmail.com', 'luiz.fernando.da.silva.amorim');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('EUSTAQUIA PRIETO', '2014-07-11', '2014-02-13', 1, 1, 'eustaquia.prieto@fb.com', 'eustaquia.prieto');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('DIEGO CESPEDES DE SOUZA', '2014-07-03', '2014-02-21', 1, 0, 'diego.cespedes.de.souza@hotmail.com', 'diego.cespedes.de.souza');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ANGELA APARECIDA BERNEGOZZE', '2014-07-09', '2014-01-16', 1, 1, 'angela.aparecida.bernegozze@gmail.com', 'angela.aparecida.bernegozze');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JUEL PRUDENCIO BORGES', '2014-07-12', '2014-03-21', 1, 1, 'juel.prudencio.borges@gmail.com', 'juel.prudencio.borges');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('EUSTAQUIA PRIETO', '2014-07-03', '2014-06-19', 0, 0, 'eustaquia.prieto@fb.com', 'eustaquia.prieto');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('VIRGILIA DIAS VIEIRA', '2014-07-08', '2014-06-07', 1, 1, 'virgilia.dias.vieira@fb.com', 'virgilia.dias.vieira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('QUITERIA LOURENCO DE LIMA', '2014-07-12', '2014-05-19', 0, 1, 'quiteria.lourenco.de.lima@hotmail.com', 'quiteria.lourenco.de.lima');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ARISMARES SOUZA PRATES', '2014-07-06', '2014-03-09', 0, 0, 'arismares.souza.prates@hotmail.com', 'arismares.souza.prates');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MIGUEL VENCESLAU MACIEL DE CAMPOS', '2014-07-07', '2014-03-31', 1, 0, 'miguel.venceslau.maciel.de.campos@fb.com', 'miguel.venceslau.maciel.de.campos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ROBSON LUIZ DO NASCIMENTO PUERTAS', '2014-07-04', '2014-03-20', 0, 1, 'robson.luiz.do.nascimento.puertas@gmail.com', 'robson.luiz.do.nascimento.puertas');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('HELIO SAMBATTI', '2014-07-12', '2014-02-13', 1, 1, 'helio.sambatti@hotmail.com', 'helio.sambatti');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('GLAUBER DA COSTA ARRUDA', '2014-07-04', '2014-06-05', 0, 0, 'glauber.da.costa.arruda@fb.com', 'glauber.da.costa.arruda');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('BENJAMIM GAUNA', '2014-07-06', '2014-03-23', 0, 0, 'benjamim.gauna@gmail.com', 'benjamim.gauna');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ILZA XAVIER DE LIMA ARAUJO', '2014-07-01', '2014-02-15', 0, 1, 'ilza.xavier.de.lima.araujo@gmail.com', 'ilza.xavier.de.lima.araujo');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LUIZA ROTTLISBERGER SILVA', '2014-07-10', '2014-01-31', 1, 0, 'luiza.rottlisberger.silva@gmail.com', 'luiza.rottlisberger.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('AURELINDA BATISTA DA SILVA', '2014-07-09', '2014-03-24', 0, 0, 'aurelinda.batista.da.silva@fb.com', 'aurelinda.batista.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARIA TEREZINHA ROCHA DE SOUZA', '2014-07-07', '2014-02-22', 1, 1, 'maria.terezinha.rocha.de.souza@fb.com', 'maria.terezinha.rocha.de.souza');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('NADIACUIABANO KUNZE', '2014-07-11', '2014-06-16', 1, 0, 'nadiacuiabano.kunze@hotmail.com', 'nadiacuiabano.kunze');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('TIMOTEO BATISTA LEITE', '2014-07-10', '2014-05-23', 1, 0, 'timoteo.batista.leite@hotmail.com', 'timoteo.batista.leite');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('BENEDITA GAUDENCIO DA COSTA', '2014-07-01', '2014-03-02', 1, 1, 'benedita.gaudencio.da.costa@hotmail.com', 'benedita.gaudencio.da.costa');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('RUBENSMORBECK LEITE', '2014-07-13', '2014-03-10', 1, 1, 'rubensmorbeck.leite@gmail.com', 'rubensmorbeck.leite');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ALICE DE SOUZA MIRANDA', '2014-07-02', '2014-03-20', 0, 0, 'alice.de.souza.miranda@hotmail.com', 'alice.de.souza.miranda');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('NEUCY DE OLIVEIRA', '2014-07-02', '2014-02-27', 0, 1, 'neucy.de.oliveira@gmail.com', 'neucy.de.oliveira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ZILDA MARTINS DE SOUZA', '2014-07-08', '2014-05-12', 0, 1, 'zilda.martins.de.souza@hotmail.com', 'zilda.martins.de.souza');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LAURA SEBASTIANA GURGEL', '2014-07-01', '2014-02-10', 0, 0, 'laura.sebastiana.gurgel@fb.com', 'laura.sebastiana.gurgel');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('RUZINO ANTUNES DA SILVA', '2014-07-10', '2014-04-11', 1, 0, 'ruzino.antunes.da.silva@fb.com', 'ruzino.antunes.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('CLEODETE CANOLA DE CAMPOS', '2014-07-04', '2014-05-03', 1, 1, 'cleodete.canola.de.campos@fb.com', 'cleodete.canola.de.campos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARIA TEREZINHA ROCHA DE SOUZA', '2014-07-08', '2014-05-27', 0, 0, 'maria.terezinha.rocha.de.souza@fb.com', 'maria.terezinha.rocha.de.souza');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LUIZ LOPES DA SILVA', '2014-07-08', '2014-06-21', 1, 0, 'luiz.lopes.da.silva@gmail.com', 'luiz.lopes.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ALDEIR ALEX ALVES LIMA', '2014-07-10', '2014-03-22', 0, 0, 'aldeir.alex.alves.lima@gmail.com', 'aldeir.alex.alves.lima');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('NEIVA OBERGER FERREIRA', '2014-07-06', '2014-06-09', 1, 1, 'neiva.oberger.ferreira@hotmail.com', 'neiva.oberger.ferreira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('RUBENSMORBECK LEITE', '2014-07-03', '2014-04-27', 1, 1, 'rubensmorbeck.leite@gmail.com', 'rubensmorbeck.leite');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MIGUEL VENCESLAU MACIEL DE CAMPOS', '2014-07-02', '2014-04-08', 0, 1, 'miguel.venceslau.maciel.de.campos@gmail.com', 'miguel.venceslau.maciel.de.campos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JOSE RIBAMAR BEZERRA SA', '2014-07-08', '2014-02-21', 1, 0, 'jose.ribamar.bezerra.sa@gmail.com', 'jose.ribamar.bezerra.sa');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('EUZEBIO DA SILVA CEZAR', '2014-07-07', '2014-04-06', 1, 1, 'euzebio.da.silva.cezar@fb.com', 'euzebio.da.silva.cezar');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JOSE NUNES PEREIRA', '2014-07-03', '2014-05-07', 1, 0, 'jose.nunes.pereira@gmail.com', 'jose.nunes.pereira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('BEATRIZ PEREIRA LIMA', '2014-07-11', '2014-05-05', 1, 0, 'beatriz.pereira.lima@gmail.com', 'beatriz.pereira.lima');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('HABIB FAHED', '2014-07-05', '2014-03-30', 0, 0, 'habib.fahed@gmail.com', 'habib.fahed');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ALIETE FRANCISCA PRATES', '2014-07-11', '2014-04-06', 0, 1, 'aliete.francisca.prates@gmail.com', 'aliete.francisca.prates');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LAURA SEBASTIANA GURGEL', '2014-07-11', '2014-03-29', 0, 0, 'laura.sebastiana.gurgel@gmail.com', 'laura.sebastiana.gurgel');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('IVANI DO NASCIMENTO VALENTIM', '2014-07-08', '2014-04-11', 0, 0, 'ivani.do.nascimento.valentim@fb.com', 'ivani.do.nascimento.valentim');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('CORNELIO DIAS DUARTE', '2014-07-06', '2014-02-02', 0, 1, 'cornelio.dias.duarte@hotmail.com', 'cornelio.dias.duarte');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('NADIACUIABANO KUNZE', '2014-07-13', '2014-02-21', 0, 0, 'nadiacuiabano.kunze@gmail.com', 'nadiacuiabano.kunze');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('NEIVA OBERGER FERREIRA', '2014-07-07', '2014-06-18', 1, 0, 'neiva.oberger.ferreira@gmail.com', 'neiva.oberger.ferreira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARIA DE LOURDES FERNANDES DIAS', '2014-07-12', '2014-04-05', 0, 0, 'maria.de.lourdes.fernandes.dias@hotmail.com', 'maria.de.lourdes.fernandes.dias');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('THANIA CRISTINA DA SILVA BARNABE', '2014-07-04', '2014-06-26', 0, 1, 'thania.cristina.da.silva.barnabe@gmail.com', 'thania.cristina.da.silva.barnabe');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('WANDERSON COSMO DE ARAUJO', '2014-07-08', '2014-04-30', 1, 1, 'wanderson.cosmo.de.araujo@hotmail.com', 'wanderson.cosmo.de.araujo');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LAURO JOSE DA SILVA', '2014-07-08', '2014-03-16', 0, 1, 'lauro.jose.da.silva@gmail.com', 'lauro.jose.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('VIRGILIA DIAS VIEIRA', '2014-07-07', '2014-02-09', 0, 1, 'virgilia.dias.vieira@fb.com', 'virgilia.dias.vieira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARIA FATIMA SCHEUNEMANN MIRANDA', '2014-07-07', '2014-06-24', 0, 0, 'maria.fatima.scheunemann.miranda@gmail.com', 'maria.fatima.scheunemann.miranda');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ROSILENE ALMEIDA DA SILVA', '2014-07-06', '2014-04-03', 1, 1, 'rosilene.almeida.da.silva@hotmail.com', 'rosilene.almeida.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ZILMA MARQUES GONCALVES RODRIGUES', '2014-07-02', '2014-03-14', 1, 0, 'zilma.marques.goncalves.rodrigues@gmail.com', 'zilma.marques.goncalves.rodrigues');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ABIGAIL DA SILVA LARA', '2014-07-08', '2014-04-27', 0, 0, 'abigail.da.silva.lara@fb.com', 'abigail.da.silva.lara');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('HABIB FAHED', '2014-07-11', '2014-06-11', 1, 0, 'habib.fahed@hotmail.com', 'habib.fahed');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('RAMIRO VEDOVATO', '2014-07-08', '2014-05-07', 1, 1, 'ramiro.vedovato@gmail.com', 'ramiro.vedovato');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ADENILTON JOSE DE MIRANDA', '2014-07-09', '2014-04-03', 1, 1, 'adenilton.jose.de.miranda@gmail.com', 'adenilton.jose.de.miranda');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JULIO APARECIDO DE SOUZA', '2014-07-06', '2014-05-12', 0, 1, 'julio.aparecido.de.souza@fb.com', 'julio.aparecido.de.souza');
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-18', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-17', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-26', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-18', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-31', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-07-07', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-06', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-21', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-20', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-18', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-07', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-31', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-13', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-16', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-15', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-07', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-29', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-15', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-23', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-02', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-04', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-17', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-23', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-25', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-31', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-25', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-21', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-24', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-06', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-20', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-19', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-03', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-14', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-19', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-10', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-11', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-16', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-03', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-10', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-07', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-02', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-18', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-10', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-06', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-23', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-25', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-15', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-25', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-10', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-30', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-23', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-04', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-07-11', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-28', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-23', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-31', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-28', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-19', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-18', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-08', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-12', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-24', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-12', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-14', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-09', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-23', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-07-12', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-22', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-10', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-07-01', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-02', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-29', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-04', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-14', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-20', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-30', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-29', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-28', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-30', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-05', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-07', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-22', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-02', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-06', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-22', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-15', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-11', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-07', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-02', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-27', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-30', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-07-03', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-19', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-17', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-28', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-28', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-07-04', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-04', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-28', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-01', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
