INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('58001-604', '2338', 'F', 'MARILEIA NUNES DE OLIVEIRA', '2014-12-02', 1, 'Cambodia', 'marileia.nunes.de.oliveira@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('58409-232', '7253', 'M', 'CELIA CRISTINA PEREIRA PINTO DOS SANTOS', '2014-06-29', 0, 'Uganda', 'celia.cristina.pereira.pinto.dos.santos@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('01987-337', '5520', 'M', 'CELIA CRISTINA PEREIRA PINTO DOS SANTOS', '2014-08-25', 1, 'Kazakhstan', 'celia.cristina.pereira.pinto.dos.santos@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('25006-722', '2956', 'F', 'ABILIO CAVALHEIRO', '2014-01-09', 0, 'Cyprus', 'abilio.cavalheiro@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('99705-738', '9658', 'M', 'LOURIVAL ROSA GUIMARAES', '2014-12-20', 0, 'Sudan', 'lourival.rosa.guimaraes@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('06025-219', '6403', 'M', 'ALCEU DOS SANTOS', '2014-09-26', 1, 'El Salvador', 'alceu.dos.santos@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('11950-106', '9353', 'F', 'ABIGAIL DA SILVA LARA', '2014-01-18', 1, 'Sao Tome & Principe', 'abigail.da.silva.lara@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('27814-404', '1783', 'F', 'MARIA LOURENCO ARISTIDES', '2014-09-24', 1, 'Lesotho', 'maria.lourenco.aristides@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('22819-003', '2054', 'F', 'ELOIDE CAVANHA', '2014-11-23', 1, 'Korea South', 'eloide.cavanha@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('76024-742', '5572', 'F', 'CLEODETE CANOLA DE CAMPOS', '2014-11-04', 1, 'Luxembourg', 'cleodete.canola.de.campos@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('59688-238', '8082', 'F', 'NADIACUIABANO KUNZE', '2014-07-28', 0, 'Belize', 'nadiacuiabano.kunze@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('72174-213', '6734', 'M', 'AUGUSTA ALVES DOS SANTOS', '2014-05-27', 1, 'Iceland', 'augusta.alves.dos.santos@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('98142-398', '3143', 'M', 'VIRGILIA DIAS VIEIRA', '2014-07-11', 0, 'Trinidad & Tobago', 'virgilia.dias.vieira@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('33587-283', '4075', 'M', 'JOSE JESUS DA HORA', '2014-12-16', 0, 'Cuba', 'jose.jesus.da.hora@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('66889-709', '8633', 'M', 'CELESIAORMOND RIBEIRO DE CAMPOS', '2014-11-30', 1, 'Venezuela', 'celesiaormond.ribeiro.de.campos@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('93892-626', '1038', 'F', 'ELOIDE CAVANHA', '2014-12-22', 1, 'India', 'eloide.cavanha@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('02312-722', '8619', 'M', 'DILMA DE SOUZA', '2014-12-20', 1, 'Kenya', 'dilma.de.souza@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('30471-229', '8999', 'M', 'CLEUSA FERREIRA MACIEL', '2014-10-07', 0, 'United Kingdom', 'cleusa.ferreira.maciel@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('39459-490', '4478', 'F', 'LUZIA RODRIGUES DE OLIVEIRA', '2014-01-12', 0, 'Mongolia', 'luzia.rodrigues.de.oliveira@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('09707-891', '7707', 'M', 'OLGA PEREIRA', '2014-02-04', 0, 'Tunisia', 'olga.pereira@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('30436-611', '1575', 'M', 'MARIA DO CARMO JERONIMO SILVA', '2014-10-19', 0, 'Peru', 'maria.do.carmo.jeronimo.silva@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('03834-390', '0988', 'F', 'AUGUSTA ALVES DOS SANTOS', '2014-07-14', 0, 'Seychelles', 'augusta.alves.dos.santos@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('08971-983', '2092', 'F', 'HELOIZA ALMEIDA DOS SANTOS', '2014-10-12', 0, 'The Philippines', 'heloiza.almeida.dos.santos@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('36838-720', '1782', 'F', 'SILVIA MENDES', '2014-01-09', 1, 'Israel', 'silvia.mendes@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('93351-725', '1294', 'M', 'LOURIVAL ROSA GUIMARAES', '2014-09-17', 0, 'Ireland', 'lourival.rosa.guimaraes@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('58081-496', '9172', 'F', 'MARILEIA NUNES DE OLIVEIRA', '2014-10-25', 0, 'Bhutan', 'marileia.nunes.de.oliveira@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('05026-862', '0020', 'M', 'MARIA DE LOURDES FERNANDES DIAS', '2014-09-17', 1, 'Czech Republic', 'maria.de.lourdes.fernandes.dias@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('65180-364', '0028', 'M', 'JOSE RIBAMAR BEZERRA SA', '2014-07-15', 0, 'Lebanon', 'jose.ribamar.bezerra.sa@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('40708-073', '7061', 'M', 'ROSIMEIRE GONCALVES LOPES RAMOS', '2014-01-06', 0, 'Nauru', 'rosimeire.goncalves.lopes.ramos@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('90499-936', '6532', 'M', 'HELIO SAMBATTI', '2014-01-08', 0, 'Belgium', 'helio.sambatti@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('09324-181', '6635', 'F', 'ELOIR CARLOS FIRMINO', '2014-10-04', 1, 'Iraq', 'eloir.carlos.firmino@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('05181-936', '7110', 'M', 'AURELINDA BATISTA DA SILVA', '2014-11-10', 1, 'Nauru', 'aurelinda.batista.da.silva@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('99253-280', '6584', 'F', 'ROBSON LUIZ DO NASCIMENTO PUERTAS', '2014-03-15', 1, 'Cape Verde', 'robson.luiz.do.nascimento.puertas@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('81047-992', '1453', 'F', 'MARIA DAIANE DE ARAUJO SOUZA', '2014-08-28', 1, 'Chad', 'maria.daiane.de.araujo.souza@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('96262-096', '4628', 'F', 'MARIA DAIANE DE ARAUJO SOUZA', '2014-08-12', 0, 'Luxembourg', 'maria.daiane.de.araujo.souza@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('10457-497', '3976', 'M', 'ANTONIO INACIO RODRIGUES', '2014-01-17', 0, 'Thailand', 'antonio.inacio.rodrigues@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('72403-250', '6215', 'F', 'SILVIA MENDES', '2014-08-16', 1, 'Papua New Guinea', 'silvia.mendes@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('48160-021', '5362', 'F', 'SILVIO TSIPE RAIRATE', '2014-09-19', 1, 'Vatican City (Holy See)', 'silvio.tsipe.rairate@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('01644-648', '5061', 'M', 'RITA IRACI ALMEIDA DA SILVA', '2014-05-21', 0, 'Serbia', 'rita.iraci.almeida.da.silva@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('32058-156', '3004', 'M', 'EUSTAQUIA PRIETO', '2014-04-05', 0, 'Cameroon', 'eustaquia.prieto@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('64570-698', '3349', 'F', 'MARIA DO CARMO JERONIMO SILVA', '2014-03-27', 1, 'Congo Democratic Republic', 'maria.do.carmo.jeronimo.silva@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('13371-273', '8931', 'F', 'FRANCISCA MARIA SILVA COSTA', '2014-07-25', 1, 'Nicaragua', 'francisca.maria.silva.costa@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('31109-642', '2176', 'M', 'CLAUDIO BARBOSA DOS SANTOS', '2014-10-07', 1, 'St. Lucia', 'claudio.barbosa.dos.santos@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('30267-194', '1726', 'F', 'SUELY DA SILVA CAVALCANTI', '2014-08-09', 1, 'New Zealand', 'suely.da.silva.cavalcanti@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('38302-190', '1099', 'M', 'MIGUEL VENCESLAU MACIEL DE CAMPOS', '2014-03-25', 1, 'Nepal', 'miguel.venceslau.maciel.de.campos@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('31919-748', '1445', 'F', 'LAURA SEBASTIANA GURGEL', '2014-09-26', 0, 'Laos', 'laura.sebastiana.gurgel@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('70159-729', '6968', 'M', 'ILZA XAVIER DE LIMA ARAUJO', '2014-12-12', 0, 'Yemen', 'ilza.xavier.de.lima.araujo@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('86677-010', '2141', 'M', 'GUIOMAR TRELHA FRANCA', '2014-07-13', 0, 'Niger', 'guiomar.trelha.franca@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('68688-829', '1938', 'F', 'OBADIAS MARCAL DE OLIVEIRA', '2014-09-08', 0, 'Mozambique', 'obadias.marcal.de.oliveira@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('23158-939', '9218', 'F', 'JOSE EVALDO DA SILVA', '2014-01-02', 1, 'The Philippines', 'jose.evaldo.da.silva@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('30828-101', '7372', 'F', 'JOSENOTARIO MUNGO', '2014-07-21', 1, 'Iran', 'josenotario.mungo@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('97382-419', '8024', 'F', 'CARLOS SERGIO URBANIN', '2014-09-10', 0, 'Jamaica', 'carlos.sergio.urbanin@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('11774-378', '6607', 'F', 'CLAUDIO BARBOSA DOS SANTOS', '2014-08-10', 1, 'Liberia', 'claudio.barbosa.dos.santos@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('68706-258', '9397', 'F', 'EDIR DIAS DE CARVALHO', '2014-11-02', 0, 'Tonga', 'edir.dias.de.carvalho@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('03087-573', '4053', 'M', 'ADENILTON JOSE DE MIRANDA', '2014-09-05', 1, 'Thailand', 'adenilton.jose.de.miranda@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('11176-200', '2083', 'M', 'CARLOS SERGIO URBANIN', '2014-08-14', 1, 'Nigeria', 'carlos.sergio.urbanin@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('31011-936', '3607', 'M', 'CELIA CRISTINA PEREIRA PINTO DOS SANTOS', '2014-05-07', 0, 'Kosovo', 'celia.cristina.pereira.pinto.dos.santos@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('92681-418', '0420', 'M', 'OSWALDIR GOMES', '2014-04-23', 0, 'Burkina Faso', 'oswaldir.gomes@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('34547-177', '7435', 'M', 'ALICE FERNANDES DE OLIVEIRA', '2014-01-27', 1, 'Korea North', 'alice.fernandes.de.oliveira@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('76339-952', '5757', 'M', 'GLAUBER DA COSTA ARRUDA', '2014-04-13', 1, 'Nepal', 'glauber.da.costa.arruda@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('77371-682', '6965', 'F', 'JULIO APARECIDO DE SOUZA', '2014-01-12', 1, 'Micronesia', 'julio.aparecido.de.souza@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('30822-920', '9112', 'F', 'RAMAO CARDOSO', '2014-05-22', 0, 'France', 'ramao.cardoso@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('66618-273', '1192', 'M', 'MARIA DE LOURDES FERNANDES DIAS', '2014-12-05', 1, 'Dominica', 'maria.de.lourdes.fernandes.dias@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('84634-722', '1914', 'F', 'NADIACUIABANO KUNZE', '2014-03-23', 1, 'Yemen', 'nadiacuiabano.kunze@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('13040-524', '0407', 'M', 'JOAQUIM BORGES RODRIGUES', '2014-02-22', 0, 'Mongolia', 'joaquim.borges.rodrigues@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('67987-983', '7479', 'M', 'ANDRE LUIS CASTRILLON GARCIA', '2014-01-08', 1, 'Solomon Islands', 'andre.luis.castrillon.garcia@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('84610-249', '6416', 'F', 'OSVALDO PEREIRA BARBOSA', '2014-03-28', 1, 'East Timor', 'osvaldo.pereira.barbosa@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('95658-249', '3923', 'M', 'MAGALI SANCHES', '2014-12-17', 0, 'Somalia', 'magali.sanches@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('96816-157', '1431', 'F', 'NADIACUIABANO KUNZE', '2014-01-15', 0, 'Cameroon', 'nadiacuiabano.kunze@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('32598-570', '4132', 'M', 'EUSTAQUIA PRIETO', '2014-12-14', 0, 'Guinea-Bissau', 'eustaquia.prieto@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('15498-084', '5463', 'M', 'LIDIANE DO PRADO BRITE', '2014-03-07', 1, 'Indonesia', 'lidiane.do.prado.brite@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('09106-646', '5464', 'M', 'OSWALDIR GOMES', '2014-09-13', 0, 'Djibouti', 'oswaldir.gomes@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('94814-812', '6786', 'M', 'IROCIDES APARECIDA FERREIRA', '2014-12-26', 0, 'Uruguay', 'irocides.aparecida.ferreira@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('52879-650', '3453', 'M', 'HABIB FAHED', '2014-08-18', 1, 'Dominican Republic', 'habib.fahed@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('51709-008', '6486', 'F', 'LAURA SEBASTIANA GURGEL', '2014-06-18', 0, 'Nauru', 'laura.sebastiana.gurgel@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('51419-134', '8221', 'F', 'RENIRA RODRIGUES DA SILVA DE SOUSA', '2014-11-02', 1, 'Moldova', 'renira.rodrigues.da.silva.de.sousa@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('44287-372', '7655', 'M', 'AUGUSTA ALVES DOS SANTOS', '2014-04-11', 0, 'Nepal', 'augusta.alves.dos.santos@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('01017-176', '0942', 'M', 'LOURIVAL ROSA GUIMARAES', '2014-07-08', 0, 'Guatemala', 'lourival.rosa.guimaraes@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('79863-683', '8339', 'F', 'MIGUEL VENCESLAU MACIEL DE CAMPOS', '2014-05-11', 1, 'Uzbekistan', 'miguel.venceslau.maciel.de.campos@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('53613-148', '0058', 'F', 'DIRCEU DE MATTOS', '2014-12-20', 0, 'Denmark', 'dirceu.de.mattos@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('53795-384', '5116', 'F', 'DIAMANTINA DA SILVA SOARES', '2014-04-13', 1, 'Hungary', 'diamantina.da.silva.soares@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('26976-350', '2686', 'M', 'LAURO JOSE DA SILVA', '2014-08-26', 0, 'St. Lucia', 'lauro.jose.da.silva@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('14506-571', '7744', 'M', 'LOURENCO DIAS', '2014-06-29', 1, 'Niger', 'lourenco.dias@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('12405-205', '7377', 'F', 'MIGUEL JOAQUIM SILVA', '2014-03-09', 0, 'Rwanda', 'miguel.joaquim.silva@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('69661-787', '7619', 'F', 'EUSTAQUIA PRIETO', '2014-06-04', 0, 'Thailand', 'eustaquia.prieto@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('51052-983', '4682', 'M', 'DELCY MARTINS DA SILVA', '2014-04-02', 1, 'Jordan', 'delcy.martins.da.silva@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('47736-157', '6360', 'F', 'ARISMARES SOUZA PRATES', '2014-08-08', 0, 'Luxembourg', 'arismares.souza.prates@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('90943-575', '0553', 'M', 'JOANA ANTUNES', '2014-01-14', 0, 'Ukraine', 'joana.antunes@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('64577-506', '5957', 'M', 'ZILDA MARTINS DE SOUZA', '2014-05-26', 0, 'Niger', 'zilda.martins.de.souza@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('74489-849', '9707', 'F', 'AMERICO FRANCISCO DA SILVA', '2014-12-24', 0, 'Kyrgyzstan', 'americo.francisco.da.silva@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('60563-800', '8381', 'M', 'MARIA DO CARMO JERONIMO SILVA', '2014-11-22', 0, 'Malta', 'maria.do.carmo.jeronimo.silva@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('17805-774', '3116', 'M', 'ZILDA MARTINS DE SOUZA', '2014-05-05', 0, 'Ecuador', 'zilda.martins.de.souza@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('36940-194', '9731', 'F', 'SOLANGE APARECIDA DO PRADO DA CRUZ', '2014-11-03', 1, 'Mongolia', 'solange.aparecida.do.prado.da.cruz@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('23214-323', '3179', 'M', 'ILZA XAVIER DE LIMA ARAUJO', '2014-10-15', 1, 'United Kingdom', 'ilza.xavier.de.lima.araujo@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('33897-559', '1113', 'F', 'SILVIO TSIPE RAIRATE', '2014-05-31', 1, 'Liechtenstein', 'silvio.tsipe.rairate@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('53960-372', '2368', 'F', 'MIGUEL JOAQUIM SILVA', '2014-10-19', 1, 'El Salvador', 'miguel.joaquim.silva@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('30644-603', '5048', 'M', 'DIRCEU DE MATTOS', '2014-01-14', 1, 'Lesotho', 'dirceu.de.mattos@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('89917-834', '6296', 'F', 'MARGARETH VIRGINIA DE REZENDE MEHLMANN', '2014-04-05', 1, 'Antigua & Barbuda', 'margareth.virginia.de.rezende.mehlmann@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('60292-916', '1418', 'M', 'DIRCEU DE MATTOS', '2014-11-19', 0, 'Mauritania', 'dirceu.de.mattos@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('87775-680', '2284', 'M', 'OBADIAS MARCAL DE OLIVEIRA', '2014-02-20', 0, 'Georgia', 'obadias.marcal.de.oliveira@gmail.com');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MAGALI SANCHES', '2014-07-10', '2014-03-28', 1, 0, 'magali.sanches@fb.com', 'magali.sanches');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('CARMINDA POMPEU AMORIM', '2014-07-01', '2014-03-26', 1, 1, 'carminda.pompeu.amorim@hotmail.com', 'carminda.pompeu.amorim');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('KLEBER MAGALHAES FERREIRA', '2014-07-10', '2014-01-14', 1, 0, 'kleber.magalhaes.ferreira@gmail.com', 'kleber.magalhaes.ferreira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('EUSTAQUIA PRIETO', '2014-07-07', '2014-03-03', 0, 1, 'eustaquia.prieto@hotmail.com', 'eustaquia.prieto');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('PAULO TEIXEIRA DE ABREU', '2014-07-10', '2014-05-21', 1, 0, 'paulo.teixeira.de.abreu@gmail.com', 'paulo.teixeira.de.abreu');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('KLEBER MAGALHAES FERREIRA', '2014-07-01', '2014-05-23', 0, 0, 'kleber.magalhaes.ferreira@gmail.com', 'kleber.magalhaes.ferreira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('RUBENSMORBECK LEITE', '2014-07-04', '2014-01-15', 1, 0, 'rubensmorbeck.leite@hotmail.com', 'rubensmorbeck.leite');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JOANA ANTUNES', '2014-07-07', '2014-03-19', 0, 1, 'joana.antunes@gmail.com', 'joana.antunes');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('GLAUBER DA COSTA ARRUDA', '2014-07-08', '2014-03-28', 0, 1, 'glauber.da.costa.arruda@gmail.com', 'glauber.da.costa.arruda');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARIA HILDA MACHADO', '2014-07-10', '2014-01-28', 1, 0, 'maria.hilda.machado@fb.com', 'maria.hilda.machado');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('CELIA CRISTINA PEREIRA PINTO DOS SANTOS', '2014-07-07', '2014-05-03', 1, 1, 'celia.cristina.pereira.pinto.dos.santos@gmail.com', 'celia.cristina.pereira.pinto.dos.santos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARIA ALVES SUTIL', '2014-07-03', '2014-04-17', 0, 0, 'maria.alves.sutil@fb.com', 'maria.alves.sutil');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ALBERTO FEIZAR CARDOSO ABDALA', '2014-07-05', '2014-01-24', 1, 1, 'alberto.feizar.cardoso.abdala@fb.com', 'alberto.feizar.cardoso.abdala');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('PAULO TEIXEIRA DE ABREU', '2014-07-01', '2014-06-01', 1, 1, 'paulo.teixeira.de.abreu@gmail.com', 'paulo.teixeira.de.abreu');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LUZIA RODRIGUES DE OLIVEIRA', '2014-07-12', '2014-03-13', 0, 1, 'luzia.rodrigues.de.oliveira@fb.com', 'luzia.rodrigues.de.oliveira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LAURO JOSE DA SILVA', '2014-07-02', '2014-06-09', 1, 1, 'lauro.jose.da.silva@gmail.com', 'lauro.jose.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ALDEIR ALEX ALVES LIMA', '2014-07-04', '2014-03-08', 0, 0, 'aldeir.alex.alves.lima@gmail.com', 'aldeir.alex.alves.lima');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ADAIL BANDINELLE DE MORAES', '2014-07-04', '2014-04-16', 1, 1, 'adail.bandinelle.de.moraes@gmail.com', 'adail.bandinelle.de.moraes');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ADENILTON JOSE DE MIRANDA', '2014-07-12', '2014-05-17', 0, 1, 'adenilton.jose.de.miranda@hotmail.com', 'adenilton.jose.de.miranda');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JOAO DE LUCA', '2014-07-05', '2014-02-09', 0, 0, 'joao.de.luca@hotmail.com', 'joao.de.luca');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('CRISTIANE PAES CORDOBA', '2014-07-08', '2014-04-03', 0, 1, 'cristiane.paes.cordoba@gmail.com', 'cristiane.paes.cordoba');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('OLGA PEREIRA', '2014-07-01', '2014-01-18', 1, 0, 'olga.pereira@fb.com', 'olga.pereira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('GUIOMAR TRELHA FRANCA', '2014-07-10', '2014-03-25', 0, 1, 'guiomar.trelha.franca@hotmail.com', 'guiomar.trelha.franca');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('RONY HUDSON OLIVEIRA CANDEIRO', '2014-07-12', '2014-06-09', 0, 1, 'rony.hudson.oliveira.candeiro@fb.com', 'rony.hudson.oliveira.candeiro');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('CORNELIO DIAS DUARTE', '2014-07-01', '2014-02-14', 1, 0, 'cornelio.dias.duarte@gmail.com', 'cornelio.dias.duarte');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('INES APARECIDA DA SILVA', '2014-07-07', '2014-05-22', 0, 0, 'ines.aparecida.da.silva@fb.com', 'ines.aparecida.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ILZA XAVIER DE LIMA ARAUJO', '2014-07-06', '2014-03-11', 1, 0, 'ilza.xavier.de.lima.araujo@fb.com', 'ilza.xavier.de.lima.araujo');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('RUBENSMORBECK LEITE', '2014-07-08', '2014-02-06', 1, 1, 'rubensmorbeck.leite@gmail.com', 'rubensmorbeck.leite');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('EUSTAQUIA PRIETO', '2014-07-04', '2014-04-27', 0, 0, 'eustaquia.prieto@fb.com', 'eustaquia.prieto');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('AMERICO FRANCISCO DA SILVA', '2014-07-08', '2014-04-02', 1, 1, 'americo.francisco.da.silva@hotmail.com', 'americo.francisco.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('TIMOTEO BATISTA LEITE', '2014-07-04', '2014-03-04', 0, 0, 'timoteo.batista.leite@hotmail.com', 'timoteo.batista.leite');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ZILDA MARTINS DE SOUZA', '2014-07-10', '2014-04-30', 1, 1, 'zilda.martins.de.souza@gmail.com', 'zilda.martins.de.souza');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ARISMARES SOUZA PRATES', '2014-07-05', '2014-05-15', 1, 1, 'arismares.souza.prates@hotmail.com', 'arismares.souza.prates');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('DIEGO CESPEDES DE SOUZA', '2014-07-11', '2014-06-27', 0, 1, 'diego.cespedes.de.souza@gmail.com', 'diego.cespedes.de.souza');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ANTONIA BORGES DA SILVA', '2014-07-05', '2014-01-14', 1, 0, 'antonia.borges.da.silva@fb.com', 'antonia.borges.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('AFONSO BARBOSA DA SILVA', '2014-07-08', '2014-06-25', 0, 0, 'afonso.barbosa.da.silva@gmail.com', 'afonso.barbosa.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('BENEDITO AMBROSIO DA COSTA', '2014-07-11', '2014-03-31', 1, 0, 'benedito.ambrosio.da.costa@hotmail.com', 'benedito.ambrosio.da.costa');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ELOIR CARLOS FIRMINO', '2014-07-02', '2014-05-03', 1, 0, 'eloir.carlos.firmino@gmail.com', 'eloir.carlos.firmino');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('IROCIDES APARECIDA FERREIRA', '2014-07-08', '2014-03-20', 1, 0, 'irocides.aparecida.ferreira@gmail.com', 'irocides.aparecida.ferreira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ALICE DE SOUZA MIRANDA', '2014-07-10', '2014-03-10', 0, 1, 'alice.de.souza.miranda@fb.com', 'alice.de.souza.miranda');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('THANIA CRISTINA DA SILVA BARNABE', '2014-07-12', '2014-04-10', 0, 1, 'thania.cristina.da.silva.barnabe@fb.com', 'thania.cristina.da.silva.barnabe');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LOURENCO DIAS', '2014-07-12', '2014-05-19', 1, 1, 'lourenco.dias@hotmail.com', 'lourenco.dias');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('EDIR DIAS DE CARVALHO', '2014-07-09', '2014-06-11', 1, 1, 'edir.dias.de.carvalho@gmail.com', 'edir.dias.de.carvalho');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ALDIVINA REIS FERNANDES', '2014-07-02', '2014-05-18', 0, 1, 'aldivina.reis.fernandes@hotmail.com', 'aldivina.reis.fernandes');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARIA TEREZINHA ROCHA DE SOUZA', '2014-07-05', '2014-06-27', 1, 0, 'maria.terezinha.rocha.de.souza@gmail.com', 'maria.terezinha.rocha.de.souza');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('AURELINDA BATISTA DA SILVA', '2014-07-02', '2014-01-22', 0, 0, 'aurelinda.batista.da.silva@hotmail.com', 'aurelinda.batista.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JORGE TETSUO TAIRA', '2014-07-07', '2014-06-09', 1, 1, 'jorge.tetsuo.taira@gmail.com', 'jorge.tetsuo.taira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ALCEU DOS SANTOS', '2014-07-03', '2014-02-14', 0, 1, 'alceu.dos.santos@fb.com', 'alceu.dos.santos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('RUBENSMORBECK LEITE', '2014-07-04', '2014-04-27', 0, 0, 'rubensmorbeck.leite@hotmail.com', 'rubensmorbeck.leite');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JOAQUIM BORGES RODRIGUES', '2014-07-06', '2014-03-24', 1, 1, 'joaquim.borges.rodrigues@gmail.com', 'joaquim.borges.rodrigues');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('BENILDE PERES DE CAMPOS', '2014-07-02', '2014-06-03', 1, 0, 'benilde.peres.de.campos@fb.com', 'benilde.peres.de.campos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ADAIL BANDINELLE DE MORAES', '2014-07-04', '2014-02-01', 0, 1, 'adail.bandinelle.de.moraes@fb.com', 'adail.bandinelle.de.moraes');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ADELSON LUIZ DA SILVA', '2014-07-08', '2014-02-10', 0, 0, 'adelson.luiz.da.silva@gmail.com', 'adelson.luiz.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('RENIRA RODRIGUES DA SILVA DE SOUSA', '2014-07-09', '2014-05-15', 1, 1, 'renira.rodrigues.da.silva.de.sousa@fb.com', 'renira.rodrigues.da.silva.de.sousa');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ANTONIO INACIO RODRIGUES', '2014-07-05', '2014-06-13', 1, 0, 'antonio.inacio.rodrigues@gmail.com', 'antonio.inacio.rodrigues');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JOSE EVALDO DA SILVA', '2014-07-11', '2014-05-12', 1, 1, 'jose.evaldo.da.silva@fb.com', 'jose.evaldo.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ANTONIO INACIO RODRIGUES', '2014-07-02', '2014-03-13', 1, 0, 'antonio.inacio.rodrigues@hotmail.com', 'antonio.inacio.rodrigues');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LAURA SEBASTIANA GURGEL', '2014-07-07', '2014-04-22', 0, 0, 'laura.sebastiana.gurgel@hotmail.com', 'laura.sebastiana.gurgel');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('VALDOMIRO LEITE DE SA', '2014-07-13', '2014-04-05', 1, 1, 'valdomiro.leite.de.sa@gmail.com', 'valdomiro.leite.de.sa');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ANDRE LUIS CASTRILLON GARCIA', '2014-07-11', '2014-01-21', 0, 1, 'andre.luis.castrillon.garcia@gmail.com', 'andre.luis.castrillon.garcia');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARIA LOURENCO ARISTIDES', '2014-07-09', '2014-03-27', 1, 1, 'maria.lourenco.aristides@fb.com', 'maria.lourenco.aristides');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MIGUEL VENCESLAU MACIEL DE CAMPOS', '2014-07-12', '2014-03-13', 0, 0, 'miguel.venceslau.maciel.de.campos@fb.com', 'miguel.venceslau.maciel.de.campos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARIA ALVES SUTIL', '2014-07-08', '2014-04-08', 0, 0, 'maria.alves.sutil@gmail.com', 'maria.alves.sutil');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ANA PAULA FIGUEIREDO DA ROCHA', '2014-07-06', '2014-03-04', 1, 1, 'ana.paula.figueiredo.da.rocha@gmail.com', 'ana.paula.figueiredo.da.rocha');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ROBSON LUIZ DO NASCIMENTO PUERTAS', '2014-07-07', '2014-04-17', 0, 1, 'robson.luiz.do.nascimento.puertas@fb.com', 'robson.luiz.do.nascimento.puertas');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('SUELY DA SILVA CAVALCANTI', '2014-07-02', '2014-01-21', 0, 0, 'suely.da.silva.cavalcanti@hotmail.com', 'suely.da.silva.cavalcanti');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('GLAUBER DA COSTA ARRUDA', '2014-07-03', '2014-04-13', 0, 0, 'glauber.da.costa.arruda@hotmail.com', 'glauber.da.costa.arruda');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('GUIOMAR TRELHA FRANCA', '2014-07-06', '2014-02-15', 1, 0, 'guiomar.trelha.franca@fb.com', 'guiomar.trelha.franca');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('SILVIA MENDES', '2014-07-06', '2014-04-07', 0, 1, 'silvia.mendes@gmail.com', 'silvia.mendes');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LOURENCO DIAS', '2014-07-04', '2014-01-15', 1, 1, 'lourenco.dias@gmail.com', 'lourenco.dias');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('BENJAMIM GAUNA', '2014-07-06', '2014-01-15', 0, 1, 'benjamim.gauna@hotmail.com', 'benjamim.gauna');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('DIEGO CESPEDES DE SOUZA', '2014-07-09', '2014-01-28', 0, 1, 'diego.cespedes.de.souza@gmail.com', 'diego.cespedes.de.souza');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('OLGA PEREIRA', '2014-07-11', '2014-06-24', 1, 0, 'olga.pereira@gmail.com', 'olga.pereira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('VIOLINDO DE SOUZA', '2014-07-10', '2014-04-13', 0, 0, 'violindo.de.souza@gmail.com', 'violindo.de.souza');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('RENIRA RODRIGUES DA SILVA DE SOUSA', '2014-07-05', '2014-05-20', 0, 1, 'renira.rodrigues.da.silva.de.sousa@gmail.com', 'renira.rodrigues.da.silva.de.sousa');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('EDIR DIAS DE CARVALHO', '2014-07-10', '2014-03-09', 0, 1, 'edir.dias.de.carvalho@gmail.com', 'edir.dias.de.carvalho');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ANA PAULA FIGUEIREDO DA ROCHA', '2014-07-11', '2014-02-17', 0, 1, 'ana.paula.figueiredo.da.rocha@fb.com', 'ana.paula.figueiredo.da.rocha');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('BENJAMIM GAUNA', '2014-07-05', '2014-01-31', 1, 1, 'benjamim.gauna@hotmail.com', 'benjamim.gauna');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('RAMAO CARDOSO', '2014-07-10', '2014-04-13', 0, 1, 'ramao.cardoso@fb.com', 'ramao.cardoso');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('EUZEBIO DA SILVA CEZAR', '2014-07-05', '2014-01-17', 1, 0, 'euzebio.da.silva.cezar@fb.com', 'euzebio.da.silva.cezar');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ANA PAULA FIGUEIREDO DA ROCHA', '2014-07-03', '2014-02-25', 1, 0, 'ana.paula.figueiredo.da.rocha@gmail.com', 'ana.paula.figueiredo.da.rocha');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ELOIDE CAVANHA', '2014-07-04', '2014-05-28', 1, 0, 'eloide.cavanha@fb.com', 'eloide.cavanha');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('DORILDA ALVES DE CARVALHO', '2014-07-05', '2014-04-27', 1, 0, 'dorilda.alves.de.carvalho@gmail.com', 'dorilda.alves.de.carvalho');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARIA LOURENCO ARISTIDES', '2014-07-11', '2014-04-19', 1, 0, 'maria.lourenco.aristides@fb.com', 'maria.lourenco.aristides');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('DIEGO CESPEDES DE SOUZA', '2014-07-02', '2014-05-25', 1, 1, 'diego.cespedes.de.souza@fb.com', 'diego.cespedes.de.souza');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MAGALI SANCHES', '2014-07-06', '2014-02-20', 1, 0, 'magali.sanches@gmail.com', 'magali.sanches');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('DORILDA ALVES DE CARVALHO', '2014-07-12', '2014-02-19', 1, 0, 'dorilda.alves.de.carvalho@gmail.com', 'dorilda.alves.de.carvalho');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('CRISTIANE PAES CORDOBA', '2014-07-03', '2014-01-14', 0, 1, 'cristiane.paes.cordoba@fb.com', 'cristiane.paes.cordoba');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('VIRGILIA DIAS VIEIRA', '2014-07-01', '2014-02-12', 0, 1, 'virgilia.dias.vieira@fb.com', 'virgilia.dias.vieira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('BENILDE PERES DE CAMPOS', '2014-07-07', '2014-06-24', 0, 1, 'benilde.peres.de.campos@gmail.com', 'benilde.peres.de.campos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LOURIVAL ROSA GUIMARAES', '2014-07-04', '2014-05-10', 0, 0, 'lourival.rosa.guimaraes@hotmail.com', 'lourival.rosa.guimaraes');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MIGUEL VENCESLAU MACIEL DE CAMPOS', '2014-07-10', '2014-06-27', 1, 0, 'miguel.venceslau.maciel.de.campos@hotmail.com', 'miguel.venceslau.maciel.de.campos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('INES APARECIDA DA SILVA', '2014-07-03', '2014-04-11', 1, 0, 'ines.aparecida.da.silva@gmail.com', 'ines.aparecida.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JOAQUIM BORGES RODRIGUES', '2014-07-13', '2014-06-03', 1, 1, 'joaquim.borges.rodrigues@gmail.com', 'joaquim.borges.rodrigues');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('INES APARECIDA DA SILVA', '2014-07-03', '2014-01-07', 1, 1, 'ines.aparecida.da.silva@hotmail.com', 'ines.aparecida.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('HELIO SAMBATTI', '2014-07-13', '2014-05-24', 0, 1, 'helio.sambatti@gmail.com', 'helio.sambatti');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ROBSON LUIZ DO NASCIMENTO PUERTAS', '2014-07-08', '2014-03-11', 1, 1, 'robson.luiz.do.nascimento.puertas@fb.com', 'robson.luiz.do.nascimento.puertas');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARIA ALVES SUTIL', '2014-07-09', '2014-05-07', 1, 1, 'maria.alves.sutil@hotmail.com', 'maria.alves.sutil');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('QUITERIA LOURENCO DE LIMA', '2014-07-07', '2014-02-22', 0, 0, 'quiteria.lourenco.de.lima@fb.com', 'quiteria.lourenco.de.lima');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('CRISTIANE PAES CORDOBA', '2014-07-05', '2014-04-02', 1, 0, 'cristiane.paes.cordoba@gmail.com', 'cristiane.paes.cordoba');
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-14', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-12', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-04', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-26', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-04', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-12', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-13', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-05', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-27', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-07-11', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-21', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-16', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-17', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-07-13', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-28', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-04', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-01', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-12', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-25', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-07', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-21', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-23', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-26', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-22', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-07-12', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-04', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-10', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-07', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-15', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-12', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-05', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-16', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-25', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-03', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-03', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-08', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-30', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-10', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-02', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-07-05', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-01', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-21', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-07-10', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-17', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-24', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-28', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-18', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-18', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-07-06', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-19', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-05', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-14', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-07', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-20', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-24', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-28', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-14', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-21', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-15', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-09', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-27', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-17', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-13', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-28', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-26', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-09', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-11', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-08', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-06', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-29', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-12', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-28', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-04', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-22', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-15', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-02', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-19', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-07', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-25', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-30', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-20', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-07', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-25', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-05', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-27', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-08', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-17', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-22', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-08', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-27', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-23', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-13', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-24', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-30', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-21', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-13', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-27', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-02', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-14', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-19', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
