INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('30499-783', '0610', 'F', 'CARLOS SERGIO URBANIN', '2014-02-01', 0, 'Mauritius', 'carlos.sergio.urbanin@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('38225-186', '7308', 'F', 'SONIA MARIA MARTINEZ PENITENTE', '2014-06-05', 0, 'Iraq', 'sonia.maria.martinez.penitente@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('32766-897', '8205', 'F', 'ADAIL BANDINELLE DE MORAES', '2014-05-07', 1, 'Gabon', 'adail.bandinelle.de.moraes@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('53574-968', '0704', 'F', 'AFONSO BARBOSA DA SILVA', '2014-12-04', 1, 'Barbados', 'afonso.barbosa.da.silva@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('77174-642', '7921', 'F', 'LUIZ FERNANDO DA SILVA AMORIM', '2014-01-30', 0, 'Norway', 'luiz.fernando.da.silva.amorim@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('91462-413', '8415', 'F', 'WANDERSON COSMO DE ARAUJO', '2014-09-28', 0, 'Kazakhstan', 'wanderson.cosmo.de.araujo@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('51549-269', '9717', 'M', 'HABIB FAHED', '2014-08-20', 0, 'Grenada', 'habib.fahed@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('57632-710', '4984', 'M', 'OLGA PEREIRA', '2014-07-17', 1, 'Macedonia', 'olga.pereira@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('11387-873', '0111', 'F', 'SONIA MARIA MARTINEZ PENITENTE', '2014-11-24', 0, 'Belgium', 'sonia.maria.martinez.penitente@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('70249-407', '7494', 'F', 'WANDERSON COSMO DE ARAUJO', '2014-12-18', 1, 'Swaziland', 'wanderson.cosmo.de.araujo@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('67104-227', '5257', 'F', 'MARLENE SANTANA MARTINS', '2014-07-01', 1, 'Moldova', 'marlene.santana.martins@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('47486-516', '4130', 'F', 'SILVIA MENDES', '2014-06-13', 0, 'Finland', 'silvia.mendes@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('12837-614', '0150', 'F', 'HELOIZA ALMEIDA DOS SANTOS', '2014-10-21', 0, 'Malawi', 'heloiza.almeida.dos.santos@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('06105-342', '5053', 'F', 'ALIETE FRANCISCA PRATES', '2014-10-25', 1, 'Vanuatu', 'aliete.francisca.prates@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('23969-372', '5741', 'F', 'ILZA XAVIER DE LIMA ARAUJO', '2014-05-31', 1, 'Kiribati', 'ilza.xavier.de.lima.araujo@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('12997-583', '0821', 'M', 'SOLANGE APARECIDA DO PRADO DA CRUZ', '2014-08-13', 1, 'Korea South', 'solange.aparecida.do.prado.da.cruz@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('33686-865', '1918', 'M', 'AURELINDA BATISTA DA SILVA', '2014-11-15', 1, 'Vietnam', 'aurelinda.batista.da.silva@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('92603-454', '1878', 'F', 'JOSE RIBAMAR BEZERRA SA', '2014-07-05', 0, 'Montenegro', 'jose.ribamar.bezerra.sa@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('21124-376', '4786', 'M', 'VIOLINDO DE SOUZA', '2014-05-05', 1, 'Suriname', 'violindo.de.souza@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('86051-489', '7330', 'M', 'ANTONIA BORGES DA SILVA', '2014-12-24', 1, 'Kyrgyzstan', 'antonia.borges.da.silva@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('82508-241', '7573', 'M', 'BEATRIZ PEREIRA LIMA', '2014-08-14', 1, 'The Netherlands', 'beatriz.pereira.lima@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('65115-156', '9636', 'F', 'MARIA LOURENCO ARISTIDES', '2014-11-11', 0, 'Turkey', 'maria.lourenco.aristides@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('45016-331', '3983', 'M', 'LUCINEIDE DE MORAES DO CARMO', '2014-01-04', 1, 'Trinidad & Tobago', 'lucineide.de.moraes.do.carmo@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('66176-490', '2478', 'F', 'EUZEBIO DA SILVA CEZAR', '2014-12-14', 1, 'Spain', 'euzebio.da.silva.cezar@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('62663-999', '7010', 'F', 'HELOIZA ALMEIDA DOS SANTOS', '2014-05-01', 1, 'Mali', 'heloiza.almeida.dos.santos@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('97463-977', '2570', 'F', 'SILVIO TSIPE RAIRATE', '2014-05-30', 0, 'Belize', 'silvio.tsipe.rairate@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('63377-314', '8392', 'M', 'EDIR DIAS DE CARVALHO', '2014-11-26', 0, 'Kuwait', 'edir.dias.de.carvalho@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('14706-939', '7092', 'F', 'NEIZA MARIA LEITE DA SILVA', '2014-08-08', 0, 'Libya', 'neiza.maria.leite.da.silva@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('13502-004', '0844', 'M', 'THANIA CRISTINA DA SILVA BARNABE', '2014-12-20', 1, 'Madagascar', 'thania.cristina.da.silva.barnabe@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('31742-968', '3305', 'F', 'RUZINO ANTUNES DA SILVA', '2014-07-02', 0, 'Romania', 'ruzino.antunes.da.silva@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('54114-570', '8577', 'F', 'AUGUSTA ALVES DOS SANTOS', '2014-11-10', 1, 'Belarus', 'augusta.alves.dos.santos@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('72371-615', '2507', 'M', 'RITA IRACI ALMEIDA DA SILVA', '2014-08-26', 1, 'Uzbekistan', 'rita.iraci.almeida.da.silva@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('78504-285', '5317', 'M', 'AUGUSTA ALVES DOS SANTOS', '2014-06-11', 0, 'Seychelles', 'augusta.alves.dos.santos@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('08264-787', '4712', 'M', 'RUBENSMORBECK LEITE', '2014-07-29', 0, 'Swaziland', 'rubensmorbeck.leite@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('30197-583', '4032', 'F', 'ROBSON LUIZ DO NASCIMENTO PUERTAS', '2014-06-17', 0, 'Belgium', 'robson.luiz.do.nascimento.puertas@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('28415-445', '8952', 'M', 'QUITERIA LOURENCO DE LIMA', '2014-03-25', 1, 'Monaco', 'quiteria.lourenco.de.lima@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('23623-133', '4901', 'M', 'ADAIL BANDINELLE DE MORAES', '2014-11-11', 0, 'Algeria', 'adail.bandinelle.de.moraes@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('86290-285', '4487', 'F', 'GUIOMAR TRELHA FRANCA', '2014-03-29', 1, 'Cameroon', 'guiomar.trelha.franca@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('16456-474', '5293', 'M', 'SILVIO TSIPE RAIRATE', '2014-08-14', 1, 'Taiwan', 'silvio.tsipe.rairate@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('97963-189', '2094', 'M', 'ADENILTON JOSE DE MIRANDA', '2014-02-12', 1, 'Denmark', 'adenilton.jose.de.miranda@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('72552-242', '9159', 'F', 'ELOIR CARLOS FIRMINO', '2014-10-17', 0, 'Mauritania', 'eloir.carlos.firmino@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('88177-031', '4535', 'M', 'LIDIANE DO PRADO BRITE', '2014-06-25', 1, 'Switzerland', 'lidiane.do.prado.brite@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('06085-820', '3714', 'M', 'JORGE TETSUO TAIRA', '2014-06-14', 1, 'Haiti', 'jorge.tetsuo.taira@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('97336-805', '4887', 'F', 'RUZINO ANTUNES DA SILVA', '2014-01-05', 1, 'Costa Rica', 'ruzino.antunes.da.silva@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('22296-267', '9844', 'F', 'CELIA CRISTINA PEREIRA PINTO DOS SANTOS', '2014-09-17', 1, 'Guyana', 'celia.cristina.pereira.pinto.dos.santos@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('64901-987', '5495', 'M', 'JOSE RIBAMAR BEZERRA SA', '2014-02-13', 0, 'Bahrain', 'jose.ribamar.bezerra.sa@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('53176-996', '2694', 'F', 'JOSE NUNES PEREIRA', '2014-01-09', 0, 'Egypt', 'jose.nunes.pereira@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('01191-461', '5045', 'F', 'ROBSON LUIZ DO NASCIMENTO PUERTAS', '2014-09-15', 0, 'Kosovo', 'robson.luiz.do.nascimento.puertas@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('18681-991', '5883', 'M', 'ILZA XAVIER DE LIMA ARAUJO', '2014-03-07', 1, 'Malta', 'ilza.xavier.de.lima.araujo@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('24673-983', '3846', 'F', 'OSWALDIR GOMES', '2014-08-13', 0, 'Burkina Faso', 'oswaldir.gomes@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('92155-677', '4735', 'F', 'NICANOR FELIZARDO DOS REIS', '2014-02-25', 0, 'Iran', 'nicanor.felizardo.dos.reis@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('52516-891', '4582', 'F', 'WANDERSON COSMO DE ARAUJO', '2014-12-08', 1, 'Senegal', 'wanderson.cosmo.de.araujo@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('74250-270', '1108', 'M', 'MAGALI SANCHES', '2014-09-08', 0, 'Russia', 'magali.sanches@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('32157-732', '7707', 'M', 'ARISMARES SOUZA PRATES', '2014-11-13', 1, 'Sudan', 'arismares.souza.prates@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('38452-173', '1522', 'F', 'JOSENOTARIO MUNGO', '2014-12-23', 1, 'Antigua & Barbuda', 'josenotario.mungo@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('35717-918', '3636', 'F', 'NADIACUIABANO KUNZE', '2014-02-09', 1, 'Chile', 'nadiacuiabano.kunze@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('80667-314', '3716', 'M', 'GLAUBER DA COSTA ARRUDA', '2014-03-08', 1, 'Palau', 'glauber.da.costa.arruda@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('76230-655', '8942', 'M', 'HELOIZA ALMEIDA DOS SANTOS', '2014-06-01', 1, 'Denmark', 'heloiza.almeida.dos.santos@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('14842-372', '6860', 'F', 'WILSON CONCEICAO DE MIRANDA', '2014-02-16', 0, 'Kuwait', 'wilson.conceicao.de.miranda@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('16518-016', '1877', 'M', 'JOAO DE LUCA', '2014-12-24', 0, 'St. Kitts & Nevis', 'joao.de.luca@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('66735-932', '9037', 'F', 'MARCIA DA SILVA OLIVEIRA', '2014-08-18', 1, 'Australia', 'marcia.da.silva.oliveira@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('18454-771', '4197', 'M', 'ANA PAULA FIGUEIREDO DA ROCHA', '2014-06-11', 0, 'Sao Tome & Principe', 'ana.paula.figueiredo.da.rocha@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('47114-793', '2156', 'F', 'LOURENCO DIAS', '2014-10-15', 1, 'Serbia', 'lourenco.dias@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('71564-757', '9849', 'F', 'CELIA CRISTINA PEREIRA PINTO DOS SANTOS', '2014-03-07', 1, 'Somalia', 'celia.cristina.pereira.pinto.dos.santos@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('88994-386', '5306', 'F', 'AUGUSTA ALVES DOS SANTOS', '2014-06-25', 1, 'Greece', 'augusta.alves.dos.santos@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('21937-188', '9698', 'M', 'SOLANGE APARECIDA DO PRADO DA CRUZ', '2014-12-25', 1, 'Mongolia', 'solange.aparecida.do.prado.da.cruz@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('96957-748', '4342', 'F', 'GLAUBER DA COSTA ARRUDA', '2014-11-30', 0, 'Laos', 'glauber.da.costa.arruda@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('23415-558', '6344', 'F', 'MARIA DE LOURDES FERNANDES DIAS', '2014-06-02', 0, 'Tanzania', 'maria.de.lourdes.fernandes.dias@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('53704-637', '9311', 'F', 'MARIA DO CARMO JERONIMO SILVA', '2014-03-19', 1, 'Nauru', 'maria.do.carmo.jeronimo.silva@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('43334-290', '6699', 'F', 'DIRCEU DE MATTOS', '2014-12-28', 1, 'Georgia', 'dirceu.de.mattos@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('73348-248', '4201', 'F', 'JOAO MAURILIO DA SILVA', '2014-08-24', 1, 'Turkey', 'joao.maurilio.da.silva@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('34747-836', '4228', 'F', 'KLEBER MAGALHAES FERREIRA', '2014-06-29', 0, 'Morocco', 'kleber.magalhaes.ferreira@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('48698-676', '0305', 'F', 'LOURENCO DIAS', '2014-11-13', 0, 'Sierra Leone', 'lourenco.dias@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('37720-287', '4593', 'M', 'RAMAO CARDOSO', '2014-07-20', 1, 'Senegal', 'ramao.cardoso@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('83685-753', '9343', 'F', 'LUIZA ROTTLISBERGER SILVA', '2014-10-05', 1, 'Botswana', 'luiza.rottlisberger.silva@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('93090-953', '6593', 'M', 'LAURO JOSE DA SILVA', '2014-05-08', 0, 'Peru', 'lauro.jose.da.silva@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('65576-042', '5335', 'M', 'SEBASTIANA BENEDITA DA COSTA', '2014-06-24', 0, 'United States of America', 'sebastiana.benedita.da.costa@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('75452-274', '4280', 'M', 'JULIO APARECIDO DE SOUZA', '2014-07-12', 1, 'Uruguay', 'julio.aparecido.de.souza@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('79021-275', '7161', 'M', 'ALBERTO FEIZAR CARDOSO ABDALA', '2014-06-22', 1, 'Liberia', 'alberto.feizar.cardoso.abdala@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('97683-529', '3760', 'M', 'LUZIA RODRIGUES DE OLIVEIRA', '2014-05-09', 0, 'Bolivia', 'luzia.rodrigues.de.oliveira@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('41474-873', '7308', 'M', 'HELIO SAMBATTI', '2014-11-06', 1, 'Chad', 'helio.sambatti@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('70973-406', '0550', 'M', 'EUSTAQUIA PRIETO', '2014-11-21', 1, 'Zimbabwe', 'eustaquia.prieto@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('28237-538', '5670', 'F', 'SEBASTIANA BENEDITA DA COSTA', '2014-09-03', 0, 'Bahrain', 'sebastiana.benedita.da.costa@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('20866-679', '9475', 'M', 'AUGUSTA ALVES DOS SANTOS', '2014-05-02', 0, 'Libya', 'augusta.alves.dos.santos@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('70435-800', '1016', 'M', 'DILMA DE SOUZA', '2014-07-21', 0, 'Spain', 'dilma.de.souza@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('98197-467', '3529', 'F', 'ABILIO CAVALHEIRO', '2014-05-07', 1, 'Malta', 'abilio.cavalheiro@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('03089-752', '1176', 'F', 'BENILDE PERES DE CAMPOS', '2014-02-16', 0, 'Morocco', 'benilde.peres.de.campos@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('82349-415', '8663', 'M', 'SILVIA MENDES', '2014-05-26', 0, 'Israel', 'silvia.mendes@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('83914-642', '9111', 'F', 'ALBERTO FEIZAR CARDOSO ABDALA', '2014-12-18', 1, 'Tunisia', 'alberto.feizar.cardoso.abdala@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('06575-884', '9485', 'M', 'LUCINEIDE DE MORAES DO CARMO', '2014-08-13', 1, 'Jamaica', 'lucineide.de.moraes.do.carmo@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('35699-547', '0764', 'F', 'NEIZA MARIA LEITE DA SILVA', '2014-09-05', 0, 'Chad', 'neiza.maria.leite.da.silva@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('94599-930', '1577', 'F', 'HABIB FAHED', '2014-03-20', 1, 'Togo', 'habib.fahed@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('98951-619', '6536', 'F', 'JOSENOTARIO MUNGO', '2014-10-11', 0, 'Taiwan', 'josenotario.mungo@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('61973-534', '2551', 'F', 'MIGUEL VENCESLAU MACIEL DE CAMPOS', '2014-04-26', 1, 'Australia', 'miguel.venceslau.maciel.de.campos@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('01552-911', '1157', 'F', 'CELIA CRISTINA PEREIRA PINTO DOS SANTOS', '2014-04-01', 1, 'Venezuela', 'celia.cristina.pereira.pinto.dos.santos@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('84160-946', '6101', 'F', 'OSVALDO PEREIRA BARBOSA', '2014-09-13', 1, 'Bahrain', 'osvaldo.pereira.barbosa@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('88555-097', '8550', 'F', 'CLEODETE CANOLA DE CAMPOS', '2014-08-21', 1, 'St. Lucia', 'cleodete.canola.de.campos@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('52090-926', '8340', 'M', 'MARILEIA NUNES DE OLIVEIRA', '2014-05-15', 0, 'Central African Republic', 'marileia.nunes.de.oliveira@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('38056-963', '3193', 'F', 'ILZA XAVIER DE LIMA ARAUJO', '2014-09-25', 0, 'The Netherlands', 'ilza.xavier.de.lima.araujo@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('58508-913', '8070', 'F', 'ZILDA MARTINS DE SOUZA', '2014-10-07', 0, 'Uzbekistan', 'zilda.martins.de.souza@hotmail.com');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ALIETE FRANCISCA PRATES', '2014-07-05', '2014-05-19', 1, 0, 'aliete.francisca.prates@gmail.com', 'aliete.francisca.prates');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARIA DO CARMO JERONIMO SILVA', '2014-07-05', '2014-06-20', 1, 1, 'maria.do.carmo.jeronimo.silva@hotmail.com', 'maria.do.carmo.jeronimo.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('INES APARECIDA DA SILVA', '2014-07-07', '2014-01-26', 1, 1, 'ines.aparecida.da.silva@gmail.com', 'ines.aparecida.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('NICANOR FELIZARDO DOS REIS', '2014-07-01', '2014-04-10', 1, 1, 'nicanor.felizardo.dos.reis@fb.com', 'nicanor.felizardo.dos.reis');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('BEATRIZ PEREIRA LIMA', '2014-07-10', '2014-01-31', 1, 0, 'beatriz.pereira.lima@gmail.com', 'beatriz.pereira.lima');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ZILDA MARTINS DE SOUZA', '2014-07-13', '2014-02-15', 0, 0, 'zilda.martins.de.souza@fb.com', 'zilda.martins.de.souza');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ELZA LIMA DE SOUZA MANSANO', '2014-07-11', '2014-06-17', 1, 1, 'elza.lima.de.souza.mansano@fb.com', 'elza.lima.de.souza.mansano');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('AMERICO FRANCISCO DA SILVA', '2014-07-10', '2014-04-26', 1, 1, 'americo.francisco.da.silva@hotmail.com', 'americo.francisco.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LUZIA RODRIGUES DE OLIVEIRA', '2014-07-04', '2014-05-08', 1, 0, 'luzia.rodrigues.de.oliveira@hotmail.com', 'luzia.rodrigues.de.oliveira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ZILMA MARQUES GONCALVES RODRIGUES', '2014-07-05', '2014-03-24', 1, 0, 'zilma.marques.goncalves.rodrigues@fb.com', 'zilma.marques.goncalves.rodrigues');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MIGUEL JOAQUIM SILVA', '2014-07-05', '2014-05-14', 1, 1, 'miguel.joaquim.silva@hotmail.com', 'miguel.joaquim.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('DILMA DE SOUZA', '2014-07-05', '2014-01-10', 0, 0, 'dilma.de.souza@gmail.com', 'dilma.de.souza');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('VALDOMIRO LEITE DE SA', '2014-07-02', '2014-06-24', 1, 0, 'valdomiro.leite.de.sa@gmail.com', 'valdomiro.leite.de.sa');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JORGE TETSUO TAIRA', '2014-07-06', '2014-02-18', 1, 0, 'jorge.tetsuo.taira@gmail.com', 'jorge.tetsuo.taira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ANA ALVES LUCIANO', '2014-07-09', '2014-04-07', 1, 0, 'ana.alves.luciano@hotmail.com', 'ana.alves.luciano');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('BENJAMIM GAUNA', '2014-07-01', '2014-02-14', 0, 0, 'benjamim.gauna@hotmail.com', 'benjamim.gauna');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARIA FATIMA SCHEUNEMANN MIRANDA', '2014-07-02', '2014-01-05', 0, 0, 'maria.fatima.scheunemann.miranda@fb.com', 'maria.fatima.scheunemann.miranda');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ANDRE LUIS CASTRILLON GARCIA', '2014-07-10', '2014-02-07', 1, 1, 'andre.luis.castrillon.garcia@fb.com', 'andre.luis.castrillon.garcia');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ELEONILDA DE LIMA RODRIGUES', '2014-07-05', '2014-05-01', 0, 0, 'eleonilda.de.lima.rodrigues@gmail.com', 'eleonilda.de.lima.rodrigues');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('DIRCEU DE MATTOS', '2014-07-02', '2014-03-25', 1, 0, 'dirceu.de.mattos@gmail.com', 'dirceu.de.mattos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JOSE RIBAMAR BEZERRA SA', '2014-07-03', '2014-01-03', 1, 1, 'jose.ribamar.bezerra.sa@gmail.com', 'jose.ribamar.bezerra.sa');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ELEONILDA DE LIMA RODRIGUES', '2014-07-08', '2014-06-18', 0, 0, 'eleonilda.de.lima.rodrigues@fb.com', 'eleonilda.de.lima.rodrigues');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('HELOIZA ALMEIDA DOS SANTOS', '2014-07-06', '2014-02-10', 0, 0, 'heloiza.almeida.dos.santos@gmail.com', 'heloiza.almeida.dos.santos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARIA DE LOURDES FERNANDES DIAS', '2014-07-02', '2014-06-22', 1, 0, 'maria.de.lourdes.fernandes.dias@fb.com', 'maria.de.lourdes.fernandes.dias');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JOSENOTARIO MUNGO', '2014-07-11', '2014-02-07', 0, 0, 'josenotario.mungo@fb.com', 'josenotario.mungo');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('NADIACUIABANO KUNZE', '2014-07-05', '2014-06-18', 1, 1, 'nadiacuiabano.kunze@hotmail.com', 'nadiacuiabano.kunze');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('HELIO SAMBATTI', '2014-07-05', '2014-03-25', 1, 1, 'helio.sambatti@gmail.com', 'helio.sambatti');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('SUELY DA SILVA CAVALCANTI', '2014-07-03', '2014-04-07', 0, 0, 'suely.da.silva.cavalcanti@gmail.com', 'suely.da.silva.cavalcanti');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ROSILENE ALMEIDA DA SILVA', '2014-07-06', '2014-01-09', 0, 1, 'rosilene.almeida.da.silva@gmail.com', 'rosilene.almeida.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JORGE TETSUO TAIRA', '2014-07-13', '2014-01-25', 1, 1, 'jorge.tetsuo.taira@fb.com', 'jorge.tetsuo.taira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ANA ALVES LUCIANO', '2014-07-11', '2014-03-09', 1, 1, 'ana.alves.luciano@fb.com', 'ana.alves.luciano');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ROBSON LUIZ DO NASCIMENTO PUERTAS', '2014-07-05', '2014-05-09', 0, 1, 'robson.luiz.do.nascimento.puertas@gmail.com', 'robson.luiz.do.nascimento.puertas');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('INES APARECIDA DA SILVA', '2014-07-02', '2014-05-02', 0, 1, 'ines.aparecida.da.silva@fb.com', 'ines.aparecida.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('IROCIDES APARECIDA FERREIRA', '2014-07-07', '2014-03-13', 0, 1, 'irocides.aparecida.ferreira@fb.com', 'irocides.aparecida.ferreira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ANA PAULA FIGUEIREDO DA ROCHA', '2014-07-07', '2014-02-18', 1, 1, 'ana.paula.figueiredo.da.rocha@gmail.com', 'ana.paula.figueiredo.da.rocha');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('TIMOTEO BATISTA LEITE', '2014-07-05', '2014-06-20', 1, 1, 'timoteo.batista.leite@gmail.com', 'timoteo.batista.leite');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('RAMAO CARDOSO', '2014-07-09', '2014-01-18', 0, 1, 'ramao.cardoso@gmail.com', 'ramao.cardoso');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LOURIVAL ROSA GUIMARAES', '2014-07-11', '2014-05-20', 1, 1, 'lourival.rosa.guimaraes@fb.com', 'lourival.rosa.guimaraes');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LIDIANE DO PRADO BRITE', '2014-07-07', '2014-05-29', 1, 0, 'lidiane.do.prado.brite@hotmail.com', 'lidiane.do.prado.brite');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('BEATRIZ PEREIRA LIMA', '2014-07-02', '2014-05-23', 0, 1, 'beatriz.pereira.lima@hotmail.com', 'beatriz.pereira.lima');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('AFONSO BARBOSA DA SILVA', '2014-07-06', '2014-02-08', 1, 0, 'afonso.barbosa.da.silva@hotmail.com', 'afonso.barbosa.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('CARLOS SERGIO URBANIN', '2014-07-04', '2014-06-26', 0, 1, 'carlos.sergio.urbanin@hotmail.com', 'carlos.sergio.urbanin');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ROSILENE ALMEIDA DA SILVA', '2014-07-05', '2014-03-11', 0, 0, 'rosilene.almeida.da.silva@gmail.com', 'rosilene.almeida.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('THANIA CRISTINA DA SILVA BARNABE', '2014-07-04', '2014-04-25', 1, 1, 'thania.cristina.da.silva.barnabe@hotmail.com', 'thania.cristina.da.silva.barnabe');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('BENEDITO AMBROSIO DA COSTA', '2014-07-12', '2014-05-10', 1, 0, 'benedito.ambrosio.da.costa@hotmail.com', 'benedito.ambrosio.da.costa');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('NICANOR FELIZARDO DOS REIS', '2014-07-11', '2014-02-20', 1, 1, 'nicanor.felizardo.dos.reis@gmail.com', 'nicanor.felizardo.dos.reis');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARCIA DA SILVA OLIVEIRA', '2014-07-03', '2014-05-26', 1, 1, 'marcia.da.silva.oliveira@gmail.com', 'marcia.da.silva.oliveira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('SILVIA MENDES', '2014-07-04', '2014-06-21', 0, 1, 'silvia.mendes@fb.com', 'silvia.mendes');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('OBADIAS MARCAL DE OLIVEIRA', '2014-07-03', '2014-01-24', 0, 1, 'obadias.marcal.de.oliveira@gmail.com', 'obadias.marcal.de.oliveira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ELISABETE ROMERO NOBRE LEAL', '2014-07-13', '2014-04-12', 1, 1, 'elisabete.romero.nobre.leal@hotmail.com', 'elisabete.romero.nobre.leal');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('BENILDE PERES DE CAMPOS', '2014-07-07', '2014-01-07', 0, 1, 'benilde.peres.de.campos@fb.com', 'benilde.peres.de.campos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('VIRGILIA DIAS VIEIRA', '2014-07-04', '2014-04-17', 0, 0, 'virgilia.dias.vieira@gmail.com', 'virgilia.dias.vieira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('CORNELIO DIAS DUARTE', '2014-07-01', '2014-03-24', 1, 1, 'cornelio.dias.duarte@gmail.com', 'cornelio.dias.duarte');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JOSE EVALDO DA SILVA', '2014-07-03', '2014-04-30', 1, 1, 'jose.evaldo.da.silva@gmail.com', 'jose.evaldo.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ELOIR CARLOS FIRMINO', '2014-07-10', '2014-01-09', 0, 1, 'eloir.carlos.firmino@gmail.com', 'eloir.carlos.firmino');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARIA DAIANE DE ARAUJO SOUZA', '2014-07-08', '2014-03-28', 0, 0, 'maria.daiane.de.araujo.souza@gmail.com', 'maria.daiane.de.araujo.souza');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('DIAMANTINA DA SILVA SOARES', '2014-07-08', '2014-04-27', 0, 0, 'diamantina.da.silva.soares@hotmail.com', 'diamantina.da.silva.soares');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LIDIANE DO PRADO BRITE', '2014-07-03', '2014-01-24', 1, 1, 'lidiane.do.prado.brite@hotmail.com', 'lidiane.do.prado.brite');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ALICE APARECIDA DOS SANTOS', '2014-07-03', '2014-05-10', 0, 0, 'alice.aparecida.dos.santos@gmail.com', 'alice.aparecida.dos.santos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ABIGAIL DA SILVA LARA', '2014-07-11', '2014-04-04', 0, 1, 'abigail.da.silva.lara@fb.com', 'abigail.da.silva.lara');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('NEIZA MARIA LEITE DA SILVA', '2014-07-03', '2014-02-28', 0, 1, 'neiza.maria.leite.da.silva@gmail.com', 'neiza.maria.leite.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARIA DO CARMO JERONIMO SILVA', '2014-07-13', '2014-02-14', 0, 0, 'maria.do.carmo.jeronimo.silva@fb.com', 'maria.do.carmo.jeronimo.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('DIAMANTINA DA SILVA SOARES', '2014-07-11', '2014-01-20', 1, 0, 'diamantina.da.silva.soares@hotmail.com', 'diamantina.da.silva.soares');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARIA HILDA MACHADO', '2014-07-05', '2014-02-21', 0, 1, 'maria.hilda.machado@fb.com', 'maria.hilda.machado');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('EDIO JUSTO BORGES', '2014-07-11', '2014-02-07', 0, 0, 'edio.justo.borges@gmail.com', 'edio.justo.borges');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARIA DO CARMO JERONIMO SILVA', '2014-07-03', '2014-02-28', 0, 0, 'maria.do.carmo.jeronimo.silva@hotmail.com', 'maria.do.carmo.jeronimo.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JOAO DE LUCA', '2014-07-01', '2014-05-26', 0, 1, 'joao.de.luca@hotmail.com', 'joao.de.luca');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('BENEDITA GAUDENCIO DA COSTA', '2014-07-12', '2014-06-13', 1, 1, 'benedita.gaudencio.da.costa@gmail.com', 'benedita.gaudencio.da.costa');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JOSE RIBAMAR BEZERRA SA', '2014-07-13', '2014-01-06', 1, 0, 'jose.ribamar.bezerra.sa@gmail.com', 'jose.ribamar.bezerra.sa');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('CLAUDIO BARBOSA DOS SANTOS', '2014-07-04', '2014-02-19', 0, 0, 'claudio.barbosa.dos.santos@hotmail.com', 'claudio.barbosa.dos.santos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('EDIO JUSTO BORGES', '2014-07-11', '2014-05-30', 1, 0, 'edio.justo.borges@gmail.com', 'edio.justo.borges');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('DELCY MARTINS DA SILVA', '2014-07-01', '2014-06-26', 1, 0, 'delcy.martins.da.silva@hotmail.com', 'delcy.martins.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('BENILDE PERES DE CAMPOS', '2014-07-04', '2014-01-14', 0, 1, 'benilde.peres.de.campos@gmail.com', 'benilde.peres.de.campos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JOAO DE LUCA', '2014-07-10', '2014-02-16', 1, 1, 'joao.de.luca@gmail.com', 'joao.de.luca');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ABILIO CAVALHEIRO', '2014-07-04', '2014-06-24', 0, 0, 'abilio.cavalheiro@gmail.com', 'abilio.cavalheiro');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JOSENOTARIO MUNGO', '2014-07-12', '2014-06-17', 0, 0, 'josenotario.mungo@gmail.com', 'josenotario.mungo');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('VIOLINDO DE SOUZA', '2014-07-10', '2014-05-06', 0, 1, 'violindo.de.souza@gmail.com', 'violindo.de.souza');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ADELSON LUIZ DA SILVA', '2014-07-07', '2014-03-10', 1, 0, 'adelson.luiz.da.silva@fb.com', 'adelson.luiz.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('NEIVA OBERGER FERREIRA', '2014-07-10', '2014-04-29', 0, 0, 'neiva.oberger.ferreira@gmail.com', 'neiva.oberger.ferreira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARIA ELENA ALVES', '2014-07-03', '2014-03-01', 1, 0, 'maria.elena.alves@fb.com', 'maria.elena.alves');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ANA PAULA FIGUEIREDO DA ROCHA', '2014-07-08', '2014-05-30', 1, 1, 'ana.paula.figueiredo.da.rocha@gmail.com', 'ana.paula.figueiredo.da.rocha');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ALICE DE SOUZA MIRANDA', '2014-07-05', '2014-04-10', 0, 0, 'alice.de.souza.miranda@hotmail.com', 'alice.de.souza.miranda');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('RONY HUDSON OLIVEIRA CANDEIRO', '2014-07-12', '2014-04-17', 0, 1, 'rony.hudson.oliveira.candeiro@gmail.com', 'rony.hudson.oliveira.candeiro');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('CORNELIO DIAS DUARTE', '2014-07-12', '2014-04-17', 1, 1, 'cornelio.dias.duarte@fb.com', 'cornelio.dias.duarte');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ALCEU DOS SANTOS', '2014-07-09', '2014-03-22', 1, 0, 'alceu.dos.santos@hotmail.com', 'alceu.dos.santos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ALCEU DOS SANTOS', '2014-07-05', '2014-05-11', 0, 0, 'alceu.dos.santos@hotmail.com', 'alceu.dos.santos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('SILVIA MENDES', '2014-07-13', '2014-01-04', 1, 0, 'silvia.mendes@hotmail.com', 'silvia.mendes');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('SILVIA MENDES', '2014-07-13', '2014-05-21', 1, 0, 'silvia.mendes@fb.com', 'silvia.mendes');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ANGELA APARECIDA BERNEGOZZE', '2014-07-02', '2014-03-15', 0, 1, 'angela.aparecida.bernegozze@fb.com', 'angela.aparecida.bernegozze');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARIA DAIANE DE ARAUJO SOUZA', '2014-07-05', '2014-02-17', 1, 0, 'maria.daiane.de.araujo.souza@fb.com', 'maria.daiane.de.araujo.souza');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ILZA XAVIER DE LIMA ARAUJO', '2014-07-03', '2014-02-27', 0, 0, 'ilza.xavier.de.lima.araujo@hotmail.com', 'ilza.xavier.de.lima.araujo');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('BENJAMIM GAUNA', '2014-07-03', '2014-01-04', 0, 0, 'benjamim.gauna@fb.com', 'benjamim.gauna');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('CLEODETE CANOLA DE CAMPOS', '2014-07-03', '2014-06-01', 0, 1, 'cleodete.canola.de.campos@fb.com', 'cleodete.canola.de.campos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('OBADIAS MARCAL DE OLIVEIRA', '2014-07-07', '2014-05-17', 1, 1, 'obadias.marcal.de.oliveira@gmail.com', 'obadias.marcal.de.oliveira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('AUGUSTA ALVES DOS SANTOS', '2014-07-01', '2014-02-13', 0, 0, 'augusta.alves.dos.santos@fb.com', 'augusta.alves.dos.santos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('DIAMANTINA DA SILVA SOARES', '2014-07-03', '2014-02-17', 0, 1, 'diamantina.da.silva.soares@gmail.com', 'diamantina.da.silva.soares');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JOANA ANTUNES', '2014-07-12', '2014-03-10', 1, 1, 'joana.antunes@fb.com', 'joana.antunes');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LAURA SEBASTIANA GURGEL', '2014-07-04', '2014-01-20', 1, 1, 'laura.sebastiana.gurgel@fb.com', 'laura.sebastiana.gurgel');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('SONIA MARIA MARTINEZ PENITENTE', '2014-07-02', '2014-04-14', 0, 0, 'sonia.maria.martinez.penitente@gmail.com', 'sonia.maria.martinez.penitente');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARIA ALVES SUTIL', '2014-07-13', '2014-02-19', 1, 0, 'maria.alves.sutil@fb.com', 'maria.alves.sutil');
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-29', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-12', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-02', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-04', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-20', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-03', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-11', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-09', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-21', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-03', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-25', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-03', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-11', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-04', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-08', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-05', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-17', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-30', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-14', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-10', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-05', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-01', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-01', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-05', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-12', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-07-09', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-26', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-19', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-14', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-08', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-15', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-18', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-16', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-10', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-08', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-27', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-07-10', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-02', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-03', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-09', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-25', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-23', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-23', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-12', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-16', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-14', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-03', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-24', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-19', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-30', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-21', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-11', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-18', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-06', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-03', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-06', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-08', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-17', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-11', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-22', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-25', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-27', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-13', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-24', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-03', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-23', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-18', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-02', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-01', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-21', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-08', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-20', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-01', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-17', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-26', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-14', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-30', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-19', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-25', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-07', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-18', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-02', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-03', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-09', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-14', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-10', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-03', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-22', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-30', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-03', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-10', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-25', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-15', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-12', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-04', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-15', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-05', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-02', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-03', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-16', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
