INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('61442-730', '5178', 'F', 'SEBASTIANA BENEDITA DA COSTA', '2014-06-12', 0, 'Macedonia', 'sebastiana.benedita.da.costa@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('16041-267', '7992', 'M', 'CRISTIANE PAES CORDOBA', '2014-08-06', 1, 'Swaziland', 'cristiane.paes.cordoba@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('97563-788', '3024', 'M', 'ANA ALVES LUCIANO', '2014-05-17', 1, 'Congo Democratic Republic', 'ana.alves.luciano@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('75830-429', '5852', 'F', 'ELZA LIMA DE SOUZA MANSANO', '2014-07-08', 0, 'Israel', 'elza.lima.de.souza.mansano@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('50778-622', '5300', 'M', 'LAURO JOSE DA SILVA', '2014-05-19', 0, 'Serbia', 'lauro.jose.da.silva@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('57369-430', '6417', 'F', 'JOAQUIM BORGES RODRIGUES', '2014-10-26', 0, 'India', 'joaquim.borges.rodrigues@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('86000-193', '4773', 'M', 'AURELINDA BATISTA DA SILVA', '2014-01-19', 1, 'Cape Verde', 'aurelinda.batista.da.silva@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('70688-133', '5332', 'M', 'ANDRE LUIS CASTRILLON GARCIA', '2014-09-03', 0, 'Costa Rica', 'andre.luis.castrillon.garcia@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('60783-219', '5859', 'F', 'VILMA VITORIA DE SOUZA MESSA', '2014-05-30', 0, 'Equatorial Guinea', 'vilma.vitoria.de.souza.messa@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('77807-375', '7410', 'F', 'ELEONILDA DE LIMA RODRIGUES', '2014-03-14', 0, 'Equatorial Guinea', 'eleonilda.de.lima.rodrigues@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('36916-347', '0026', 'F', 'ABILIO CAVALHEIRO', '2014-01-21', 1, 'The Netherlands', 'abilio.cavalheiro@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('91484-842', '0689', 'M', 'EDIR DIAS DE CARVALHO', '2014-07-10', 0, 'Monaco', 'edir.dias.de.carvalho@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('03169-129', '5280', 'M', 'MARIA DE LOURDES FERNANDES DIAS', '2014-05-11', 1, 'Morocco', 'maria.de.lourdes.fernandes.dias@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('71517-726', '3099', 'F', 'LOURIVAL ROSA GUIMARAES', '2014-10-05', 1, 'Central African Republic', 'lourival.rosa.guimaraes@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('12155-211', '2412', 'M', 'ELZA LIMA DE SOUZA MANSANO', '2014-08-31', 0, 'Kyrgyzstan', 'elza.lima.de.souza.mansano@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('42315-720', '6127', 'M', 'ALICE DE SOUZA MIRANDA', '2014-05-26', 0, 'Benin', 'alice.de.souza.miranda@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('21701-418', '9772', 'F', 'ELOIDE CAVANHA', '2014-10-19', 0, 'Iran', 'eloide.cavanha@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('74822-774', '2553', 'F', 'QUITERIA LOURENCO DE LIMA', '2014-08-30', 1, 'Uzbekistan', 'quiteria.lourenco.de.lima@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('78099-807', '7372', 'F', 'AFONSO BARBOSA DA SILVA', '2014-12-14', 0, 'Croatia', 'afonso.barbosa.da.silva@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('45493-929', '3876', 'M', 'GLAUBER DA COSTA ARRUDA', '2014-04-26', 0, 'Jordan', 'glauber.da.costa.arruda@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('03542-181', '6817', 'F', 'BENEDITO AMBROSIO DA COSTA', '2014-11-13', 1, 'Tajikistan', 'benedito.ambrosio.da.costa@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('07405-017', '9275', 'M', 'MIGUEL VENCESLAU MACIEL DE CAMPOS', '2014-04-22', 1, 'Senegal', 'miguel.venceslau.maciel.de.campos@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('56487-380', '3043', 'M', 'ELOIDE CAVANHA', '2014-11-23', 1, 'Lebanon', 'eloide.cavanha@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('79176-144', '9841', 'M', 'ATAIDE DIAS DE MOURA', '2014-05-21', 1, 'Ethiopia', 'ataide.dias.de.moura@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('07906-295', '8004', 'F', 'LUCINEIDE DE MORAES DO CARMO', '2014-11-27', 1, 'United States of America', 'lucineide.de.moraes.do.carmo@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('36477-786', '8614', 'M', 'ANA ALVES LUCIANO', '2014-11-25', 1, 'Kiribati', 'ana.alves.luciano@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('11198-333', '3154', 'M', 'ZILDA MARTINS DE SOUZA', '2014-01-04', 1, 'Angola', 'zilda.martins.de.souza@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('38664-945', '5680', 'M', 'MARIA LOURENCO ARISTIDES', '2014-02-15', 1, 'Moldova', 'maria.lourenco.aristides@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('88405-377', '2072', 'F', 'RUBENSMORBECK LEITE', '2014-12-21', 1, 'Cyprus', 'rubensmorbeck.leite@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('84060-044', '0794', 'F', 'CARLOS SERGIO URBANIN', '2014-12-27', 1, 'Estonia', 'carlos.sergio.urbanin@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('23511-351', '2147', 'F', 'EUZEBIO DA SILVA CEZAR', '2014-05-12', 1, 'Bahrain', 'euzebio.da.silva.cezar@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('93262-363', '6176', 'M', 'ANA PAULA FIGUEIREDO DA ROCHA', '2014-05-11', 0, 'Ukraine', 'ana.paula.figueiredo.da.rocha@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('57298-257', '0858', 'M', 'ANA ALVES LUCIANO', '2014-02-13', 0, 'Italy', 'ana.alves.luciano@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('75734-918', '1198', 'F', 'OSVALDO PEREIRA BARBOSA', '2014-11-30', 0, 'Slovenia', 'osvaldo.pereira.barbosa@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('13139-044', '3511', 'F', 'RAMIRO VEDOVATO', '2014-03-27', 1, 'Nepal', 'ramiro.vedovato@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('79054-882', '8501', 'F', 'LAURO JOSE DA SILVA', '2014-03-21', 0, 'Korea North', 'lauro.jose.da.silva@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('76884-160', '4705', 'M', 'AFONSO BARBOSA DA SILVA', '2014-09-05', 1, 'Antigua & Barbuda', 'afonso.barbosa.da.silva@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('10716-618', '7712', 'M', 'RAMIRO VEDOVATO', '2014-08-29', 0, 'Sao Tome & Principe', 'ramiro.vedovato@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('36987-043', '9018', 'M', 'OLGA PEREIRA', '2014-10-02', 0, 'Canada', 'olga.pereira@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('37930-199', '6697', 'M', 'BENJAMIM GAUNA', '2014-01-03', 1, 'Norway', 'benjamim.gauna@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('60840-428', '4789', 'M', 'HELIO SAMBATTI', '2014-05-05', 1, 'Slovakia', 'helio.sambatti@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('11911-092', '0491', 'F', 'HELOIZA ALMEIDA DOS SANTOS', '2014-04-12', 1, 'Belgium', 'heloiza.almeida.dos.santos@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('71062-271', '3439', 'F', 'CELESIAORMOND RIBEIRO DE CAMPOS', '2014-12-09', 0, 'Ireland', 'celesiaormond.ribeiro.de.campos@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('17410-202', '8415', 'F', 'GLAUBER DA COSTA ARRUDA', '2014-11-03', 0, 'Togo', 'glauber.da.costa.arruda@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('56641-085', '2900', 'F', 'ILZA XAVIER DE LIMA ARAUJO', '2014-07-17', 1, 'Vatican City (Holy See)', 'ilza.xavier.de.lima.araujo@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('38159-291', '8842', 'F', 'ANTONIA BORGES DA SILVA', '2014-11-03', 1, 'Kenya', 'antonia.borges.da.silva@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('65223-071', '8485', 'F', 'ATAIDE DIAS DE MOURA', '2014-06-12', 0, 'Sweden', 'ataide.dias.de.moura@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('44641-883', '1350', 'M', 'JOSE EVALDO DA SILVA', '2014-08-13', 1, 'Cuba', 'jose.evaldo.da.silva@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('29404-696', '1669', 'M', 'EUZEBIO DA SILVA CEZAR', '2014-05-12', 0, 'Latvia', 'euzebio.da.silva.cezar@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('25631-612', '2425', 'F', 'LOURENCO DIAS', '2014-11-20', 1, 'Tuvalu', 'lourenco.dias@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('67178-590', '5563', 'M', 'ELOIR CARLOS FIRMINO', '2014-12-20', 0, 'Dominican Republic', 'eloir.carlos.firmino@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('29149-872', '5040', 'F', 'JULIO APARECIDO DE SOUZA', '2014-12-28', 0, 'San Marino', 'julio.aparecido.de.souza@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('96868-156', '6310', 'F', 'MIGUEL VENCESLAU MACIEL DE CAMPOS', '2014-10-19', 1, 'Norway', 'miguel.venceslau.maciel.de.campos@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('89089-428', '5365', 'F', 'ANA PAULA FIGUEIREDO DA ROCHA', '2014-08-29', 0, 'Rwanda', 'ana.paula.figueiredo.da.rocha@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('41676-302', '9417', 'F', 'VIOLINDO DE SOUZA', '2014-08-08', 1, 'Somalia', 'violindo.de.souza@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('17748-660', '5019', 'M', 'OBADIAS MARCAL DE OLIVEIRA', '2014-08-30', 0, 'Mauritania', 'obadias.marcal.de.oliveira@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('49250-568', '1894', 'M', 'INES APARECIDA DA SILVA', '2014-02-03', 1, 'Dominica', 'ines.aparecida.da.silva@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('22026-491', '1372', 'F', 'ABILIO CAVALHEIRO', '2014-08-03', 0, 'Niger', 'abilio.cavalheiro@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('55487-626', '8605', 'M', 'JOSE EVALDO DA SILVA', '2014-05-01', 1, 'Bhutan', 'jose.evaldo.da.silva@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('08219-944', '7716', 'M', 'RUZINO ANTUNES DA SILVA', '2014-09-15', 1, 'Guinea', 'ruzino.antunes.da.silva@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('64828-935', '8412', 'M', 'ZILMA MARQUES GONCALVES RODRIGUES', '2014-04-01', 1, 'Costa Rica', 'zilma.marques.goncalves.rodrigues@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('83021-489', '5176', 'M', 'OSWALDIR GOMES', '2014-04-01', 0, 'Qatar', 'oswaldir.gomes@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('60163-883', '2041', 'M', 'ATAIDE DIAS DE MOURA', '2014-11-29', 0, 'Paraguay', 'ataide.dias.de.moura@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('27422-446', '6964', 'F', 'ANA ALVES LUCIANO', '2014-01-02', 0, 'St. Kitts & Nevis', 'ana.alves.luciano@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('50744-845', '2936', 'F', 'CELIA CRISTINA PEREIRA PINTO DOS SANTOS', '2014-12-05', 1, 'Brazil', 'celia.cristina.pereira.pinto.dos.santos@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('05885-010', '0673', 'M', 'LIDIANE DO PRADO BRITE', '2014-04-29', 0, 'Azerbaijan', 'lidiane.do.prado.brite@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('65290-291', '5103', 'M', 'MARILEIA NUNES DE OLIVEIRA', '2014-03-11', 0, 'Egypt', 'marileia.nunes.de.oliveira@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('02891-662', '2077', 'M', 'VILMA VITORIA DE SOUZA MESSA', '2014-03-02', 0, 'Kiribati', 'vilma.vitoria.de.souza.messa@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('30349-362', '1977', 'F', 'LUIZ LOPES DA SILVA', '2014-11-10', 1, 'United Kingdom', 'luiz.lopes.da.silva@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('74828-651', '9178', 'M', 'MARIA ELENA ALVES', '2014-05-04', 0, 'Sudan', 'maria.elena.alves@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('08829-121', '4172', 'M', 'FRANCISCA MARIA SILVA COSTA', '2014-09-10', 1, 'Chile', 'francisca.maria.silva.costa@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('33180-850', '4420', 'F', 'RENIRA RODRIGUES DA SILVA DE SOUSA', '2014-12-18', 1, 'Norway', 'renira.rodrigues.da.silva.de.sousa@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('88365-938', '6235', 'F', 'IVANI DO NASCIMENTO VALENTIM', '2014-07-27', 1, 'Uruguay', 'ivani.do.nascimento.valentim@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('42639-489', '2533', 'M', 'RAMAO CARDOSO', '2014-03-30', 1, 'Mauritius', 'ramao.cardoso@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('74543-185', '8553', 'M', 'EDIO JUSTO BORGES', '2014-02-21', 1, 'Honduras', 'edio.justo.borges@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('16177-554', '8917', 'F', 'MARIA ALVES SUTIL', '2014-12-27', 1, 'Ecuador', 'maria.alves.sutil@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('21852-804', '6139', 'M', 'OSWALDIR GOMES', '2014-11-02', 0, 'Afghanistan', 'oswaldir.gomes@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('75114-863', '6767', 'F', 'JOAQUIM BORGES RODRIGUES', '2014-09-10', 1, 'Hungary', 'joaquim.borges.rodrigues@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('36251-534', '3225', 'M', 'JUEL PRUDENCIO BORGES', '2014-08-22', 0, 'Indonesia', 'juel.prudencio.borges@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('80388-194', '5009', 'M', 'ZILDA MARTINS DE SOUZA', '2014-04-20', 0, 'Malawi', 'zilda.martins.de.souza@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('61775-927', '6063', 'M', 'SILVIA MENDES', '2014-07-16', 0, 'Vanuatu', 'silvia.mendes@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('82429-042', '2383', 'M', 'JOSE NUNES PEREIRA', '2014-07-01', 1, 'Botswana', 'jose.nunes.pereira@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('89738-661', '1064', 'F', 'ALCEU DOS SANTOS', '2014-01-10', 1, 'Kyrgyzstan', 'alceu.dos.santos@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('78687-070', '5403', 'M', 'ANDRE LUIS CASTRILLON GARCIA', '2014-01-12', 1, 'Belize', 'andre.luis.castrillon.garcia@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('35035-394', '5535', 'F', 'RITA IRACI ALMEIDA DA SILVA', '2014-09-13', 0, 'Honduras', 'rita.iraci.almeida.da.silva@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('66438-603', '6280', 'M', 'HELOIZA ALMEIDA DOS SANTOS', '2014-10-30', 1, 'Brazil', 'heloiza.almeida.dos.santos@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('16590-653', '6518', 'M', 'ANA PAULA FIGUEIREDO DA ROCHA', '2014-07-28', 1, 'Jordan', 'ana.paula.figueiredo.da.rocha@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('51453-140', '5731', 'F', 'MARILEIA NUNES DE OLIVEIRA', '2014-05-02', 1, 'Norway', 'marileia.nunes.de.oliveira@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('28942-463', '2216', 'M', 'FRANCISCA MARIA SILVA COSTA', '2014-08-15', 0, 'Kazakhstan', 'francisca.maria.silva.costa@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('04720-696', '3450', 'M', 'BENEDITO AMBROSIO DA COSTA', '2014-04-28', 0, 'Congo', 'benedito.ambrosio.da.costa@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('17043-461', '5791', 'F', 'ALDIVINA REIS FERNANDES', '2014-11-16', 0, 'Mauritius', 'aldivina.reis.fernandes@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('68266-366', '6810', 'M', 'DAVINA PEREIRA DE SALES', '2014-07-03', 1, 'Samoa', 'davina.pereira.de.sales@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('67980-614', '9984', 'F', 'ATAIDE DIAS DE MOURA', '2014-03-18', 0, 'Bolivia', 'ataide.dias.de.moura@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('50517-566', '4238', 'M', 'OBADIAS MARCAL DE OLIVEIRA', '2014-08-15', 0, 'Kenya', 'obadias.marcal.de.oliveira@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('75887-985', '2751', 'M', 'INES APARECIDA DA SILVA', '2014-01-24', 1, 'Eritrea', 'ines.aparecida.da.silva@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('69908-226', '6792', 'F', 'EDIR DIAS DE CARVALHO', '2014-06-27', 1, 'Zambia', 'edir.dias.de.carvalho@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('82390-584', '3533', 'F', 'IROCIDES APARECIDA FERREIRA', '2014-12-10', 0, 'Egypt', 'irocides.aparecida.ferreira@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('04392-721', '2839', 'M', 'ANDRE LUIS CASTRILLON GARCIA', '2014-06-01', 0, 'Estonia', 'andre.luis.castrillon.garcia@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('54843-502', '3855', 'F', 'ANGELA APARECIDA BERNEGOZZE', '2014-08-17', 0, 'Switzerland', 'angela.aparecida.bernegozze@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('51241-344', '6290', 'F', 'JOAO MAURILIO DA SILVA', '2014-05-05', 1, 'Mali', 'joao.maurilio.da.silva@gmail.com');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARIA HILDA MACHADO', '2014-07-12', '2014-03-26', 1, 1, 'maria.hilda.machado@hotmail.com', 'maria.hilda.machado');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('RAMIRO VEDOVATO', '2014-07-06', '2014-03-09', 0, 1, 'ramiro.vedovato@hotmail.com', 'ramiro.vedovato');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARIA HILDA MACHADO', '2014-07-05', '2014-03-02', 1, 0, 'maria.hilda.machado@hotmail.com', 'maria.hilda.machado');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARLENE SANTANA MARTINS', '2014-07-03', '2014-01-03', 1, 1, 'marlene.santana.martins@hotmail.com', 'marlene.santana.martins');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARGARETH VIRGINIA DE REZENDE MEHLMANN', '2014-07-06', '2014-06-02', 0, 1, 'margareth.virginia.de.rezende.mehlmann@gmail.com', 'margareth.virginia.de.rezende.mehlmann');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARILEIA NUNES DE OLIVEIRA', '2014-07-09', '2014-03-09', 1, 1, 'marileia.nunes.de.oliveira@fb.com', 'marileia.nunes.de.oliveira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ANTONIO INACIO RODRIGUES', '2014-07-09', '2014-03-29', 1, 0, 'antonio.inacio.rodrigues@gmail.com', 'antonio.inacio.rodrigues');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ELEONILDA DE LIMA RODRIGUES', '2014-07-01', '2014-03-18', 1, 1, 'eleonilda.de.lima.rodrigues@hotmail.com', 'eleonilda.de.lima.rodrigues');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('RENIRA RODRIGUES DA SILVA DE SOUSA', '2014-07-09', '2014-05-29', 1, 1, 'renira.rodrigues.da.silva.de.sousa@fb.com', 'renira.rodrigues.da.silva.de.sousa');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('WILSON CONCEICAO DE MIRANDA', '2014-07-01', '2014-01-31', 1, 0, 'wilson.conceicao.de.miranda@gmail.com', 'wilson.conceicao.de.miranda');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('SILVIA MENDES', '2014-07-13', '2014-01-31', 0, 1, 'silvia.mendes@gmail.com', 'silvia.mendes');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('BEATRIZ PEREIRA LIMA', '2014-07-03', '2014-04-09', 1, 0, 'beatriz.pereira.lima@gmail.com', 'beatriz.pereira.lima');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('DORILDA ALVES DE CARVALHO', '2014-07-06', '2014-05-05', 1, 0, 'dorilda.alves.de.carvalho@gmail.com', 'dorilda.alves.de.carvalho');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LOURENCO DIAS', '2014-07-08', '2014-02-15', 0, 0, 'lourenco.dias@gmail.com', 'lourenco.dias');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('RENIRA RODRIGUES DA SILVA DE SOUSA', '2014-07-11', '2014-03-20', 0, 0, 'renira.rodrigues.da.silva.de.sousa@gmail.com', 'renira.rodrigues.da.silva.de.sousa');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('AURELINDA BATISTA DA SILVA', '2014-07-06', '2014-03-29', 1, 0, 'aurelinda.batista.da.silva@gmail.com', 'aurelinda.batista.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('CELIA CRISTINA PEREIRA PINTO DOS SANTOS', '2014-07-09', '2014-05-31', 0, 1, 'celia.cristina.pereira.pinto.dos.santos@hotmail.com', 'celia.cristina.pereira.pinto.dos.santos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('SILVIA MENDES', '2014-07-13', '2014-04-11', 1, 1, 'silvia.mendes@gmail.com', 'silvia.mendes');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ADENILTON JOSE DE MIRANDA', '2014-07-05', '2014-03-15', 0, 0, 'adenilton.jose.de.miranda@hotmail.com', 'adenilton.jose.de.miranda');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ZILMA MARQUES GONCALVES RODRIGUES', '2014-07-03', '2014-01-02', 1, 1, 'zilma.marques.goncalves.rodrigues@hotmail.com', 'zilma.marques.goncalves.rodrigues');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LUIZA ROTTLISBERGER SILVA', '2014-07-02', '2014-05-30', 0, 1, 'luiza.rottlisberger.silva@gmail.com', 'luiza.rottlisberger.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ELISABETE ROMERO NOBRE LEAL', '2014-07-12', '2014-03-14', 1, 1, 'elisabete.romero.nobre.leal@gmail.com', 'elisabete.romero.nobre.leal');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('BEATRIZ PEREIRA LIMA', '2014-07-01', '2014-02-23', 0, 1, 'beatriz.pereira.lima@fb.com', 'beatriz.pereira.lima');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('NEIZA MARIA LEITE DA SILVA', '2014-07-08', '2014-03-08', 1, 1, 'neiza.maria.leite.da.silva@gmail.com', 'neiza.maria.leite.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LOURIVAL ROSA GUIMARAES', '2014-07-04', '2014-04-02', 1, 1, 'lourival.rosa.guimaraes@hotmail.com', 'lourival.rosa.guimaraes');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ALCEU DOS SANTOS', '2014-07-04', '2014-06-13', 1, 0, 'alceu.dos.santos@gmail.com', 'alceu.dos.santos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('NEIVA OBERGER FERREIRA', '2014-07-04', '2014-01-13', 1, 1, 'neiva.oberger.ferreira@fb.com', 'neiva.oberger.ferreira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ADENILTON JOSE DE MIRANDA', '2014-07-12', '2014-06-11', 0, 1, 'adenilton.jose.de.miranda@hotmail.com', 'adenilton.jose.de.miranda');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('GLAUBER DA COSTA ARRUDA', '2014-07-13', '2014-04-29', 1, 1, 'glauber.da.costa.arruda@hotmail.com', 'glauber.da.costa.arruda');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JORGE TETSUO TAIRA', '2014-07-01', '2014-01-31', 0, 1, 'jorge.tetsuo.taira@hotmail.com', 'jorge.tetsuo.taira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ALBERTO FEIZAR CARDOSO ABDALA', '2014-07-01', '2014-06-01', 0, 1, 'alberto.feizar.cardoso.abdala@hotmail.com', 'alberto.feizar.cardoso.abdala');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARIA DE LOURDES FERNANDES DIAS', '2014-07-07', '2014-02-19', 1, 1, 'maria.de.lourdes.fernandes.dias@gmail.com', 'maria.de.lourdes.fernandes.dias');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('DIRCEU DE MATTOS', '2014-07-03', '2014-04-10', 1, 0, 'dirceu.de.mattos@hotmail.com', 'dirceu.de.mattos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JOAO DE LUCA', '2014-07-10', '2014-03-03', 1, 1, 'joao.de.luca@gmail.com', 'joao.de.luca');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ELEONILDA DE LIMA RODRIGUES', '2014-07-04', '2014-05-04', 1, 0, 'eleonilda.de.lima.rodrigues@fb.com', 'eleonilda.de.lima.rodrigues');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('AUGUSTA ALVES DOS SANTOS', '2014-07-10', '2014-03-20', 1, 1, 'augusta.alves.dos.santos@fb.com', 'augusta.alves.dos.santos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('AMERICO FRANCISCO DA SILVA', '2014-07-10', '2014-04-22', 1, 1, 'americo.francisco.da.silva@gmail.com', 'americo.francisco.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('DORILDA ALVES DE CARVALHO', '2014-07-06', '2014-04-23', 0, 0, 'dorilda.alves.de.carvalho@hotmail.com', 'dorilda.alves.de.carvalho');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('RUBENSMORBECK LEITE', '2014-07-06', '2014-03-24', 0, 1, 'rubensmorbeck.leite@hotmail.com', 'rubensmorbeck.leite');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JOSE NUNES PEREIRA', '2014-07-08', '2014-02-17', 1, 0, 'jose.nunes.pereira@fb.com', 'jose.nunes.pereira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARGARETH VIRGINIA DE REZENDE MEHLMANN', '2014-07-06', '2014-04-15', 1, 0, 'margareth.virginia.de.rezende.mehlmann@hotmail.com', 'margareth.virginia.de.rezende.mehlmann');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('EUZEBIO DA SILVA CEZAR', '2014-07-10', '2014-01-04', 1, 0, 'euzebio.da.silva.cezar@gmail.com', 'euzebio.da.silva.cezar');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('SOLANGE APARECIDA DO PRADO DA CRUZ', '2014-07-03', '2014-03-19', 0, 1, 'solange.aparecida.do.prado.da.cruz@gmail.com', 'solange.aparecida.do.prado.da.cruz');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ZILMA MARQUES GONCALVES RODRIGUES', '2014-07-09', '2014-02-19', 0, 1, 'zilma.marques.goncalves.rodrigues@gmail.com', 'zilma.marques.goncalves.rodrigues');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARIA HILDA MACHADO', '2014-07-06', '2014-05-24', 1, 0, 'maria.hilda.machado@hotmail.com', 'maria.hilda.machado');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ABILIO CAVALHEIRO', '2014-07-07', '2014-03-05', 1, 1, 'abilio.cavalheiro@hotmail.com', 'abilio.cavalheiro');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('OSWALDIR GOMES', '2014-07-10', '2014-04-27', 0, 1, 'oswaldir.gomes@hotmail.com', 'oswaldir.gomes');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LOURIVAL ROSA GUIMARAES', '2014-07-03', '2014-06-27', 1, 0, 'lourival.rosa.guimaraes@hotmail.com', 'lourival.rosa.guimaraes');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ALIETE FRANCISCA PRATES', '2014-07-12', '2014-01-23', 0, 0, 'aliete.francisca.prates@gmail.com', 'aliete.francisca.prates');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('AFONSO BARBOSA DA SILVA', '2014-07-12', '2014-06-23', 0, 0, 'afonso.barbosa.da.silva@gmail.com', 'afonso.barbosa.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('BENEDITA GAUDENCIO DA COSTA', '2014-07-06', '2014-03-01', 0, 1, 'benedita.gaudencio.da.costa@fb.com', 'benedita.gaudencio.da.costa');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('FRANCISCA MARIA SILVA COSTA', '2014-07-13', '2014-06-09', 1, 1, 'francisca.maria.silva.costa@hotmail.com', 'francisca.maria.silva.costa');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MIGUEL VENCESLAU MACIEL DE CAMPOS', '2014-07-05', '2014-02-24', 0, 1, 'miguel.venceslau.maciel.de.campos@fb.com', 'miguel.venceslau.maciel.de.campos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('EUZEBIO DA SILVA CEZAR', '2014-07-13', '2014-02-04', 0, 1, 'euzebio.da.silva.cezar@hotmail.com', 'euzebio.da.silva.cezar');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ELZA LIMA DE SOUZA MANSANO', '2014-07-13', '2014-05-10', 0, 1, 'elza.lima.de.souza.mansano@hotmail.com', 'elza.lima.de.souza.mansano');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('GLAUBER DA COSTA ARRUDA', '2014-07-10', '2014-01-10', 1, 1, 'glauber.da.costa.arruda@gmail.com', 'glauber.da.costa.arruda');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LUZIA RODRIGUES DE OLIVEIRA', '2014-07-06', '2014-01-02', 0, 1, 'luzia.rodrigues.de.oliveira@fb.com', 'luzia.rodrigues.de.oliveira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('RITA IRACI ALMEIDA DA SILVA', '2014-07-02', '2014-03-28', 0, 0, 'rita.iraci.almeida.da.silva@hotmail.com', 'rita.iraci.almeida.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('FRANCISCA MARIA SILVA COSTA', '2014-07-08', '2014-02-20', 1, 0, 'francisca.maria.silva.costa@hotmail.com', 'francisca.maria.silva.costa');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LAURA SEBASTIANA GURGEL', '2014-07-01', '2014-02-15', 0, 1, 'laura.sebastiana.gurgel@fb.com', 'laura.sebastiana.gurgel');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ELOIDE CAVANHA', '2014-07-08', '2014-05-28', 0, 1, 'eloide.cavanha@fb.com', 'eloide.cavanha');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('QUITERIA LOURENCO DE LIMA', '2014-07-05', '2014-05-02', 1, 0, 'quiteria.lourenco.de.lima@gmail.com', 'quiteria.lourenco.de.lima');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ROBSON LUIZ DO NASCIMENTO PUERTAS', '2014-07-04', '2014-03-17', 0, 0, 'robson.luiz.do.nascimento.puertas@gmail.com', 'robson.luiz.do.nascimento.puertas');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('SEBASTIANA BENEDITA DA COSTA', '2014-07-07', '2014-03-26', 1, 1, 'sebastiana.benedita.da.costa@hotmail.com', 'sebastiana.benedita.da.costa');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('EUZEBIO DA SILVA CEZAR', '2014-07-08', '2014-03-01', 0, 1, 'euzebio.da.silva.cezar@gmail.com', 'euzebio.da.silva.cezar');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LOURENCO DIAS', '2014-07-09', '2014-03-23', 0, 0, 'lourenco.dias@gmail.com', 'lourenco.dias');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('AURELINDA BATISTA DA SILVA', '2014-07-04', '2014-03-01', 0, 1, 'aurelinda.batista.da.silva@hotmail.com', 'aurelinda.batista.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('SUELY DA SILVA CAVALCANTI', '2014-07-13', '2014-03-02', 1, 1, 'suely.da.silva.cavalcanti@gmail.com', 'suely.da.silva.cavalcanti');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARIA DE LOURDES FERNANDES DIAS', '2014-07-01', '2014-05-28', 1, 1, 'maria.de.lourdes.fernandes.dias@fb.com', 'maria.de.lourdes.fernandes.dias');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('CRISTIANE PAES CORDOBA', '2014-07-05', '2014-02-08', 1, 1, 'cristiane.paes.cordoba@gmail.com', 'cristiane.paes.cordoba');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('NEIZA MARIA LEITE DA SILVA', '2014-07-09', '2014-01-23', 0, 1, 'neiza.maria.leite.da.silva@fb.com', 'neiza.maria.leite.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARIA DE LOURDES FERNANDES DIAS', '2014-07-03', '2014-01-30', 0, 0, 'maria.de.lourdes.fernandes.dias@gmail.com', 'maria.de.lourdes.fernandes.dias');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ARISMARES SOUZA PRATES', '2014-07-02', '2014-03-21', 0, 0, 'arismares.souza.prates@gmail.com', 'arismares.souza.prates');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ALDIVINA REIS FERNANDES', '2014-07-13', '2014-05-19', 0, 1, 'aldivina.reis.fernandes@fb.com', 'aldivina.reis.fernandes');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JUEL PRUDENCIO BORGES', '2014-07-06', '2014-01-03', 0, 1, 'juel.prudencio.borges@fb.com', 'juel.prudencio.borges');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('RUZINO ANTUNES DA SILVA', '2014-07-08', '2014-01-27', 0, 1, 'ruzino.antunes.da.silva@hotmail.com', 'ruzino.antunes.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ALCEU DOS SANTOS', '2014-07-11', '2014-06-03', 0, 0, 'alceu.dos.santos@fb.com', 'alceu.dos.santos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JOSENOTARIO MUNGO', '2014-07-07', '2014-03-30', 0, 1, 'josenotario.mungo@hotmail.com', 'josenotario.mungo');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('HELOIZA ALMEIDA DOS SANTOS', '2014-07-11', '2014-06-15', 1, 0, 'heloiza.almeida.dos.santos@fb.com', 'heloiza.almeida.dos.santos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('KLEBER MAGALHAES FERREIRA', '2014-07-07', '2014-05-01', 1, 0, 'kleber.magalhaes.ferreira@fb.com', 'kleber.magalhaes.ferreira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('CRISTIANE PAES CORDOBA', '2014-07-05', '2014-06-23', 1, 1, 'cristiane.paes.cordoba@gmail.com', 'cristiane.paes.cordoba');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ANTONIO INACIO RODRIGUES', '2014-07-05', '2014-06-15', 1, 0, 'antonio.inacio.rodrigues@gmail.com', 'antonio.inacio.rodrigues');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('DIEGO CESPEDES DE SOUZA', '2014-07-03', '2014-05-03', 1, 0, 'diego.cespedes.de.souza@fb.com', 'diego.cespedes.de.souza');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JULIO APARECIDO DE SOUZA', '2014-07-06', '2014-04-30', 1, 0, 'julio.aparecido.de.souza@gmail.com', 'julio.aparecido.de.souza');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('RUBENSMORBECK LEITE', '2014-07-09', '2014-04-01', 0, 1, 'rubensmorbeck.leite@gmail.com', 'rubensmorbeck.leite');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ANDRE LUIS CASTRILLON GARCIA', '2014-07-02', '2014-06-23', 1, 0, 'andre.luis.castrillon.garcia@fb.com', 'andre.luis.castrillon.garcia');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('CARLOS SERGIO URBANIN', '2014-07-13', '2014-03-14', 1, 1, 'carlos.sergio.urbanin@gmail.com', 'carlos.sergio.urbanin');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ATAIDE DIAS DE MOURA', '2014-07-09', '2014-05-28', 1, 1, 'ataide.dias.de.moura@hotmail.com', 'ataide.dias.de.moura');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ALIETE FRANCISCA PRATES', '2014-07-10', '2014-03-30', 0, 1, 'aliete.francisca.prates@fb.com', 'aliete.francisca.prates');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('SEBASTIANA BENEDITA DA COSTA', '2014-07-03', '2014-05-31', 1, 1, 'sebastiana.benedita.da.costa@hotmail.com', 'sebastiana.benedita.da.costa');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('NEUCY DE OLIVEIRA', '2014-07-03', '2014-03-24', 1, 0, 'neucy.de.oliveira@hotmail.com', 'neucy.de.oliveira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LIDIANE DO PRADO BRITE', '2014-07-05', '2014-03-18', 0, 1, 'lidiane.do.prado.brite@gmail.com', 'lidiane.do.prado.brite');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('RUBENSMORBECK LEITE', '2014-07-09', '2014-03-06', 1, 0, 'rubensmorbeck.leite@gmail.com', 'rubensmorbeck.leite');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('NEIVA OBERGER FERREIRA', '2014-07-10', '2014-01-15', 1, 0, 'neiva.oberger.ferreira@fb.com', 'neiva.oberger.ferreira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARIA HILDA MACHADO', '2014-07-05', '2014-01-08', 1, 1, 'maria.hilda.machado@gmail.com', 'maria.hilda.machado');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('EDIO JUSTO BORGES', '2014-07-05', '2014-06-21', 1, 0, 'edio.justo.borges@fb.com', 'edio.justo.borges');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARIA ELENA ALVES', '2014-07-06', '2014-05-07', 0, 1, 'maria.elena.alves@hotmail.com', 'maria.elena.alves');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('BEATRIZ PEREIRA LIMA', '2014-07-06', '2014-04-20', 0, 0, 'beatriz.pereira.lima@hotmail.com', 'beatriz.pereira.lima');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ROSIMEIRE GONCALVES LOPES RAMOS', '2014-07-10', '2014-02-11', 1, 1, 'rosimeire.goncalves.lopes.ramos@gmail.com', 'rosimeire.goncalves.lopes.ramos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('OBADIAS MARCAL DE OLIVEIRA', '2014-07-01', '2014-02-27', 1, 0, 'obadias.marcal.de.oliveira@hotmail.com', 'obadias.marcal.de.oliveira');
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-13', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-09', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-11', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-09', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-01', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-03', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-01', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-03', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-18', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-26', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-26', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-07-11', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-09', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-11', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-20', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-28', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-11', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-21', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-15', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-03', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-07-07', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-01', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-07-09', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-23', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-30', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-18', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-14', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-24', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-07-09', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-18', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-14', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-13', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-07-10', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-09', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-19', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-03', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-08', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-19', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-06', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-09', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-10', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-18', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-15', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-07-08', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-28', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-12', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-22', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-02', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-03', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-27', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-04', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-28', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-07-06', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-28', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-18', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-11', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-28', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-25', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-25', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-28', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-07-02', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-30', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-06', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-20', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-03', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-27', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-28', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-24', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-20', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-15', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-26', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-29', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-09', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-24', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-09', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-26', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-11', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-22', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-12', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-20', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-20', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-28', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-19', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-26', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-07-13', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-11', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-11', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-07-02', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-07', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-28', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-11', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-19', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-04', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-13', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-12', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-15', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-20', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-08', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-20', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-05', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
