INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('86898-660', '6525', 'M', 'JOAO DE LUCA', '2014-02-10', 0, 'Vietnam', 'joao.de.luca@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('00696-832', '5243', 'F', 'DIRCEU DE MATTOS', '2014-03-30', 1, 'St. Kitts & Nevis', 'dirceu.de.mattos@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('90896-993', '8645', 'F', 'JOSENOTARIO MUNGO', '2014-06-05', 1, 'East Timor', 'josenotario.mungo@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('82507-714', '1744', 'M', 'OSVALDO PEREIRA BARBOSA', '2014-09-22', 0, 'Saudi Arabia', 'osvaldo.pereira.barbosa@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('20521-536', '1719', 'F', 'ILZA XAVIER DE LIMA ARAUJO', '2014-06-15', 0, 'Poland', 'ilza.xavier.de.lima.araujo@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('65950-531', '7993', 'M', 'ANTONIO INACIO RODRIGUES', '2014-10-25', 0, 'Vatican City (Holy See)', 'antonio.inacio.rodrigues@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('11402-319', '5266', 'M', 'RONY HUDSON OLIVEIRA CANDEIRO', '2014-05-08', 1, 'Eritrea', 'rony.hudson.oliveira.candeiro@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('63575-201', '4132', 'M', 'ELISABETE ROMERO NOBRE LEAL', '2014-03-20', 0, 'Algeria', 'elisabete.romero.nobre.leal@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('98268-386', '2656', 'M', 'NEIVA OBERGER FERREIRA', '2014-03-26', 1, 'Mongolia', 'neiva.oberger.ferreira@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('69985-160', '2278', 'F', 'MARILEIA NUNES DE OLIVEIRA', '2014-01-31', 1, 'Antigua & Barbuda', 'marileia.nunes.de.oliveira@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('79456-891', '7140', 'M', 'ADELSON LUIZ DA SILVA', '2014-11-27', 0, 'Guinea', 'adelson.luiz.da.silva@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('48676-807', '0004', 'M', 'MIGUEL JOAQUIM SILVA', '2014-09-23', 1, 'Niger', 'miguel.joaquim.silva@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('56781-723', '4054', 'M', 'JOAO MAURILIO DA SILVA', '2014-07-21', 1, 'Egypt', 'joao.maurilio.da.silva@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('88459-913', '4305', 'M', 'NEIVA OBERGER FERREIRA', '2014-05-26', 0, 'China', 'neiva.oberger.ferreira@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('40750-144', '2228', 'M', 'DIRCEU DE MATTOS', '2014-06-29', 1, 'Ukraine', 'dirceu.de.mattos@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('72040-276', '2366', 'F', 'LUIZ LOPES DA SILVA', '2014-03-03', 0, 'Belize', 'luiz.lopes.da.silva@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('87064-270', '5901', 'F', 'CRISTIANE PAES CORDOBA', '2014-10-06', 1, 'Iceland', 'cristiane.paes.cordoba@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('85924-341', '7184', 'F', 'ROSILENE ALMEIDA DA SILVA', '2014-02-12', 1, 'Liechtenstein', 'rosilene.almeida.da.silva@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('85651-746', '0645', 'F', 'MIGUEL VENCESLAU MACIEL DE CAMPOS', '2014-05-20', 0, 'Panama', 'miguel.venceslau.maciel.de.campos@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('76780-640', '3671', 'F', 'NEUCY DE OLIVEIRA', '2014-11-05', 0, 'Uruguay', 'neucy.de.oliveira@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('82902-244', '3416', 'F', 'ALBERTO FEIZAR CARDOSO ABDALA', '2014-11-18', 0, 'Israel', 'alberto.feizar.cardoso.abdala@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('75774-049', '7118', 'M', 'SOLANGE APARECIDA DO PRADO DA CRUZ', '2014-07-27', 0, 'Sri Lanka', 'solange.aparecida.do.prado.da.cruz@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('14543-907', '5939', 'M', 'ELOIDE CAVANHA', '2014-10-18', 1, 'Palestinian State', 'eloide.cavanha@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('53025-282', '2010', 'M', 'MAGALI SANCHES', '2014-10-17', 0, 'Oman', 'magali.sanches@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('58810-543', '5210', 'F', 'LIDIANE DO PRADO BRITE', '2014-05-09', 0, 'Maldives', 'lidiane.do.prado.brite@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('56009-871', '0506', 'F', 'MARIA ALVES SUTIL', '2014-11-02', 0, 'Albania', 'maria.alves.sutil@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('25989-047', '9960', 'F', 'NEIZA MARIA LEITE DA SILVA', '2014-04-30', 0, 'Estonia', 'neiza.maria.leite.da.silva@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('72162-979', '6846', 'F', 'WILSON CONCEICAO DE MIRANDA', '2014-06-20', 0, 'Germany', 'wilson.conceicao.de.miranda@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('40670-320', '5852', 'M', 'ALDIVINA REIS FERNANDES', '2014-11-21', 0, 'Iraq', 'aldivina.reis.fernandes@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('76217-242', '4647', 'F', 'THANIA CRISTINA DA SILVA BARNABE', '2014-09-07', 0, 'Cyprus', 'thania.cristina.da.silva.barnabe@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('69962-797', '8468', 'F', 'IROCIDES APARECIDA FERREIRA', '2014-10-04', 1, 'Bulgaria', 'irocides.aparecida.ferreira@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('47971-244', '0993', 'M', 'ATAIDE DIAS DE MOURA', '2014-03-29', 0, 'Mozambique', 'ataide.dias.de.moura@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('09641-771', '3293', 'F', 'GLAUBER DA COSTA ARRUDA', '2014-12-16', 0, 'Mozambique', 'glauber.da.costa.arruda@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('69367-195', '2455', 'F', 'DIAMANTINA DA SILVA SOARES', '2014-06-24', 1, 'United Kingdom', 'diamantina.da.silva.soares@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('47023-921', '3191', 'M', 'RUZINO ANTUNES DA SILVA', '2014-05-20', 0, 'Kuwait', 'ruzino.antunes.da.silva@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('88323-703', '3025', 'M', 'MARCIA DA SILVA OLIVEIRA', '2014-12-21', 0, 'Zambia', 'marcia.da.silva.oliveira@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('96306-205', '4208', 'F', 'LOURIVAL ROSA GUIMARAES', '2014-07-22', 0, 'Cyprus', 'lourival.rosa.guimaraes@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('58156-166', '7714', 'M', 'NEUCY DE OLIVEIRA', '2014-05-10', 1, 'Pakistan', 'neucy.de.oliveira@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('98664-104', '2702', 'F', 'SONIA MARIA MARTINEZ PENITENTE', '2014-04-20', 1, 'Mozambique', 'sonia.maria.martinez.penitente@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('90089-132', '0991', 'F', 'LUCINEIDE DE MORAES DO CARMO', '2014-06-23', 1, 'Haiti', 'lucineide.de.moraes.do.carmo@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('86828-287', '8183', 'F', 'OLGA PEREIRA', '2014-07-22', 0, 'Mongolia', 'olga.pereira@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('21044-308', '5370', 'F', 'LAURO JOSE DA SILVA', '2014-12-08', 1, 'Burkina Faso', 'lauro.jose.da.silva@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('74843-391', '0824', 'F', 'NEUCY DE OLIVEIRA', '2014-02-12', 0, 'United States of America', 'neucy.de.oliveira@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('00571-418', '3310', 'M', 'LAURO JOSE DA SILVA', '2014-01-23', 0, 'Cote d''Ivoire', 'lauro.jose.da.silva@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('35171-769', '0277', 'F', 'LIDIANE DO PRADO BRITE', '2014-02-02', 0, 'Malta', 'lidiane.do.prado.brite@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('88398-692', '0321', 'M', 'SEBASTIANA BENEDITA DA COSTA', '2014-07-17', 1, 'St. Lucia', 'sebastiana.benedita.da.costa@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('95963-063', '8631', 'M', 'JUEL PRUDENCIO BORGES', '2014-12-10', 1, 'Oman', 'juel.prudencio.borges@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('83036-435', '1323', 'F', 'DILMA DE SOUZA', '2014-09-18', 1, 'Pakistan', 'dilma.de.souza@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('23534-500', '2908', 'M', 'ALBERTO FEIZAR CARDOSO ABDALA', '2014-12-12', 1, 'Iceland', 'alberto.feizar.cardoso.abdala@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('79787-208', '1419', 'M', 'IROCIDES APARECIDA FERREIRA', '2014-11-09', 0, 'Eritrea', 'irocides.aparecida.ferreira@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('49546-447', '8737', 'F', 'ILZA XAVIER DE LIMA ARAUJO', '2014-11-26', 0, 'Haiti', 'ilza.xavier.de.lima.araujo@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('94533-771', '6372', 'M', 'MIGUEL JOAQUIM SILVA', '2014-03-17', 0, 'Guinea-Bissau', 'miguel.joaquim.silva@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('47206-515', '4422', 'M', 'ALDIVINA REIS FERNANDES', '2014-06-28', 0, 'Libya', 'aldivina.reis.fernandes@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('34772-256', '4680', 'F', 'MARIA TEREZINHA ROCHA DE SOUZA', '2014-03-21', 0, 'Turkmenistan', 'maria.terezinha.rocha.de.souza@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('37845-709', '8121', 'F', 'ELZA LIMA DE SOUZA MANSANO', '2014-06-10', 1, 'Myanmar (Burma)', 'elza.lima.de.souza.mansano@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('81841-578', '3488', 'M', 'CRISTIANE PAES CORDOBA', '2014-08-19', 1, 'Honduras', 'cristiane.paes.cordoba@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('39798-709', '0612', 'M', 'JUEL PRUDENCIO BORGES', '2014-09-05', 0, 'Korea North', 'juel.prudencio.borges@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('76640-478', '1276', 'F', 'TIMOTEO BATISTA LEITE', '2014-04-05', 0, 'Libya', 'timoteo.batista.leite@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('25982-600', '1488', 'M', 'ARISMARES SOUZA PRATES', '2014-09-23', 0, 'Ghana', 'arismares.souza.prates@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('74104-249', '9609', 'F', 'LUIZ FERNANDO DA SILVA AMORIM', '2014-12-10', 0, 'Vanuatu', 'luiz.fernando.da.silva.amorim@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('58283-892', '2425', 'M', 'MARCIA DA SILVA OLIVEIRA', '2014-03-20', 0, 'Uruguay', 'marcia.da.silva.oliveira@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('73097-954', '5496', 'M', 'IROCIDES APARECIDA FERREIRA', '2014-10-11', 0, 'Bangladesh', 'irocides.aparecida.ferreira@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('64236-828', '3267', 'M', 'VIRGILIA DIAS VIEIRA', '2014-11-03', 1, 'Liechtenstein', 'virgilia.dias.vieira@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('17423-956', '1302', 'M', 'BEATRIZ PEREIRA LIMA', '2014-11-07', 1, 'Turkmenistan', 'beatriz.pereira.lima@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('49391-151', '1446', 'M', 'JUEL PRUDENCIO BORGES', '2014-06-03', 1, 'Finland', 'juel.prudencio.borges@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('39224-458', '1308', 'M', 'ANDRE LUIS CASTRILLON GARCIA', '2014-11-02', 0, 'United States of America', 'andre.luis.castrillon.garcia@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('45965-631', '5279', 'F', 'DIEGO CESPEDES DE SOUZA', '2014-04-07', 0, 'Poland', 'diego.cespedes.de.souza@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('13967-880', '9163', 'M', 'RAMAO CARDOSO', '2014-12-13', 0, 'Oman', 'ramao.cardoso@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('80226-869', '2335', 'F', 'NEIZA MARIA LEITE DA SILVA', '2014-11-23', 1, 'China', 'neiza.maria.leite.da.silva@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('79487-581', '8723', 'F', 'ROSIMEIRE GONCALVES LOPES RAMOS', '2014-02-12', 0, 'Djibouti', 'rosimeire.goncalves.lopes.ramos@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('24113-201', '5154', 'M', 'BENILDE PERES DE CAMPOS', '2014-10-26', 1, 'Cuba', 'benilde.peres.de.campos@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('33578-096', '5285', 'M', 'CLAUDIO BARBOSA DOS SANTOS', '2014-08-18', 0, 'Andorra', 'claudio.barbosa.dos.santos@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('69414-791', '6074', 'F', 'JOAQUIM BORGES RODRIGUES', '2014-11-02', 0, 'Lebanon', 'joaquim.borges.rodrigues@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('09904-286', '6347', 'F', 'QUITERIA LOURENCO DE LIMA', '2014-07-06', 0, 'The Netherlands', 'quiteria.lourenco.de.lima@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('10020-138', '9584', 'F', 'ILZA XAVIER DE LIMA ARAUJO', '2014-12-19', 1, 'Latvia', 'ilza.xavier.de.lima.araujo@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('20340-863', '5626', 'F', 'MIGUEL VENCESLAU MACIEL DE CAMPOS', '2014-10-26', 0, 'Palestinian State', 'miguel.venceslau.maciel.de.campos@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('44530-059', '2427', 'M', 'ANTONIO INACIO RODRIGUES', '2014-03-22', 0, 'St. Vincent & The Grenadines', 'antonio.inacio.rodrigues@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('88650-123', '4864', 'F', 'JOSENOTARIO MUNGO', '2014-03-14', 1, 'Kenya', 'josenotario.mungo@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('31571-630', '5500', 'F', 'IVANI DO NASCIMENTO VALENTIM', '2014-06-03', 1, 'Swaziland', 'ivani.do.nascimento.valentim@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('98603-231', '0683', 'M', 'ROSIMEIRE GONCALVES LOPES RAMOS', '2014-11-19', 1, 'Bosnia & Herzegovina', 'rosimeire.goncalves.lopes.ramos@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('46075-810', '0800', 'F', 'ALCEU DOS SANTOS', '2014-07-17', 1, 'Monaco', 'alceu.dos.santos@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('55330-832', '0722', 'F', 'LUIZ LOPES DA SILVA', '2014-06-04', 0, 'Somalia', 'luiz.lopes.da.silva@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('23311-645', '2576', 'M', 'ANTONIA BORGES DA SILVA', '2014-10-27', 1, 'France', 'antonia.borges.da.silva@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('22859-029', '9315', 'M', 'LOURIVAL ROSA GUIMARAES', '2014-02-12', 0, 'Guyana', 'lourival.rosa.guimaraes@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('31801-239', '1879', 'F', 'OSVALDO PEREIRA BARBOSA', '2014-09-26', 0, 'Uganda', 'osvaldo.pereira.barbosa@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('89050-037', '5379', 'M', 'FRANCISCA MARIA SILVA COSTA', '2014-01-22', 0, 'Sri Lanka', 'francisca.maria.silva.costa@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('10416-831', '7428', 'M', 'HELOIZA ALMEIDA DOS SANTOS', '2014-08-26', 1, 'Congo', 'heloiza.almeida.dos.santos@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('22672-460', '5018', 'M', 'NADIACUIABANO KUNZE', '2014-05-25', 0, 'Mongolia', 'nadiacuiabano.kunze@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('62869-280', '6390', 'F', 'ZILMA MARQUES GONCALVES RODRIGUES', '2014-08-08', 1, 'Monaco', 'zilma.marques.goncalves.rodrigues@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('19322-375', '6777', 'F', 'ANDRE LUIS CASTRILLON GARCIA', '2014-09-25', 0, 'Grenada', 'andre.luis.castrillon.garcia@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('01878-868', '6430', 'F', 'OSWALDIR GOMES', '2014-03-01', 1, 'Bulgaria', 'oswaldir.gomes@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('12545-386', '3734', 'F', 'GLAUBER DA COSTA ARRUDA', '2014-04-05', 0, 'South Africa', 'glauber.da.costa.arruda@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('24408-374', '9072', 'M', 'OBADIAS MARCAL DE OLIVEIRA', '2014-04-11', 0, 'Trinidad & Tobago', 'obadias.marcal.de.oliveira@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('27362-910', '3244', 'F', 'ALDEIR ALEX ALVES LIMA', '2014-04-16', 0, 'San Marino', 'aldeir.alex.alves.lima@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('97485-585', '0344', 'F', 'NADIACUIABANO KUNZE', '2014-11-02', 0, 'Senegal', 'nadiacuiabano.kunze@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('82632-256', '6288', 'F', 'ADAIL BANDINELLE DE MORAES', '2014-10-19', 0, 'Indonesia', 'adail.bandinelle.de.moraes@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('34844-432', '9405', 'F', 'JOSENOTARIO MUNGO', '2014-04-09', 0, 'Czech Republic', 'josenotario.mungo@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('41917-891', '1414', 'F', 'DORILDA ALVES DE CARVALHO', '2014-08-01', 1, 'Bahamas', 'dorilda.alves.de.carvalho@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('38583-728', '0467', 'M', 'ATAIDE DIAS DE MOURA', '2014-05-18', 0, 'Germany', 'ataide.dias.de.moura@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('20546-016', '1231', 'F', 'CLEUSA FERREIRA MACIEL', '2014-05-09', 0, 'Luxembourg', 'cleusa.ferreira.maciel@gmail.com');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('EUZEBIO DA SILVA CEZAR', '2014-07-04', '2014-01-07', 1, 1, 'euzebio.da.silva.cezar@hotmail.com', 'euzebio.da.silva.cezar');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JULIO APARECIDO DE SOUZA', '2014-07-09', '2014-03-14', 0, 1, 'julio.aparecido.de.souza@fb.com', 'julio.aparecido.de.souza');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JOAQUIM BORGES RODRIGUES', '2014-07-07', '2014-03-06', 0, 0, 'joaquim.borges.rodrigues@hotmail.com', 'joaquim.borges.rodrigues');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('GLAUBER DA COSTA ARRUDA', '2014-07-03', '2014-05-29', 1, 0, 'glauber.da.costa.arruda@fb.com', 'glauber.da.costa.arruda');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ZILDA MARTINS DE SOUZA', '2014-07-13', '2014-03-11', 1, 0, 'zilda.martins.de.souza@hotmail.com', 'zilda.martins.de.souza');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LUZIA RODRIGUES DE OLIVEIRA', '2014-07-08', '2014-01-10', 0, 1, 'luzia.rodrigues.de.oliveira@gmail.com', 'luzia.rodrigues.de.oliveira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MIGUEL JOAQUIM SILVA', '2014-07-05', '2014-03-13', 1, 1, 'miguel.joaquim.silva@hotmail.com', 'miguel.joaquim.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARCIA DA SILVA OLIVEIRA', '2014-07-13', '2014-02-22', 1, 1, 'marcia.da.silva.oliveira@gmail.com', 'marcia.da.silva.oliveira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARIA ALVES SUTIL', '2014-07-04', '2014-05-09', 0, 0, 'maria.alves.sutil@gmail.com', 'maria.alves.sutil');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARIA HILDA MACHADO', '2014-07-10', '2014-06-17', 0, 1, 'maria.hilda.machado@gmail.com', 'maria.hilda.machado');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LOURIVAL ROSA GUIMARAES', '2014-07-03', '2014-03-18', 0, 1, 'lourival.rosa.guimaraes@hotmail.com', 'lourival.rosa.guimaraes');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JOSE JESUS DA HORA', '2014-07-01', '2014-05-21', 0, 1, 'jose.jesus.da.hora@gmail.com', 'jose.jesus.da.hora');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('SILVIA MENDES', '2014-07-02', '2014-05-02', 0, 0, 'silvia.mendes@gmail.com', 'silvia.mendes');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ELEONILDA DE LIMA RODRIGUES', '2014-07-08', '2014-06-29', 1, 0, 'eleonilda.de.lima.rodrigues@hotmail.com', 'eleonilda.de.lima.rodrigues');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ELEONILDA DE LIMA RODRIGUES', '2014-07-11', '2014-02-24', 1, 1, 'eleonilda.de.lima.rodrigues@fb.com', 'eleonilda.de.lima.rodrigues');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ELISABETE ROMERO NOBRE LEAL', '2014-07-09', '2014-06-21', 1, 0, 'elisabete.romero.nobre.leal@hotmail.com', 'elisabete.romero.nobre.leal');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARCONI GEORGE RIBEIRO DA SILVA', '2014-07-12', '2014-02-28', 1, 0, 'marconi.george.ribeiro.da.silva@gmail.com', 'marconi.george.ribeiro.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('FRANCISCA MARIA SILVA COSTA', '2014-07-02', '2014-06-01', 1, 0, 'francisca.maria.silva.costa@fb.com', 'francisca.maria.silva.costa');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('GLAUBER DA COSTA ARRUDA', '2014-07-08', '2014-01-11', 1, 0, 'glauber.da.costa.arruda@hotmail.com', 'glauber.da.costa.arruda');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JOANA ANTUNES', '2014-07-07', '2014-02-20', 0, 0, 'joana.antunes@fb.com', 'joana.antunes');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('VALDOMIRO LEITE DE SA', '2014-07-08', '2014-01-08', 1, 0, 'valdomiro.leite.de.sa@fb.com', 'valdomiro.leite.de.sa');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('EUZEBIO DA SILVA CEZAR', '2014-07-08', '2014-03-16', 0, 0, 'euzebio.da.silva.cezar@hotmail.com', 'euzebio.da.silva.cezar');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('RENIRA RODRIGUES DA SILVA DE SOUSA', '2014-07-12', '2014-03-07', 1, 0, 'renira.rodrigues.da.silva.de.sousa@fb.com', 'renira.rodrigues.da.silva.de.sousa');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARILEIA NUNES DE OLIVEIRA', '2014-07-07', '2014-03-01', 1, 1, 'marileia.nunes.de.oliveira@fb.com', 'marileia.nunes.de.oliveira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('OSWALDIR GOMES', '2014-07-13', '2014-01-19', 1, 1, 'oswaldir.gomes@fb.com', 'oswaldir.gomes');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('RAMAO CARDOSO', '2014-07-11', '2014-05-23', 1, 0, 'ramao.cardoso@fb.com', 'ramao.cardoso');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('IROCIDES APARECIDA FERREIRA', '2014-07-03', '2014-05-26', 0, 0, 'irocides.aparecida.ferreira@fb.com', 'irocides.aparecida.ferreira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ABILIO CAVALHEIRO', '2014-07-06', '2014-06-03', 0, 0, 'abilio.cavalheiro@hotmail.com', 'abilio.cavalheiro');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ALICE DE SOUZA MIRANDA', '2014-07-01', '2014-03-15', 0, 1, 'alice.de.souza.miranda@fb.com', 'alice.de.souza.miranda');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('SILVIO TSIPE RAIRATE', '2014-07-07', '2014-06-06', 0, 0, 'silvio.tsipe.rairate@gmail.com', 'silvio.tsipe.rairate');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ZILMA MARQUES GONCALVES RODRIGUES', '2014-07-02', '2014-03-30', 0, 0, 'zilma.marques.goncalves.rodrigues@hotmail.com', 'zilma.marques.goncalves.rodrigues');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('SILVIO TSIPE RAIRATE', '2014-07-03', '2014-03-12', 1, 0, 'silvio.tsipe.rairate@hotmail.com', 'silvio.tsipe.rairate');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('AURELINDA BATISTA DA SILVA', '2014-07-11', '2014-04-08', 0, 0, 'aurelinda.batista.da.silva@hotmail.com', 'aurelinda.batista.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LUIZ FERNANDO DA SILVA AMORIM', '2014-07-08', '2014-02-05', 0, 0, 'luiz.fernando.da.silva.amorim@fb.com', 'luiz.fernando.da.silva.amorim');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LOURENCO DIAS', '2014-07-13', '2014-04-19', 1, 0, 'lourenco.dias@gmail.com', 'lourenco.dias');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('BENEDITO AMBROSIO DA COSTA', '2014-07-01', '2014-02-05', 0, 0, 'benedito.ambrosio.da.costa@fb.com', 'benedito.ambrosio.da.costa');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('NEUCY DE OLIVEIRA', '2014-07-08', '2014-03-29', 0, 1, 'neucy.de.oliveira@fb.com', 'neucy.de.oliveira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('THANIA CRISTINA DA SILVA BARNABE', '2014-07-01', '2014-01-03', 0, 1, 'thania.cristina.da.silva.barnabe@hotmail.com', 'thania.cristina.da.silva.barnabe');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('GUIOMAR TRELHA FRANCA', '2014-07-09', '2014-05-17', 1, 1, 'guiomar.trelha.franca@hotmail.com', 'guiomar.trelha.franca');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('RAMAO CARDOSO', '2014-07-10', '2014-05-31', 0, 0, 'ramao.cardoso@hotmail.com', 'ramao.cardoso');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARILEIA NUNES DE OLIVEIRA', '2014-07-03', '2014-03-02', 0, 0, 'marileia.nunes.de.oliveira@hotmail.com', 'marileia.nunes.de.oliveira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('THANIA CRISTINA DA SILVA BARNABE', '2014-07-07', '2014-06-22', 0, 0, 'thania.cristina.da.silva.barnabe@gmail.com', 'thania.cristina.da.silva.barnabe');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('DIEGO CESPEDES DE SOUZA', '2014-07-08', '2014-01-30', 1, 0, 'diego.cespedes.de.souza@hotmail.com', 'diego.cespedes.de.souza');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LUIZA ROTTLISBERGER SILVA', '2014-07-02', '2014-02-07', 0, 1, 'luiza.rottlisberger.silva@hotmail.com', 'luiza.rottlisberger.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('CRISTIANE PAES CORDOBA', '2014-07-07', '2014-01-04', 0, 0, 'cristiane.paes.cordoba@hotmail.com', 'cristiane.paes.cordoba');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('BENEDITA GAUDENCIO DA COSTA', '2014-07-01', '2014-04-06', 0, 0, 'benedita.gaudencio.da.costa@fb.com', 'benedita.gaudencio.da.costa');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ANTONIA BORGES DA SILVA', '2014-07-02', '2014-01-30', 0, 1, 'antonia.borges.da.silva@hotmail.com', 'antonia.borges.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ANGELA APARECIDA BERNEGOZZE', '2014-07-01', '2014-04-01', 0, 0, 'angela.aparecida.bernegozze@fb.com', 'angela.aparecida.bernegozze');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ROSILENE ALMEIDA DA SILVA', '2014-07-05', '2014-05-03', 0, 1, 'rosilene.almeida.da.silva@gmail.com', 'rosilene.almeida.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('SILVIO TSIPE RAIRATE', '2014-07-03', '2014-03-19', 0, 1, 'silvio.tsipe.rairate@gmail.com', 'silvio.tsipe.rairate');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ANDRE LUIS CASTRILLON GARCIA', '2014-07-09', '2014-06-03', 1, 1, 'andre.luis.castrillon.garcia@fb.com', 'andre.luis.castrillon.garcia');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('DAVINA PEREIRA DE SALES', '2014-07-02', '2014-01-19', 0, 0, 'davina.pereira.de.sales@hotmail.com', 'davina.pereira.de.sales');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LUIZ LOPES DA SILVA', '2014-07-04', '2014-02-26', 1, 0, 'luiz.lopes.da.silva@hotmail.com', 'luiz.lopes.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ELZA LIMA DE SOUZA MANSANO', '2014-07-10', '2014-03-16', 1, 1, 'elza.lima.de.souza.mansano@fb.com', 'elza.lima.de.souza.mansano');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('VIOLINDO DE SOUZA', '2014-07-09', '2014-04-26', 1, 1, 'violindo.de.souza@hotmail.com', 'violindo.de.souza');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('CORNELIO DIAS DUARTE', '2014-07-02', '2014-06-08', 1, 1, 'cornelio.dias.duarte@gmail.com', 'cornelio.dias.duarte');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('EDIR DIAS DE CARVALHO', '2014-07-12', '2014-04-27', 0, 0, 'edir.dias.de.carvalho@hotmail.com', 'edir.dias.de.carvalho');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('DILMA DE SOUZA', '2014-07-07', '2014-02-21', 1, 0, 'dilma.de.souza@gmail.com', 'dilma.de.souza');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('NICANOR FELIZARDO DOS REIS', '2014-07-07', '2014-05-22', 1, 1, 'nicanor.felizardo.dos.reis@gmail.com', 'nicanor.felizardo.dos.reis');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('CELIA CRISTINA PEREIRA PINTO DOS SANTOS', '2014-07-03', '2014-04-21', 1, 1, 'celia.cristina.pereira.pinto.dos.santos@hotmail.com', 'celia.cristina.pereira.pinto.dos.santos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('NEUCY DE OLIVEIRA', '2014-07-08', '2014-01-25', 1, 1, 'neucy.de.oliveira@hotmail.com', 'neucy.de.oliveira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARIA ELENA ALVES', '2014-07-04', '2014-01-08', 1, 1, 'maria.elena.alves@fb.com', 'maria.elena.alves');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('NEUCY DE OLIVEIRA', '2014-07-01', '2014-03-07', 1, 0, 'neucy.de.oliveira@fb.com', 'neucy.de.oliveira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('VILMA VITORIA DE SOUZA MESSA', '2014-07-08', '2014-02-24', 1, 0, 'vilma.vitoria.de.souza.messa@fb.com', 'vilma.vitoria.de.souza.messa');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('RUBENSMORBECK LEITE', '2014-07-10', '2014-04-16', 1, 0, 'rubensmorbeck.leite@gmail.com', 'rubensmorbeck.leite');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('OLGA PEREIRA', '2014-07-08', '2014-01-06', 1, 1, 'olga.pereira@fb.com', 'olga.pereira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('THANIA CRISTINA DA SILVA BARNABE', '2014-07-02', '2014-01-09', 0, 1, 'thania.cristina.da.silva.barnabe@fb.com', 'thania.cristina.da.silva.barnabe');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('VALDOMIRO LEITE DE SA', '2014-07-03', '2014-05-22', 0, 0, 'valdomiro.leite.de.sa@gmail.com', 'valdomiro.leite.de.sa');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('RUZINO ANTUNES DA SILVA', '2014-07-07', '2014-05-30', 0, 0, 'ruzino.antunes.da.silva@fb.com', 'ruzino.antunes.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ADAIL BANDINELLE DE MORAES', '2014-07-06', '2014-02-28', 1, 1, 'adail.bandinelle.de.moraes@gmail.com', 'adail.bandinelle.de.moraes');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('BENILDE PERES DE CAMPOS', '2014-07-13', '2014-01-21', 1, 1, 'benilde.peres.de.campos@fb.com', 'benilde.peres.de.campos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('AURELINDA BATISTA DA SILVA', '2014-07-13', '2014-03-08', 0, 0, 'aurelinda.batista.da.silva@fb.com', 'aurelinda.batista.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('DIAMANTINA DA SILVA SOARES', '2014-07-08', '2014-02-07', 1, 0, 'diamantina.da.silva.soares@hotmail.com', 'diamantina.da.silva.soares');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('CARMINDA POMPEU AMORIM', '2014-07-01', '2014-04-28', 1, 1, 'carminda.pompeu.amorim@fb.com', 'carminda.pompeu.amorim');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('SONIA MARIA MARTINEZ PENITENTE', '2014-07-10', '2014-04-06', 1, 1, 'sonia.maria.martinez.penitente@fb.com', 'sonia.maria.martinez.penitente');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARIA TEREZINHA ROCHA DE SOUZA', '2014-07-05', '2014-02-27', 0, 0, 'maria.terezinha.rocha.de.souza@gmail.com', 'maria.terezinha.rocha.de.souza');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JOAO DE LUCA', '2014-07-02', '2014-06-02', 1, 0, 'joao.de.luca@gmail.com', 'joao.de.luca');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ABILIO CAVALHEIRO', '2014-07-03', '2014-03-11', 1, 0, 'abilio.cavalheiro@gmail.com', 'abilio.cavalheiro');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARCIA DA SILVA OLIVEIRA', '2014-07-13', '2014-05-13', 0, 1, 'marcia.da.silva.oliveira@fb.com', 'marcia.da.silva.oliveira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('DORILDA ALVES DE CARVALHO', '2014-07-04', '2014-06-09', 0, 1, 'dorilda.alves.de.carvalho@hotmail.com', 'dorilda.alves.de.carvalho');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('DIEGO CESPEDES DE SOUZA', '2014-07-04', '2014-06-25', 0, 0, 'diego.cespedes.de.souza@hotmail.com', 'diego.cespedes.de.souza');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('AFONSO BARBOSA DA SILVA', '2014-07-05', '2014-03-03', 0, 1, 'afonso.barbosa.da.silva@gmail.com', 'afonso.barbosa.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ANTONIA BORGES DA SILVA', '2014-07-08', '2014-02-03', 0, 0, 'antonia.borges.da.silva@fb.com', 'antonia.borges.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MAGALI SANCHES', '2014-07-02', '2014-02-02', 1, 1, 'magali.sanches@gmail.com', 'magali.sanches');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('BENILDE PERES DE CAMPOS', '2014-07-05', '2014-05-03', 0, 1, 'benilde.peres.de.campos@hotmail.com', 'benilde.peres.de.campos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('HABIB FAHED', '2014-07-04', '2014-05-09', 0, 1, 'habib.fahed@fb.com', 'habib.fahed');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LUIZ FERNANDO DA SILVA AMORIM', '2014-07-01', '2014-01-21', 1, 0, 'luiz.fernando.da.silva.amorim@gmail.com', 'luiz.fernando.da.silva.amorim');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LUIZ FERNANDO DA SILVA AMORIM', '2014-07-10', '2014-01-24', 1, 0, 'luiz.fernando.da.silva.amorim@hotmail.com', 'luiz.fernando.da.silva.amorim');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('DIRCEU DE MATTOS', '2014-07-09', '2014-05-02', 1, 0, 'dirceu.de.mattos@fb.com', 'dirceu.de.mattos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ALICE APARECIDA DOS SANTOS', '2014-07-10', '2014-04-19', 0, 1, 'alice.aparecida.dos.santos@hotmail.com', 'alice.aparecida.dos.santos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('CELESIAORMOND RIBEIRO DE CAMPOS', '2014-07-06', '2014-02-10', 1, 1, 'celesiaormond.ribeiro.de.campos@fb.com', 'celesiaormond.ribeiro.de.campos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ANGELA APARECIDA BERNEGOZZE', '2014-07-02', '2014-05-26', 0, 1, 'angela.aparecida.bernegozze@fb.com', 'angela.aparecida.bernegozze');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LAURA SEBASTIANA GURGEL', '2014-07-10', '2014-03-14', 1, 1, 'laura.sebastiana.gurgel@fb.com', 'laura.sebastiana.gurgel');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('QUITERIA LOURENCO DE LIMA', '2014-07-09', '2014-06-14', 0, 1, 'quiteria.lourenco.de.lima@hotmail.com', 'quiteria.lourenco.de.lima');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('RENIRA RODRIGUES DA SILVA DE SOUSA', '2014-07-13', '2014-02-28', 0, 0, 'renira.rodrigues.da.silva.de.sousa@hotmail.com', 'renira.rodrigues.da.silva.de.sousa');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ALICE DE SOUZA MIRANDA', '2014-07-07', '2014-03-31', 0, 0, 'alice.de.souza.miranda@fb.com', 'alice.de.souza.miranda');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ALCEU DOS SANTOS', '2014-07-07', '2014-01-23', 0, 1, 'alceu.dos.santos@gmail.com', 'alceu.dos.santos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LUCINEIDE DE MORAES DO CARMO', '2014-07-07', '2014-01-27', 1, 1, 'lucineide.de.moraes.do.carmo@hotmail.com', 'lucineide.de.moraes.do.carmo');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('SEBASTIANA BENEDITA DA COSTA', '2014-07-04', '2014-02-23', 1, 0, 'sebastiana.benedita.da.costa@fb.com', 'sebastiana.benedita.da.costa');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('BENILDE PERES DE CAMPOS', '2014-07-04', '2014-04-07', 0, 0, 'benilde.peres.de.campos@fb.com', 'benilde.peres.de.campos');
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-27', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-18', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-03', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-21', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-29', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-24', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-20', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-12', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-16', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-20', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-29', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-19', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-06', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-07', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-11', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-02', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-05', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-26', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-07', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-16', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-11', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-07', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-25', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-02', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-07-01', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-14', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-19', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-07-08', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-28', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-18', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-14', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-07', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-21', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-18', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-28', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-30', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-09', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-27', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-21', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-28', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-12', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-06', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-14', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-08', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-06', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-10', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-25', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-27', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-05', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-07', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-26', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-20', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-01', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-20', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-18', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-25', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-07-03', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-05', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-31', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-28', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-02', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-25', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-16', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-25', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-19', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-19', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-31', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-31', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-18', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-21', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-07-08', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-07-07', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-06', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-10', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-30', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-12', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-10', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-17', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-25', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-19', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-26', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-19', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-24', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-31', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-14', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-05', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-09', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-10', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-10', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-18', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-22', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-10', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-07', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-11', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-17', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-08', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-09', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-07-08', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-01', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-22', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
