INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('64733-978', '3464', 'M', 'ANTONIA BORGES DA SILVA', '2014-10-07', 0, 'Italy', 'antonia.borges.da.silva@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('33007-828', '3097', 'F', 'KLEBER MAGALHAES FERREIRA', '2014-12-21', 1, 'Montenegro', 'kleber.magalhaes.ferreira@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('24972-933', '8436', 'M', 'KLEBER MAGALHAES FERREIRA', '2014-01-21', 0, 'Niger', 'kleber.magalhaes.ferreira@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('66289-857', '5547', 'F', 'MARIA TEREZINHA ROCHA DE SOUZA', '2014-10-14', 1, 'St. Vincent & The Grenadines', 'maria.terezinha.rocha.de.souza@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('77838-802', '7959', 'M', 'SUELY DA SILVA CAVALCANTI', '2014-07-11', 0, 'Bosnia & Herzegovina', 'suely.da.silva.cavalcanti@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('55471-260', '9494', 'F', 'ALDEIR ALEX ALVES LIMA', '2014-02-08', 1, 'Senegal', 'aldeir.alex.alves.lima@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('49695-062', '1079', 'F', 'JOSENOTARIO MUNGO', '2014-02-12', 0, 'Saudi Arabia', 'josenotario.mungo@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('30819-173', '9776', 'M', 'OSVALDO PEREIRA BARBOSA', '2014-02-09', 1, 'Tunisia', 'osvaldo.pereira.barbosa@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('71433-298', '8918', 'F', 'WANDERSON COSMO DE ARAUJO', '2014-09-05', 1, 'Korea South', 'wanderson.cosmo.de.araujo@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('24115-960', '0419', 'M', 'ELOIDE CAVANHA', '2014-08-29', 1, 'Monaco', 'eloide.cavanha@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('78146-866', '6779', 'M', 'OSWALDIR GOMES', '2014-12-02', 1, 'Mongolia', 'oswaldir.gomes@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('23674-018', '1666', 'M', 'OSVALDO PEREIRA BARBOSA', '2014-05-11', 1, 'Romania', 'osvaldo.pereira.barbosa@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('89618-521', '3802', 'M', 'RONY HUDSON OLIVEIRA CANDEIRO', '2014-04-08', 1, 'Afghanistan', 'rony.hudson.oliveira.candeiro@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('91946-534', '7536', 'M', 'ANTONIA BORGES DA SILVA', '2014-04-29', 1, 'Thailand', 'antonia.borges.da.silva@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('20301-210', '4061', 'M', 'MARIA TEREZINHA ROCHA DE SOUZA', '2014-05-29', 1, 'Guinea-Bissau', 'maria.terezinha.rocha.de.souza@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('61881-697', '0264', 'M', 'JOAO MAURILIO DA SILVA', '2014-04-14', 0, 'Monaco', 'joao.maurilio.da.silva@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('48177-091', '8258', 'F', 'DIEGO CESPEDES DE SOUZA', '2014-05-23', 1, 'Jamaica', 'diego.cespedes.de.souza@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('68330-154', '0536', 'F', 'LUCINEIDE DE MORAES DO CARMO', '2014-09-26', 0, 'Congo Democratic Republic', 'lucineide.de.moraes.do.carmo@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('74647-757', '2695', 'M', 'MARLENE SANTANA MARTINS', '2014-05-21', 1, 'Korea North', 'marlene.santana.martins@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('14838-072', '3590', 'M', 'MARIA FATIMA SCHEUNEMANN MIRANDA', '2014-03-10', 0, 'Monaco', 'maria.fatima.scheunemann.miranda@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('45661-649', '0597', 'F', 'SEBASTIANA BENEDITA DA COSTA', '2014-08-12', 1, 'Belize', 'sebastiana.benedita.da.costa@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('52692-250', '6831', 'M', 'NADIACUIABANO KUNZE', '2014-10-18', 0, 'Thailand', 'nadiacuiabano.kunze@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('21288-767', '3305', 'M', 'MARILEIA NUNES DE OLIVEIRA', '2014-01-19', 0, 'Niger', 'marileia.nunes.de.oliveira@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('59440-658', '0918', 'M', 'MARIA FATIMA SCHEUNEMANN MIRANDA', '2014-01-05', 1, 'Czech Republic', 'maria.fatima.scheunemann.miranda@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('36704-785', '4283', 'M', 'CRISTIANE PAES CORDOBA', '2014-02-26', 1, 'South Africa', 'cristiane.paes.cordoba@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('36315-789', '4646', 'M', 'MARCIA DA SILVA OLIVEIRA', '2014-04-09', 0, 'South Sudan', 'marcia.da.silva.oliveira@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('93840-481', '8492', 'M', 'ALICE DE SOUZA MIRANDA', '2014-06-16', 1, 'San Marino', 'alice.de.souza.miranda@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('43037-253', '5927', 'F', 'OSWALDIR GOMES', '2014-04-30', 1, 'Guyana', 'oswaldir.gomes@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('17215-582', '7436', 'M', 'MARCONI GEORGE RIBEIRO DA SILVA', '2014-02-23', 1, 'Palau', 'marconi.george.ribeiro.da.silva@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('09668-795', '5643', 'M', 'AFONSO BARBOSA DA SILVA', '2014-11-24', 0, 'St. Lucia', 'afonso.barbosa.da.silva@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('78624-404', '6164', 'M', 'MARCIA DA SILVA OLIVEIRA', '2014-06-28', 1, 'Iraq', 'marcia.da.silva.oliveira@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('02561-382', '9422', 'M', 'BENEDITO AMBROSIO DA COSTA', '2014-09-05', 1, 'Montenegro', 'benedito.ambrosio.da.costa@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('23288-249', '9579', 'F', 'RAMIRO VEDOVATO', '2014-07-21', 1, 'Luxembourg', 'ramiro.vedovato@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('70798-302', '9995', 'M', 'DAVINA PEREIRA DE SALES', '2014-12-19', 0, 'Djibouti', 'davina.pereira.de.sales@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('14784-519', '5638', 'F', 'ADENILTON JOSE DE MIRANDA', '2014-01-24', 1, 'Uganda', 'adenilton.jose.de.miranda@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('37369-764', '3440', 'M', 'ANTONIA BORGES DA SILVA', '2014-11-06', 1, 'Central African Republic', 'antonia.borges.da.silva@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('61445-286', '1120', 'M', 'JORGE TETSUO TAIRA', '2014-10-26', 0, 'Macedonia', 'jorge.tetsuo.taira@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('29766-292', '0675', 'F', 'IVANI DO NASCIMENTO VALENTIM', '2014-04-17', 0, 'France', 'ivani.do.nascimento.valentim@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('18602-410', '9831', 'F', 'ADELSON LUIZ DA SILVA', '2014-04-03', 1, 'Norway', 'adelson.luiz.da.silva@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('36996-947', '5738', 'M', 'SILVIA MENDES', '2014-09-25', 0, 'Namibia', 'silvia.mendes@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('47519-396', '8612', 'F', 'MARCONI GEORGE RIBEIRO DA SILVA', '2014-04-25', 1, 'Qatar', 'marconi.george.ribeiro.da.silva@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('60462-639', '1854', 'M', 'JOSE RIBAMAR BEZERRA SA', '2014-03-04', 1, 'Bhutan', 'jose.ribamar.bezerra.sa@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('29104-004', '1553', 'M', 'FRANCISCA MARIA SILVA COSTA', '2014-03-15', 1, 'Sao Tome & Principe', 'francisca.maria.silva.costa@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('23633-882', '0914', 'M', 'ANA PAULA FIGUEIREDO DA ROCHA', '2014-09-25', 1, 'Cyprus', 'ana.paula.figueiredo.da.rocha@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('99622-945', '6270', 'M', 'QUITERIA LOURENCO DE LIMA', '2014-07-04', 0, 'Turkey', 'quiteria.lourenco.de.lima@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('05678-429', '9552', 'F', 'IROCIDES APARECIDA FERREIRA', '2014-07-16', 0, 'Cote d''Ivoire', 'irocides.aparecida.ferreira@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('06081-738', '6873', 'F', 'NADIACUIABANO KUNZE', '2014-12-21', 1, 'Micronesia', 'nadiacuiabano.kunze@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('95256-971', '7662', 'F', 'ADAIL BANDINELLE DE MORAES', '2014-11-22', 1, 'Cuba', 'adail.bandinelle.de.moraes@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('89998-261', '1089', 'M', 'NICANOR FELIZARDO DOS REIS', '2014-02-21', 1, 'Eritrea', 'nicanor.felizardo.dos.reis@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('86276-231', '3643', 'M', 'ZILMA MARQUES GONCALVES RODRIGUES', '2014-07-24', 1, 'Kiribati', 'zilma.marques.goncalves.rodrigues@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('73078-059', '7676', 'F', 'IVANI DO NASCIMENTO VALENTIM', '2014-04-01', 1, 'Iceland', 'ivani.do.nascimento.valentim@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('80126-913', '6619', 'F', 'LUZIA RODRIGUES DE OLIVEIRA', '2014-11-03', 1, 'Bulgaria', 'luzia.rodrigues.de.oliveira@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('18211-701', '8815', 'F', 'MARIA DO CARMO JERONIMO SILVA', '2014-07-11', 0, 'Maldives', 'maria.do.carmo.jeronimo.silva@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('31770-930', '0288', 'F', 'EUSTAQUIA PRIETO', '2014-10-05', 1, 'Guinea-Bissau', 'eustaquia.prieto@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('36458-076', '2832', 'F', 'ALBERTO FEIZAR CARDOSO ABDALA', '2014-07-21', 1, 'Cameroon', 'alberto.feizar.cardoso.abdala@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('02263-229', '8913', 'M', 'AMERICO FRANCISCO DA SILVA', '2014-07-31', 1, 'Lebanon', 'americo.francisco.da.silva@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('99094-656', '1384', 'F', 'ROSIMEIRE GONCALVES LOPES RAMOS', '2014-03-27', 0, 'India', 'rosimeire.goncalves.lopes.ramos@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('14786-501', '4806', 'M', 'GUIOMAR TRELHA FRANCA', '2014-11-28', 0, 'Seychelles', 'guiomar.trelha.franca@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('51147-682', '3041', 'F', 'ZILMA MARQUES GONCALVES RODRIGUES', '2014-12-29', 0, 'Qatar', 'zilma.marques.goncalves.rodrigues@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('03549-556', '7192', 'M', 'AMERICO FRANCISCO DA SILVA', '2014-05-22', 0, 'Moldova', 'americo.francisco.da.silva@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('78621-381', '8992', 'F', 'CLAUDIO BARBOSA DOS SANTOS', '2014-05-25', 1, 'Congo', 'claudio.barbosa.dos.santos@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('68245-964', '9250', 'M', 'VIRGILIA DIAS VIEIRA', '2014-03-21', 0, 'Tanzania', 'virgilia.dias.vieira@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('90610-717', '2045', 'F', 'ADAIL BANDINELLE DE MORAES', '2014-03-14', 1, 'Uganda', 'adail.bandinelle.de.moraes@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('16537-934', '6023', 'F', 'SILVIA MENDES', '2014-07-01', 1, 'Kyrgyzstan', 'silvia.mendes@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('03090-544', '9304', 'F', 'CELESIAORMOND RIBEIRO DE CAMPOS', '2014-07-20', 1, 'Malaysia', 'celesiaormond.ribeiro.de.campos@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('83956-133', '2478', 'F', 'WILSON CONCEICAO DE MIRANDA', '2014-05-09', 1, 'Armenia', 'wilson.conceicao.de.miranda@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('92724-095', '5255', 'M', 'SEBASTIANA BENEDITA DA COSTA', '2014-02-14', 0, 'Niger', 'sebastiana.benedita.da.costa@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('84222-167', '1343', 'F', 'JOAO MAURILIO DA SILVA', '2014-12-11', 0, 'Slovakia', 'joao.maurilio.da.silva@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('98984-124', '4312', 'F', 'ALIETE FRANCISCA PRATES', '2014-06-22', 1, 'Fiji', 'aliete.francisca.prates@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('16617-690', '6797', 'M', 'MARLENE SANTANA MARTINS', '2014-10-18', 0, 'Germany', 'marlene.santana.martins@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('63967-548', '9421', 'M', 'ALDIVINA REIS FERNANDES', '2014-01-17', 0, 'Saudi Arabia', 'aldivina.reis.fernandes@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('82960-489', '1571', 'F', 'CELESIAORMOND RIBEIRO DE CAMPOS', '2014-10-15', 0, 'St. Kitts & Nevis', 'celesiaormond.ribeiro.de.campos@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('87710-409', '5166', 'F', 'RITA IRACI ALMEIDA DA SILVA', '2014-02-19', 1, 'Botswana', 'rita.iraci.almeida.da.silva@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('59013-537', '3697', 'F', 'ANTONIO INACIO RODRIGUES', '2014-05-28', 1, 'Turkey', 'antonio.inacio.rodrigues@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('07389-404', '0422', 'M', 'MARIA ELENA ALVES', '2014-10-02', 0, 'Brunei', 'maria.elena.alves@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('24938-685', '2436', 'M', 'HABIB FAHED', '2014-06-23', 0, 'Somalia', 'habib.fahed@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('65774-311', '8318', 'M', 'ATAIDE DIAS DE MOURA', '2014-08-02', 0, 'Syria', 'ataide.dias.de.moura@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('49003-109', '5069', 'M', 'ALDEIR ALEX ALVES LIMA', '2014-03-11', 0, 'Kyrgyzstan', 'aldeir.alex.alves.lima@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('11328-024', '6676', 'F', 'CLAUDIO BARBOSA DOS SANTOS', '2014-10-06', 1, 'Argentina', 'claudio.barbosa.dos.santos@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('83486-785', '7993', 'F', 'ELOIR CARLOS FIRMINO', '2014-05-15', 1, 'Vietnam', 'eloir.carlos.firmino@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('25668-199', '5670', 'F', 'ELISABETE ROMERO NOBRE LEAL', '2014-09-21', 0, 'Swaziland', 'elisabete.romero.nobre.leal@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('43899-960', '0909', 'M', 'MARLENE SANTANA MARTINS', '2014-01-26', 0, 'Belarus', 'marlene.santana.martins@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('90090-501', '9320', 'M', 'JOAO DE LUCA', '2014-06-27', 0, 'Burkina Faso', 'joao.de.luca@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('85093-426', '8604', 'M', 'VIRGILIA DIAS VIEIRA', '2014-04-10', 1, 'Namibia', 'virgilia.dias.vieira@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('48930-965', '1064', 'F', 'DAVINA PEREIRA DE SALES', '2014-12-25', 0, 'Belgium', 'davina.pereira.de.sales@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('06513-889', '8988', 'M', 'VALDOMIRO LEITE DE SA', '2014-06-30', 0, 'Kuwait', 'valdomiro.leite.de.sa@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('27151-041', '7149', 'M', 'DIRCEU DE MATTOS', '2014-06-18', 0, 'Thailand', 'dirceu.de.mattos@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('90321-866', '0568', 'M', 'ANTONIO INACIO RODRIGUES', '2014-12-28', 0, 'Norway', 'antonio.inacio.rodrigues@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('49430-114', '3111', 'M', 'ADENILTON JOSE DE MIRANDA', '2014-09-10', 1, 'Austria', 'adenilton.jose.de.miranda@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('23571-076', '3940', 'M', 'ANDRE LUIS CASTRILLON GARCIA', '2014-06-01', 0, 'Morocco', 'andre.luis.castrillon.garcia@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('12047-791', '1958', 'F', 'CLAUDIO BARBOSA DOS SANTOS', '2014-08-07', 1, 'Albania', 'claudio.barbosa.dos.santos@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('65401-952', '6756', 'F', 'VIRGILIA DIAS VIEIRA', '2014-06-26', 1, 'Tajikistan', 'virgilia.dias.vieira@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('60405-275', '9639', 'F', 'IVANI DO NASCIMENTO VALENTIM', '2014-08-18', 0, 'United States of America', 'ivani.do.nascimento.valentim@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('89524-131', '7543', 'F', 'ELZA LIMA DE SOUZA MANSANO', '2014-07-31', 1, 'Poland', 'elza.lima.de.souza.mansano@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('91131-157', '7162', 'M', 'ANA ALVES LUCIANO', '2014-09-17', 1, 'Australia', 'ana.alves.luciano@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('57145-702', '8480', 'F', 'ADAIL BANDINELLE DE MORAES', '2014-08-03', 0, 'Lesotho', 'adail.bandinelle.de.moraes@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('04589-428', '8247', 'F', 'ANA ALVES LUCIANO', '2014-05-11', 0, 'Senegal', 'ana.alves.luciano@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('45017-902', '4631', 'M', 'MARILEIA NUNES DE OLIVEIRA', '2014-07-18', 0, 'Slovenia', 'marileia.nunes.de.oliveira@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('96907-794', '5631', 'F', 'ANTONIA BORGES DA SILVA', '2014-10-30', 0, 'Kazakhstan', 'antonia.borges.da.silva@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('49610-189', '1620', 'F', 'ALIETE FRANCISCA PRATES', '2014-10-12', 0, 'Swaziland', 'aliete.francisca.prates@yahoo.com');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('NEIVA OBERGER FERREIRA', '2014-07-01', '2014-03-20', 0, 1, 'neiva.oberger.ferreira@gmail.com', 'neiva.oberger.ferreira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('NADIACUIABANO KUNZE', '2014-07-03', '2014-01-13', 0, 1, 'nadiacuiabano.kunze@hotmail.com', 'nadiacuiabano.kunze');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('KLEBER MAGALHAES FERREIRA', '2014-07-02', '2014-03-18', 0, 0, 'kleber.magalhaes.ferreira@fb.com', 'kleber.magalhaes.ferreira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('SUELY DA SILVA CAVALCANTI', '2014-07-04', '2014-05-15', 1, 0, 'suely.da.silva.cavalcanti@fb.com', 'suely.da.silva.cavalcanti');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LUIZ LOPES DA SILVA', '2014-07-11', '2014-01-02', 1, 0, 'luiz.lopes.da.silva@gmail.com', 'luiz.lopes.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('HABIB FAHED', '2014-07-01', '2014-05-17', 1, 1, 'habib.fahed@fb.com', 'habib.fahed');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JOSE RIBAMAR BEZERRA SA', '2014-07-11', '2014-02-28', 0, 1, 'jose.ribamar.bezerra.sa@hotmail.com', 'jose.ribamar.bezerra.sa');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('KLEBER MAGALHAES FERREIRA', '2014-07-06', '2014-06-22', 1, 0, 'kleber.magalhaes.ferreira@fb.com', 'kleber.magalhaes.ferreira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('AFONSO BARBOSA DA SILVA', '2014-07-06', '2014-05-12', 1, 1, 'afonso.barbosa.da.silva@hotmail.com', 'afonso.barbosa.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ALICE FERNANDES DE OLIVEIRA', '2014-07-01', '2014-02-22', 1, 0, 'alice.fernandes.de.oliveira@hotmail.com', 'alice.fernandes.de.oliveira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('GLAUBER DA COSTA ARRUDA', '2014-07-09', '2014-05-24', 1, 1, 'glauber.da.costa.arruda@hotmail.com', 'glauber.da.costa.arruda');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('QUITERIA LOURENCO DE LIMA', '2014-07-03', '2014-06-13', 0, 0, 'quiteria.lourenco.de.lima@hotmail.com', 'quiteria.lourenco.de.lima');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('EDIO JUSTO BORGES', '2014-07-05', '2014-06-08', 0, 1, 'edio.justo.borges@fb.com', 'edio.justo.borges');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('HELIO SAMBATTI', '2014-07-10', '2014-01-03', 0, 0, 'helio.sambatti@fb.com', 'helio.sambatti');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LOURIVAL ROSA GUIMARAES', '2014-07-10', '2014-04-12', 1, 0, 'lourival.rosa.guimaraes@hotmail.com', 'lourival.rosa.guimaraes');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('HELOIZA ALMEIDA DOS SANTOS', '2014-07-08', '2014-06-29', 0, 1, 'heloiza.almeida.dos.santos@fb.com', 'heloiza.almeida.dos.santos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('SUELY DA SILVA CAVALCANTI', '2014-07-03', '2014-06-14', 1, 0, 'suely.da.silva.cavalcanti@hotmail.com', 'suely.da.silva.cavalcanti');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('AFONSO BARBOSA DA SILVA', '2014-07-10', '2014-02-19', 1, 1, 'afonso.barbosa.da.silva@gmail.com', 'afonso.barbosa.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('RUBENSMORBECK LEITE', '2014-07-09', '2014-04-30', 1, 0, 'rubensmorbeck.leite@fb.com', 'rubensmorbeck.leite');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARIA DO CARMO JERONIMO SILVA', '2014-07-07', '2014-03-24', 1, 1, 'maria.do.carmo.jeronimo.silva@fb.com', 'maria.do.carmo.jeronimo.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('EUZEBIO DA SILVA CEZAR', '2014-07-02', '2014-03-16', 1, 1, 'euzebio.da.silva.cezar@gmail.com', 'euzebio.da.silva.cezar');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LUIZ LOPES DA SILVA', '2014-07-13', '2014-04-03', 1, 0, 'luiz.lopes.da.silva@gmail.com', 'luiz.lopes.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('PAULO TEIXEIRA DE ABREU', '2014-07-03', '2014-03-03', 0, 0, 'paulo.teixeira.de.abreu@gmail.com', 'paulo.teixeira.de.abreu');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ALICE APARECIDA DOS SANTOS', '2014-07-05', '2014-02-12', 0, 1, 'alice.aparecida.dos.santos@fb.com', 'alice.aparecida.dos.santos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LIDIANE DO PRADO BRITE', '2014-07-02', '2014-02-17', 0, 1, 'lidiane.do.prado.brite@fb.com', 'lidiane.do.prado.brite');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('VILMA VITORIA DE SOUZA MESSA', '2014-07-06', '2014-02-16', 1, 0, 'vilma.vitoria.de.souza.messa@gmail.com', 'vilma.vitoria.de.souza.messa');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JOSE JESUS DA HORA', '2014-07-04', '2014-03-06', 0, 1, 'jose.jesus.da.hora@fb.com', 'jose.jesus.da.hora');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ALBERTO FEIZAR CARDOSO ABDALA', '2014-07-11', '2014-05-20', 1, 0, 'alberto.feizar.cardoso.abdala@fb.com', 'alberto.feizar.cardoso.abdala');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARIA ALVES SUTIL', '2014-07-03', '2014-03-22', 1, 0, 'maria.alves.sutil@fb.com', 'maria.alves.sutil');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('IROCIDES APARECIDA FERREIRA', '2014-07-04', '2014-01-20', 0, 1, 'irocides.aparecida.ferreira@hotmail.com', 'irocides.aparecida.ferreira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ELISABETE ROMERO NOBRE LEAL', '2014-07-05', '2014-06-23', 1, 0, 'elisabete.romero.nobre.leal@fb.com', 'elisabete.romero.nobre.leal');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('AURELINDA BATISTA DA SILVA', '2014-07-05', '2014-03-18', 0, 1, 'aurelinda.batista.da.silva@hotmail.com', 'aurelinda.batista.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('SOLANGE APARECIDA DO PRADO DA CRUZ', '2014-07-12', '2014-01-22', 0, 1, 'solange.aparecida.do.prado.da.cruz@hotmail.com', 'solange.aparecida.do.prado.da.cruz');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JOSE JESUS DA HORA', '2014-07-02', '2014-02-25', 0, 0, 'jose.jesus.da.hora@fb.com', 'jose.jesus.da.hora');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ANA ALVES LUCIANO', '2014-07-11', '2014-04-08', 1, 1, 'ana.alves.luciano@hotmail.com', 'ana.alves.luciano');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARCIA DA SILVA OLIVEIRA', '2014-07-06', '2014-06-26', 1, 1, 'marcia.da.silva.oliveira@hotmail.com', 'marcia.da.silva.oliveira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LAURA SEBASTIANA GURGEL', '2014-07-10', '2014-01-26', 1, 0, 'laura.sebastiana.gurgel@hotmail.com', 'laura.sebastiana.gurgel');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARCONI GEORGE RIBEIRO DA SILVA', '2014-07-03', '2014-04-11', 0, 1, 'marconi.george.ribeiro.da.silva@fb.com', 'marconi.george.ribeiro.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARIA TEREZINHA ROCHA DE SOUZA', '2014-07-06', '2014-02-12', 1, 0, 'maria.terezinha.rocha.de.souza@fb.com', 'maria.terezinha.rocha.de.souza');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ANGELA APARECIDA BERNEGOZZE', '2014-07-04', '2014-05-15', 1, 0, 'angela.aparecida.bernegozze@gmail.com', 'angela.aparecida.bernegozze');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('BENEDITO AMBROSIO DA COSTA', '2014-07-06', '2014-01-25', 0, 0, 'benedito.ambrosio.da.costa@fb.com', 'benedito.ambrosio.da.costa');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ALDIVINA REIS FERNANDES', '2014-07-08', '2014-06-10', 0, 1, 'aldivina.reis.fernandes@gmail.com', 'aldivina.reis.fernandes');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('QUITERIA LOURENCO DE LIMA', '2014-07-09', '2014-03-08', 1, 0, 'quiteria.lourenco.de.lima@hotmail.com', 'quiteria.lourenco.de.lima');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ANA ALVES LUCIANO', '2014-07-12', '2014-02-13', 1, 1, 'ana.alves.luciano@hotmail.com', 'ana.alves.luciano');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ABILIO CAVALHEIRO', '2014-07-11', '2014-02-03', 0, 0, 'abilio.cavalheiro@fb.com', 'abilio.cavalheiro');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('EUSTAQUIA PRIETO', '2014-07-13', '2014-02-13', 1, 0, 'eustaquia.prieto@gmail.com', 'eustaquia.prieto');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LOURIVAL ROSA GUIMARAES', '2014-07-10', '2014-01-19', 0, 1, 'lourival.rosa.guimaraes@fb.com', 'lourival.rosa.guimaraes');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('INES APARECIDA DA SILVA', '2014-07-07', '2014-06-18', 0, 0, 'ines.aparecida.da.silva@gmail.com', 'ines.aparecida.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('KLEBER MAGALHAES FERREIRA', '2014-07-01', '2014-03-28', 0, 1, 'kleber.magalhaes.ferreira@hotmail.com', 'kleber.magalhaes.ferreira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARIA DAIANE DE ARAUJO SOUZA', '2014-07-07', '2014-01-30', 1, 1, 'maria.daiane.de.araujo.souza@fb.com', 'maria.daiane.de.araujo.souza');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ALDIVINA REIS FERNANDES', '2014-07-03', '2014-04-02', 1, 1, 'aldivina.reis.fernandes@gmail.com', 'aldivina.reis.fernandes');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ABIGAIL DA SILVA LARA', '2014-07-13', '2014-03-08', 1, 1, 'abigail.da.silva.lara@gmail.com', 'abigail.da.silva.lara');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('OSVALDO PEREIRA BARBOSA', '2014-07-11', '2014-02-28', 0, 0, 'osvaldo.pereira.barbosa@hotmail.com', 'osvaldo.pereira.barbosa');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('NEUCY DE OLIVEIRA', '2014-07-04', '2014-06-08', 1, 0, 'neucy.de.oliveira@gmail.com', 'neucy.de.oliveira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARIA ELENA ALVES', '2014-07-12', '2014-03-14', 0, 1, 'maria.elena.alves@gmail.com', 'maria.elena.alves');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JOAO MAURILIO DA SILVA', '2014-07-12', '2014-01-24', 0, 0, 'joao.maurilio.da.silva@gmail.com', 'joao.maurilio.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('BENEDITO AMBROSIO DA COSTA', '2014-07-13', '2014-03-12', 0, 0, 'benedito.ambrosio.da.costa@gmail.com', 'benedito.ambrosio.da.costa');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JOAQUIM BORGES RODRIGUES', '2014-07-05', '2014-03-08', 1, 0, 'joaquim.borges.rodrigues@hotmail.com', 'joaquim.borges.rodrigues');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JOANA ANTUNES', '2014-07-05', '2014-02-18', 1, 1, 'joana.antunes@fb.com', 'joana.antunes');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('SILVIO TSIPE RAIRATE', '2014-07-07', '2014-02-10', 0, 0, 'silvio.tsipe.rairate@hotmail.com', 'silvio.tsipe.rairate');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LUIZA ROTTLISBERGER SILVA', '2014-07-13', '2014-03-08', 0, 1, 'luiza.rottlisberger.silva@fb.com', 'luiza.rottlisberger.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('SEBASTIANA BENEDITA DA COSTA', '2014-07-08', '2014-04-04', 1, 1, 'sebastiana.benedita.da.costa@hotmail.com', 'sebastiana.benedita.da.costa');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('VIOLINDO DE SOUZA', '2014-07-05', '2014-02-03', 0, 0, 'violindo.de.souza@hotmail.com', 'violindo.de.souza');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('AFONSO BARBOSA DA SILVA', '2014-07-12', '2014-05-22', 1, 0, 'afonso.barbosa.da.silva@gmail.com', 'afonso.barbosa.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('NADIACUIABANO KUNZE', '2014-07-06', '2014-06-19', 1, 0, 'nadiacuiabano.kunze@fb.com', 'nadiacuiabano.kunze');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('WANDERSON COSMO DE ARAUJO', '2014-07-02', '2014-02-23', 1, 0, 'wanderson.cosmo.de.araujo@hotmail.com', 'wanderson.cosmo.de.araujo');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JOSE NUNES PEREIRA', '2014-07-02', '2014-03-22', 0, 0, 'jose.nunes.pereira@gmail.com', 'jose.nunes.pereira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('SONIA MARIA MARTINEZ PENITENTE', '2014-07-13', '2014-04-22', 1, 0, 'sonia.maria.martinez.penitente@hotmail.com', 'sonia.maria.martinez.penitente');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ROSILENE ALMEIDA DA SILVA', '2014-07-01', '2014-04-23', 0, 1, 'rosilene.almeida.da.silva@fb.com', 'rosilene.almeida.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('IROCIDES APARECIDA FERREIRA', '2014-07-08', '2014-04-21', 0, 1, 'irocides.aparecida.ferreira@gmail.com', 'irocides.aparecida.ferreira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JOSE NUNES PEREIRA', '2014-07-01', '2014-06-24', 0, 1, 'jose.nunes.pereira@fb.com', 'jose.nunes.pereira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('CARMINDA POMPEU AMORIM', '2014-07-10', '2014-02-14', 0, 0, 'carminda.pompeu.amorim@fb.com', 'carminda.pompeu.amorim');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JULIO APARECIDO DE SOUZA', '2014-07-07', '2014-04-11', 0, 0, 'julio.aparecido.de.souza@fb.com', 'julio.aparecido.de.souza');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LOURENCO DIAS', '2014-07-13', '2014-03-31', 0, 1, 'lourenco.dias@hotmail.com', 'lourenco.dias');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('AURELINDA BATISTA DA SILVA', '2014-07-06', '2014-02-16', 0, 0, 'aurelinda.batista.da.silva@gmail.com', 'aurelinda.batista.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('FRANCISCA MARIA SILVA COSTA', '2014-07-03', '2014-02-03', 1, 0, 'francisca.maria.silva.costa@hotmail.com', 'francisca.maria.silva.costa');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LUIZ LOPES DA SILVA', '2014-07-04', '2014-01-13', 0, 0, 'luiz.lopes.da.silva@gmail.com', 'luiz.lopes.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('EUSTAQUIA PRIETO', '2014-07-04', '2014-05-27', 1, 1, 'eustaquia.prieto@gmail.com', 'eustaquia.prieto');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('CARLOS SERGIO URBANIN', '2014-07-13', '2014-06-30', 1, 0, 'carlos.sergio.urbanin@hotmail.com', 'carlos.sergio.urbanin');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('EDIR DIAS DE CARVALHO', '2014-07-12', '2014-05-26', 1, 0, 'edir.dias.de.carvalho@gmail.com', 'edir.dias.de.carvalho');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('NEUCY DE OLIVEIRA', '2014-07-04', '2014-06-23', 0, 0, 'neucy.de.oliveira@gmail.com', 'neucy.de.oliveira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JOSE NUNES PEREIRA', '2014-07-07', '2014-02-09', 0, 1, 'jose.nunes.pereira@fb.com', 'jose.nunes.pereira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('RITA IRACI ALMEIDA DA SILVA', '2014-07-06', '2014-01-10', 1, 0, 'rita.iraci.almeida.da.silva@fb.com', 'rita.iraci.almeida.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('DIRCEU DE MATTOS', '2014-07-08', '2014-06-22', 0, 0, 'dirceu.de.mattos@gmail.com', 'dirceu.de.mattos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('CARLOS SERGIO URBANIN', '2014-07-05', '2014-01-02', 0, 0, 'carlos.sergio.urbanin@hotmail.com', 'carlos.sergio.urbanin');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARLENE SANTANA MARTINS', '2014-07-06', '2014-01-27', 0, 0, 'marlene.santana.martins@gmail.com', 'marlene.santana.martins');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARGARETH VIRGINIA DE REZENDE MEHLMANN', '2014-07-07', '2014-01-15', 1, 0, 'margareth.virginia.de.rezende.mehlmann@hotmail.com', 'margareth.virginia.de.rezende.mehlmann');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LUZIA RODRIGUES DE OLIVEIRA', '2014-07-08', '2014-01-20', 1, 1, 'luzia.rodrigues.de.oliveira@hotmail.com', 'luzia.rodrigues.de.oliveira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('CLEUSA FERREIRA MACIEL', '2014-07-11', '2014-02-08', 1, 1, 'cleusa.ferreira.maciel@hotmail.com', 'cleusa.ferreira.maciel');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('SEBASTIANA BENEDITA DA COSTA', '2014-07-01', '2014-03-17', 0, 1, 'sebastiana.benedita.da.costa@hotmail.com', 'sebastiana.benedita.da.costa');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('KLEBER MAGALHAES FERREIRA', '2014-07-01', '2014-06-16', 0, 0, 'kleber.magalhaes.ferreira@fb.com', 'kleber.magalhaes.ferreira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LAURA SEBASTIANA GURGEL', '2014-07-04', '2014-01-17', 0, 1, 'laura.sebastiana.gurgel@hotmail.com', 'laura.sebastiana.gurgel');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('WANDERSON COSMO DE ARAUJO', '2014-07-12', '2014-05-01', 0, 0, 'wanderson.cosmo.de.araujo@hotmail.com', 'wanderson.cosmo.de.araujo');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('IVANI DO NASCIMENTO VALENTIM', '2014-07-02', '2014-01-28', 1, 1, 'ivani.do.nascimento.valentim@hotmail.com', 'ivani.do.nascimento.valentim');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('CARLOS SERGIO URBANIN', '2014-07-09', '2014-06-05', 1, 1, 'carlos.sergio.urbanin@gmail.com', 'carlos.sergio.urbanin');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('CRISTIANE PAES CORDOBA', '2014-07-02', '2014-05-14', 1, 1, 'cristiane.paes.cordoba@fb.com', 'cristiane.paes.cordoba');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('VIOLINDO DE SOUZA', '2014-07-02', '2014-04-03', 0, 1, 'violindo.de.souza@fb.com', 'violindo.de.souza');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('BENEDITA GAUDENCIO DA COSTA', '2014-07-04', '2014-03-29', 0, 1, 'benedita.gaudencio.da.costa@fb.com', 'benedita.gaudencio.da.costa');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('CARLOS SERGIO URBANIN', '2014-07-08', '2014-03-21', 1, 0, 'carlos.sergio.urbanin@gmail.com', 'carlos.sergio.urbanin');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARGARETH VIRGINIA DE REZENDE MEHLMANN', '2014-07-03', '2014-03-06', 1, 0, 'margareth.virginia.de.rezende.mehlmann@fb.com', 'margareth.virginia.de.rezende.mehlmann');
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-07', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-10', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-03', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-08', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-25', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-30', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-17', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-24', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-29', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-06', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-13', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-16', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-03', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-05', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-20', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-24', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-08', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-27', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-07-10', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-21', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-21', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-30', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-30', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-31', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-15', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-17', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-31', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-24', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-26', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-15', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-17', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-05', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-23', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-20', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-10', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-11', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-15', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-26', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-07-05', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-07-04', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-13', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-02', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-01', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-21', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-05', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-17', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-12', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-14', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-09', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-10', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-25', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-28', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-30', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-21', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-12', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-26', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-16', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-24', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-09', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-21', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-28', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-17', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-16', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-25', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-31', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-22', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-04', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-02', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-07', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-07-07', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-07-12', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-17', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-20', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-07', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-02', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-22', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-04', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-21', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-26', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-29', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-04', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-05', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-29', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-05', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-29', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-20', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-19', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-31', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-18', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-20', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-20', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-25', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-14', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-27', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-16', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-14', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-18', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-16', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-03', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-17', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
