INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('88911-698', '0488', 'M', 'THANIA CRISTINA DA SILVA BARNABE', '2014-02-14', 0, 'St. Kitts & Nevis', 'thania.cristina.da.silva.barnabe@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('57576-303', '5632', 'M', 'ANTONIO INACIO RODRIGUES', '2014-03-10', 0, 'Cape Verde', 'antonio.inacio.rodrigues@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('34635-197', '8739', 'F', 'LUIZA ROTTLISBERGER SILVA', '2014-02-18', 0, 'Gabon', 'luiza.rottlisberger.silva@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('04415-868', '6924', 'F', 'LAURA SEBASTIANA GURGEL', '2014-07-30', 1, 'Brunei', 'laura.sebastiana.gurgel@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('62359-564', '9322', 'M', 'SILVIO TSIPE RAIRATE', '2014-04-18', 1, 'Albania', 'silvio.tsipe.rairate@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('05377-594', '7285', 'M', 'RENIRA RODRIGUES DA SILVA DE SOUSA', '2014-12-25', 0, 'Turkmenistan', 'renira.rodrigues.da.silva.de.sousa@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('16733-595', '2641', 'M', 'ALICE DE SOUZA MIRANDA', '2014-04-05', 0, 'Slovenia', 'alice.de.souza.miranda@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('12669-106', '4934', 'F', 'RUZINO ANTUNES DA SILVA', '2014-05-02', 0, 'Niger', 'ruzino.antunes.da.silva@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('16624-131', '1467', 'M', 'ELOIDE CAVANHA', '2014-12-27', 0, 'Chile', 'eloide.cavanha@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('32417-213', '5565', 'F', 'IROCIDES APARECIDA FERREIRA', '2014-02-22', 1, 'Burundi', 'irocides.aparecida.ferreira@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('64260-785', '0870', 'M', 'SONIA MARIA MARTINEZ PENITENTE', '2014-01-14', 1, 'Niger', 'sonia.maria.martinez.penitente@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('33173-052', '3975', 'F', 'DIEGO CESPEDES DE SOUZA', '2014-07-06', 0, 'Jamaica', 'diego.cespedes.de.souza@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('64068-728', '3424', 'F', 'CORNELIO DIAS DUARTE', '2014-04-07', 1, 'Swaziland', 'cornelio.dias.duarte@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('63910-039', '2908', 'F', 'MARGARETH VIRGINIA DE REZENDE MEHLMANN', '2014-08-15', 0, 'Djibouti', 'margareth.virginia.de.rezende.mehlmann@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('03907-985', '2936', 'M', 'BENJAMIM GAUNA', '2014-09-17', 0, 'St. Lucia', 'benjamim.gauna@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('35159-545', '7986', 'M', 'LIDIANE DO PRADO BRITE', '2014-03-19', 0, 'Uganda', 'lidiane.do.prado.brite@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('81794-062', '1164', 'M', 'ROSILENE ALMEIDA DA SILVA', '2014-08-14', 1, 'Nepal', 'rosilene.almeida.da.silva@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('91392-925', '8217', 'F', 'BENILDE PERES DE CAMPOS', '2014-09-11', 1, 'New Zealand', 'benilde.peres.de.campos@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('32202-730', '0309', 'F', 'BEATRIZ PEREIRA LIMA', '2014-02-27', 0, 'Palestinian State', 'beatriz.pereira.lima@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('71742-441', '0965', 'F', 'SEBASTIANA BENEDITA DA COSTA', '2014-04-08', 1, 'Rwanda', 'sebastiana.benedita.da.costa@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('60131-097', '3976', 'F', 'CARMINDA POMPEU AMORIM', '2014-12-13', 1, 'Guinea-Bissau', 'carminda.pompeu.amorim@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('31533-361', '5458', 'F', 'CLEODETE CANOLA DE CAMPOS', '2014-01-31', 0, 'Belgium', 'cleodete.canola.de.campos@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('47307-839', '7559', 'M', 'MARIA FATIMA SCHEUNEMANN MIRANDA', '2014-12-27', 0, 'Mauritania', 'maria.fatima.scheunemann.miranda@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('04331-810', '8107', 'M', 'PAULO TEIXEIRA DE ABREU', '2014-09-09', 0, 'Switzerland', 'paulo.teixeira.de.abreu@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('15237-082', '6578', 'M', 'LUIZ FERNANDO DA SILVA AMORIM', '2014-01-14', 1, 'San Marino', 'luiz.fernando.da.silva.amorim@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('20718-895', '0072', 'F', 'JOSE JESUS DA HORA', '2014-01-05', 1, 'Liechtenstein', 'jose.jesus.da.hora@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('82852-379', '7871', 'M', 'DIRCEU DE MATTOS', '2014-05-05', 0, 'Kosovo', 'dirceu.de.mattos@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('65906-514', '0894', 'F', 'VALDOMIRO LEITE DE SA', '2014-05-10', 0, 'Kazakhstan', 'valdomiro.leite.de.sa@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('49348-646', '2457', 'F', 'ROBSON LUIZ DO NASCIMENTO PUERTAS', '2014-08-15', 0, 'Swaziland', 'robson.luiz.do.nascimento.puertas@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('33637-414', '8646', 'M', 'JOSE JESUS DA HORA', '2014-08-03', 0, 'The Netherlands', 'jose.jesus.da.hora@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('40775-213', '2143', 'M', 'MARIA DO CARMO JERONIMO SILVA', '2014-11-26', 1, 'Congo', 'maria.do.carmo.jeronimo.silva@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('79277-553', '7121', 'F', 'MARIA ELENA ALVES', '2014-07-15', 0, 'Congo Democratic Republic', 'maria.elena.alves@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('44590-796', '2821', 'M', 'JULIO APARECIDO DE SOUZA', '2014-09-29', 0, 'Uruguay', 'julio.aparecido.de.souza@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('48890-720', '9790', 'F', 'LUCINEIDE DE MORAES DO CARMO', '2014-12-16', 0, 'Tonga', 'lucineide.de.moraes.do.carmo@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('61188-735', '7780', 'M', 'JOSE EVALDO DA SILVA', '2014-03-18', 1, 'Canada', 'jose.evaldo.da.silva@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('50150-288', '3609', 'F', 'VIRGILIA DIAS VIEIRA', '2014-06-23', 0, 'Kiribati', 'virgilia.dias.vieira@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('83042-590', '9792', 'M', 'PAULO TEIXEIRA DE ABREU', '2014-07-08', 0, 'Dominican Republic', 'paulo.teixeira.de.abreu@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('02965-606', '3098', 'F', 'EDIO JUSTO BORGES', '2014-02-16', 0, 'Papua New Guinea', 'edio.justo.borges@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('54683-967', '6315', 'F', 'ALICE FERNANDES DE OLIVEIRA', '2014-05-14', 0, 'East Timor', 'alice.fernandes.de.oliveira@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('10330-300', '6987', 'M', 'EDIO JUSTO BORGES', '2014-07-23', 0, 'Congo', 'edio.justo.borges@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('41863-648', '8063', 'F', 'EDIR DIAS DE CARVALHO', '2014-08-12', 0, 'Sweden', 'edir.dias.de.carvalho@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('98168-230', '6307', 'M', 'ANA ALVES LUCIANO', '2014-01-27', 0, 'Bulgaria', 'ana.alves.luciano@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('93646-116', '2367', 'F', 'MIGUEL JOAQUIM SILVA', '2014-02-28', 1, 'Tanzania', 'miguel.joaquim.silva@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('90544-420', '4813', 'M', 'MARCIA DA SILVA OLIVEIRA', '2014-09-28', 1, 'Bahamas', 'marcia.da.silva.oliveira@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('18472-886', '6120', 'M', 'NEUCY DE OLIVEIRA', '2014-10-25', 1, 'Congo Democratic Republic', 'neucy.de.oliveira@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('33761-788', '2449', 'F', 'LAURA SEBASTIANA GURGEL', '2014-03-22', 1, 'Saudi Arabia', 'laura.sebastiana.gurgel@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('51524-527', '7614', 'F', 'SONIA MARIA MARTINEZ PENITENTE', '2014-04-12', 1, 'Myanmar (Burma)', 'sonia.maria.martinez.penitente@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('74105-652', '2463', 'F', 'RAMAO CARDOSO', '2014-09-29', 0, 'Bhutan', 'ramao.cardoso@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('54843-306', '2382', 'F', 'GLAUBER DA COSTA ARRUDA', '2014-05-07', 0, 'Australia', 'glauber.da.costa.arruda@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('07489-237', '1366', 'F', 'ALIETE FRANCISCA PRATES', '2014-04-15', 0, 'Moldova', 'aliete.francisca.prates@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('60588-932', '8478', 'M', 'FRANCISCA MARIA SILVA COSTA', '2014-02-22', 1, 'Bhutan', 'francisca.maria.silva.costa@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('40207-397', '7509', 'F', 'ANGELA APARECIDA BERNEGOZZE', '2014-05-25', 1, 'Czech Republic', 'angela.aparecida.bernegozze@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('55342-080', '7292', 'F', 'JOSE EVALDO DA SILVA', '2014-08-02', 1, 'Swaziland', 'jose.evaldo.da.silva@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('21829-096', '5491', 'M', 'ANDRE LUIS CASTRILLON GARCIA', '2014-06-29', 0, 'Guatemala', 'andre.luis.castrillon.garcia@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('03505-433', '3084', 'M', 'ADAIL BANDINELLE DE MORAES', '2014-04-07', 1, 'Latvia', 'adail.bandinelle.de.moraes@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('36902-257', '8344', 'M', 'LUCINEIDE DE MORAES DO CARMO', '2014-10-27', 1, 'Finland', 'lucineide.de.moraes.do.carmo@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('77406-036', '4039', 'F', 'SILVIO TSIPE RAIRATE', '2014-08-09', 0, 'Mali', 'silvio.tsipe.rairate@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('28148-467', '8773', 'F', 'DELCY MARTINS DA SILVA', '2014-06-18', 0, 'Ecuador', 'delcy.martins.da.silva@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('52211-055', '6245', 'F', 'CLAUDIO BARBOSA DOS SANTOS', '2014-09-24', 1, 'Cape Verde', 'claudio.barbosa.dos.santos@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('30846-134', '8658', 'F', 'SONIA MARIA MARTINEZ PENITENTE', '2014-12-25', 0, 'Rwanda', 'sonia.maria.martinez.penitente@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('00312-890', '7355', 'F', 'MIGUEL JOAQUIM SILVA', '2014-11-30', 1, 'Algeria', 'miguel.joaquim.silva@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('97253-095', '6151', 'F', 'KLEBER MAGALHAES FERREIRA', '2014-12-26', 0, 'South Africa', 'kleber.magalhaes.ferreira@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('27980-861', '3999', 'F', 'JOSE NUNES PEREIRA', '2014-05-04', 0, 'Algeria', 'jose.nunes.pereira@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('34231-069', '1338', 'M', 'CLAUDIO BARBOSA DOS SANTOS', '2014-07-03', 0, 'Costa Rica', 'claudio.barbosa.dos.santos@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('56591-076', '7258', 'M', 'BEATRIZ PEREIRA LIMA', '2014-03-03', 0, 'Central African Republic', 'beatriz.pereira.lima@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('09249-655', '5744', 'M', 'CORNELIO DIAS DUARTE', '2014-10-15', 1, 'Vietnam', 'cornelio.dias.duarte@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('63518-856', '1635', 'M', 'MARIA DO CARMO JERONIMO SILVA', '2014-12-06', 0, 'Kazakhstan', 'maria.do.carmo.jeronimo.silva@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('60191-742', '9059', 'M', 'ALICE APARECIDA DOS SANTOS', '2014-02-13', 1, 'Israel', 'alice.aparecida.dos.santos@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('78447-366', '3973', 'M', 'ABIGAIL DA SILVA LARA', '2014-06-25', 1, 'Azerbaijan', 'abigail.da.silva.lara@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('42554-896', '4212', 'M', 'ANGELA APARECIDA BERNEGOZZE', '2014-02-14', 1, 'Sudan', 'angela.aparecida.bernegozze@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('10289-638', '6882', 'M', 'MAGALI SANCHES', '2014-06-30', 0, 'Turkey', 'magali.sanches@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('93899-375', '1696', 'M', 'MAGALI SANCHES', '2014-10-20', 0, 'Gabon', 'magali.sanches@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('65516-064', '7391', 'M', 'OSVALDO PEREIRA BARBOSA', '2014-12-19', 0, 'Guatemala', 'osvaldo.pereira.barbosa@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('53666-132', '3351', 'F', 'JOSE RIBAMAR BEZERRA SA', '2014-10-08', 0, 'Portugal', 'jose.ribamar.bezerra.sa@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('89491-974', '6461', 'F', 'DELCY MARTINS DA SILVA', '2014-07-21', 1, 'Maldives', 'delcy.martins.da.silva@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('15130-140', '0051', 'M', 'MARCONI GEORGE RIBEIRO DA SILVA', '2014-10-23', 0, 'Tajikistan', 'marconi.george.ribeiro.da.silva@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('34978-861', '7758', 'F', 'VILMA VITORIA DE SOUZA MESSA', '2014-04-17', 0, 'Bhutan', 'vilma.vitoria.de.souza.messa@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('44729-885', '7108', 'F', 'AURELINDA BATISTA DA SILVA', '2014-06-16', 0, 'Ecuador', 'aurelinda.batista.da.silva@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('38269-382', '5466', 'M', 'JOSE NUNES PEREIRA', '2014-08-03', 0, 'Malta', 'jose.nunes.pereira@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('03405-636', '9771', 'M', 'JOAO DE LUCA', '2014-02-10', 0, 'Burkina Faso', 'joao.de.luca@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('60608-858', '5155', 'M', 'EDIR DIAS DE CARVALHO', '2014-03-15', 1, 'Iran', 'edir.dias.de.carvalho@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('78166-716', '1394', 'M', 'JOSE NUNES PEREIRA', '2014-08-08', 0, 'The Philippines', 'jose.nunes.pereira@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('31610-395', '6114', 'M', 'LUZIA RODRIGUES DE OLIVEIRA', '2014-12-12', 0, 'Czech Republic', 'luzia.rodrigues.de.oliveira@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('18325-659', '2976', 'F', 'RONY HUDSON OLIVEIRA CANDEIRO', '2014-01-05', 0, 'Kyrgyzstan', 'rony.hudson.oliveira.candeiro@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('48843-492', '3612', 'M', 'LUZIA RODRIGUES DE OLIVEIRA', '2014-07-28', 0, 'Bahamas', 'luzia.rodrigues.de.oliveira@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('81895-241', '0771', 'M', 'SILVIO TSIPE RAIRATE', '2014-11-05', 0, 'Iceland', 'silvio.tsipe.rairate@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('54887-185', '6457', 'M', 'JOANA ANTUNES', '2014-01-12', 1, 'Lithuania', 'joana.antunes@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('15987-087', '3003', 'F', 'ARISMARES SOUZA PRATES', '2014-05-24', 0, 'Marshall Islands', 'arismares.souza.prates@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('02603-488', '7323', 'F', 'GLAUBER DA COSTA ARRUDA', '2014-02-17', 1, 'Vanuatu', 'glauber.da.costa.arruda@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('50943-451', '9561', 'F', 'WILSON CONCEICAO DE MIRANDA', '2014-08-01', 0, 'Nigeria', 'wilson.conceicao.de.miranda@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('56986-512', '3193', 'M', 'HELIO SAMBATTI', '2014-09-11', 0, 'Mongolia', 'helio.sambatti@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('38226-727', '9469', 'F', 'RONY HUDSON OLIVEIRA CANDEIRO', '2014-07-20', 1, 'Japan', 'rony.hudson.oliveira.candeiro@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('38195-029', '6137', 'M', 'MARIA ALVES SUTIL', '2014-11-03', 1, 'Congo', 'maria.alves.sutil@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('88271-646', '5211', 'F', 'CELESIAORMOND RIBEIRO DE CAMPOS', '2014-03-20', 1, 'Kosovo', 'celesiaormond.ribeiro.de.campos@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('20170-906', '3180', 'M', 'JOAO DE LUCA', '2014-11-07', 0, 'Bahrain', 'joao.de.luca@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('42391-383', '5503', 'F', 'SUELY DA SILVA CAVALCANTI', '2014-06-04', 0, 'Nauru', 'suely.da.silva.cavalcanti@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('32462-084', '2669', 'F', 'GUIOMAR TRELHA FRANCA', '2014-10-29', 1, 'Liechtenstein', 'guiomar.trelha.franca@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('86265-103', '4147', 'F', 'HABIB FAHED', '2014-07-15', 1, 'Comoros', 'habib.fahed@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('06126-283', '1237', 'M', 'AMERICO FRANCISCO DA SILVA', '2014-09-05', 1, 'Bahrain', 'americo.francisco.da.silva@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('72422-579', '2148', 'F', 'ANDRE LUIS CASTRILLON GARCIA', '2014-06-22', 0, 'Venezuela', 'andre.luis.castrillon.garcia@yahoo.com');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('BENJAMIM GAUNA', '2014-07-02', '2014-02-17', 0, 0, 'benjamim.gauna@hotmail.com', 'benjamim.gauna');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('CELIA CRISTINA PEREIRA PINTO DOS SANTOS', '2014-07-04', '2014-01-28', 1, 0, 'celia.cristina.pereira.pinto.dos.santos@gmail.com', 'celia.cristina.pereira.pinto.dos.santos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('EUZEBIO DA SILVA CEZAR', '2014-07-11', '2014-03-24', 1, 0, 'euzebio.da.silva.cezar@fb.com', 'euzebio.da.silva.cezar');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('OSWALDIR GOMES', '2014-07-12', '2014-01-27', 1, 0, 'oswaldir.gomes@fb.com', 'oswaldir.gomes');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('SILVIA MENDES', '2014-07-03', '2014-06-29', 0, 0, 'silvia.mendes@hotmail.com', 'silvia.mendes');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JOSE RIBAMAR BEZERRA SA', '2014-07-11', '2014-06-13', 0, 1, 'jose.ribamar.bezerra.sa@hotmail.com', 'jose.ribamar.bezerra.sa');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('GLAUBER DA COSTA ARRUDA', '2014-07-10', '2014-02-17', 0, 1, 'glauber.da.costa.arruda@gmail.com', 'glauber.da.costa.arruda');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('RUZINO ANTUNES DA SILVA', '2014-07-13', '2014-03-06', 1, 1, 'ruzino.antunes.da.silva@fb.com', 'ruzino.antunes.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARIA HILDA MACHADO', '2014-07-04', '2014-02-09', 0, 1, 'maria.hilda.machado@fb.com', 'maria.hilda.machado');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ALBERTO FEIZAR CARDOSO ABDALA', '2014-07-01', '2014-01-29', 0, 1, 'alberto.feizar.cardoso.abdala@hotmail.com', 'alberto.feizar.cardoso.abdala');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ANDRE LUIS CASTRILLON GARCIA', '2014-07-05', '2014-06-17', 0, 1, 'andre.luis.castrillon.garcia@fb.com', 'andre.luis.castrillon.garcia');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ADENILTON JOSE DE MIRANDA', '2014-07-12', '2014-04-19', 0, 1, 'adenilton.jose.de.miranda@hotmail.com', 'adenilton.jose.de.miranda');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARIA TEREZINHA ROCHA DE SOUZA', '2014-07-11', '2014-03-23', 1, 1, 'maria.terezinha.rocha.de.souza@gmail.com', 'maria.terezinha.rocha.de.souza');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('CLEUSA FERREIRA MACIEL', '2014-07-08', '2014-03-23', 1, 1, 'cleusa.ferreira.maciel@gmail.com', 'cleusa.ferreira.maciel');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('DILMA DE SOUZA', '2014-07-11', '2014-04-26', 1, 1, 'dilma.de.souza@hotmail.com', 'dilma.de.souza');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('EUSTAQUIA PRIETO', '2014-07-08', '2014-03-26', 1, 0, 'eustaquia.prieto@fb.com', 'eustaquia.prieto');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('CARMINDA POMPEU AMORIM', '2014-07-08', '2014-01-15', 1, 0, 'carminda.pompeu.amorim@hotmail.com', 'carminda.pompeu.amorim');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ALDEIR ALEX ALVES LIMA', '2014-07-03', '2014-03-03', 0, 0, 'aldeir.alex.alves.lima@gmail.com', 'aldeir.alex.alves.lima');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('AMERICO FRANCISCO DA SILVA', '2014-07-02', '2014-06-23', 0, 0, 'americo.francisco.da.silva@hotmail.com', 'americo.francisco.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('QUITERIA LOURENCO DE LIMA', '2014-07-03', '2014-03-14', 0, 0, 'quiteria.lourenco.de.lima@gmail.com', 'quiteria.lourenco.de.lima');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('WILSON CONCEICAO DE MIRANDA', '2014-07-01', '2014-02-07', 0, 0, 'wilson.conceicao.de.miranda@fb.com', 'wilson.conceicao.de.miranda');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('SUELY DA SILVA CAVALCANTI', '2014-07-01', '2014-02-20', 1, 1, 'suely.da.silva.cavalcanti@hotmail.com', 'suely.da.silva.cavalcanti');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('EDIO JUSTO BORGES', '2014-07-11', '2014-02-26', 0, 0, 'edio.justo.borges@gmail.com', 'edio.justo.borges');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('VIOLINDO DE SOUZA', '2014-07-04', '2014-04-29', 1, 1, 'violindo.de.souza@gmail.com', 'violindo.de.souza');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARIA ELENA ALVES', '2014-07-11', '2014-01-25', 0, 1, 'maria.elena.alves@hotmail.com', 'maria.elena.alves');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('RITA IRACI ALMEIDA DA SILVA', '2014-07-11', '2014-06-17', 0, 0, 'rita.iraci.almeida.da.silva@hotmail.com', 'rita.iraci.almeida.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('VIRGILIA DIAS VIEIRA', '2014-07-06', '2014-06-04', 0, 0, 'virgilia.dias.vieira@hotmail.com', 'virgilia.dias.vieira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('RENIRA RODRIGUES DA SILVA DE SOUSA', '2014-07-03', '2014-03-15', 1, 0, 'renira.rodrigues.da.silva.de.sousa@fb.com', 'renira.rodrigues.da.silva.de.sousa');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('TIMOTEO BATISTA LEITE', '2014-07-04', '2014-01-16', 0, 0, 'timoteo.batista.leite@fb.com', 'timoteo.batista.leite');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('OBADIAS MARCAL DE OLIVEIRA', '2014-07-04', '2014-05-09', 1, 1, 'obadias.marcal.de.oliveira@hotmail.com', 'obadias.marcal.de.oliveira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('BENJAMIM GAUNA', '2014-07-07', '2014-03-25', 0, 1, 'benjamim.gauna@fb.com', 'benjamim.gauna');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JOSE RIBAMAR BEZERRA SA', '2014-07-05', '2014-02-27', 0, 1, 'jose.ribamar.bezerra.sa@hotmail.com', 'jose.ribamar.bezerra.sa');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JUEL PRUDENCIO BORGES', '2014-07-07', '2014-06-19', 1, 1, 'juel.prudencio.borges@hotmail.com', 'juel.prudencio.borges');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('THANIA CRISTINA DA SILVA BARNABE', '2014-07-12', '2014-03-14', 1, 0, 'thania.cristina.da.silva.barnabe@hotmail.com', 'thania.cristina.da.silva.barnabe');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('CLEUSA FERREIRA MACIEL', '2014-07-09', '2014-04-22', 0, 1, 'cleusa.ferreira.maciel@hotmail.com', 'cleusa.ferreira.maciel');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('FRANCISCA MARIA SILVA COSTA', '2014-07-06', '2014-06-27', 0, 0, 'francisca.maria.silva.costa@hotmail.com', 'francisca.maria.silva.costa');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JORGE TETSUO TAIRA', '2014-07-03', '2014-05-02', 1, 0, 'jorge.tetsuo.taira@fb.com', 'jorge.tetsuo.taira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ROSIMEIRE GONCALVES LOPES RAMOS', '2014-07-02', '2014-04-05', 0, 1, 'rosimeire.goncalves.lopes.ramos@hotmail.com', 'rosimeire.goncalves.lopes.ramos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('BENEDITO AMBROSIO DA COSTA', '2014-07-07', '2014-02-04', 0, 1, 'benedito.ambrosio.da.costa@hotmail.com', 'benedito.ambrosio.da.costa');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('AFONSO BARBOSA DA SILVA', '2014-07-06', '2014-05-23', 1, 1, 'afonso.barbosa.da.silva@hotmail.com', 'afonso.barbosa.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LAURA SEBASTIANA GURGEL', '2014-07-04', '2014-03-25', 0, 1, 'laura.sebastiana.gurgel@hotmail.com', 'laura.sebastiana.gurgel');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARIA TEREZINHA ROCHA DE SOUZA', '2014-07-04', '2014-06-09', 0, 1, 'maria.terezinha.rocha.de.souza@hotmail.com', 'maria.terezinha.rocha.de.souza');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ELOIR CARLOS FIRMINO', '2014-07-05', '2014-06-10', 0, 0, 'eloir.carlos.firmino@fb.com', 'eloir.carlos.firmino');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('CELESIAORMOND RIBEIRO DE CAMPOS', '2014-07-11', '2014-04-11', 0, 0, 'celesiaormond.ribeiro.de.campos@hotmail.com', 'celesiaormond.ribeiro.de.campos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('DIAMANTINA DA SILVA SOARES', '2014-07-05', '2014-02-21', 0, 1, 'diamantina.da.silva.soares@hotmail.com', 'diamantina.da.silva.soares');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LUIZ FERNANDO DA SILVA AMORIM', '2014-07-08', '2014-06-30', 1, 0, 'luiz.fernando.da.silva.amorim@hotmail.com', 'luiz.fernando.da.silva.amorim');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JOAQUIM BORGES RODRIGUES', '2014-07-03', '2014-01-24', 0, 0, 'joaquim.borges.rodrigues@gmail.com', 'joaquim.borges.rodrigues');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('NEIVA OBERGER FERREIRA', '2014-07-11', '2014-06-18', 0, 0, 'neiva.oberger.ferreira@gmail.com', 'neiva.oberger.ferreira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JOAO DE LUCA', '2014-07-09', '2014-04-28', 1, 0, 'joao.de.luca@fb.com', 'joao.de.luca');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ANA ALVES LUCIANO', '2014-07-13', '2014-06-18', 1, 1, 'ana.alves.luciano@fb.com', 'ana.alves.luciano');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARIA ELENA ALVES', '2014-07-04', '2014-01-20', 0, 1, 'maria.elena.alves@fb.com', 'maria.elena.alves');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ALICE DE SOUZA MIRANDA', '2014-07-12', '2014-01-08', 1, 0, 'alice.de.souza.miranda@gmail.com', 'alice.de.souza.miranda');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARIA DAIANE DE ARAUJO SOUZA', '2014-07-12', '2014-06-02', 1, 1, 'maria.daiane.de.araujo.souza@hotmail.com', 'maria.daiane.de.araujo.souza');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ROSILENE ALMEIDA DA SILVA', '2014-07-10', '2014-04-24', 0, 0, 'rosilene.almeida.da.silva@gmail.com', 'rosilene.almeida.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('RUBENSMORBECK LEITE', '2014-07-13', '2014-04-29', 0, 0, 'rubensmorbeck.leite@fb.com', 'rubensmorbeck.leite');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('GLAUBER DA COSTA ARRUDA', '2014-07-05', '2014-03-01', 0, 1, 'glauber.da.costa.arruda@hotmail.com', 'glauber.da.costa.arruda');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ANTONIA BORGES DA SILVA', '2014-07-10', '2014-04-28', 1, 0, 'antonia.borges.da.silva@fb.com', 'antonia.borges.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('GLAUBER DA COSTA ARRUDA', '2014-07-11', '2014-02-22', 0, 1, 'glauber.da.costa.arruda@fb.com', 'glauber.da.costa.arruda');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('IVANI DO NASCIMENTO VALENTIM', '2014-07-05', '2014-02-22', 0, 1, 'ivani.do.nascimento.valentim@fb.com', 'ivani.do.nascimento.valentim');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('IROCIDES APARECIDA FERREIRA', '2014-07-05', '2014-01-15', 1, 0, 'irocides.aparecida.ferreira@gmail.com', 'irocides.aparecida.ferreira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JORGE TETSUO TAIRA', '2014-07-09', '2014-05-14', 0, 1, 'jorge.tetsuo.taira@gmail.com', 'jorge.tetsuo.taira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LUIZ LOPES DA SILVA', '2014-07-13', '2014-02-10', 1, 0, 'luiz.lopes.da.silva@hotmail.com', 'luiz.lopes.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JOSE NUNES PEREIRA', '2014-07-09', '2014-01-05', 0, 1, 'jose.nunes.pereira@gmail.com', 'jose.nunes.pereira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ELOIDE CAVANHA', '2014-07-10', '2014-02-06', 1, 1, 'eloide.cavanha@hotmail.com', 'eloide.cavanha');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LUIZ FERNANDO DA SILVA AMORIM', '2014-07-10', '2014-02-10', 0, 0, 'luiz.fernando.da.silva.amorim@gmail.com', 'luiz.fernando.da.silva.amorim');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('NADIACUIABANO KUNZE', '2014-07-01', '2014-06-18', 1, 1, 'nadiacuiabano.kunze@hotmail.com', 'nadiacuiabano.kunze');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('CARMINDA POMPEU AMORIM', '2014-07-09', '2014-06-06', 1, 0, 'carminda.pompeu.amorim@fb.com', 'carminda.pompeu.amorim');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('CLAUDIO BARBOSA DOS SANTOS', '2014-07-13', '2014-04-22', 1, 0, 'claudio.barbosa.dos.santos@fb.com', 'claudio.barbosa.dos.santos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('GLAUBER DA COSTA ARRUDA', '2014-07-02', '2014-05-25', 0, 1, 'glauber.da.costa.arruda@hotmail.com', 'glauber.da.costa.arruda');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('SILVIO TSIPE RAIRATE', '2014-07-02', '2014-02-11', 1, 1, 'silvio.tsipe.rairate@hotmail.com', 'silvio.tsipe.rairate');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('CLEODETE CANOLA DE CAMPOS', '2014-07-05', '2014-03-14', 0, 1, 'cleodete.canola.de.campos@hotmail.com', 'cleodete.canola.de.campos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LAURO JOSE DA SILVA', '2014-07-09', '2014-05-26', 1, 0, 'lauro.jose.da.silva@fb.com', 'lauro.jose.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('VIRGILIA DIAS VIEIRA', '2014-07-12', '2014-03-13', 1, 0, 'virgilia.dias.vieira@hotmail.com', 'virgilia.dias.vieira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('VIOLINDO DE SOUZA', '2014-07-04', '2014-01-25', 1, 0, 'violindo.de.souza@hotmail.com', 'violindo.de.souza');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('DIEGO CESPEDES DE SOUZA', '2014-07-13', '2014-02-22', 0, 1, 'diego.cespedes.de.souza@fb.com', 'diego.cespedes.de.souza');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('IROCIDES APARECIDA FERREIRA', '2014-07-09', '2014-01-12', 0, 1, 'irocides.aparecida.ferreira@gmail.com', 'irocides.aparecida.ferreira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARGARETH VIRGINIA DE REZENDE MEHLMANN', '2014-07-07', '2014-01-19', 1, 0, 'margareth.virginia.de.rezende.mehlmann@gmail.com', 'margareth.virginia.de.rezende.mehlmann');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('EDIO JUSTO BORGES', '2014-07-02', '2014-06-12', 1, 0, 'edio.justo.borges@fb.com', 'edio.justo.borges');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARILEIA NUNES DE OLIVEIRA', '2014-07-02', '2014-01-13', 1, 1, 'marileia.nunes.de.oliveira@fb.com', 'marileia.nunes.de.oliveira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('SOLANGE APARECIDA DO PRADO DA CRUZ', '2014-07-05', '2014-01-14', 1, 0, 'solange.aparecida.do.prado.da.cruz@gmail.com', 'solange.aparecida.do.prado.da.cruz');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('OSVALDO PEREIRA BARBOSA', '2014-07-12', '2014-04-14', 0, 0, 'osvaldo.pereira.barbosa@hotmail.com', 'osvaldo.pereira.barbosa');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LAURO JOSE DA SILVA', '2014-07-05', '2014-01-08', 1, 0, 'lauro.jose.da.silva@gmail.com', 'lauro.jose.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARIA FATIMA SCHEUNEMANN MIRANDA', '2014-07-13', '2014-02-03', 0, 0, 'maria.fatima.scheunemann.miranda@fb.com', 'maria.fatima.scheunemann.miranda');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('DORILDA ALVES DE CARVALHO', '2014-07-09', '2014-02-12', 0, 0, 'dorilda.alves.de.carvalho@hotmail.com', 'dorilda.alves.de.carvalho');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('CARLOS SERGIO URBANIN', '2014-07-07', '2014-04-30', 1, 0, 'carlos.sergio.urbanin@fb.com', 'carlos.sergio.urbanin');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('BENEDITO AMBROSIO DA COSTA', '2014-07-08', '2014-06-25', 1, 1, 'benedito.ambrosio.da.costa@hotmail.com', 'benedito.ambrosio.da.costa');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ADENILTON JOSE DE MIRANDA', '2014-07-13', '2014-02-24', 0, 1, 'adenilton.jose.de.miranda@gmail.com', 'adenilton.jose.de.miranda');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JOAQUIM BORGES RODRIGUES', '2014-07-09', '2014-05-12', 1, 1, 'joaquim.borges.rodrigues@hotmail.com', 'joaquim.borges.rodrigues');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('KLEBER MAGALHAES FERREIRA', '2014-07-12', '2014-02-25', 1, 0, 'kleber.magalhaes.ferreira@hotmail.com', 'kleber.magalhaes.ferreira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('CARLOS SERGIO URBANIN', '2014-07-11', '2014-03-05', 1, 1, 'carlos.sergio.urbanin@gmail.com', 'carlos.sergio.urbanin');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('WANDERSON COSMO DE ARAUJO', '2014-07-05', '2014-01-08', 0, 0, 'wanderson.cosmo.de.araujo@fb.com', 'wanderson.cosmo.de.araujo');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('BENILDE PERES DE CAMPOS', '2014-07-09', '2014-05-22', 0, 0, 'benilde.peres.de.campos@hotmail.com', 'benilde.peres.de.campos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARCIA DA SILVA OLIVEIRA', '2014-07-03', '2014-06-14', 1, 0, 'marcia.da.silva.oliveira@fb.com', 'marcia.da.silva.oliveira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('CLEODETE CANOLA DE CAMPOS', '2014-07-05', '2014-01-22', 1, 1, 'cleodete.canola.de.campos@hotmail.com', 'cleodete.canola.de.campos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('RAMAO CARDOSO', '2014-07-04', '2014-03-07', 1, 0, 'ramao.cardoso@fb.com', 'ramao.cardoso');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('BENILDE PERES DE CAMPOS', '2014-07-06', '2014-04-24', 1, 0, 'benilde.peres.de.campos@fb.com', 'benilde.peres.de.campos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LAURO JOSE DA SILVA', '2014-07-01', '2014-02-24', 0, 1, 'lauro.jose.da.silva@hotmail.com', 'lauro.jose.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('BENEDITO AMBROSIO DA COSTA', '2014-07-04', '2014-04-18', 0, 0, 'benedito.ambrosio.da.costa@hotmail.com', 'benedito.ambrosio.da.costa');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JOAQUIM BORGES RODRIGUES', '2014-07-07', '2014-02-14', 0, 1, 'joaquim.borges.rodrigues@fb.com', 'joaquim.borges.rodrigues');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('OBADIAS MARCAL DE OLIVEIRA', '2014-07-07', '2014-01-23', 1, 1, 'obadias.marcal.de.oliveira@fb.com', 'obadias.marcal.de.oliveira');
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-07-07', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-03', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-15', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-21', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-04', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-07-07', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-30', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-17', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-12', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-03', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-09', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-03', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-05', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-20', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-11', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-27', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-13', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-19', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-14', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-12', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-27', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-29', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-29', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-28', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-15', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-21', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-01', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-07-08', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-07-12', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-29', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-26', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-09', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-19', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-14', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-07-11', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-12', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-04', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-03', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-31', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-16', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-17', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-09', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-30', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-19', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-25', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-10', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-02', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-09', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-04', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-26', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-28', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-07-04', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-07-06', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-02', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-20', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-12', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-07', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-07-07', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-22', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-13', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-07', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-31', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-07-07', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-05', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-29', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-07', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-29', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-20', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-15', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-11', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-14', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-10', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-31', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-08', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-24', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-27', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-13', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-09', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-20', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-11', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-16', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-04', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-30', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-20', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-26', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-08', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-05', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-07', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-15', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-01', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-24', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-28', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-03', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-05', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-11', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-10', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-18', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-22', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-20', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-28', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
