INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('15167-395', '8584', 'M', 'ALCEU DOS SANTOS', '2014-09-14', 0, 'Guyana', 'alceu.dos.santos@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('60836-224', '9932', 'M', 'MIGUEL JOAQUIM SILVA', '2014-04-15', 0, 'Malta', 'miguel.joaquim.silva@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('15713-208', '2856', 'F', 'AFONSO BARBOSA DA SILVA', '2014-04-28', 1, 'Hungary', 'afonso.barbosa.da.silva@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('31387-327', '3910', 'M', 'EUZEBIO DA SILVA CEZAR', '2014-11-26', 1, 'Singapore', 'euzebio.da.silva.cezar@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('71265-201', '2893', 'M', 'VILMA VITORIA DE SOUZA MESSA', '2014-04-10', 1, 'Cameroon', 'vilma.vitoria.de.souza.messa@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('28279-834', '5803', 'M', 'OLGA PEREIRA', '2014-07-09', 0, 'Zambia', 'olga.pereira@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('70709-106', '1584', 'F', 'ALICE DE SOUZA MIRANDA', '2014-11-07', 1, 'Peru', 'alice.de.souza.miranda@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('91191-024', '6132', 'M', 'SILVIA MENDES', '2014-08-26', 1, 'Nigeria', 'silvia.mendes@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('62479-853', '1110', 'M', 'LUZIA RODRIGUES DE OLIVEIRA', '2014-11-23', 1, 'Namibia', 'luzia.rodrigues.de.oliveira@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('14879-273', '1348', 'M', 'HABIB FAHED', '2014-08-20', 1, 'Gambia', 'habib.fahed@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('34088-309', '7550', 'F', 'CARLOS SERGIO URBANIN', '2014-02-14', 1, 'Argentina', 'carlos.sergio.urbanin@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('46693-013', '4615', 'M', 'ADAIL BANDINELLE DE MORAES', '2014-10-16', 1, 'Morocco', 'adail.bandinelle.de.moraes@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('68648-820', '2967', 'M', 'PAULO TEIXEIRA DE ABREU', '2014-01-12', 1, 'Central African Republic', 'paulo.teixeira.de.abreu@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('86897-494', '8023', 'F', 'AMERICO FRANCISCO DA SILVA', '2014-02-04', 0, 'Poland', 'americo.francisco.da.silva@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('25541-440', '1123', 'F', 'EDIO JUSTO BORGES', '2014-07-22', 0, 'Peru', 'edio.justo.borges@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('37646-501', '9815', 'F', 'GLAUBER DA COSTA ARRUDA', '2014-01-01', 1, 'Liberia', 'glauber.da.costa.arruda@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('21658-844', '0295', 'F', 'JOSE RIBAMAR BEZERRA SA', '2014-07-29', 0, 'Ireland', 'jose.ribamar.bezerra.sa@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('71119-060', '4637', 'M', 'DELCY MARTINS DA SILVA', '2014-02-04', 0, 'Togo', 'delcy.martins.da.silva@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('67805-284', '6146', 'F', 'NICANOR FELIZARDO DOS REIS', '2014-02-08', 0, 'Switzerland', 'nicanor.felizardo.dos.reis@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('21844-385', '6353', 'M', 'LAURA SEBASTIANA GURGEL', '2014-03-03', 1, 'Trinidad & Tobago', 'laura.sebastiana.gurgel@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('23191-401', '4833', 'M', 'NEIVA OBERGER FERREIRA', '2014-09-15', 1, 'Benin', 'neiva.oberger.ferreira@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('44383-799', '2906', 'M', 'LUIZ LOPES DA SILVA', '2014-08-01', 0, 'Barbados', 'luiz.lopes.da.silva@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('14648-221', '4617', 'M', 'LUZIA RODRIGUES DE OLIVEIRA', '2014-09-02', 1, 'Libya', 'luzia.rodrigues.de.oliveira@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('59788-100', '6929', 'M', 'CRISTIANE PAES CORDOBA', '2014-03-30', 1, 'Jordan', 'cristiane.paes.cordoba@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('80527-720', '2661', 'F', 'LUCINEIDE DE MORAES DO CARMO', '2014-09-08', 0, 'Costa Rica', 'lucineide.de.moraes.do.carmo@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('49344-208', '5052', 'M', 'ILZA XAVIER DE LIMA ARAUJO', '2014-08-06', 0, 'Oman', 'ilza.xavier.de.lima.araujo@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('34328-892', '9213', 'F', 'ANA PAULA FIGUEIREDO DA ROCHA', '2014-02-28', 0, 'Venezuela', 'ana.paula.figueiredo.da.rocha@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('30127-348', '0013', 'M', 'QUITERIA LOURENCO DE LIMA', '2014-11-04', 0, 'Ukraine', 'quiteria.lourenco.de.lima@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('57633-256', '7730', 'M', 'SILVIO TSIPE RAIRATE', '2014-12-02', 1, 'Dominican Republic', 'silvio.tsipe.rairate@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('16926-400', '0441', 'M', 'VIRGILIA DIAS VIEIRA', '2014-04-21', 1, 'Chile', 'virgilia.dias.vieira@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('62242-588', '5483', 'M', 'MARIA ELENA ALVES', '2014-04-02', 1, 'Burkina Faso', 'maria.elena.alves@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('13904-460', '7825', 'M', 'ROBSON LUIZ DO NASCIMENTO PUERTAS', '2014-03-24', 0, 'Bulgaria', 'robson.luiz.do.nascimento.puertas@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('07105-193', '5253', 'M', 'ANTONIA BORGES DA SILVA', '2014-06-06', 1, 'Czech Republic', 'antonia.borges.da.silva@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('84583-380', '5284', 'F', 'JUEL PRUDENCIO BORGES', '2014-11-22', 0, 'Suriname', 'juel.prudencio.borges@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('72177-872', '5442', 'M', 'TIMOTEO BATISTA LEITE', '2014-11-13', 0, 'Fiji', 'timoteo.batista.leite@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('73459-177', '9263', 'M', 'HELOIZA ALMEIDA DOS SANTOS', '2014-02-16', 1, 'Seychelles', 'heloiza.almeida.dos.santos@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('83743-240', '8566', 'F', 'VILMA VITORIA DE SOUZA MESSA', '2014-02-02', 1, 'Georgia', 'vilma.vitoria.de.souza.messa@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('30976-672', '0244', 'F', 'SUELY DA SILVA CAVALCANTI', '2014-10-09', 1, 'Gambia', 'suely.da.silva.cavalcanti@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('67610-245', '5883', 'M', 'JOSE NUNES PEREIRA', '2014-11-16', 0, 'Romania', 'jose.nunes.pereira@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('58501-794', '5155', 'M', 'JOSE RIBAMAR BEZERRA SA', '2014-06-27', 0, 'St. Kitts & Nevis', 'jose.ribamar.bezerra.sa@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('97319-505', '9546', 'F', 'ELOIDE CAVANHA', '2014-06-04', 1, 'Cote d''Ivoire', 'eloide.cavanha@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('43468-862', '4812', 'F', 'AMERICO FRANCISCO DA SILVA', '2014-06-28', 1, 'Micronesia', 'americo.francisco.da.silva@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('13856-814', '8223', 'M', 'MIGUEL VENCESLAU MACIEL DE CAMPOS', '2014-03-02', 1, 'Egypt', 'miguel.venceslau.maciel.de.campos@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('88363-378', '1917', 'M', 'EUZEBIO DA SILVA CEZAR', '2014-11-23', 1, 'Russia', 'euzebio.da.silva.cezar@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('34452-221', '9889', 'M', 'INES APARECIDA DA SILVA', '2014-02-12', 1, 'Denmark', 'ines.aparecida.da.silva@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('25044-705', '9599', 'F', 'CARLOS SERGIO URBANIN', '2014-11-07', 0, 'Palau', 'carlos.sergio.urbanin@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('60436-784', '8584', 'F', 'LUIZ LOPES DA SILVA', '2014-10-28', 0, 'Syria', 'luiz.lopes.da.silva@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('58692-570', '1716', 'F', 'ALIETE FRANCISCA PRATES', '2014-06-04', 1, 'Georgia', 'aliete.francisca.prates@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('19204-435', '3865', 'F', 'MARIA FATIMA SCHEUNEMANN MIRANDA', '2014-10-11', 1, 'Yemen', 'maria.fatima.scheunemann.miranda@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('99142-141', '0888', 'F', 'CARMINDA POMPEU AMORIM', '2014-07-25', 0, 'Ethiopia', 'carminda.pompeu.amorim@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('88805-867', '5058', 'M', 'MARIA HILDA MACHADO', '2014-11-13', 0, 'Dominica', 'maria.hilda.machado@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('38646-842', '2400', 'M', 'ANA ALVES LUCIANO', '2014-04-24', 1, 'Vietnam', 'ana.alves.luciano@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('31101-672', '4758', 'M', 'VIRGILIA DIAS VIEIRA', '2014-06-25', 0, 'Ghana', 'virgilia.dias.vieira@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('92083-406', '6102', 'M', 'ZILDA MARTINS DE SOUZA', '2014-08-20', 1, 'India', 'zilda.martins.de.souza@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('37169-492', '3484', 'M', 'ALBERTO FEIZAR CARDOSO ABDALA', '2014-10-26', 1, 'Moldova', 'alberto.feizar.cardoso.abdala@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('88911-190', '2790', 'M', 'JULIO APARECIDO DE SOUZA', '2014-01-20', 0, 'Malaysia', 'julio.aparecido.de.souza@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('33821-047', '0734', 'M', 'LUCINEIDE DE MORAES DO CARMO', '2014-05-11', 0, 'Central African Republic', 'lucineide.de.moraes.do.carmo@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('29991-282', '8575', 'F', 'JOSE EVALDO DA SILVA', '2014-12-10', 1, 'Serbia', 'jose.evaldo.da.silva@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('61408-837', '4264', 'M', 'ADAIL BANDINELLE DE MORAES', '2014-03-15', 1, 'Italy', 'adail.bandinelle.de.moraes@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('63261-947', '7086', 'M', 'VIRGILIA DIAS VIEIRA', '2014-01-05', 1, 'China', 'virgilia.dias.vieira@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('06419-187', '9829', 'M', 'ROSILENE ALMEIDA DA SILVA', '2014-12-28', 0, 'Guyana', 'rosilene.almeida.da.silva@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('64718-242', '6314', 'M', 'MARIA HILDA MACHADO', '2014-05-10', 1, 'Niger', 'maria.hilda.machado@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('37735-554', '1218', 'M', 'ADELSON LUIZ DA SILVA', '2014-07-14', 0, 'Paraguay', 'adelson.luiz.da.silva@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('15107-316', '3163', 'F', 'ANTONIA BORGES DA SILVA', '2014-11-24', 1, 'St. Lucia', 'antonia.borges.da.silva@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('66569-823', '3118', 'M', 'DAVINA PEREIRA DE SALES', '2014-09-04', 0, 'Palestinian State', 'davina.pereira.de.sales@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('43924-017', '1756', 'F', 'JOANA ANTUNES', '2014-10-30', 1, 'Turkmenistan', 'joana.antunes@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('63683-900', '8859', 'M', 'DAVINA PEREIRA DE SALES', '2014-02-24', 1, 'India', 'davina.pereira.de.sales@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('54751-292', '1336', 'F', 'GUIOMAR TRELHA FRANCA', '2014-07-29', 1, 'United Arab Emirates', 'guiomar.trelha.franca@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('42074-100', '3969', 'M', 'CRISTIANE PAES CORDOBA', '2014-07-30', 0, 'Kazakhstan', 'cristiane.paes.cordoba@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('39086-352', '7926', 'M', 'HABIB FAHED', '2014-11-30', 0, 'Tuvalu', 'habib.fahed@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('44545-235', '2890', 'M', 'BENILDE PERES DE CAMPOS', '2014-08-24', 0, 'Togo', 'benilde.peres.de.campos@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('15362-660', '3593', 'M', 'LOURIVAL ROSA GUIMARAES', '2014-12-18', 0, 'Seychelles', 'lourival.rosa.guimaraes@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('50695-879', '4688', 'M', 'NEIVA OBERGER FERREIRA', '2014-04-04', 1, 'San Marino', 'neiva.oberger.ferreira@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('68725-716', '2070', 'F', 'OLGA PEREIRA', '2014-07-25', 0, 'Ethiopia', 'olga.pereira@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('64091-956', '5811', 'F', 'MARCIA DA SILVA OLIVEIRA', '2014-02-15', 1, 'Cyprus', 'marcia.da.silva.oliveira@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('52711-048', '4974', 'F', 'OLGA PEREIRA', '2014-08-26', 1, 'Brazil', 'olga.pereira@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('87155-468', '0950', 'M', 'AMERICO FRANCISCO DA SILVA', '2014-06-01', 0, 'Nicaragua', 'americo.francisco.da.silva@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('93418-712', '3729', 'M', 'ELZA LIMA DE SOUZA MANSANO', '2014-11-12', 1, 'Belize', 'elza.lima.de.souza.mansano@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('73126-600', '1184', 'F', 'ABILIO CAVALHEIRO', '2014-09-04', 0, 'Slovakia', 'abilio.cavalheiro@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('31334-394', '6908', 'M', 'MAGALI SANCHES', '2014-06-22', 0, 'Benin', 'magali.sanches@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('54661-840', '7561', 'F', 'MAGALI SANCHES', '2014-06-12', 0, 'Denmark', 'magali.sanches@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('52603-443', '8238', 'F', 'MARIA FATIMA SCHEUNEMANN MIRANDA', '2014-02-24', 0, 'Maldives', 'maria.fatima.scheunemann.miranda@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('20893-730', '1275', 'M', 'MARIA ELENA ALVES', '2014-02-26', 0, 'Dominica', 'maria.elena.alves@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('30113-807', '4806', 'M', 'MARIA ELENA ALVES', '2014-07-28', 0, 'Qatar', 'maria.elena.alves@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('53086-430', '1624', 'F', 'MARIA DO CARMO JERONIMO SILVA', '2014-12-29', 1, 'Korea South', 'maria.do.carmo.jeronimo.silva@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('59825-078', '2353', 'M', 'RENIRA RODRIGUES DA SILVA DE SOUSA', '2014-03-25', 0, 'Zambia', 'renira.rodrigues.da.silva.de.sousa@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('03151-338', '4509', 'F', 'BENEDITA GAUDENCIO DA COSTA', '2014-03-28', 1, 'Kuwait', 'benedita.gaudencio.da.costa@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('32370-343', '2036', 'F', 'ADENILTON JOSE DE MIRANDA', '2014-08-04', 1, 'Turkey', 'adenilton.jose.de.miranda@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('50883-643', '7608', 'M', 'MARIA DE LOURDES FERNANDES DIAS', '2014-01-29', 0, 'Chad', 'maria.de.lourdes.fernandes.dias@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('79487-908', '5429', 'M', 'MARGARETH VIRGINIA DE REZENDE MEHLMANN', '2014-05-06', 0, 'Nicaragua', 'margareth.virginia.de.rezende.mehlmann@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('11691-219', '8693', 'M', 'ALCEU DOS SANTOS', '2014-02-05', 0, 'Belize', 'alceu.dos.santos@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('50992-160', '7215', 'M', 'ANTONIA BORGES DA SILVA', '2014-06-11', 1, 'Uzbekistan', 'antonia.borges.da.silva@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('69226-247', '5343', 'M', 'RAMIRO VEDOVATO', '2014-10-14', 1, 'Guinea-Bissau', 'ramiro.vedovato@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('40529-905', '7620', 'F', 'LOURIVAL ROSA GUIMARAES', '2014-08-19', 0, 'Ghana', 'lourival.rosa.guimaraes@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('81122-778', '1617', 'F', 'GLAUBER DA COSTA ARRUDA', '2014-09-04', 1, 'Haiti', 'glauber.da.costa.arruda@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('06340-144', '5407', 'M', 'DIEGO CESPEDES DE SOUZA', '2014-02-16', 0, 'Barbados', 'diego.cespedes.de.souza@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('58698-254', '8021', 'F', 'RAMAO CARDOSO', '2014-05-13', 1, 'Mozambique', 'ramao.cardoso@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('94992-344', '3075', 'F', 'ZILMA MARQUES GONCALVES RODRIGUES', '2014-02-11', 1, 'Namibia', 'zilma.marques.goncalves.rodrigues@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('87050-036', '9124', 'F', 'OSVALDO PEREIRA BARBOSA', '2014-04-29', 0, 'Haiti', 'osvaldo.pereira.barbosa@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('84973-963', '1795', 'M', 'SOLANGE APARECIDA DO PRADO DA CRUZ', '2014-07-19', 1, 'United Kingdom', 'solange.aparecida.do.prado.da.cruz@gmail.com');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('AMERICO FRANCISCO DA SILVA', '2014-07-12', '2014-05-17', 1, 0, 'americo.francisco.da.silva@hotmail.com', 'americo.francisco.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MIGUEL VENCESLAU MACIEL DE CAMPOS', '2014-07-12', '2014-06-15', 0, 1, 'miguel.venceslau.maciel.de.campos@hotmail.com', 'miguel.venceslau.maciel.de.campos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARIA HILDA MACHADO', '2014-07-01', '2014-01-07', 1, 1, 'maria.hilda.machado@gmail.com', 'maria.hilda.machado');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ROSILENE ALMEIDA DA SILVA', '2014-07-12', '2014-04-08', 1, 1, 'rosilene.almeida.da.silva@gmail.com', 'rosilene.almeida.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JOSENOTARIO MUNGO', '2014-07-10', '2014-02-18', 0, 0, 'josenotario.mungo@fb.com', 'josenotario.mungo');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARIA HILDA MACHADO', '2014-07-04', '2014-05-25', 0, 1, 'maria.hilda.machado@fb.com', 'maria.hilda.machado');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LOURIVAL ROSA GUIMARAES', '2014-07-05', '2014-03-27', 1, 0, 'lourival.rosa.guimaraes@hotmail.com', 'lourival.rosa.guimaraes');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ATAIDE DIAS DE MOURA', '2014-07-12', '2014-03-27', 1, 0, 'ataide.dias.de.moura@gmail.com', 'ataide.dias.de.moura');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ZILMA MARQUES GONCALVES RODRIGUES', '2014-07-07', '2014-06-19', 1, 0, 'zilma.marques.goncalves.rodrigues@fb.com', 'zilma.marques.goncalves.rodrigues');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('TIMOTEO BATISTA LEITE', '2014-07-07', '2014-05-09', 0, 0, 'timoteo.batista.leite@fb.com', 'timoteo.batista.leite');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ELEONILDA DE LIMA RODRIGUES', '2014-07-05', '2014-06-08', 1, 0, 'eleonilda.de.lima.rodrigues@hotmail.com', 'eleonilda.de.lima.rodrigues');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('RITA IRACI ALMEIDA DA SILVA', '2014-07-02', '2014-03-23', 1, 0, 'rita.iraci.almeida.da.silva@gmail.com', 'rita.iraci.almeida.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('PAULO TEIXEIRA DE ABREU', '2014-07-09', '2014-06-16', 1, 1, 'paulo.teixeira.de.abreu@gmail.com', 'paulo.teixeira.de.abreu');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MIGUEL JOAQUIM SILVA', '2014-07-08', '2014-01-09', 1, 1, 'miguel.joaquim.silva@fb.com', 'miguel.joaquim.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('RENIRA RODRIGUES DA SILVA DE SOUSA', '2014-07-09', '2014-04-20', 0, 1, 'renira.rodrigues.da.silva.de.sousa@hotmail.com', 'renira.rodrigues.da.silva.de.sousa');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('DILMA DE SOUZA', '2014-07-07', '2014-03-07', 0, 1, 'dilma.de.souza@hotmail.com', 'dilma.de.souza');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARIA DE LOURDES FERNANDES DIAS', '2014-07-07', '2014-03-17', 1, 1, 'maria.de.lourdes.fernandes.dias@hotmail.com', 'maria.de.lourdes.fernandes.dias');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JOSE RIBAMAR BEZERRA SA', '2014-07-01', '2014-04-11', 1, 1, 'jose.ribamar.bezerra.sa@gmail.com', 'jose.ribamar.bezerra.sa');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('VIOLINDO DE SOUZA', '2014-07-01', '2014-02-20', 0, 0, 'violindo.de.souza@gmail.com', 'violindo.de.souza');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('HELOIZA ALMEIDA DOS SANTOS', '2014-07-12', '2014-02-07', 1, 1, 'heloiza.almeida.dos.santos@hotmail.com', 'heloiza.almeida.dos.santos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ELEONILDA DE LIMA RODRIGUES', '2014-07-02', '2014-03-18', 0, 0, 'eleonilda.de.lima.rodrigues@fb.com', 'eleonilda.de.lima.rodrigues');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LOURIVAL ROSA GUIMARAES', '2014-07-02', '2014-04-03', 0, 1, 'lourival.rosa.guimaraes@fb.com', 'lourival.rosa.guimaraes');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('QUITERIA LOURENCO DE LIMA', '2014-07-12', '2014-05-04', 0, 0, 'quiteria.lourenco.de.lima@hotmail.com', 'quiteria.lourenco.de.lima');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('VIRGILIA DIAS VIEIRA', '2014-07-13', '2014-02-01', 1, 0, 'virgilia.dias.vieira@hotmail.com', 'virgilia.dias.vieira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ELZA LIMA DE SOUZA MANSANO', '2014-07-12', '2014-06-05', 1, 1, 'elza.lima.de.souza.mansano@hotmail.com', 'elza.lima.de.souza.mansano');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ANA ALVES LUCIANO', '2014-07-01', '2014-06-12', 0, 1, 'ana.alves.luciano@gmail.com', 'ana.alves.luciano');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('BENJAMIM GAUNA', '2014-07-12', '2014-05-24', 1, 1, 'benjamim.gauna@gmail.com', 'benjamim.gauna');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LUCINEIDE DE MORAES DO CARMO', '2014-07-11', '2014-06-17', 0, 0, 'lucineide.de.moraes.do.carmo@hotmail.com', 'lucineide.de.moraes.do.carmo');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LOURENCO DIAS', '2014-07-05', '2014-06-22', 0, 1, 'lourenco.dias@gmail.com', 'lourenco.dias');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('DIAMANTINA DA SILVA SOARES', '2014-07-04', '2014-02-05', 0, 1, 'diamantina.da.silva.soares@fb.com', 'diamantina.da.silva.soares');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ROBSON LUIZ DO NASCIMENTO PUERTAS', '2014-07-04', '2014-05-18', 0, 0, 'robson.luiz.do.nascimento.puertas@gmail.com', 'robson.luiz.do.nascimento.puertas');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ADELSON LUIZ DA SILVA', '2014-07-09', '2014-03-21', 1, 1, 'adelson.luiz.da.silva@hotmail.com', 'adelson.luiz.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MIGUEL JOAQUIM SILVA', '2014-07-04', '2014-05-28', 0, 1, 'miguel.joaquim.silva@fb.com', 'miguel.joaquim.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('DAVINA PEREIRA DE SALES', '2014-07-06', '2014-02-13', 1, 0, 'davina.pereira.de.sales@fb.com', 'davina.pereira.de.sales');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('RENIRA RODRIGUES DA SILVA DE SOUSA', '2014-07-07', '2014-05-17', 1, 0, 'renira.rodrigues.da.silva.de.sousa@fb.com', 'renira.rodrigues.da.silva.de.sousa');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('AURELINDA BATISTA DA SILVA', '2014-07-06', '2014-03-30', 0, 1, 'aurelinda.batista.da.silva@hotmail.com', 'aurelinda.batista.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('RUBENSMORBECK LEITE', '2014-07-08', '2014-04-29', 1, 1, 'rubensmorbeck.leite@fb.com', 'rubensmorbeck.leite');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('NICANOR FELIZARDO DOS REIS', '2014-07-03', '2014-06-14', 1, 0, 'nicanor.felizardo.dos.reis@gmail.com', 'nicanor.felizardo.dos.reis');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ILZA XAVIER DE LIMA ARAUJO', '2014-07-06', '2014-06-04', 1, 0, 'ilza.xavier.de.lima.araujo@hotmail.com', 'ilza.xavier.de.lima.araujo');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JOSE EVALDO DA SILVA', '2014-07-02', '2014-05-03', 1, 1, 'jose.evaldo.da.silva@fb.com', 'jose.evaldo.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('SUELY DA SILVA CAVALCANTI', '2014-07-11', '2014-06-14', 1, 1, 'suely.da.silva.cavalcanti@hotmail.com', 'suely.da.silva.cavalcanti');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('BENILDE PERES DE CAMPOS', '2014-07-13', '2014-03-02', 1, 1, 'benilde.peres.de.campos@fb.com', 'benilde.peres.de.campos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARCONI GEORGE RIBEIRO DA SILVA', '2014-07-02', '2014-01-20', 0, 1, 'marconi.george.ribeiro.da.silva@hotmail.com', 'marconi.george.ribeiro.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ALICE FERNANDES DE OLIVEIRA', '2014-07-10', '2014-02-19', 1, 1, 'alice.fernandes.de.oliveira@fb.com', 'alice.fernandes.de.oliveira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('OBADIAS MARCAL DE OLIVEIRA', '2014-07-12', '2014-06-08', 1, 1, 'obadias.marcal.de.oliveira@hotmail.com', 'obadias.marcal.de.oliveira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('CARLOS SERGIO URBANIN', '2014-07-05', '2014-02-25', 0, 1, 'carlos.sergio.urbanin@fb.com', 'carlos.sergio.urbanin');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('WILSON CONCEICAO DE MIRANDA', '2014-07-13', '2014-01-14', 0, 0, 'wilson.conceicao.de.miranda@hotmail.com', 'wilson.conceicao.de.miranda');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JUEL PRUDENCIO BORGES', '2014-07-10', '2014-04-27', 1, 1, 'juel.prudencio.borges@gmail.com', 'juel.prudencio.borges');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('RAMIRO VEDOVATO', '2014-07-11', '2014-03-26', 1, 0, 'ramiro.vedovato@hotmail.com', 'ramiro.vedovato');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ADAIL BANDINELLE DE MORAES', '2014-07-07', '2014-03-19', 0, 1, 'adail.bandinelle.de.moraes@gmail.com', 'adail.bandinelle.de.moraes');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ANTONIA BORGES DA SILVA', '2014-07-10', '2014-03-21', 0, 0, 'antonia.borges.da.silva@fb.com', 'antonia.borges.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARIA FATIMA SCHEUNEMANN MIRANDA', '2014-07-04', '2014-01-28', 0, 0, 'maria.fatima.scheunemann.miranda@gmail.com', 'maria.fatima.scheunemann.miranda');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('DIRCEU DE MATTOS', '2014-07-04', '2014-02-22', 0, 1, 'dirceu.de.mattos@fb.com', 'dirceu.de.mattos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ATAIDE DIAS DE MOURA', '2014-07-07', '2014-05-25', 1, 1, 'ataide.dias.de.moura@gmail.com', 'ataide.dias.de.moura');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JOSE NUNES PEREIRA', '2014-07-07', '2014-05-19', 0, 1, 'jose.nunes.pereira@fb.com', 'jose.nunes.pereira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LOURIVAL ROSA GUIMARAES', '2014-07-11', '2014-04-29', 1, 1, 'lourival.rosa.guimaraes@hotmail.com', 'lourival.rosa.guimaraes');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LOURENCO DIAS', '2014-07-02', '2014-03-21', 1, 0, 'lourenco.dias@fb.com', 'lourenco.dias');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ABILIO CAVALHEIRO', '2014-07-09', '2014-04-07', 0, 1, 'abilio.cavalheiro@gmail.com', 'abilio.cavalheiro');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MIGUEL JOAQUIM SILVA', '2014-07-02', '2014-02-13', 0, 1, 'miguel.joaquim.silva@hotmail.com', 'miguel.joaquim.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MAGALI SANCHES', '2014-07-06', '2014-06-11', 0, 1, 'magali.sanches@hotmail.com', 'magali.sanches');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ROBSON LUIZ DO NASCIMENTO PUERTAS', '2014-07-01', '2014-01-11', 1, 0, 'robson.luiz.do.nascimento.puertas@hotmail.com', 'robson.luiz.do.nascimento.puertas');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('AUGUSTA ALVES DOS SANTOS', '2014-07-06', '2014-05-15', 1, 0, 'augusta.alves.dos.santos@hotmail.com', 'augusta.alves.dos.santos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('DILMA DE SOUZA', '2014-07-08', '2014-03-29', 1, 1, 'dilma.de.souza@fb.com', 'dilma.de.souza');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('SILVIA MENDES', '2014-07-12', '2014-02-23', 1, 0, 'silvia.mendes@gmail.com', 'silvia.mendes');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JOAO MAURILIO DA SILVA', '2014-07-08', '2014-03-07', 0, 0, 'joao.maurilio.da.silva@hotmail.com', 'joao.maurilio.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ELOIDE CAVANHA', '2014-07-09', '2014-06-24', 1, 1, 'eloide.cavanha@hotmail.com', 'eloide.cavanha');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('AUGUSTA ALVES DOS SANTOS', '2014-07-03', '2014-04-07', 1, 0, 'augusta.alves.dos.santos@fb.com', 'augusta.alves.dos.santos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('DILMA DE SOUZA', '2014-07-11', '2014-05-15', 0, 1, 'dilma.de.souza@hotmail.com', 'dilma.de.souza');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARCONI GEORGE RIBEIRO DA SILVA', '2014-07-04', '2014-06-23', 0, 1, 'marconi.george.ribeiro.da.silva@gmail.com', 'marconi.george.ribeiro.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('WANDERSON COSMO DE ARAUJO', '2014-07-08', '2014-06-10', 1, 1, 'wanderson.cosmo.de.araujo@gmail.com', 'wanderson.cosmo.de.araujo');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('IVANI DO NASCIMENTO VALENTIM', '2014-07-04', '2014-03-18', 1, 1, 'ivani.do.nascimento.valentim@fb.com', 'ivani.do.nascimento.valentim');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ABILIO CAVALHEIRO', '2014-07-13', '2014-06-27', 1, 0, 'abilio.cavalheiro@hotmail.com', 'abilio.cavalheiro');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('HELIO SAMBATTI', '2014-07-07', '2014-01-08', 0, 0, 'helio.sambatti@fb.com', 'helio.sambatti');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('RONY HUDSON OLIVEIRA CANDEIRO', '2014-07-12', '2014-04-11', 0, 1, 'rony.hudson.oliveira.candeiro@gmail.com', 'rony.hudson.oliveira.candeiro');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('AUGUSTA ALVES DOS SANTOS', '2014-07-04', '2014-04-22', 0, 0, 'augusta.alves.dos.santos@fb.com', 'augusta.alves.dos.santos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('CORNELIO DIAS DUARTE', '2014-07-11', '2014-05-28', 0, 1, 'cornelio.dias.duarte@gmail.com', 'cornelio.dias.duarte');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LUCINEIDE DE MORAES DO CARMO', '2014-07-11', '2014-03-02', 1, 1, 'lucineide.de.moraes.do.carmo@hotmail.com', 'lucineide.de.moraes.do.carmo');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('GUIOMAR TRELHA FRANCA', '2014-07-10', '2014-01-03', 1, 1, 'guiomar.trelha.franca@gmail.com', 'guiomar.trelha.franca');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('BENEDITO AMBROSIO DA COSTA', '2014-07-05', '2014-05-20', 0, 1, 'benedito.ambrosio.da.costa@hotmail.com', 'benedito.ambrosio.da.costa');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ABIGAIL DA SILVA LARA', '2014-07-07', '2014-05-26', 1, 0, 'abigail.da.silva.lara@gmail.com', 'abigail.da.silva.lara');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('DIAMANTINA DA SILVA SOARES', '2014-07-12', '2014-04-25', 0, 0, 'diamantina.da.silva.soares@fb.com', 'diamantina.da.silva.soares');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('NADIACUIABANO KUNZE', '2014-07-09', '2014-03-24', 1, 1, 'nadiacuiabano.kunze@hotmail.com', 'nadiacuiabano.kunze');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('VALDOMIRO LEITE DE SA', '2014-07-04', '2014-02-10', 1, 1, 'valdomiro.leite.de.sa@hotmail.com', 'valdomiro.leite.de.sa');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARCIA DA SILVA OLIVEIRA', '2014-07-09', '2014-03-09', 0, 0, 'marcia.da.silva.oliveira@hotmail.com', 'marcia.da.silva.oliveira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('THANIA CRISTINA DA SILVA BARNABE', '2014-07-02', '2014-04-08', 1, 0, 'thania.cristina.da.silva.barnabe@fb.com', 'thania.cristina.da.silva.barnabe');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ALICE APARECIDA DOS SANTOS', '2014-07-05', '2014-03-12', 1, 0, 'alice.aparecida.dos.santos@fb.com', 'alice.aparecida.dos.santos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('RUZINO ANTUNES DA SILVA', '2014-07-03', '2014-06-14', 0, 0, 'ruzino.antunes.da.silva@fb.com', 'ruzino.antunes.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('BENILDE PERES DE CAMPOS', '2014-07-06', '2014-02-15', 0, 0, 'benilde.peres.de.campos@gmail.com', 'benilde.peres.de.campos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LAURO JOSE DA SILVA', '2014-07-12', '2014-05-16', 0, 1, 'lauro.jose.da.silva@hotmail.com', 'lauro.jose.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('PAULO TEIXEIRA DE ABREU', '2014-07-13', '2014-05-18', 1, 0, 'paulo.teixeira.de.abreu@fb.com', 'paulo.teixeira.de.abreu');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ALDEIR ALEX ALVES LIMA', '2014-07-08', '2014-03-19', 1, 0, 'aldeir.alex.alves.lima@gmail.com', 'aldeir.alex.alves.lima');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LAURA SEBASTIANA GURGEL', '2014-07-13', '2014-05-24', 0, 1, 'laura.sebastiana.gurgel@fb.com', 'laura.sebastiana.gurgel');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('WANDERSON COSMO DE ARAUJO', '2014-07-06', '2014-05-02', 1, 0, 'wanderson.cosmo.de.araujo@fb.com', 'wanderson.cosmo.de.araujo');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARIA DE LOURDES FERNANDES DIAS', '2014-07-06', '2014-02-04', 0, 1, 'maria.de.lourdes.fernandes.dias@fb.com', 'maria.de.lourdes.fernandes.dias');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MIGUEL JOAQUIM SILVA', '2014-07-06', '2014-02-07', 0, 0, 'miguel.joaquim.silva@fb.com', 'miguel.joaquim.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('OSVALDO PEREIRA BARBOSA', '2014-07-12', '2014-01-29', 0, 0, 'osvaldo.pereira.barbosa@fb.com', 'osvaldo.pereira.barbosa');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ALDIVINA REIS FERNANDES', '2014-07-12', '2014-01-11', 0, 0, 'aldivina.reis.fernandes@fb.com', 'aldivina.reis.fernandes');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JOSENOTARIO MUNGO', '2014-07-06', '2014-05-01', 0, 1, 'josenotario.mungo@hotmail.com', 'josenotario.mungo');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('AUGUSTA ALVES DOS SANTOS', '2014-07-01', '2014-01-01', 1, 1, 'augusta.alves.dos.santos@hotmail.com', 'augusta.alves.dos.santos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JOAO DE LUCA', '2014-07-12', '2014-03-13', 0, 0, 'joao.de.luca@fb.com', 'joao.de.luca');
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-09', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-22', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-01', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-26', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-12', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-28', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-02', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-21', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-11', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-07', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-09', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-31', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-04', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-05', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-25', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-10', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-20', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-07', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-30', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-17', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-07-12', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-14', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-20', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-15', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-21', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-30', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-09', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-08', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-28', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-28', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-29', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-20', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-17', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-26', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-29', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-16', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-03', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-31', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-07', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-04', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-27', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-05', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-21', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-04', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-08', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-14', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-28', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-14', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-17', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-23', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-27', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-30', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-10', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-24', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-25', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-17', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-06', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-27', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-21', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-30', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-20', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-13', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-13', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-20', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-30', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-01', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-27', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-23', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-07-04', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-11', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-30', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-25', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-26', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-15', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-15', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-28', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-27', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-23', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-18', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-22', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-29', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-20', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-24', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-30', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-18', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-14', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-23', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-07-07', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-22', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-07', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-04', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-23', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-29', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-24', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-26', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-09', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-07-08', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-02', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-30', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-17', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
