INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('94287-469', '0460', 'M', 'JOSE RIBAMAR BEZERRA SA', '2014-11-27', 1, 'Venezuela', 'jose.ribamar.bezerra.sa@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('03112-743', '5303', 'F', 'SEBASTIANA BENEDITA DA COSTA', '2014-02-13', 1, 'Korea South', 'sebastiana.benedita.da.costa@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('66120-242', '5964', 'M', 'ROSILENE ALMEIDA DA SILVA', '2014-10-22', 1, 'Burundi', 'rosilene.almeida.da.silva@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('33739-507', '6441', 'M', 'MARCONI GEORGE RIBEIRO DA SILVA', '2014-01-23', 1, 'Vanuatu', 'marconi.george.ribeiro.da.silva@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('33079-283', '6363', 'M', 'WANDERSON COSMO DE ARAUJO', '2014-02-20', 1, 'Guatemala', 'wanderson.cosmo.de.araujo@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('59760-600', '3510', 'F', 'VIRGILIA DIAS VIEIRA', '2014-06-03', 0, 'Lithuania', 'virgilia.dias.vieira@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('46758-989', '8163', 'F', 'ALICE FERNANDES DE OLIVEIRA', '2014-08-09', 1, 'Uganda', 'alice.fernandes.de.oliveira@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('86544-060', '6571', 'M', 'MARIA HILDA MACHADO', '2014-07-11', 0, 'Oman', 'maria.hilda.machado@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('17893-531', '8648', 'F', 'MARIA DAIANE DE ARAUJO SOUZA', '2014-04-10', 1, 'Portugal', 'maria.daiane.de.araujo.souza@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('73541-169', '2091', 'F', 'MARIA ALVES SUTIL', '2014-10-22', 0, 'Luxembourg', 'maria.alves.sutil@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('38787-852', '4850', 'M', 'CELESIAORMOND RIBEIRO DE CAMPOS', '2014-02-26', 1, 'Costa Rica', 'celesiaormond.ribeiro.de.campos@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('08934-652', '8706', 'M', 'WILSON CONCEICAO DE MIRANDA', '2014-03-19', 1, 'Austria', 'wilson.conceicao.de.miranda@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('37453-325', '0755', 'M', 'JOSE RIBAMAR BEZERRA SA', '2014-11-10', 1, 'Switzerland', 'jose.ribamar.bezerra.sa@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('49058-782', '7646', 'M', 'NADIACUIABANO KUNZE', '2014-10-09', 0, 'Bosnia & Herzegovina', 'nadiacuiabano.kunze@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('93595-600', '8788', 'M', 'NEUCY DE OLIVEIRA', '2014-03-27', 1, 'St. Vincent & The Grenadines', 'neucy.de.oliveira@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('38684-360', '2087', 'F', 'MARIA HILDA MACHADO', '2014-04-21', 0, 'Yemen', 'maria.hilda.machado@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('96921-778', '9648', 'F', 'AURELINDA BATISTA DA SILVA', '2014-11-26', 0, 'Bulgaria', 'aurelinda.batista.da.silva@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('75839-065', '4532', 'F', 'DIEGO CESPEDES DE SOUZA', '2014-10-26', 1, 'Grenada', 'diego.cespedes.de.souza@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('24773-613', '8342', 'F', 'DORILDA ALVES DE CARVALHO', '2014-06-19', 1, 'France', 'dorilda.alves.de.carvalho@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('91095-033', '5723', 'F', 'LAURA SEBASTIANA GURGEL', '2014-06-24', 1, 'Indonesia', 'laura.sebastiana.gurgel@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('94737-234', '4524', 'F', 'KLEBER MAGALHAES FERREIRA', '2014-09-11', 0, 'Togo', 'kleber.magalhaes.ferreira@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('19170-536', '0258', 'F', 'VALDOMIRO LEITE DE SA', '2014-09-06', 1, 'Dominica', 'valdomiro.leite.de.sa@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('65963-947', '9808', 'F', 'AFONSO BARBOSA DA SILVA', '2014-09-29', 0, 'Benin', 'afonso.barbosa.da.silva@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('58458-061', '3904', 'M', 'VIOLINDO DE SOUZA', '2014-10-23', 1, 'Guinea', 'violindo.de.souza@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('02464-389', '7667', 'F', 'MAGALI SANCHES', '2014-02-07', 0, 'Solomon Islands', 'magali.sanches@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('85406-636', '1237', 'F', 'JOSE JESUS DA HORA', '2014-11-18', 0, 'Cuba', 'jose.jesus.da.hora@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('47657-693', '9000', 'M', 'ALBERTO FEIZAR CARDOSO ABDALA', '2014-11-07', 1, 'Hungary', 'alberto.feizar.cardoso.abdala@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('86331-587', '8368', 'M', 'MARIA TEREZINHA ROCHA DE SOUZA', '2014-06-17', 1, 'Cyprus', 'maria.terezinha.rocha.de.souza@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('74379-943', '1161', 'M', 'CARMINDA POMPEU AMORIM', '2014-09-20', 1, 'Benin', 'carminda.pompeu.amorim@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('53045-889', '1907', 'F', 'ALCEU DOS SANTOS', '2014-04-15', 0, 'Bangladesh', 'alceu.dos.santos@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('08106-143', '9963', 'F', 'OSWALDIR GOMES', '2014-04-11', 0, 'Japan', 'oswaldir.gomes@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('83762-716', '9006', 'M', 'DIAMANTINA DA SILVA SOARES', '2014-12-09', 1, 'Mozambique', 'diamantina.da.silva.soares@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('94164-078', '6624', 'F', 'IROCIDES APARECIDA FERREIRA', '2014-03-02', 1, 'Swaziland', 'irocides.aparecida.ferreira@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('95508-022', '1445', 'F', 'JORGE TETSUO TAIRA', '2014-04-18', 1, 'Rwanda', 'jorge.tetsuo.taira@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('30319-559', '6181', 'F', 'OBADIAS MARCAL DE OLIVEIRA', '2014-09-07', 0, 'Korea North', 'obadias.marcal.de.oliveira@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('32739-546', '5890', 'F', 'CARLOS SERGIO URBANIN', '2014-06-28', 1, 'China', 'carlos.sergio.urbanin@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('13983-030', '7207', 'M', 'LOURIVAL ROSA GUIMARAES', '2014-12-16', 0, 'Togo', 'lourival.rosa.guimaraes@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('59094-594', '6463', 'F', 'NEUCY DE OLIVEIRA', '2014-04-30', 1, 'Austria', 'neucy.de.oliveira@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('47378-521', '7340', 'M', 'LUIZ FERNANDO DA SILVA AMORIM', '2014-10-02', 1, 'Australia', 'luiz.fernando.da.silva.amorim@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('64178-914', '6041', 'M', 'ADENILTON JOSE DE MIRANDA', '2014-08-09', 1, 'Lesotho', 'adenilton.jose.de.miranda@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('08784-053', '1504', 'M', 'CELIA CRISTINA PEREIRA PINTO DOS SANTOS', '2014-02-11', 1, 'Germany', 'celia.cristina.pereira.pinto.dos.santos@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('15819-406', '5536', 'F', 'NEUCY DE OLIVEIRA', '2014-01-12', 1, 'Kyrgyzstan', 'neucy.de.oliveira@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('21326-699', '2679', 'F', 'MARGARETH VIRGINIA DE REZENDE MEHLMANN', '2014-08-24', 0, 'Mauritius', 'margareth.virginia.de.rezende.mehlmann@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('58066-904', '1416', 'M', 'FRANCISCA MARIA SILVA COSTA', '2014-12-15', 0, 'Sri Lanka', 'francisca.maria.silva.costa@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('80769-458', '7886', 'F', 'LOURENCO DIAS', '2014-12-20', 0, 'Iceland', 'lourenco.dias@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('27154-364', '3064', 'F', 'CARLOS SERGIO URBANIN', '2014-11-07', 0, 'Saudi Arabia', 'carlos.sergio.urbanin@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('03992-788', '0698', 'M', 'LUIZA ROTTLISBERGER SILVA', '2014-01-02', 0, 'Kazakhstan', 'luiza.rottlisberger.silva@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('36185-215', '5871', 'M', 'BENJAMIM GAUNA', '2014-01-08', 1, 'Syria', 'benjamim.gauna@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('48039-296', '9354', 'M', 'BENJAMIM GAUNA', '2014-08-10', 0, 'Algeria', 'benjamim.gauna@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('24545-406', '1586', 'F', 'MARIA DO CARMO JERONIMO SILVA', '2014-12-26', 0, 'Nauru', 'maria.do.carmo.jeronimo.silva@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('00818-206', '4218', 'F', 'JOAO DE LUCA', '2014-01-09', 1, 'South Africa', 'joao.de.luca@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('09295-615', '9159', 'M', 'ALICE FERNANDES DE OLIVEIRA', '2014-10-25', 1, 'United Arab Emirates', 'alice.fernandes.de.oliveira@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('38409-339', '2431', 'M', 'ANTONIA BORGES DA SILVA', '2014-11-18', 1, 'Kyrgyzstan', 'antonia.borges.da.silva@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('76783-105', '4942', 'M', 'OSWALDIR GOMES', '2014-08-11', 0, 'Palau', 'oswaldir.gomes@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('38448-392', '5536', 'F', 'MARGARETH VIRGINIA DE REZENDE MEHLMANN', '2014-05-03', 1, 'Monaco', 'margareth.virginia.de.rezende.mehlmann@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('24946-090', '0833', 'M', 'MARIA ALVES SUTIL', '2014-06-09', 1, 'Vatican City (Holy See)', 'maria.alves.sutil@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('95640-471', '9708', 'M', 'MARIA DO CARMO JERONIMO SILVA', '2014-04-07', 1, 'Gabon', 'maria.do.carmo.jeronimo.silva@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('27288-939', '2167', 'F', 'MIGUEL VENCESLAU MACIEL DE CAMPOS', '2014-06-22', 0, 'Gambia', 'miguel.venceslau.maciel.de.campos@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('00206-289', '5955', 'M', 'GLAUBER DA COSTA ARRUDA', '2014-09-03', 0, 'Congo Democratic Republic', 'glauber.da.costa.arruda@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('63397-633', '2808', 'F', 'ZILMA MARQUES GONCALVES RODRIGUES', '2014-08-28', 0, 'Tanzania', 'zilma.marques.goncalves.rodrigues@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('18803-777', '6137', 'F', 'HELOIZA ALMEIDA DOS SANTOS', '2014-08-17', 0, 'Grenada', 'heloiza.almeida.dos.santos@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('26086-945', '4054', 'F', 'MARIA LOURENCO ARISTIDES', '2014-05-12', 1, 'China', 'maria.lourenco.aristides@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('57029-090', '2032', 'F', 'ROBSON LUIZ DO NASCIMENTO PUERTAS', '2014-12-18', 0, 'Romania', 'robson.luiz.do.nascimento.puertas@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('54478-834', '6954', 'M', 'THANIA CRISTINA DA SILVA BARNABE', '2014-06-10', 1, 'Australia', 'thania.cristina.da.silva.barnabe@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('99694-166', '2576', 'F', 'MARIA DO CARMO JERONIMO SILVA', '2014-06-01', 0, 'Sri Lanka', 'maria.do.carmo.jeronimo.silva@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('90381-209', '8311', 'F', 'LAURA SEBASTIANA GURGEL', '2014-06-03', 0, 'Zimbabwe', 'laura.sebastiana.gurgel@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('57259-537', '5752', 'F', 'CARMINDA POMPEU AMORIM', '2014-10-22', 0, 'Cape Verde', 'carminda.pompeu.amorim@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('19743-467', '3648', 'M', 'LUIZA ROTTLISBERGER SILVA', '2014-03-22', 1, 'Russia', 'luiza.rottlisberger.silva@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('54434-595', '4741', 'F', 'GUIOMAR TRELHA FRANCA', '2014-12-06', 0, 'Serbia', 'guiomar.trelha.franca@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('26165-214', '2499', 'M', 'MARCIA DA SILVA OLIVEIRA', '2014-07-04', 0, 'Moldova', 'marcia.da.silva.oliveira@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('34676-648', '0362', 'F', 'ALICE FERNANDES DE OLIVEIRA', '2014-07-09', 0, 'Kosovo', 'alice.fernandes.de.oliveira@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('16985-485', '0165', 'M', 'SONIA MARIA MARTINEZ PENITENTE', '2014-04-14', 0, 'Gabon', 'sonia.maria.martinez.penitente@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('33956-036', '7721', 'M', 'ELOIR CARLOS FIRMINO', '2014-08-24', 1, 'Germany', 'eloir.carlos.firmino@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('71743-710', '3452', 'M', 'ALIETE FRANCISCA PRATES', '2014-08-20', 0, 'Kosovo', 'aliete.francisca.prates@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('73588-645', '9671', 'F', 'ILZA XAVIER DE LIMA ARAUJO', '2014-12-15', 0, 'Tuvalu', 'ilza.xavier.de.lima.araujo@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('37244-936', '9388', 'F', 'JOSENOTARIO MUNGO', '2014-12-24', 0, 'Chad', 'josenotario.mungo@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('56681-043', '8407', 'F', 'NEIVA OBERGER FERREIRA', '2014-09-05', 0, 'Madagascar', 'neiva.oberger.ferreira@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('12283-153', '4739', 'F', 'TIMOTEO BATISTA LEITE', '2014-09-13', 0, 'Andorra', 'timoteo.batista.leite@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('47444-775', '3298', 'M', 'VILMA VITORIA DE SOUZA MESSA', '2014-04-17', 1, 'Belize', 'vilma.vitoria.de.souza.messa@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('88358-322', '2533', 'F', 'ELOIR CARLOS FIRMINO', '2014-03-05', 1, 'Azerbaijan', 'eloir.carlos.firmino@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('70259-446', '6843', 'F', 'SUELY DA SILVA CAVALCANTI', '2014-08-04', 1, 'Israel', 'suely.da.silva.cavalcanti@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('02549-965', '7876', 'F', 'ROBSON LUIZ DO NASCIMENTO PUERTAS', '2014-11-10', 0, 'China', 'robson.luiz.do.nascimento.puertas@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('57900-184', '5021', 'F', 'MARLENE SANTANA MARTINS', '2014-10-24', 1, 'Singapore', 'marlene.santana.martins@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('90618-803', '6252', 'F', 'HELOIZA ALMEIDA DOS SANTOS', '2014-11-14', 1, 'Central African Republic', 'heloiza.almeida.dos.santos@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('58023-732', '0454', 'M', 'ELZA LIMA DE SOUZA MANSANO', '2014-02-06', 1, 'Korea North', 'elza.lima.de.souza.mansano@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('81864-964', '0466', 'F', 'JOSENOTARIO MUNGO', '2014-10-21', 0, 'Nicaragua', 'josenotario.mungo@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('39903-888', '0565', 'M', 'NICANOR FELIZARDO DOS REIS', '2014-09-17', 1, 'Brunei', 'nicanor.felizardo.dos.reis@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('70297-706', '6145', 'F', 'SEBASTIANA BENEDITA DA COSTA', '2014-03-28', 1, 'Malta', 'sebastiana.benedita.da.costa@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('08947-098', '3231', 'M', 'ADELSON LUIZ DA SILVA', '2014-03-06', 1, 'Palestinian State', 'adelson.luiz.da.silva@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('93923-252', '5755', 'F', 'MARIA ALVES SUTIL', '2014-07-28', 0, 'San Marino', 'maria.alves.sutil@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('28570-161', '5474', 'M', 'ROSILENE ALMEIDA DA SILVA', '2014-04-30', 1, 'Latvia', 'rosilene.almeida.da.silva@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('25052-211', '5119', 'F', 'BEATRIZ PEREIRA LIMA', '2014-02-06', 1, 'Finland', 'beatriz.pereira.lima@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('48736-566', '3865', 'M', 'ANA PAULA FIGUEIREDO DA ROCHA', '2014-04-16', 1, 'Madagascar', 'ana.paula.figueiredo.da.rocha@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('74360-785', '9289', 'M', 'CLEUSA FERREIRA MACIEL', '2014-03-04', 1, 'Liechtenstein', 'cleusa.ferreira.maciel@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('60927-733', '1288', 'F', 'EDIO JUSTO BORGES', '2014-02-16', 1, 'Nepal', 'edio.justo.borges@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('59464-051', '2159', 'M', 'DAVINA PEREIRA DE SALES', '2014-04-25', 1, 'Slovakia', 'davina.pereira.de.sales@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('08691-425', '0407', 'F', 'JOSE EVALDO DA SILVA', '2014-10-25', 1, 'Saudi Arabia', 'jose.evaldo.da.silva@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('70852-302', '4440', 'M', 'GUIOMAR TRELHA FRANCA', '2014-07-11', 0, 'Cambodia', 'guiomar.trelha.franca@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('41378-756', '8500', 'M', 'FRANCISCA MARIA SILVA COSTA', '2014-05-17', 0, 'Kuwait', 'francisca.maria.silva.costa@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('10930-156', '5245', 'F', 'MARIA ELENA ALVES', '2014-11-04', 1, 'The Philippines', 'maria.elena.alves@hotmail.com');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LOURIVAL ROSA GUIMARAES', '2014-07-02', '2014-05-08', 0, 1, 'lourival.rosa.guimaraes@hotmail.com', 'lourival.rosa.guimaraes');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('CLAUDIO BARBOSA DOS SANTOS', '2014-07-13', '2014-01-03', 0, 0, 'claudio.barbosa.dos.santos@hotmail.com', 'claudio.barbosa.dos.santos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ELOIR CARLOS FIRMINO', '2014-07-07', '2014-02-01', 1, 1, 'eloir.carlos.firmino@gmail.com', 'eloir.carlos.firmino');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('RONY HUDSON OLIVEIRA CANDEIRO', '2014-07-03', '2014-05-31', 1, 0, 'rony.hudson.oliveira.candeiro@gmail.com', 'rony.hudson.oliveira.candeiro');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ALICE FERNANDES DE OLIVEIRA', '2014-07-11', '2014-04-03', 0, 1, 'alice.fernandes.de.oliveira@fb.com', 'alice.fernandes.de.oliveira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARIA DAIANE DE ARAUJO SOUZA', '2014-07-06', '2014-01-26', 1, 1, 'maria.daiane.de.araujo.souza@fb.com', 'maria.daiane.de.araujo.souza');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JUEL PRUDENCIO BORGES', '2014-07-07', '2014-06-09', 1, 0, 'juel.prudencio.borges@hotmail.com', 'juel.prudencio.borges');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('BENEDITA GAUDENCIO DA COSTA', '2014-07-02', '2014-01-04', 0, 1, 'benedita.gaudencio.da.costa@gmail.com', 'benedita.gaudencio.da.costa');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('VIOLINDO DE SOUZA', '2014-07-05', '2014-04-02', 1, 1, 'violindo.de.souza@fb.com', 'violindo.de.souza');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ZILDA MARTINS DE SOUZA', '2014-07-13', '2014-01-15', 0, 1, 'zilda.martins.de.souza@fb.com', 'zilda.martins.de.souza');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('QUITERIA LOURENCO DE LIMA', '2014-07-08', '2014-02-18', 1, 0, 'quiteria.lourenco.de.lima@gmail.com', 'quiteria.lourenco.de.lima');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JOSE NUNES PEREIRA', '2014-07-07', '2014-01-12', 1, 0, 'jose.nunes.pereira@fb.com', 'jose.nunes.pereira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('KLEBER MAGALHAES FERREIRA', '2014-07-06', '2014-03-22', 0, 0, 'kleber.magalhaes.ferreira@gmail.com', 'kleber.magalhaes.ferreira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('WANDERSON COSMO DE ARAUJO', '2014-07-13', '2014-01-04', 0, 1, 'wanderson.cosmo.de.araujo@gmail.com', 'wanderson.cosmo.de.araujo');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARCIA DA SILVA OLIVEIRA', '2014-07-11', '2014-04-26', 1, 0, 'marcia.da.silva.oliveira@hotmail.com', 'marcia.da.silva.oliveira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARIA FATIMA SCHEUNEMANN MIRANDA', '2014-07-04', '2014-02-12', 0, 0, 'maria.fatima.scheunemann.miranda@fb.com', 'maria.fatima.scheunemann.miranda');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('BENILDE PERES DE CAMPOS', '2014-07-03', '2014-01-14', 0, 0, 'benilde.peres.de.campos@hotmail.com', 'benilde.peres.de.campos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('NADIACUIABANO KUNZE', '2014-07-12', '2014-04-15', 0, 0, 'nadiacuiabano.kunze@gmail.com', 'nadiacuiabano.kunze');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ALICE FERNANDES DE OLIVEIRA', '2014-07-01', '2014-02-11', 0, 0, 'alice.fernandes.de.oliveira@fb.com', 'alice.fernandes.de.oliveira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('SUELY DA SILVA CAVALCANTI', '2014-07-07', '2014-04-13', 1, 1, 'suely.da.silva.cavalcanti@hotmail.com', 'suely.da.silva.cavalcanti');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('HABIB FAHED', '2014-07-04', '2014-01-05', 0, 0, 'habib.fahed@gmail.com', 'habib.fahed');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARIA FATIMA SCHEUNEMANN MIRANDA', '2014-07-10', '2014-02-11', 0, 1, 'maria.fatima.scheunemann.miranda@fb.com', 'maria.fatima.scheunemann.miranda');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JOSE RIBAMAR BEZERRA SA', '2014-07-06', '2014-01-04', 0, 1, 'jose.ribamar.bezerra.sa@fb.com', 'jose.ribamar.bezerra.sa');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('RUZINO ANTUNES DA SILVA', '2014-07-09', '2014-06-09', 0, 0, 'ruzino.antunes.da.silva@gmail.com', 'ruzino.antunes.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LUIZ FERNANDO DA SILVA AMORIM', '2014-07-06', '2014-01-17', 0, 0, 'luiz.fernando.da.silva.amorim@hotmail.com', 'luiz.fernando.da.silva.amorim');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LUIZA ROTTLISBERGER SILVA', '2014-07-12', '2014-03-22', 0, 1, 'luiza.rottlisberger.silva@hotmail.com', 'luiza.rottlisberger.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('DILMA DE SOUZA', '2014-07-12', '2014-01-27', 1, 0, 'dilma.de.souza@gmail.com', 'dilma.de.souza');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ALDIVINA REIS FERNANDES', '2014-07-04', '2014-02-25', 1, 0, 'aldivina.reis.fernandes@hotmail.com', 'aldivina.reis.fernandes');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('BENEDITO AMBROSIO DA COSTA', '2014-07-05', '2014-05-02', 0, 0, 'benedito.ambrosio.da.costa@hotmail.com', 'benedito.ambrosio.da.costa');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('VILMA VITORIA DE SOUZA MESSA', '2014-07-01', '2014-04-17', 0, 0, 'vilma.vitoria.de.souza.messa@fb.com', 'vilma.vitoria.de.souza.messa');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('SILVIA MENDES', '2014-07-11', '2014-04-20', 0, 0, 'silvia.mendes@hotmail.com', 'silvia.mendes');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARGARETH VIRGINIA DE REZENDE MEHLMANN', '2014-07-01', '2014-05-11', 1, 1, 'margareth.virginia.de.rezende.mehlmann@hotmail.com', 'margareth.virginia.de.rezende.mehlmann');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LUZIA RODRIGUES DE OLIVEIRA', '2014-07-12', '2014-06-28', 0, 0, 'luzia.rodrigues.de.oliveira@fb.com', 'luzia.rodrigues.de.oliveira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARCIA DA SILVA OLIVEIRA', '2014-07-11', '2014-04-08', 0, 0, 'marcia.da.silva.oliveira@hotmail.com', 'marcia.da.silva.oliveira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('VIRGILIA DIAS VIEIRA', '2014-07-05', '2014-03-12', 0, 0, 'virgilia.dias.vieira@hotmail.com', 'virgilia.dias.vieira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LIDIANE DO PRADO BRITE', '2014-07-08', '2014-04-10', 1, 1, 'lidiane.do.prado.brite@gmail.com', 'lidiane.do.prado.brite');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARIA DAIANE DE ARAUJO SOUZA', '2014-07-01', '2014-05-20', 0, 0, 'maria.daiane.de.araujo.souza@hotmail.com', 'maria.daiane.de.araujo.souza');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ROBSON LUIZ DO NASCIMENTO PUERTAS', '2014-07-12', '2014-06-16', 0, 1, 'robson.luiz.do.nascimento.puertas@fb.com', 'robson.luiz.do.nascimento.puertas');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARCIA DA SILVA OLIVEIRA', '2014-07-02', '2014-02-14', 0, 1, 'marcia.da.silva.oliveira@hotmail.com', 'marcia.da.silva.oliveira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('AURELINDA BATISTA DA SILVA', '2014-07-08', '2014-03-18', 0, 0, 'aurelinda.batista.da.silva@fb.com', 'aurelinda.batista.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('VALDOMIRO LEITE DE SA', '2014-07-05', '2014-06-03', 0, 1, 'valdomiro.leite.de.sa@hotmail.com', 'valdomiro.leite.de.sa');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LAURA SEBASTIANA GURGEL', '2014-07-06', '2014-05-12', 1, 0, 'laura.sebastiana.gurgel@hotmail.com', 'laura.sebastiana.gurgel');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARIA DO CARMO JERONIMO SILVA', '2014-07-02', '2014-05-24', 0, 0, 'maria.do.carmo.jeronimo.silva@hotmail.com', 'maria.do.carmo.jeronimo.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JOSENOTARIO MUNGO', '2014-07-03', '2014-02-21', 1, 0, 'josenotario.mungo@hotmail.com', 'josenotario.mungo');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ABIGAIL DA SILVA LARA', '2014-07-11', '2014-01-04', 1, 1, 'abigail.da.silva.lara@gmail.com', 'abigail.da.silva.lara');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ILZA XAVIER DE LIMA ARAUJO', '2014-07-09', '2014-05-04', 1, 0, 'ilza.xavier.de.lima.araujo@hotmail.com', 'ilza.xavier.de.lima.araujo');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('KLEBER MAGALHAES FERREIRA', '2014-07-02', '2014-03-20', 0, 0, 'kleber.magalhaes.ferreira@hotmail.com', 'kleber.magalhaes.ferreira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARLENE SANTANA MARTINS', '2014-07-12', '2014-05-02', 0, 1, 'marlene.santana.martins@fb.com', 'marlene.santana.martins');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ILZA XAVIER DE LIMA ARAUJO', '2014-07-10', '2014-06-21', 1, 1, 'ilza.xavier.de.lima.araujo@fb.com', 'ilza.xavier.de.lima.araujo');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('BENEDITA GAUDENCIO DA COSTA', '2014-07-09', '2014-02-24', 1, 0, 'benedita.gaudencio.da.costa@gmail.com', 'benedita.gaudencio.da.costa');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('SILVIO TSIPE RAIRATE', '2014-07-11', '2014-06-24', 0, 0, 'silvio.tsipe.rairate@hotmail.com', 'silvio.tsipe.rairate');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('HABIB FAHED', '2014-07-08', '2014-05-09', 0, 0, 'habib.fahed@gmail.com', 'habib.fahed');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARCONI GEORGE RIBEIRO DA SILVA', '2014-07-08', '2014-01-24', 0, 0, 'marconi.george.ribeiro.da.silva@fb.com', 'marconi.george.ribeiro.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARIA ELENA ALVES', '2014-07-12', '2014-03-05', 0, 1, 'maria.elena.alves@fb.com', 'maria.elena.alves');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('CELESIAORMOND RIBEIRO DE CAMPOS', '2014-07-12', '2014-04-26', 0, 0, 'celesiaormond.ribeiro.de.campos@hotmail.com', 'celesiaormond.ribeiro.de.campos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('IROCIDES APARECIDA FERREIRA', '2014-07-04', '2014-02-23', 0, 0, 'irocides.aparecida.ferreira@fb.com', 'irocides.aparecida.ferreira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ARISMARES SOUZA PRATES', '2014-07-10', '2014-05-07', 1, 1, 'arismares.souza.prates@fb.com', 'arismares.souza.prates');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LIDIANE DO PRADO BRITE', '2014-07-06', '2014-04-22', 1, 0, 'lidiane.do.prado.brite@gmail.com', 'lidiane.do.prado.brite');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('THANIA CRISTINA DA SILVA BARNABE', '2014-07-02', '2014-03-27', 0, 0, 'thania.cristina.da.silva.barnabe@fb.com', 'thania.cristina.da.silva.barnabe');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ATAIDE DIAS DE MOURA', '2014-07-09', '2014-04-14', 0, 0, 'ataide.dias.de.moura@hotmail.com', 'ataide.dias.de.moura');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('BEATRIZ PEREIRA LIMA', '2014-07-12', '2014-02-23', 0, 0, 'beatriz.pereira.lima@gmail.com', 'beatriz.pereira.lima');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ADELSON LUIZ DA SILVA', '2014-07-08', '2014-02-12', 1, 0, 'adelson.luiz.da.silva@hotmail.com', 'adelson.luiz.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ANGELA APARECIDA BERNEGOZZE', '2014-07-02', '2014-03-25', 0, 0, 'angela.aparecida.bernegozze@gmail.com', 'angela.aparecida.bernegozze');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JULIO APARECIDO DE SOUZA', '2014-07-03', '2014-06-13', 0, 0, 'julio.aparecido.de.souza@fb.com', 'julio.aparecido.de.souza');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('VILMA VITORIA DE SOUZA MESSA', '2014-07-03', '2014-04-09', 1, 1, 'vilma.vitoria.de.souza.messa@gmail.com', 'vilma.vitoria.de.souza.messa');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ROSILENE ALMEIDA DA SILVA', '2014-07-11', '2014-02-10', 1, 1, 'rosilene.almeida.da.silva@hotmail.com', 'rosilene.almeida.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARIA TEREZINHA ROCHA DE SOUZA', '2014-07-11', '2014-04-28', 0, 1, 'maria.terezinha.rocha.de.souza@gmail.com', 'maria.terezinha.rocha.de.souza');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARILEIA NUNES DE OLIVEIRA', '2014-07-02', '2014-02-16', 1, 1, 'marileia.nunes.de.oliveira@gmail.com', 'marileia.nunes.de.oliveira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARIA TEREZINHA ROCHA DE SOUZA', '2014-07-04', '2014-03-30', 0, 0, 'maria.terezinha.rocha.de.souza@gmail.com', 'maria.terezinha.rocha.de.souza');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('IVANI DO NASCIMENTO VALENTIM', '2014-07-10', '2014-05-23', 0, 0, 'ivani.do.nascimento.valentim@fb.com', 'ivani.do.nascimento.valentim');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ANA ALVES LUCIANO', '2014-07-11', '2014-03-18', 1, 0, 'ana.alves.luciano@gmail.com', 'ana.alves.luciano');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('DILMA DE SOUZA', '2014-07-01', '2014-01-27', 0, 1, 'dilma.de.souza@fb.com', 'dilma.de.souza');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('RAMIRO VEDOVATO', '2014-07-07', '2014-01-29', 1, 0, 'ramiro.vedovato@gmail.com', 'ramiro.vedovato');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JOAQUIM BORGES RODRIGUES', '2014-07-11', '2014-06-29', 1, 0, 'joaquim.borges.rodrigues@gmail.com', 'joaquim.borges.rodrigues');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('AURELINDA BATISTA DA SILVA', '2014-07-10', '2014-02-07', 1, 0, 'aurelinda.batista.da.silva@hotmail.com', 'aurelinda.batista.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARCIA DA SILVA OLIVEIRA', '2014-07-06', '2014-04-20', 0, 1, 'marcia.da.silva.oliveira@fb.com', 'marcia.da.silva.oliveira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARIA TEREZINHA ROCHA DE SOUZA', '2014-07-01', '2014-02-09', 0, 0, 'maria.terezinha.rocha.de.souza@hotmail.com', 'maria.terezinha.rocha.de.souza');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('AURELINDA BATISTA DA SILVA', '2014-07-02', '2014-05-20', 0, 0, 'aurelinda.batista.da.silva@hotmail.com', 'aurelinda.batista.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('WILSON CONCEICAO DE MIRANDA', '2014-07-03', '2014-06-30', 0, 1, 'wilson.conceicao.de.miranda@hotmail.com', 'wilson.conceicao.de.miranda');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('OLGA PEREIRA', '2014-07-08', '2014-01-15', 1, 0, 'olga.pereira@gmail.com', 'olga.pereira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('SILVIA MENDES', '2014-07-08', '2014-01-29', 1, 1, 'silvia.mendes@hotmail.com', 'silvia.mendes');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('RENIRA RODRIGUES DA SILVA DE SOUSA', '2014-07-13', '2014-04-28', 1, 0, 'renira.rodrigues.da.silva.de.sousa@fb.com', 'renira.rodrigues.da.silva.de.sousa');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('DORILDA ALVES DE CARVALHO', '2014-07-06', '2014-02-15', 0, 1, 'dorilda.alves.de.carvalho@gmail.com', 'dorilda.alves.de.carvalho');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('FRANCISCA MARIA SILVA COSTA', '2014-07-08', '2014-06-03', 0, 0, 'francisca.maria.silva.costa@gmail.com', 'francisca.maria.silva.costa');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('HELIO SAMBATTI', '2014-07-08', '2014-02-08', 1, 0, 'helio.sambatti@gmail.com', 'helio.sambatti');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('BENJAMIM GAUNA', '2014-07-13', '2014-01-04', 0, 1, 'benjamim.gauna@hotmail.com', 'benjamim.gauna');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JOSE JESUS DA HORA', '2014-07-12', '2014-06-17', 0, 1, 'jose.jesus.da.hora@fb.com', 'jose.jesus.da.hora');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ILZA XAVIER DE LIMA ARAUJO', '2014-07-08', '2014-05-28', 0, 0, 'ilza.xavier.de.lima.araujo@hotmail.com', 'ilza.xavier.de.lima.araujo');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ALDIVINA REIS FERNANDES', '2014-07-02', '2014-04-27', 1, 1, 'aldivina.reis.fernandes@hotmail.com', 'aldivina.reis.fernandes');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LOURIVAL ROSA GUIMARAES', '2014-07-02', '2014-01-05', 0, 0, 'lourival.rosa.guimaraes@hotmail.com', 'lourival.rosa.guimaraes');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LOURIVAL ROSA GUIMARAES', '2014-07-05', '2014-03-19', 0, 0, 'lourival.rosa.guimaraes@fb.com', 'lourival.rosa.guimaraes');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ANTONIO INACIO RODRIGUES', '2014-07-10', '2014-01-09', 1, 1, 'antonio.inacio.rodrigues@hotmail.com', 'antonio.inacio.rodrigues');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ALDEIR ALEX ALVES LIMA', '2014-07-02', '2014-03-12', 0, 1, 'aldeir.alex.alves.lima@gmail.com', 'aldeir.alex.alves.lima');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ROSILENE ALMEIDA DA SILVA', '2014-07-07', '2014-01-27', 0, 1, 'rosilene.almeida.da.silva@fb.com', 'rosilene.almeida.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LIDIANE DO PRADO BRITE', '2014-07-10', '2014-06-21', 0, 1, 'lidiane.do.prado.brite@fb.com', 'lidiane.do.prado.brite');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('SUELY DA SILVA CAVALCANTI', '2014-07-12', '2014-05-12', 0, 1, 'suely.da.silva.cavalcanti@fb.com', 'suely.da.silva.cavalcanti');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARILEIA NUNES DE OLIVEIRA', '2014-07-10', '2014-04-08', 0, 1, 'marileia.nunes.de.oliveira@hotmail.com', 'marileia.nunes.de.oliveira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('CRISTIANE PAES CORDOBA', '2014-07-13', '2014-06-02', 0, 1, 'cristiane.paes.cordoba@gmail.com', 'cristiane.paes.cordoba');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('AMERICO FRANCISCO DA SILVA', '2014-07-13', '2014-04-08', 1, 0, 'americo.francisco.da.silva@hotmail.com', 'americo.francisco.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARGARETH VIRGINIA DE REZENDE MEHLMANN', '2014-07-10', '2014-05-12', 0, 0, 'margareth.virginia.de.rezende.mehlmann@gmail.com', 'margareth.virginia.de.rezende.mehlmann');
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-10', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-08', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-28', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-04', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-07-12', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-28', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-09', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-31', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-20', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-22', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-06', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-20', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-14', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-06', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-15', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-12', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-13', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-29', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-21', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-07-10', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-03', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-22', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-24', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-23', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-16', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-30', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-26', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-10', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-18', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-22', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-20', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-26', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-26', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-16', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-30', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-30', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-21', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-25', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-26', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-09', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-19', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-13', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-22', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-04', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-31', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-16', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-07-06', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-07-06', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-21', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-22', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-29', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-18', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-27', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-17', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-02', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-07-04', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-03', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-24', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-13', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-24', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-05', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-19', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-11', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-12', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-15', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-04', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-05', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-10', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-17', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-19', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-22', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-02', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-07-06', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-29', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-08', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-19', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-24', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-29', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-22', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-23', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-25', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-08', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-02', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-07-09', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-15', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-02', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-19', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-20', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-10', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-07', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-02', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-29', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-22', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-24', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-12', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-07-10', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-10', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-01', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-18', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-24', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
