INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('58525-001', '2884', 'M', 'MARIA ELENA ALVES', '2014-02-07', 0, 'Cyprus', 'maria.elena.alves@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('41733-093', '6428', 'M', 'AURELINDA BATISTA DA SILVA', '2014-07-24', 0, 'Somalia', 'aurelinda.batista.da.silva@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('78496-027', '4699', 'F', 'ANGELA APARECIDA BERNEGOZZE', '2014-10-19', 1, 'Panama', 'angela.aparecida.bernegozze@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('45663-876', '3771', 'M', 'DILMA DE SOUZA', '2014-07-26', 1, 'Estonia', 'dilma.de.souza@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('40157-450', '7227', 'F', 'ANA ALVES LUCIANO', '2014-08-16', 0, 'Laos', 'ana.alves.luciano@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('36005-677', '0276', 'F', 'LUIZ FERNANDO DA SILVA AMORIM', '2014-03-21', 1, 'Guyana', 'luiz.fernando.da.silva.amorim@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('25519-482', '8016', 'F', 'ALICE FERNANDES DE OLIVEIRA', '2014-12-06', 1, 'Tunisia', 'alice.fernandes.de.oliveira@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('21077-814', '7999', 'F', 'ALICE FERNANDES DE OLIVEIRA', '2014-01-11', 1, 'Peru', 'alice.fernandes.de.oliveira@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('62087-425', '9808', 'M', 'ANTONIA BORGES DA SILVA', '2014-11-22', 1, 'Russia', 'antonia.borges.da.silva@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('70261-133', '1672', 'F', 'GLAUBER DA COSTA ARRUDA', '2014-12-15', 0, 'Congo', 'glauber.da.costa.arruda@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('11669-789', '6876', 'F', 'PAULO TEIXEIRA DE ABREU', '2014-08-11', 0, 'Gambia', 'paulo.teixeira.de.abreu@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('65108-167', '1206', 'F', 'ANTONIO INACIO RODRIGUES', '2014-04-15', 1, 'Monaco', 'antonio.inacio.rodrigues@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('83329-925', '9155', 'M', 'SUELY DA SILVA CAVALCANTI', '2014-04-05', 0, 'St. Kitts & Nevis', 'suely.da.silva.cavalcanti@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('32944-116', '5466', 'F', 'ALICE APARECIDA DOS SANTOS', '2014-12-07', 1, 'Honduras', 'alice.aparecida.dos.santos@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('44810-559', '8191', 'F', 'LOURIVAL ROSA GUIMARAES', '2014-10-11', 0, 'Madagascar', 'lourival.rosa.guimaraes@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('04710-936', '6804', 'M', 'NEUCY DE OLIVEIRA', '2014-04-30', 1, 'Kosovo', 'neucy.de.oliveira@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('41591-586', '4908', 'M', 'DILMA DE SOUZA', '2014-06-11', 1, 'Mozambique', 'dilma.de.souza@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('78444-711', '6025', 'F', 'MARIA TEREZINHA ROCHA DE SOUZA', '2014-04-23', 0, 'Serbia', 'maria.terezinha.rocha.de.souza@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('76986-491', '0317', 'F', 'LUIZA ROTTLISBERGER SILVA', '2014-07-30', 1, 'Haiti', 'luiza.rottlisberger.silva@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('13198-159', '5892', 'M', 'ELOIR CARLOS FIRMINO', '2014-06-15', 0, 'Spain', 'eloir.carlos.firmino@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('82995-177', '1293', 'F', 'JOSE JESUS DA HORA', '2014-09-21', 0, 'Colombia', 'jose.jesus.da.hora@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('61960-881', '0755', 'F', 'JOSENOTARIO MUNGO', '2014-08-16', 0, 'Italy', 'josenotario.mungo@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('97115-041', '4091', 'F', 'ELEONILDA DE LIMA RODRIGUES', '2014-12-10', 0, 'East Timor', 'eleonilda.de.lima.rodrigues@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('22656-083', '4991', 'F', 'RUZINO ANTUNES DA SILVA', '2014-02-16', 0, 'Djibouti', 'ruzino.antunes.da.silva@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('73971-768', '0962', 'M', 'MARLENE SANTANA MARTINS', '2014-10-25', 0, 'Iceland', 'marlene.santana.martins@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('39658-028', '5556', 'F', 'ABILIO CAVALHEIRO', '2014-01-30', 0, 'France', 'abilio.cavalheiro@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('41405-847', '3464', 'M', 'ALICE FERNANDES DE OLIVEIRA', '2014-02-23', 0, 'Kenya', 'alice.fernandes.de.oliveira@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('21183-918', '3279', 'F', 'ALICE APARECIDA DOS SANTOS', '2014-07-04', 1, 'Armenia', 'alice.aparecida.dos.santos@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('62124-758', '1337', 'F', 'SUELY DA SILVA CAVALCANTI', '2014-08-25', 0, 'Taiwan', 'suely.da.silva.cavalcanti@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('98422-431', '3832', 'F', 'MARCIA DA SILVA OLIVEIRA', '2014-09-11', 0, 'Eritrea', 'marcia.da.silva.oliveira@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('67762-448', '8816', 'F', 'VIOLINDO DE SOUZA', '2014-04-02', 0, 'Honduras', 'violindo.de.souza@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('21326-460', '0892', 'M', 'VIRGILIA DIAS VIEIRA', '2014-03-07', 0, 'San Marino', 'virgilia.dias.vieira@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('46238-426', '7899', 'M', 'MIGUEL VENCESLAU MACIEL DE CAMPOS', '2014-12-16', 1, 'Rwanda', 'miguel.venceslau.maciel.de.campos@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('36746-466', '7903', 'F', 'NEIVA OBERGER FERREIRA', '2014-08-30', 0, 'Iraq', 'neiva.oberger.ferreira@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('40723-041', '7407', 'M', 'CARLOS SERGIO URBANIN', '2014-06-20', 1, 'Vatican City (Holy See)', 'carlos.sergio.urbanin@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('11868-528', '8660', 'F', 'JOSE JESUS DA HORA', '2014-12-18', 1, 'Bahrain', 'jose.jesus.da.hora@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('46814-099', '0082', 'F', 'ANTONIO INACIO RODRIGUES', '2014-09-05', 1, 'Brunei', 'antonio.inacio.rodrigues@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('84650-862', '0741', 'M', 'WILSON CONCEICAO DE MIRANDA', '2014-12-14', 0, 'Albania', 'wilson.conceicao.de.miranda@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('15624-143', '7731', 'M', 'LAURA SEBASTIANA GURGEL', '2014-06-13', 0, 'Lesotho', 'laura.sebastiana.gurgel@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('30918-961', '1908', 'M', 'ANTONIA BORGES DA SILVA', '2014-06-21', 0, 'Rwanda', 'antonia.borges.da.silva@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('11980-493', '8934', 'M', 'WILSON CONCEICAO DE MIRANDA', '2014-05-31', 1, 'East Timor', 'wilson.conceicao.de.miranda@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('74478-947', '2965', 'F', 'ALICE APARECIDA DOS SANTOS', '2014-01-07', 1, 'Fiji', 'alice.aparecida.dos.santos@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('83875-953', '3685', 'M', 'KLEBER MAGALHAES FERREIRA', '2014-09-20', 1, 'Cambodia', 'kleber.magalhaes.ferreira@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('21710-913', '2455', 'M', 'MARLENE SANTANA MARTINS', '2014-11-04', 1, 'Portugal', 'marlene.santana.martins@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('73466-899', '2872', 'M', 'MARIA DO CARMO JERONIMO SILVA', '2014-03-01', 0, 'Monaco', 'maria.do.carmo.jeronimo.silva@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('76465-858', '2082', 'M', 'LAURO JOSE DA SILVA', '2014-04-01', 0, 'Palau', 'lauro.jose.da.silva@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('43540-894', '9044', 'M', 'GUIOMAR TRELHA FRANCA', '2014-06-12', 0, 'Cote d''Ivoire', 'guiomar.trelha.franca@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('48573-102', '7645', 'M', 'VALDOMIRO LEITE DE SA', '2014-04-10', 1, 'Oman', 'valdomiro.leite.de.sa@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('63429-785', '8470', 'F', 'JOAQUIM BORGES RODRIGUES', '2014-11-10', 1, 'Bahrain', 'joaquim.borges.rodrigues@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('32454-591', '9138', 'M', 'ARISMARES SOUZA PRATES', '2014-09-12', 1, 'Congo', 'arismares.souza.prates@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('16655-631', '2139', 'M', 'JULIO APARECIDO DE SOUZA', '2014-10-29', 0, 'Congo Democratic Republic', 'julio.aparecido.de.souza@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('06445-701', '1813', 'F', 'MARIA ELENA ALVES', '2014-07-06', 0, 'Spain', 'maria.elena.alves@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('06551-021', '1811', 'F', 'ALICE FERNANDES DE OLIVEIRA', '2014-05-22', 1, 'The Netherlands', 'alice.fernandes.de.oliveira@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('07864-535', '9434', 'F', 'ATAIDE DIAS DE MOURA', '2014-09-03', 1, 'The Netherlands', 'ataide.dias.de.moura@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('75926-409', '9924', 'F', 'ANGELA APARECIDA BERNEGOZZE', '2014-06-06', 0, 'Cambodia', 'angela.aparecida.bernegozze@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('36844-517', '1203', 'M', 'LUZIA RODRIGUES DE OLIVEIRA', '2014-05-01', 1, 'Sierra Leone', 'luzia.rodrigues.de.oliveira@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('57174-544', '0129', 'M', 'JOSE EVALDO DA SILVA', '2014-10-31', 1, 'France', 'jose.evaldo.da.silva@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('53413-341', '5925', 'M', 'MARLENE SANTANA MARTINS', '2014-01-01', 0, 'Samoa', 'marlene.santana.martins@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('38276-576', '2061', 'F', 'ELISABETE ROMERO NOBRE LEAL', '2014-09-11', 0, 'Jordan', 'elisabete.romero.nobre.leal@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('03395-952', '8432', 'M', 'ATAIDE DIAS DE MOURA', '2014-01-04', 1, 'Estonia', 'ataide.dias.de.moura@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('51002-471', '8383', 'F', 'JOANA ANTUNES', '2014-02-07', 0, 'Bhutan', 'joana.antunes@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('80094-936', '7439', 'M', 'MARGARETH VIRGINIA DE REZENDE MEHLMANN', '2014-03-20', 0, 'Sweden', 'margareth.virginia.de.rezende.mehlmann@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('45752-700', '3915', 'F', 'NEUCY DE OLIVEIRA', '2014-02-19', 1, 'Grenada', 'neucy.de.oliveira@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('57706-232', '4454', 'F', 'LIDIANE DO PRADO BRITE', '2014-07-12', 1, 'Cyprus', 'lidiane.do.prado.brite@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('17944-893', '6306', 'F', 'JOAO DE LUCA', '2014-09-19', 0, 'Slovenia', 'joao.de.luca@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('93910-905', '4952', 'M', 'GLAUBER DA COSTA ARRUDA', '2014-10-20', 0, 'Malawi', 'glauber.da.costa.arruda@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('50041-148', '2768', 'M', 'ADELSON LUIZ DA SILVA', '2014-03-07', 1, 'Burkina Faso', 'adelson.luiz.da.silva@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('85261-341', '0087', 'M', 'WANDERSON COSMO DE ARAUJO', '2014-02-02', 1, 'Indonesia', 'wanderson.cosmo.de.araujo@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('72374-695', '6349', 'F', 'ROBSON LUIZ DO NASCIMENTO PUERTAS', '2014-10-11', 0, 'Sierra Leone', 'robson.luiz.do.nascimento.puertas@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('88908-535', '2854', 'M', 'ANDRE LUIS CASTRILLON GARCIA', '2014-03-20', 1, 'Botswana', 'andre.luis.castrillon.garcia@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('42507-604', '5288', 'M', 'MARIA HILDA MACHADO', '2014-12-22', 1, 'Jamaica', 'maria.hilda.machado@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('72001-932', '6555', 'F', 'NEIVA OBERGER FERREIRA', '2014-02-03', 1, 'New Zealand', 'neiva.oberger.ferreira@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('21474-974', '1702', 'M', 'JOAQUIM BORGES RODRIGUES', '2014-05-27', 1, 'Congo', 'joaquim.borges.rodrigues@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('20501-283', '0972', 'M', 'LUCINEIDE DE MORAES DO CARMO', '2014-06-20', 0, 'Romania', 'lucineide.de.moraes.do.carmo@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('67826-446', '8284', 'M', 'INES APARECIDA DA SILVA', '2014-08-22', 0, 'San Marino', 'ines.aparecida.da.silva@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('43906-850', '4218', 'M', 'VIRGILIA DIAS VIEIRA', '2014-03-05', 0, 'Norway', 'virgilia.dias.vieira@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('03256-350', '3632', 'M', 'NEIZA MARIA LEITE DA SILVA', '2014-10-06', 1, 'San Marino', 'neiza.maria.leite.da.silva@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('93478-127', '2139', 'F', 'MARIA LOURENCO ARISTIDES', '2014-08-26', 1, 'Madagascar', 'maria.lourenco.aristides@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('40008-106', '2560', 'M', 'MIGUEL VENCESLAU MACIEL DE CAMPOS', '2014-03-22', 1, 'Lesotho', 'miguel.venceslau.maciel.de.campos@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('82023-477', '6066', 'M', 'ANA PAULA FIGUEIREDO DA ROCHA', '2014-07-27', 1, 'Lithuania', 'ana.paula.figueiredo.da.rocha@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('62306-267', '1890', 'M', 'LOURENCO DIAS', '2014-09-29', 1, 'Iraq', 'lourenco.dias@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('84173-223', '9747', 'F', 'CELIA CRISTINA PEREIRA PINTO DOS SANTOS', '2014-01-17', 0, 'Kenya', 'celia.cristina.pereira.pinto.dos.santos@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('99322-800', '5574', 'M', 'AURELINDA BATISTA DA SILVA', '2014-05-23', 0, 'Portugal', 'aurelinda.batista.da.silva@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('99303-388', '8636', 'M', 'CELESIAORMOND RIBEIRO DE CAMPOS', '2014-08-05', 1, 'Uganda', 'celesiaormond.ribeiro.de.campos@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('80086-905', '6191', 'M', 'THANIA CRISTINA DA SILVA BARNABE', '2014-05-11', 0, 'Azerbaijan', 'thania.cristina.da.silva.barnabe@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('00407-003', '4144', 'F', 'BENJAMIM GAUNA', '2014-11-01', 0, 'Morocco', 'benjamim.gauna@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('73566-664', '8323', 'F', 'MARIA LOURENCO ARISTIDES', '2014-04-01', 0, 'Mexico', 'maria.lourenco.aristides@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('87799-211', '9169', 'M', 'ELOIR CARLOS FIRMINO', '2014-10-25', 0, 'Samoa', 'eloir.carlos.firmino@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('47257-269', '3851', 'F', 'ADENILTON JOSE DE MIRANDA', '2014-03-02', 1, 'Barbados', 'adenilton.jose.de.miranda@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('23769-248', '7722', 'M', 'MAGALI SANCHES', '2014-03-14', 1, 'Honduras', 'magali.sanches@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('31098-879', '6507', 'F', 'PAULO TEIXEIRA DE ABREU', '2014-10-28', 1, 'Central African Republic', 'paulo.teixeira.de.abreu@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('03597-553', '2835', 'F', 'VIOLINDO DE SOUZA', '2014-03-14', 0, 'Argentina', 'violindo.de.souza@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('20631-676', '0282', 'F', 'LOURENCO DIAS', '2014-10-14', 1, 'Kosovo', 'lourenco.dias@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('92490-969', '7351', 'M', 'BEATRIZ PEREIRA LIMA', '2014-08-17', 1, 'Papua New Guinea', 'beatriz.pereira.lima@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('00913-349', '4891', 'F', 'HABIB FAHED', '2014-08-07', 1, 'The Philippines', 'habib.fahed@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('05421-814', '3630', 'M', 'OSVALDO PEREIRA BARBOSA', '2014-09-08', 1, 'Finland', 'osvaldo.pereira.barbosa@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('15937-159', '7117', 'F', 'VALDOMIRO LEITE DE SA', '2014-09-19', 0, 'Benin', 'valdomiro.leite.de.sa@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('23513-186', '5400', 'M', 'LUIZ FERNANDO DA SILVA AMORIM', '2014-03-22', 1, 'Turkey', 'luiz.fernando.da.silva.amorim@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('40721-655', '4386', 'F', 'ROSILENE ALMEIDA DA SILVA', '2014-01-02', 1, 'Uganda', 'rosilene.almeida.da.silva@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('25359-526', '9890', 'F', 'ALICE DE SOUZA MIRANDA', '2014-06-11', 0, 'Paraguay', 'alice.de.souza.miranda@hotmail.com');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ZILDA MARTINS DE SOUZA', '2014-07-03', '2014-01-28', 1, 1, 'zilda.martins.de.souza@fb.com', 'zilda.martins.de.souza');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ZILMA MARQUES GONCALVES RODRIGUES', '2014-07-13', '2014-04-04', 1, 0, 'zilma.marques.goncalves.rodrigues@gmail.com', 'zilma.marques.goncalves.rodrigues');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ZILMA MARQUES GONCALVES RODRIGUES', '2014-07-08', '2014-03-17', 0, 0, 'zilma.marques.goncalves.rodrigues@fb.com', 'zilma.marques.goncalves.rodrigues');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JOSE RIBAMAR BEZERRA SA', '2014-07-10', '2014-01-08', 1, 0, 'jose.ribamar.bezerra.sa@hotmail.com', 'jose.ribamar.bezerra.sa');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('AUGUSTA ALVES DOS SANTOS', '2014-07-11', '2014-02-26', 0, 1, 'augusta.alves.dos.santos@hotmail.com', 'augusta.alves.dos.santos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('RAMAO CARDOSO', '2014-07-04', '2014-05-04', 0, 0, 'ramao.cardoso@hotmail.com', 'ramao.cardoso');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JUEL PRUDENCIO BORGES', '2014-07-04', '2014-05-23', 1, 1, 'juel.prudencio.borges@fb.com', 'juel.prudencio.borges');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('BEATRIZ PEREIRA LIMA', '2014-07-13', '2014-04-01', 1, 1, 'beatriz.pereira.lima@hotmail.com', 'beatriz.pereira.lima');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LUIZA ROTTLISBERGER SILVA', '2014-07-06', '2014-01-01', 1, 1, 'luiza.rottlisberger.silva@gmail.com', 'luiza.rottlisberger.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARGARETH VIRGINIA DE REZENDE MEHLMANN', '2014-07-07', '2014-02-11', 1, 0, 'margareth.virginia.de.rezende.mehlmann@hotmail.com', 'margareth.virginia.de.rezende.mehlmann');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MIGUEL VENCESLAU MACIEL DE CAMPOS', '2014-07-06', '2014-03-30', 1, 0, 'miguel.venceslau.maciel.de.campos@fb.com', 'miguel.venceslau.maciel.de.campos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('KLEBER MAGALHAES FERREIRA', '2014-07-08', '2014-02-12', 1, 1, 'kleber.magalhaes.ferreira@hotmail.com', 'kleber.magalhaes.ferreira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARGARETH VIRGINIA DE REZENDE MEHLMANN', '2014-07-13', '2014-03-07', 0, 0, 'margareth.virginia.de.rezende.mehlmann@fb.com', 'margareth.virginia.de.rezende.mehlmann');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ANGELA APARECIDA BERNEGOZZE', '2014-07-06', '2014-03-03', 1, 0, 'angela.aparecida.bernegozze@hotmail.com', 'angela.aparecida.bernegozze');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('RITA IRACI ALMEIDA DA SILVA', '2014-07-01', '2014-03-02', 1, 0, 'rita.iraci.almeida.da.silva@fb.com', 'rita.iraci.almeida.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('CLEODETE CANOLA DE CAMPOS', '2014-07-08', '2014-04-26', 1, 1, 'cleodete.canola.de.campos@hotmail.com', 'cleodete.canola.de.campos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JOSE EVALDO DA SILVA', '2014-07-05', '2014-02-04', 1, 0, 'jose.evaldo.da.silva@fb.com', 'jose.evaldo.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('OSWALDIR GOMES', '2014-07-13', '2014-06-14', 0, 0, 'oswaldir.gomes@gmail.com', 'oswaldir.gomes');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LUIZA ROTTLISBERGER SILVA', '2014-07-03', '2014-06-11', 1, 0, 'luiza.rottlisberger.silva@gmail.com', 'luiza.rottlisberger.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('OSWALDIR GOMES', '2014-07-06', '2014-02-16', 0, 0, 'oswaldir.gomes@hotmail.com', 'oswaldir.gomes');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ROBSON LUIZ DO NASCIMENTO PUERTAS', '2014-07-05', '2014-06-16', 0, 0, 'robson.luiz.do.nascimento.puertas@fb.com', 'robson.luiz.do.nascimento.puertas');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('SOLANGE APARECIDA DO PRADO DA CRUZ', '2014-07-05', '2014-06-26', 0, 0, 'solange.aparecida.do.prado.da.cruz@fb.com', 'solange.aparecida.do.prado.da.cruz');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('DIEGO CESPEDES DE SOUZA', '2014-07-13', '2014-06-18', 0, 1, 'diego.cespedes.de.souza@hotmail.com', 'diego.cespedes.de.souza');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('CORNELIO DIAS DUARTE', '2014-07-09', '2014-06-29', 0, 0, 'cornelio.dias.duarte@gmail.com', 'cornelio.dias.duarte');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('SOLANGE APARECIDA DO PRADO DA CRUZ', '2014-07-13', '2014-02-03', 0, 1, 'solange.aparecida.do.prado.da.cruz@hotmail.com', 'solange.aparecida.do.prado.da.cruz');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('WANDERSON COSMO DE ARAUJO', '2014-07-04', '2014-01-26', 1, 0, 'wanderson.cosmo.de.araujo@fb.com', 'wanderson.cosmo.de.araujo');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('RITA IRACI ALMEIDA DA SILVA', '2014-07-10', '2014-01-28', 0, 0, 'rita.iraci.almeida.da.silva@gmail.com', 'rita.iraci.almeida.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ELEONILDA DE LIMA RODRIGUES', '2014-07-03', '2014-05-07', 1, 0, 'eleonilda.de.lima.rodrigues@hotmail.com', 'eleonilda.de.lima.rodrigues');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARIA DAIANE DE ARAUJO SOUZA', '2014-07-01', '2014-02-02', 1, 1, 'maria.daiane.de.araujo.souza@hotmail.com', 'maria.daiane.de.araujo.souza');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('NEIVA OBERGER FERREIRA', '2014-07-09', '2014-01-30', 1, 1, 'neiva.oberger.ferreira@fb.com', 'neiva.oberger.ferreira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARIA HILDA MACHADO', '2014-07-02', '2014-02-27', 0, 0, 'maria.hilda.machado@fb.com', 'maria.hilda.machado');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JOSE EVALDO DA SILVA', '2014-07-10', '2014-05-14', 1, 0, 'jose.evaldo.da.silva@gmail.com', 'jose.evaldo.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ABIGAIL DA SILVA LARA', '2014-07-02', '2014-06-14', 0, 0, 'abigail.da.silva.lara@hotmail.com', 'abigail.da.silva.lara');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LUCINEIDE DE MORAES DO CARMO', '2014-07-08', '2014-01-19', 0, 0, 'lucineide.de.moraes.do.carmo@hotmail.com', 'lucineide.de.moraes.do.carmo');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('CELESIAORMOND RIBEIRO DE CAMPOS', '2014-07-11', '2014-04-05', 1, 1, 'celesiaormond.ribeiro.de.campos@hotmail.com', 'celesiaormond.ribeiro.de.campos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ALICE APARECIDA DOS SANTOS', '2014-07-09', '2014-02-02', 1, 0, 'alice.aparecida.dos.santos@gmail.com', 'alice.aparecida.dos.santos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('RITA IRACI ALMEIDA DA SILVA', '2014-07-12', '2014-01-04', 1, 0, 'rita.iraci.almeida.da.silva@gmail.com', 'rita.iraci.almeida.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('NEIZA MARIA LEITE DA SILVA', '2014-07-11', '2014-02-15', 0, 1, 'neiza.maria.leite.da.silva@gmail.com', 'neiza.maria.leite.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('DIRCEU DE MATTOS', '2014-07-06', '2014-01-14', 1, 1, 'dirceu.de.mattos@hotmail.com', 'dirceu.de.mattos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('RONY HUDSON OLIVEIRA CANDEIRO', '2014-07-06', '2014-05-01', 1, 0, 'rony.hudson.oliveira.candeiro@gmail.com', 'rony.hudson.oliveira.candeiro');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ATAIDE DIAS DE MOURA', '2014-07-07', '2014-01-02', 0, 1, 'ataide.dias.de.moura@fb.com', 'ataide.dias.de.moura');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JORGE TETSUO TAIRA', '2014-07-05', '2014-01-10', 0, 1, 'jorge.tetsuo.taira@gmail.com', 'jorge.tetsuo.taira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('EUSTAQUIA PRIETO', '2014-07-07', '2014-04-09', 0, 0, 'eustaquia.prieto@gmail.com', 'eustaquia.prieto');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LUIZ LOPES DA SILVA', '2014-07-02', '2014-03-12', 0, 1, 'luiz.lopes.da.silva@gmail.com', 'luiz.lopes.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('EUSTAQUIA PRIETO', '2014-07-05', '2014-02-01', 0, 1, 'eustaquia.prieto@gmail.com', 'eustaquia.prieto');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JOAO DE LUCA', '2014-07-05', '2014-03-09', 1, 0, 'joao.de.luca@hotmail.com', 'joao.de.luca');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JOAQUIM BORGES RODRIGUES', '2014-07-08', '2014-02-08', 1, 1, 'joaquim.borges.rodrigues@gmail.com', 'joaquim.borges.rodrigues');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('HABIB FAHED', '2014-07-07', '2014-01-04', 0, 1, 'habib.fahed@gmail.com', 'habib.fahed');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARIA DO CARMO JERONIMO SILVA', '2014-07-02', '2014-04-03', 1, 0, 'maria.do.carmo.jeronimo.silva@gmail.com', 'maria.do.carmo.jeronimo.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ILZA XAVIER DE LIMA ARAUJO', '2014-07-06', '2014-04-18', 0, 0, 'ilza.xavier.de.lima.araujo@hotmail.com', 'ilza.xavier.de.lima.araujo');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('INES APARECIDA DA SILVA', '2014-07-10', '2014-05-10', 0, 0, 'ines.aparecida.da.silva@hotmail.com', 'ines.aparecida.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ANDRE LUIS CASTRILLON GARCIA', '2014-07-08', '2014-05-27', 0, 1, 'andre.luis.castrillon.garcia@gmail.com', 'andre.luis.castrillon.garcia');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ABIGAIL DA SILVA LARA', '2014-07-05', '2014-04-07', 1, 1, 'abigail.da.silva.lara@hotmail.com', 'abigail.da.silva.lara');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ALICE DE SOUZA MIRANDA', '2014-07-10', '2014-06-07', 0, 0, 'alice.de.souza.miranda@gmail.com', 'alice.de.souza.miranda');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JOAO DE LUCA', '2014-07-01', '2014-06-25', 1, 1, 'joao.de.luca@gmail.com', 'joao.de.luca');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('BENILDE PERES DE CAMPOS', '2014-07-06', '2014-03-31', 1, 1, 'benilde.peres.de.campos@gmail.com', 'benilde.peres.de.campos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('HELOIZA ALMEIDA DOS SANTOS', '2014-07-11', '2014-05-12', 1, 0, 'heloiza.almeida.dos.santos@gmail.com', 'heloiza.almeida.dos.santos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ALICE DE SOUZA MIRANDA', '2014-07-01', '2014-05-15', 0, 1, 'alice.de.souza.miranda@gmail.com', 'alice.de.souza.miranda');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('EDIO JUSTO BORGES', '2014-07-05', '2014-04-12', 1, 0, 'edio.justo.borges@fb.com', 'edio.justo.borges');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ILZA XAVIER DE LIMA ARAUJO', '2014-07-01', '2014-02-24', 0, 0, 'ilza.xavier.de.lima.araujo@hotmail.com', 'ilza.xavier.de.lima.araujo');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('WANDERSON COSMO DE ARAUJO', '2014-07-13', '2014-01-01', 0, 0, 'wanderson.cosmo.de.araujo@gmail.com', 'wanderson.cosmo.de.araujo');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ANA PAULA FIGUEIREDO DA ROCHA', '2014-07-02', '2014-03-30', 1, 1, 'ana.paula.figueiredo.da.rocha@fb.com', 'ana.paula.figueiredo.da.rocha');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('TIMOTEO BATISTA LEITE', '2014-07-07', '2014-01-12', 1, 0, 'timoteo.batista.leite@fb.com', 'timoteo.batista.leite');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('DIAMANTINA DA SILVA SOARES', '2014-07-07', '2014-03-12', 1, 0, 'diamantina.da.silva.soares@gmail.com', 'diamantina.da.silva.soares');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ATAIDE DIAS DE MOURA', '2014-07-12', '2014-06-02', 1, 0, 'ataide.dias.de.moura@gmail.com', 'ataide.dias.de.moura');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('IROCIDES APARECIDA FERREIRA', '2014-07-06', '2014-03-02', 0, 0, 'irocides.aparecida.ferreira@fb.com', 'irocides.aparecida.ferreira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('RITA IRACI ALMEIDA DA SILVA', '2014-07-09', '2014-02-27', 0, 0, 'rita.iraci.almeida.da.silva@hotmail.com', 'rita.iraci.almeida.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARIA ALVES SUTIL', '2014-07-11', '2014-06-12', 0, 0, 'maria.alves.sutil@gmail.com', 'maria.alves.sutil');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ELZA LIMA DE SOUZA MANSANO', '2014-07-06', '2014-01-01', 0, 0, 'elza.lima.de.souza.mansano@fb.com', 'elza.lima.de.souza.mansano');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MIGUEL JOAQUIM SILVA', '2014-07-09', '2014-04-19', 0, 1, 'miguel.joaquim.silva@fb.com', 'miguel.joaquim.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('CRISTIANE PAES CORDOBA', '2014-07-12', '2014-05-23', 0, 1, 'cristiane.paes.cordoba@fb.com', 'cristiane.paes.cordoba');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('RUZINO ANTUNES DA SILVA', '2014-07-02', '2014-01-02', 1, 0, 'ruzino.antunes.da.silva@fb.com', 'ruzino.antunes.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ROSILENE ALMEIDA DA SILVA', '2014-07-05', '2014-06-15', 1, 0, 'rosilene.almeida.da.silva@hotmail.com', 'rosilene.almeida.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('NICANOR FELIZARDO DOS REIS', '2014-07-01', '2014-06-01', 1, 0, 'nicanor.felizardo.dos.reis@gmail.com', 'nicanor.felizardo.dos.reis');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARILEIA NUNES DE OLIVEIRA', '2014-07-11', '2014-02-20', 1, 1, 'marileia.nunes.de.oliveira@gmail.com', 'marileia.nunes.de.oliveira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ALDEIR ALEX ALVES LIMA', '2014-07-08', '2014-05-26', 1, 1, 'aldeir.alex.alves.lima@hotmail.com', 'aldeir.alex.alves.lima');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ALICE FERNANDES DE OLIVEIRA', '2014-07-08', '2014-03-19', 0, 0, 'alice.fernandes.de.oliveira@gmail.com', 'alice.fernandes.de.oliveira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ELZA LIMA DE SOUZA MANSANO', '2014-07-11', '2014-06-01', 1, 1, 'elza.lima.de.souza.mansano@gmail.com', 'elza.lima.de.souza.mansano');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ALDIVINA REIS FERNANDES', '2014-07-09', '2014-03-05', 1, 0, 'aldivina.reis.fernandes@fb.com', 'aldivina.reis.fernandes');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ABIGAIL DA SILVA LARA', '2014-07-06', '2014-02-27', 1, 1, 'abigail.da.silva.lara@gmail.com', 'abigail.da.silva.lara');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('NEIVA OBERGER FERREIRA', '2014-07-03', '2014-01-06', 1, 1, 'neiva.oberger.ferreira@gmail.com', 'neiva.oberger.ferreira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARIA FATIMA SCHEUNEMANN MIRANDA', '2014-07-03', '2014-04-20', 0, 0, 'maria.fatima.scheunemann.miranda@hotmail.com', 'maria.fatima.scheunemann.miranda');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('AURELINDA BATISTA DA SILVA', '2014-07-01', '2014-04-12', 1, 1, 'aurelinda.batista.da.silva@hotmail.com', 'aurelinda.batista.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('VIRGILIA DIAS VIEIRA', '2014-07-13', '2014-02-07', 0, 1, 'virgilia.dias.vieira@gmail.com', 'virgilia.dias.vieira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LAURO JOSE DA SILVA', '2014-07-11', '2014-01-15', 0, 1, 'lauro.jose.da.silva@fb.com', 'lauro.jose.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ANTONIA BORGES DA SILVA', '2014-07-03', '2014-02-09', 0, 0, 'antonia.borges.da.silva@hotmail.com', 'antonia.borges.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ELEONILDA DE LIMA RODRIGUES', '2014-07-12', '2014-01-12', 1, 0, 'eleonilda.de.lima.rodrigues@fb.com', 'eleonilda.de.lima.rodrigues');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ALCEU DOS SANTOS', '2014-07-08', '2014-06-12', 0, 0, 'alceu.dos.santos@fb.com', 'alceu.dos.santos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARCONI GEORGE RIBEIRO DA SILVA', '2014-07-02', '2014-03-15', 0, 0, 'marconi.george.ribeiro.da.silva@gmail.com', 'marconi.george.ribeiro.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ANA ALVES LUCIANO', '2014-07-12', '2014-01-07', 1, 0, 'ana.alves.luciano@fb.com', 'ana.alves.luciano');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('BENEDITA GAUDENCIO DA COSTA', '2014-07-08', '2014-05-13', 1, 1, 'benedita.gaudencio.da.costa@gmail.com', 'benedita.gaudencio.da.costa');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LOURENCO DIAS', '2014-07-06', '2014-04-14', 1, 0, 'lourenco.dias@gmail.com', 'lourenco.dias');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ROSILENE ALMEIDA DA SILVA', '2014-07-12', '2014-02-23', 0, 0, 'rosilene.almeida.da.silva@hotmail.com', 'rosilene.almeida.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('HELOIZA ALMEIDA DOS SANTOS', '2014-07-02', '2014-01-11', 0, 1, 'heloiza.almeida.dos.santos@hotmail.com', 'heloiza.almeida.dos.santos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARIA TEREZINHA ROCHA DE SOUZA', '2014-07-01', '2014-05-09', 0, 0, 'maria.terezinha.rocha.de.souza@fb.com', 'maria.terezinha.rocha.de.souza');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARCONI GEORGE RIBEIRO DA SILVA', '2014-07-01', '2014-02-23', 0, 0, 'marconi.george.ribeiro.da.silva@hotmail.com', 'marconi.george.ribeiro.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('RONY HUDSON OLIVEIRA CANDEIRO', '2014-07-04', '2014-03-19', 1, 0, 'rony.hudson.oliveira.candeiro@fb.com', 'rony.hudson.oliveira.candeiro');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('BENEDITA GAUDENCIO DA COSTA', '2014-07-10', '2014-05-20', 1, 0, 'benedita.gaudencio.da.costa@hotmail.com', 'benedita.gaudencio.da.costa');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('DELCY MARTINS DA SILVA', '2014-07-09', '2014-06-29', 1, 1, 'delcy.martins.da.silva@fb.com', 'delcy.martins.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MIGUEL JOAQUIM SILVA', '2014-07-03', '2014-02-17', 1, 1, 'miguel.joaquim.silva@hotmail.com', 'miguel.joaquim.silva');
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-04', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-04', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-19', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-24', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-25', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-01', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-26', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-18', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-23', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-04', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-11', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-07', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-29', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-24', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-20', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-09', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-29', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-31', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-16', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-07', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-08', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-25', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-09', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-23', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-24', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-08', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-03', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-17', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-03', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-04', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-06', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-07', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-07', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-19', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-15', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-30', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-30', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-19', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-31', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-07-07', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-07', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-08', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-20', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-07', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-29', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-21', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-10', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-19', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-06', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-07-01', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-15', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-13', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-14', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-20', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-02', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-25', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-10', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-05', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-09', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-13', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-23', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-25', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-09', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-04', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-07', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-14', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-11', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-13', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-29', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-13', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-04', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-21', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-01', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-03', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-02', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-06', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-17', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-07-11', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-26', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-02', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-17', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-07-10', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-14', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-25', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-04', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-07-13', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-01', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-19', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-15', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-07-08', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-27', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-18', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-10', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-26', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-03', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-17', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-09', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-10', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-26', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-14', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
