INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('26722-773', '6657', 'M', 'EDIR DIAS DE CARVALHO', '2014-01-17', 1, 'Korea North', 'edir.dias.de.carvalho@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('91740-826', '9661', 'F', 'OLGA PEREIRA', '2014-07-19', 1, 'Guatemala', 'olga.pereira@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('75510-964', '5274', 'F', 'EDIO JUSTO BORGES', '2014-11-07', 0, 'Tonga', 'edio.justo.borges@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('47180-959', '5172', 'F', 'AURELINDA BATISTA DA SILVA', '2014-06-02', 1, 'Korea North', 'aurelinda.batista.da.silva@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('60601-448', '8546', 'F', 'NADIACUIABANO KUNZE', '2014-02-25', 0, 'Sweden', 'nadiacuiabano.kunze@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('23372-805', '8566', 'F', 'DILMA DE SOUZA', '2014-08-29', 0, 'Sudan', 'dilma.de.souza@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('21981-480', '7550', 'F', 'EDIR DIAS DE CARVALHO', '2014-06-09', 0, 'Cyprus', 'edir.dias.de.carvalho@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('71548-261', '4487', 'M', 'AMERICO FRANCISCO DA SILVA', '2014-02-01', 0, 'Ethiopia', 'americo.francisco.da.silva@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('78389-529', '9853', 'F', 'BENEDITO AMBROSIO DA COSTA', '2014-12-21', 0, 'Croatia', 'benedito.ambrosio.da.costa@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('73035-067', '0643', 'M', 'BEATRIZ PEREIRA LIMA', '2014-01-20', 1, 'Bosnia & Herzegovina', 'beatriz.pereira.lima@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('74660-708', '9807', 'M', 'QUITERIA LOURENCO DE LIMA', '2014-10-01', 0, 'Tunisia', 'quiteria.lourenco.de.lima@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('01838-456', '8831', 'F', 'ANDRE LUIS CASTRILLON GARCIA', '2014-07-31', 0, 'South Sudan', 'andre.luis.castrillon.garcia@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('56848-270', '8151', 'F', 'AMERICO FRANCISCO DA SILVA', '2014-08-20', 1, 'Seychelles', 'americo.francisco.da.silva@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('71384-499', '1056', 'M', 'LUCINEIDE DE MORAES DO CARMO', '2014-06-13', 1, 'Comoros', 'lucineide.de.moraes.do.carmo@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('71174-739', '0304', 'F', 'WANDERSON COSMO DE ARAUJO', '2014-05-20', 0, 'Luxembourg', 'wanderson.cosmo.de.araujo@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('59467-982', '8609', 'M', 'CLEUSA FERREIRA MACIEL', '2014-03-15', 0, 'Peru', 'cleusa.ferreira.maciel@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('18868-255', '4001', 'M', 'JOSE NUNES PEREIRA', '2014-11-28', 1, 'Korea South', 'jose.nunes.pereira@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('78443-287', '0889', 'F', 'MARIA DE LOURDES FERNANDES DIAS', '2014-06-14', 0, 'Papua New Guinea', 'maria.de.lourdes.fernandes.dias@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('34615-255', '2048', 'F', 'TIMOTEO BATISTA LEITE', '2014-05-06', 0, 'St. Kitts & Nevis', 'timoteo.batista.leite@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('73567-595', '0344', 'M', 'RITA IRACI ALMEIDA DA SILVA', '2014-07-04', 0, 'Bahamas', 'rita.iraci.almeida.da.silva@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('09658-387', '7842', 'M', 'BENEDITA GAUDENCIO DA COSTA', '2014-11-04', 1, 'New Zealand', 'benedita.gaudencio.da.costa@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('79141-174', '0864', 'M', 'ALDIVINA REIS FERNANDES', '2014-11-18', 1, 'Barbados', 'aldivina.reis.fernandes@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('66358-169', '6961', 'M', 'LAURA SEBASTIANA GURGEL', '2014-12-09', 1, 'Comoros', 'laura.sebastiana.gurgel@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('82553-658', '8195', 'M', 'SONIA MARIA MARTINEZ PENITENTE', '2014-03-08', 0, 'Kuwait', 'sonia.maria.martinez.penitente@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('37145-614', '5694', 'M', 'MARIA FATIMA SCHEUNEMANN MIRANDA', '2014-01-25', 0, 'Egypt', 'maria.fatima.scheunemann.miranda@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('21565-020', '3321', 'F', 'NEIVA OBERGER FERREIRA', '2014-11-05', 0, 'Vietnam', 'neiva.oberger.ferreira@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('41469-120', '5318', 'F', 'ANDRE LUIS CASTRILLON GARCIA', '2014-11-17', 1, 'Switzerland', 'andre.luis.castrillon.garcia@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('01251-616', '5641', 'F', 'ANGELA APARECIDA BERNEGOZZE', '2014-12-29', 0, 'Togo', 'angela.aparecida.bernegozze@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('92764-347', '3289', 'M', 'PAULO TEIXEIRA DE ABREU', '2014-12-02', 1, 'Iran', 'paulo.teixeira.de.abreu@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('19512-460', '9642', 'F', 'SEBASTIANA BENEDITA DA COSTA', '2014-07-26', 1, 'Cuba', 'sebastiana.benedita.da.costa@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('49771-649', '9229', 'F', 'ADENILTON JOSE DE MIRANDA', '2014-04-05', 0, 'Congo Democratic Republic', 'adenilton.jose.de.miranda@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('90616-642', '3742', 'F', 'ZILDA MARTINS DE SOUZA', '2014-01-06', 0, 'East Timor', 'zilda.martins.de.souza@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('46313-151', '3116', 'F', 'SOLANGE APARECIDA DO PRADO DA CRUZ', '2014-07-10', 1, 'Burundi', 'solange.aparecida.do.prado.da.cruz@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('68080-245', '8673', 'M', 'DIRCEU DE MATTOS', '2014-12-16', 1, 'Vanuatu', 'dirceu.de.mattos@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('17148-101', '9649', 'M', 'CORNELIO DIAS DUARTE', '2014-03-22', 1, 'Switzerland', 'cornelio.dias.duarte@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('79285-772', '5196', 'M', 'DORILDA ALVES DE CARVALHO', '2014-09-10', 0, 'United States of America', 'dorilda.alves.de.carvalho@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('08810-217', '0003', 'F', 'LUIZ FERNANDO DA SILVA AMORIM', '2014-08-30', 0, 'Botswana', 'luiz.fernando.da.silva.amorim@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('56218-480', '2784', 'M', 'MARCONI GEORGE RIBEIRO DA SILVA', '2014-05-28', 1, 'Zambia', 'marconi.george.ribeiro.da.silva@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('20764-469', '6081', 'M', 'RENIRA RODRIGUES DA SILVA DE SOUSA', '2014-06-07', 1, 'Canada', 'renira.rodrigues.da.silva.de.sousa@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('58457-699', '7682', 'M', 'MARCONI GEORGE RIBEIRO DA SILVA', '2014-04-06', 1, 'Qatar', 'marconi.george.ribeiro.da.silva@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('19966-976', '6234', 'M', 'EUSTAQUIA PRIETO', '2014-04-22', 0, 'Taiwan', 'eustaquia.prieto@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('46354-192', '4502', 'F', 'CRISTIANE PAES CORDOBA', '2014-04-14', 0, 'Zimbabwe', 'cristiane.paes.cordoba@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('87672-200', '9503', 'M', 'MARIA DE LOURDES FERNANDES DIAS', '2014-04-16', 0, 'Sweden', 'maria.de.lourdes.fernandes.dias@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('27783-578', '1836', 'F', 'CLEODETE CANOLA DE CAMPOS', '2014-04-08', 0, 'Luxembourg', 'cleodete.canola.de.campos@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('74146-692', '0132', 'F', 'CELIA CRISTINA PEREIRA PINTO DOS SANTOS', '2014-09-12', 1, 'Canada', 'celia.cristina.pereira.pinto.dos.santos@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('13047-291', '8113', 'F', 'ALIETE FRANCISCA PRATES', '2014-09-19', 0, 'Vatican City (Holy See)', 'aliete.francisca.prates@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('71757-193', '7965', 'F', 'FRANCISCA MARIA SILVA COSTA', '2014-05-27', 1, 'Indonesia', 'francisca.maria.silva.costa@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('69910-164', '4280', 'F', 'PAULO TEIXEIRA DE ABREU', '2014-07-01', 0, 'Canada', 'paulo.teixeira.de.abreu@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('10754-730', '4537', 'F', 'RAMIRO VEDOVATO', '2014-12-24', 1, 'Liberia', 'ramiro.vedovato@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('87485-674', '8068', 'F', 'RUZINO ANTUNES DA SILVA', '2014-05-09', 1, 'Switzerland', 'ruzino.antunes.da.silva@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('63783-539', '0477', 'F', 'JOAO DE LUCA', '2014-05-18', 1, 'United States of America', 'joao.de.luca@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('15627-761', '5589', 'F', 'JOSENOTARIO MUNGO', '2014-11-07', 0, 'Dominica', 'josenotario.mungo@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('88835-373', '6967', 'M', 'MARIA DO CARMO JERONIMO SILVA', '2014-04-08', 0, 'Rwanda', 'maria.do.carmo.jeronimo.silva@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('50078-870', '5082', 'F', 'PAULO TEIXEIRA DE ABREU', '2014-10-03', 1, 'Latvia', 'paulo.teixeira.de.abreu@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('95474-256', '9565', 'F', 'VIOLINDO DE SOUZA', '2014-06-27', 0, 'Botswana', 'violindo.de.souza@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('49777-056', '8049', 'F', 'SONIA MARIA MARTINEZ PENITENTE', '2014-01-20', 1, 'Gambia', 'sonia.maria.martinez.penitente@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('93566-065', '7835', 'F', 'ALICE DE SOUZA MIRANDA', '2014-02-18', 1, 'Turkmenistan', 'alice.de.souza.miranda@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('67975-579', '3959', 'F', 'BENILDE PERES DE CAMPOS', '2014-07-26', 1, 'Gambia', 'benilde.peres.de.campos@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('43100-384', '9749', 'M', 'NEIZA MARIA LEITE DA SILVA', '2014-11-19', 1, 'Japan', 'neiza.maria.leite.da.silva@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('96281-768', '1175', 'M', 'ANTONIA BORGES DA SILVA', '2014-02-09', 0, 'Lesotho', 'antonia.borges.da.silva@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('16150-624', '2541', 'M', 'OBADIAS MARCAL DE OLIVEIRA', '2014-05-23', 1, 'Belize', 'obadias.marcal.de.oliveira@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('57349-815', '8187', 'M', 'ALCEU DOS SANTOS', '2014-09-15', 1, 'Cuba', 'alceu.dos.santos@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('74618-163', '8941', 'M', 'MARCONI GEORGE RIBEIRO DA SILVA', '2014-11-12', 1, 'Kenya', 'marconi.george.ribeiro.da.silva@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('13063-761', '1195', 'M', 'ABILIO CAVALHEIRO', '2014-12-17', 1, 'China', 'abilio.cavalheiro@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('14211-417', '1067', 'M', 'ALDIVINA REIS FERNANDES', '2014-11-01', 1, 'The Netherlands', 'aldivina.reis.fernandes@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('58792-755', '5450', 'F', 'DAVINA PEREIRA DE SALES', '2014-10-20', 1, 'Poland', 'davina.pereira.de.sales@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('07492-880', '7663', 'F', 'ELOIDE CAVANHA', '2014-08-26', 0, 'France', 'eloide.cavanha@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('21168-983', '9711', 'M', 'RAMAO CARDOSO', '2014-03-24', 1, 'Afghanistan', 'ramao.cardoso@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('97924-693', '8559', 'M', 'JOSE RIBAMAR BEZERRA SA', '2014-09-15', 1, 'Uruguay', 'jose.ribamar.bezerra.sa@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('12228-393', '9844', 'M', 'QUITERIA LOURENCO DE LIMA', '2014-09-05', 1, 'Sao Tome & Principe', 'quiteria.lourenco.de.lima@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('65979-201', '9233', 'M', 'CRISTIANE PAES CORDOBA', '2014-03-19', 0, 'Monaco', 'cristiane.paes.cordoba@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('27700-545', '6135', 'M', 'CRISTIANE PAES CORDOBA', '2014-02-10', 1, 'Tonga', 'cristiane.paes.cordoba@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('06964-482', '8764', 'M', 'SONIA MARIA MARTINEZ PENITENTE', '2014-05-06', 1, 'Mauritania', 'sonia.maria.martinez.penitente@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('49814-995', '9252', 'M', 'CRISTIANE PAES CORDOBA', '2014-10-23', 1, 'Swaziland', 'cristiane.paes.cordoba@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('95308-709', '8891', 'F', 'DORILDA ALVES DE CARVALHO', '2014-09-15', 1, 'Barbados', 'dorilda.alves.de.carvalho@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('95168-118', '6599', 'M', 'MARIA TEREZINHA ROCHA DE SOUZA', '2014-02-16', 1, 'Norway', 'maria.terezinha.rocha.de.souza@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('62998-398', '0067', 'M', 'NICANOR FELIZARDO DOS REIS', '2014-12-13', 0, 'Myanmar (Burma)', 'nicanor.felizardo.dos.reis@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('39620-409', '5170', 'F', 'MARIA ELENA ALVES', '2014-12-02', 1, 'Djibouti', 'maria.elena.alves@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('46127-715', '2179', 'F', 'BENJAMIM GAUNA', '2014-06-04', 0, 'Iran', 'benjamim.gauna@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('76571-158', '8185', 'M', 'ALDIVINA REIS FERNANDES', '2014-07-03', 0, 'Uzbekistan', 'aldivina.reis.fernandes@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('20077-013', '5873', 'M', 'MARIA ELENA ALVES', '2014-08-09', 1, 'St. Vincent & The Grenadines', 'maria.elena.alves@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('19676-466', '9875', 'M', 'GLAUBER DA COSTA ARRUDA', '2014-12-01', 0, 'China', 'glauber.da.costa.arruda@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('84609-086', '1633', 'F', 'ADENILTON JOSE DE MIRANDA', '2014-12-12', 1, 'Swaziland', 'adenilton.jose.de.miranda@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('94140-678', '2050', 'M', 'LAURA SEBASTIANA GURGEL', '2014-04-06', 1, 'Benin', 'laura.sebastiana.gurgel@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('27021-879', '5782', 'M', 'LUIZ FERNANDO DA SILVA AMORIM', '2014-06-08', 0, 'Norway', 'luiz.fernando.da.silva.amorim@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('75739-990', '4577', 'M', 'MIGUEL VENCESLAU MACIEL DE CAMPOS', '2014-10-28', 0, 'Fiji', 'miguel.venceslau.maciel.de.campos@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('59250-979', '8790', 'M', 'EUSTAQUIA PRIETO', '2014-03-05', 0, 'Kuwait', 'eustaquia.prieto@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('31784-288', '3527', 'F', 'CRISTIANE PAES CORDOBA', '2014-02-26', 0, 'Liechtenstein', 'cristiane.paes.cordoba@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('10922-245', '8712', 'M', 'JOSE RIBAMAR BEZERRA SA', '2014-12-12', 1, 'Argentina', 'jose.ribamar.bezerra.sa@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('48280-833', '8034', 'F', 'BENILDE PERES DE CAMPOS', '2014-11-25', 1, 'Nigeria', 'benilde.peres.de.campos@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('04367-372', '3814', 'M', 'ROBSON LUIZ DO NASCIMENTO PUERTAS', '2014-02-06', 1, 'Venezuela', 'robson.luiz.do.nascimento.puertas@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('34074-960', '3930', 'F', 'ROSIMEIRE GONCALVES LOPES RAMOS', '2014-02-02', 1, 'Russia', 'rosimeire.goncalves.lopes.ramos@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('98602-196', '2294', 'F', 'OBADIAS MARCAL DE OLIVEIRA', '2014-10-16', 0, 'Jordan', 'obadias.marcal.de.oliveira@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('63232-494', '6054', 'F', 'ADELSON LUIZ DA SILVA', '2014-10-29', 0, 'Micronesia', 'adelson.luiz.da.silva@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('69043-138', '4468', 'F', 'JOSE JESUS DA HORA', '2014-02-03', 1, 'Iceland', 'jose.jesus.da.hora@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('16492-182', '5220', 'F', 'DIEGO CESPEDES DE SOUZA', '2014-09-29', 1, 'India', 'diego.cespedes.de.souza@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('09413-215', '9114', 'F', 'EUZEBIO DA SILVA CEZAR', '2014-10-25', 1, 'South Sudan', 'euzebio.da.silva.cezar@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('26198-161', '5788', 'M', 'DAVINA PEREIRA DE SALES', '2014-10-16', 1, 'Belize', 'davina.pereira.de.sales@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('16170-920', '2873', 'M', 'VIOLINDO DE SOUZA', '2014-11-28', 1, 'Palestinian State', 'violindo.de.souza@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('22725-105', '3372', 'F', 'RONY HUDSON OLIVEIRA CANDEIRO', '2014-07-17', 1, 'Suriname', 'rony.hudson.oliveira.candeiro@yahoo.com');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARCIA DA SILVA OLIVEIRA', '2014-07-05', '2014-02-04', 1, 1, 'marcia.da.silva.oliveira@fb.com', 'marcia.da.silva.oliveira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('OSVALDO PEREIRA BARBOSA', '2014-07-09', '2014-06-26', 0, 0, 'osvaldo.pereira.barbosa@gmail.com', 'osvaldo.pereira.barbosa');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('BENILDE PERES DE CAMPOS', '2014-07-07', '2014-01-17', 0, 0, 'benilde.peres.de.campos@hotmail.com', 'benilde.peres.de.campos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('WILSON CONCEICAO DE MIRANDA', '2014-07-04', '2014-06-10', 0, 0, 'wilson.conceicao.de.miranda@fb.com', 'wilson.conceicao.de.miranda');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JOSE RIBAMAR BEZERRA SA', '2014-07-03', '2014-04-15', 0, 0, 'jose.ribamar.bezerra.sa@fb.com', 'jose.ribamar.bezerra.sa');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LAURA SEBASTIANA GURGEL', '2014-07-11', '2014-03-13', 1, 0, 'laura.sebastiana.gurgel@hotmail.com', 'laura.sebastiana.gurgel');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('DELCY MARTINS DA SILVA', '2014-07-05', '2014-06-27', 0, 1, 'delcy.martins.da.silva@gmail.com', 'delcy.martins.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('EUSTAQUIA PRIETO', '2014-07-13', '2014-03-10', 0, 0, 'eustaquia.prieto@hotmail.com', 'eustaquia.prieto');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ANTONIO INACIO RODRIGUES', '2014-07-13', '2014-02-10', 1, 1, 'antonio.inacio.rodrigues@hotmail.com', 'antonio.inacio.rodrigues');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ARISMARES SOUZA PRATES', '2014-07-05', '2014-04-24', 1, 0, 'arismares.souza.prates@fb.com', 'arismares.souza.prates');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JUEL PRUDENCIO BORGES', '2014-07-04', '2014-03-01', 1, 0, 'juel.prudencio.borges@hotmail.com', 'juel.prudencio.borges');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('AURELINDA BATISTA DA SILVA', '2014-07-01', '2014-02-11', 0, 1, 'aurelinda.batista.da.silva@gmail.com', 'aurelinda.batista.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('SOLANGE APARECIDA DO PRADO DA CRUZ', '2014-07-12', '2014-02-16', 0, 0, 'solange.aparecida.do.prado.da.cruz@gmail.com', 'solange.aparecida.do.prado.da.cruz');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('INES APARECIDA DA SILVA', '2014-07-10', '2014-01-22', 0, 1, 'ines.aparecida.da.silva@hotmail.com', 'ines.aparecida.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('SILVIO TSIPE RAIRATE', '2014-07-07', '2014-03-14', 1, 1, 'silvio.tsipe.rairate@hotmail.com', 'silvio.tsipe.rairate');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LAURO JOSE DA SILVA', '2014-07-13', '2014-04-11', 1, 1, 'lauro.jose.da.silva@gmail.com', 'lauro.jose.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JOSE NUNES PEREIRA', '2014-07-09', '2014-03-27', 0, 1, 'jose.nunes.pereira@gmail.com', 'jose.nunes.pereira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ELZA LIMA DE SOUZA MANSANO', '2014-07-04', '2014-02-17', 0, 0, 'elza.lima.de.souza.mansano@hotmail.com', 'elza.lima.de.souza.mansano');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARLENE SANTANA MARTINS', '2014-07-01', '2014-03-05', 0, 0, 'marlene.santana.martins@fb.com', 'marlene.santana.martins');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('NEIZA MARIA LEITE DA SILVA', '2014-07-03', '2014-06-19', 1, 0, 'neiza.maria.leite.da.silva@hotmail.com', 'neiza.maria.leite.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ADENILTON JOSE DE MIRANDA', '2014-07-08', '2014-05-14', 0, 1, 'adenilton.jose.de.miranda@gmail.com', 'adenilton.jose.de.miranda');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('DAVINA PEREIRA DE SALES', '2014-07-06', '2014-05-03', 0, 1, 'davina.pereira.de.sales@hotmail.com', 'davina.pereira.de.sales');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LUIZA ROTTLISBERGER SILVA', '2014-07-04', '2014-02-20', 1, 0, 'luiza.rottlisberger.silva@fb.com', 'luiza.rottlisberger.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LIDIANE DO PRADO BRITE', '2014-07-04', '2014-06-26', 1, 1, 'lidiane.do.prado.brite@fb.com', 'lidiane.do.prado.brite');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LAURO JOSE DA SILVA', '2014-07-08', '2014-06-23', 0, 0, 'lauro.jose.da.silva@hotmail.com', 'lauro.jose.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('QUITERIA LOURENCO DE LIMA', '2014-07-12', '2014-01-16', 0, 1, 'quiteria.lourenco.de.lima@fb.com', 'quiteria.lourenco.de.lima');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARIA HILDA MACHADO', '2014-07-01', '2014-06-07', 1, 0, 'maria.hilda.machado@hotmail.com', 'maria.hilda.machado');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ANTONIA BORGES DA SILVA', '2014-07-02', '2014-03-28', 1, 0, 'antonia.borges.da.silva@hotmail.com', 'antonia.borges.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('NADIACUIABANO KUNZE', '2014-07-08', '2014-03-18', 0, 1, 'nadiacuiabano.kunze@gmail.com', 'nadiacuiabano.kunze');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ANTONIO INACIO RODRIGUES', '2014-07-03', '2014-05-08', 1, 0, 'antonio.inacio.rodrigues@gmail.com', 'antonio.inacio.rodrigues');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('NEIVA OBERGER FERREIRA', '2014-07-05', '2014-01-20', 1, 0, 'neiva.oberger.ferreira@gmail.com', 'neiva.oberger.ferreira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LOURENCO DIAS', '2014-07-12', '2014-01-20', 1, 0, 'lourenco.dias@hotmail.com', 'lourenco.dias');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('CRISTIANE PAES CORDOBA', '2014-07-13', '2014-02-20', 0, 1, 'cristiane.paes.cordoba@hotmail.com', 'cristiane.paes.cordoba');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LAURO JOSE DA SILVA', '2014-07-13', '2014-05-07', 0, 0, 'lauro.jose.da.silva@fb.com', 'lauro.jose.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JOSE JESUS DA HORA', '2014-07-03', '2014-02-12', 0, 1, 'jose.jesus.da.hora@hotmail.com', 'jose.jesus.da.hora');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('NEIVA OBERGER FERREIRA', '2014-07-11', '2014-06-09', 0, 0, 'neiva.oberger.ferreira@fb.com', 'neiva.oberger.ferreira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ALDIVINA REIS FERNANDES', '2014-07-09', '2014-04-30', 1, 1, 'aldivina.reis.fernandes@gmail.com', 'aldivina.reis.fernandes');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LOURIVAL ROSA GUIMARAES', '2014-07-02', '2014-06-15', 1, 1, 'lourival.rosa.guimaraes@gmail.com', 'lourival.rosa.guimaraes');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('CRISTIANE PAES CORDOBA', '2014-07-03', '2014-04-27', 1, 1, 'cristiane.paes.cordoba@fb.com', 'cristiane.paes.cordoba');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('RENIRA RODRIGUES DA SILVA DE SOUSA', '2014-07-02', '2014-03-25', 1, 0, 'renira.rodrigues.da.silva.de.sousa@hotmail.com', 'renira.rodrigues.da.silva.de.sousa');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('AURELINDA BATISTA DA SILVA', '2014-07-01', '2014-03-05', 1, 1, 'aurelinda.batista.da.silva@fb.com', 'aurelinda.batista.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('NEIZA MARIA LEITE DA SILVA', '2014-07-11', '2014-04-21', 1, 0, 'neiza.maria.leite.da.silva@hotmail.com', 'neiza.maria.leite.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ROSIMEIRE GONCALVES LOPES RAMOS', '2014-07-06', '2014-03-14', 1, 1, 'rosimeire.goncalves.lopes.ramos@gmail.com', 'rosimeire.goncalves.lopes.ramos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('CARLOS SERGIO URBANIN', '2014-07-10', '2014-03-02', 1, 0, 'carlos.sergio.urbanin@fb.com', 'carlos.sergio.urbanin');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LUZIA RODRIGUES DE OLIVEIRA', '2014-07-13', '2014-01-05', 1, 0, 'luzia.rodrigues.de.oliveira@fb.com', 'luzia.rodrigues.de.oliveira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LUIZA ROTTLISBERGER SILVA', '2014-07-09', '2014-02-19', 1, 1, 'luiza.rottlisberger.silva@gmail.com', 'luiza.rottlisberger.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('OSVALDO PEREIRA BARBOSA', '2014-07-01', '2014-04-24', 1, 0, 'osvaldo.pereira.barbosa@fb.com', 'osvaldo.pereira.barbosa');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MAGALI SANCHES', '2014-07-02', '2014-04-12', 0, 1, 'magali.sanches@fb.com', 'magali.sanches');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('SONIA MARIA MARTINEZ PENITENTE', '2014-07-10', '2014-04-02', 1, 1, 'sonia.maria.martinez.penitente@fb.com', 'sonia.maria.martinez.penitente');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JOAO DE LUCA', '2014-07-13', '2014-02-18', 1, 0, 'joao.de.luca@hotmail.com', 'joao.de.luca');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('EUSTAQUIA PRIETO', '2014-07-01', '2014-04-24', 0, 0, 'eustaquia.prieto@hotmail.com', 'eustaquia.prieto');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('VALDOMIRO LEITE DE SA', '2014-07-10', '2014-05-03', 1, 1, 'valdomiro.leite.de.sa@fb.com', 'valdomiro.leite.de.sa');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JOAO MAURILIO DA SILVA', '2014-07-03', '2014-04-07', 1, 0, 'joao.maurilio.da.silva@gmail.com', 'joao.maurilio.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('SONIA MARIA MARTINEZ PENITENTE', '2014-07-05', '2014-06-04', 0, 0, 'sonia.maria.martinez.penitente@hotmail.com', 'sonia.maria.martinez.penitente');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('EUSTAQUIA PRIETO', '2014-07-09', '2014-04-11', 0, 1, 'eustaquia.prieto@hotmail.com', 'eustaquia.prieto');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ADENILTON JOSE DE MIRANDA', '2014-07-12', '2014-03-17', 1, 1, 'adenilton.jose.de.miranda@hotmail.com', 'adenilton.jose.de.miranda');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ABIGAIL DA SILVA LARA', '2014-07-04', '2014-04-22', 0, 0, 'abigail.da.silva.lara@gmail.com', 'abigail.da.silva.lara');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('EUZEBIO DA SILVA CEZAR', '2014-07-07', '2014-01-20', 0, 0, 'euzebio.da.silva.cezar@hotmail.com', 'euzebio.da.silva.cezar');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ELISABETE ROMERO NOBRE LEAL', '2014-07-05', '2014-02-25', 0, 0, 'elisabete.romero.nobre.leal@gmail.com', 'elisabete.romero.nobre.leal');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ADAIL BANDINELLE DE MORAES', '2014-07-06', '2014-03-22', 0, 1, 'adail.bandinelle.de.moraes@gmail.com', 'adail.bandinelle.de.moraes');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ANA PAULA FIGUEIREDO DA ROCHA', '2014-07-11', '2014-02-23', 1, 0, 'ana.paula.figueiredo.da.rocha@fb.com', 'ana.paula.figueiredo.da.rocha');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('RONY HUDSON OLIVEIRA CANDEIRO', '2014-07-11', '2014-04-09', 1, 1, 'rony.hudson.oliveira.candeiro@hotmail.com', 'rony.hudson.oliveira.candeiro');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ELISABETE ROMERO NOBRE LEAL', '2014-07-02', '2014-03-29', 1, 1, 'elisabete.romero.nobre.leal@fb.com', 'elisabete.romero.nobre.leal');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('RENIRA RODRIGUES DA SILVA DE SOUSA', '2014-07-08', '2014-03-04', 0, 0, 'renira.rodrigues.da.silva.de.sousa@hotmail.com', 'renira.rodrigues.da.silva.de.sousa');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('AURELINDA BATISTA DA SILVA', '2014-07-02', '2014-04-07', 0, 0, 'aurelinda.batista.da.silva@hotmail.com', 'aurelinda.batista.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('SILVIO TSIPE RAIRATE', '2014-07-12', '2014-04-14', 0, 0, 'silvio.tsipe.rairate@fb.com', 'silvio.tsipe.rairate');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('IVANI DO NASCIMENTO VALENTIM', '2014-07-08', '2014-05-24', 1, 1, 'ivani.do.nascimento.valentim@gmail.com', 'ivani.do.nascimento.valentim');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('OSWALDIR GOMES', '2014-07-11', '2014-02-03', 1, 1, 'oswaldir.gomes@fb.com', 'oswaldir.gomes');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('RUBENSMORBECK LEITE', '2014-07-03', '2014-01-27', 0, 0, 'rubensmorbeck.leite@fb.com', 'rubensmorbeck.leite');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JOAO MAURILIO DA SILVA', '2014-07-12', '2014-01-07', 0, 0, 'joao.maurilio.da.silva@hotmail.com', 'joao.maurilio.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARIA HILDA MACHADO', '2014-07-07', '2014-04-15', 0, 0, 'maria.hilda.machado@hotmail.com', 'maria.hilda.machado');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ALBERTO FEIZAR CARDOSO ABDALA', '2014-07-01', '2014-06-19', 1, 0, 'alberto.feizar.cardoso.abdala@fb.com', 'alberto.feizar.cardoso.abdala');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ABIGAIL DA SILVA LARA', '2014-07-12', '2014-04-25', 1, 0, 'abigail.da.silva.lara@fb.com', 'abigail.da.silva.lara');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LOURENCO DIAS', '2014-07-09', '2014-05-27', 0, 1, 'lourenco.dias@fb.com', 'lourenco.dias');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ABILIO CAVALHEIRO', '2014-07-13', '2014-02-27', 1, 1, 'abilio.cavalheiro@fb.com', 'abilio.cavalheiro');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('VALDOMIRO LEITE DE SA', '2014-07-12', '2014-05-08', 0, 0, 'valdomiro.leite.de.sa@fb.com', 'valdomiro.leite.de.sa');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('NEIVA OBERGER FERREIRA', '2014-07-06', '2014-01-13', 0, 1, 'neiva.oberger.ferreira@fb.com', 'neiva.oberger.ferreira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('IROCIDES APARECIDA FERREIRA', '2014-07-13', '2014-03-05', 0, 1, 'irocides.aparecida.ferreira@fb.com', 'irocides.aparecida.ferreira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ALICE APARECIDA DOS SANTOS', '2014-07-02', '2014-04-15', 0, 0, 'alice.aparecida.dos.santos@fb.com', 'alice.aparecida.dos.santos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LUZIA RODRIGUES DE OLIVEIRA', '2014-07-12', '2014-01-21', 1, 1, 'luzia.rodrigues.de.oliveira@hotmail.com', 'luzia.rodrigues.de.oliveira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LOURENCO DIAS', '2014-07-05', '2014-02-03', 1, 1, 'lourenco.dias@gmail.com', 'lourenco.dias');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('RUBENSMORBECK LEITE', '2014-07-13', '2014-03-28', 1, 1, 'rubensmorbeck.leite@fb.com', 'rubensmorbeck.leite');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('VIRGILIA DIAS VIEIRA', '2014-07-06', '2014-05-17', 1, 1, 'virgilia.dias.vieira@fb.com', 'virgilia.dias.vieira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('VALDOMIRO LEITE DE SA', '2014-07-06', '2014-01-06', 0, 0, 'valdomiro.leite.de.sa@fb.com', 'valdomiro.leite.de.sa');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ELISABETE ROMERO NOBRE LEAL', '2014-07-08', '2014-05-03', 0, 0, 'elisabete.romero.nobre.leal@hotmail.com', 'elisabete.romero.nobre.leal');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ALICE FERNANDES DE OLIVEIRA', '2014-07-08', '2014-01-28', 0, 1, 'alice.fernandes.de.oliveira@gmail.com', 'alice.fernandes.de.oliveira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('CELIA CRISTINA PEREIRA PINTO DOS SANTOS', '2014-07-09', '2014-04-06', 1, 0, 'celia.cristina.pereira.pinto.dos.santos@gmail.com', 'celia.cristina.pereira.pinto.dos.santos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ANA PAULA FIGUEIREDO DA ROCHA', '2014-07-13', '2014-03-29', 0, 1, 'ana.paula.figueiredo.da.rocha@fb.com', 'ana.paula.figueiredo.da.rocha');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('RENIRA RODRIGUES DA SILVA DE SOUSA', '2014-07-01', '2014-06-04', 0, 0, 'renira.rodrigues.da.silva.de.sousa@gmail.com', 'renira.rodrigues.da.silva.de.sousa');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ZILDA MARTINS DE SOUZA', '2014-07-04', '2014-04-14', 0, 0, 'zilda.martins.de.souza@gmail.com', 'zilda.martins.de.souza');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('RAMAO CARDOSO', '2014-07-06', '2014-05-26', 0, 1, 'ramao.cardoso@fb.com', 'ramao.cardoso');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ZILMA MARQUES GONCALVES RODRIGUES', '2014-07-12', '2014-06-04', 0, 0, 'zilma.marques.goncalves.rodrigues@hotmail.com', 'zilma.marques.goncalves.rodrigues');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('CLEUSA FERREIRA MACIEL', '2014-07-01', '2014-02-14', 1, 1, 'cleusa.ferreira.maciel@gmail.com', 'cleusa.ferreira.maciel');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('CARLOS SERGIO URBANIN', '2014-07-06', '2014-03-13', 0, 0, 'carlos.sergio.urbanin@hotmail.com', 'carlos.sergio.urbanin');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MIGUEL VENCESLAU MACIEL DE CAMPOS', '2014-07-03', '2014-05-03', 0, 1, 'miguel.venceslau.maciel.de.campos@hotmail.com', 'miguel.venceslau.maciel.de.campos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('RITA IRACI ALMEIDA DA SILVA', '2014-07-05', '2014-02-02', 1, 1, 'rita.iraci.almeida.da.silva@fb.com', 'rita.iraci.almeida.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('OSWALDIR GOMES', '2014-07-11', '2014-02-06', 0, 1, 'oswaldir.gomes@gmail.com', 'oswaldir.gomes');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('NEUCY DE OLIVEIRA', '2014-07-07', '2014-03-19', 0, 1, 'neucy.de.oliveira@gmail.com', 'neucy.de.oliveira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('WILSON CONCEICAO DE MIRANDA', '2014-07-01', '2014-05-13', 0, 0, 'wilson.conceicao.de.miranda@gmail.com', 'wilson.conceicao.de.miranda');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('FRANCISCA MARIA SILVA COSTA', '2014-07-05', '2014-06-18', 1, 0, 'francisca.maria.silva.costa@gmail.com', 'francisca.maria.silva.costa');
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-11', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-04', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-05', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-02', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-17', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-27', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-07', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-05', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-28', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-25', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-03', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-19', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-20', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-17', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-25', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-29', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-13', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-06', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-13', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-19', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-27', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-21', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-07-05', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-11', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-11', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-19', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-17', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-25', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-10', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-13', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-09', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-16', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-14', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-02', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-30', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-14', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-18', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-22', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-23', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-31', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-29', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-29', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-04', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-06', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-04', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-30', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-30', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-07', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-31', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-18', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-01', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-06', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-25', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-20', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-18', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-07-10', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-15', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-23', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-05', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-26', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-01', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-23', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-17', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-29', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-25', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-25', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-16', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-27', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-30', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-20', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-24', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-12', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-09', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-30', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-07', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-11', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-15', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-07-13', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-19', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-07-10', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-24', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-28', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-04', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-23', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-15', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-09', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-31', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-16', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-14', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-09', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-17', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-10', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-03', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-19', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-22', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-17', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-01', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-12', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-07-04', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-27', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
