INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('32026-960', '9159', 'F', 'DIRCEU DE MATTOS', '2014-02-17', 0, 'Honduras', 'dirceu.de.mattos@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('50633-178', '5152', 'M', 'DIEGO CESPEDES DE SOUZA', '2014-03-05', 0, 'Cameroon', 'diego.cespedes.de.souza@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('31426-417', '3162', 'M', 'JOSE RIBAMAR BEZERRA SA', '2014-07-29', 1, 'Mali', 'jose.ribamar.bezerra.sa@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('82474-770', '4642', 'F', 'RITA IRACI ALMEIDA DA SILVA', '2014-07-14', 1, 'Latvia', 'rita.iraci.almeida.da.silva@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('38607-713', '2039', 'F', 'RAMIRO VEDOVATO', '2014-05-11', 0, 'Uganda', 'ramiro.vedovato@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('55276-658', '5283', 'M', 'GUIOMAR TRELHA FRANCA', '2014-06-23', 1, 'Burkina Faso', 'guiomar.trelha.franca@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('48974-184', '2549', 'F', 'AUGUSTA ALVES DOS SANTOS', '2014-09-19', 1, 'Slovenia', 'augusta.alves.dos.santos@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('60104-434', '3207', 'M', 'EUZEBIO DA SILVA CEZAR', '2014-10-17', 0, 'Uzbekistan', 'euzebio.da.silva.cezar@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('37198-469', '9954', 'F', 'ANGELA APARECIDA BERNEGOZZE', '2014-04-18', 0, 'Nauru', 'angela.aparecida.bernegozze@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('18921-181', '2258', 'F', 'INES APARECIDA DA SILVA', '2014-11-17', 0, 'Cameroon', 'ines.aparecida.da.silva@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('56141-019', '3483', 'F', 'OLGA PEREIRA', '2014-02-27', 1, 'Ethiopia', 'olga.pereira@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('17247-496', '6597', 'M', 'TIMOTEO BATISTA LEITE', '2014-08-29', 1, 'Laos', 'timoteo.batista.leite@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('76776-197', '4870', 'M', 'ZILMA MARQUES GONCALVES RODRIGUES', '2014-11-29', 1, 'Bangladesh', 'zilma.marques.goncalves.rodrigues@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('46467-374', '8948', 'F', 'MARGARETH VIRGINIA DE REZENDE MEHLMANN', '2014-06-16', 0, 'Czech Republic', 'margareth.virginia.de.rezende.mehlmann@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('63967-378', '9943', 'M', 'THANIA CRISTINA DA SILVA BARNABE', '2014-01-25', 1, 'Burundi', 'thania.cristina.da.silva.barnabe@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('32030-401', '7617', 'F', 'ALICE FERNANDES DE OLIVEIRA', '2014-06-06', 0, 'Antigua & Barbuda', 'alice.fernandes.de.oliveira@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('60662-878', '7813', 'F', 'NADIACUIABANO KUNZE', '2014-12-08', 0, 'Panama', 'nadiacuiabano.kunze@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('35508-078', '0659', 'M', 'OLGA PEREIRA', '2014-06-01', 0, 'Yemen', 'olga.pereira@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('28802-920', '6400', 'M', 'ALDIVINA REIS FERNANDES', '2014-01-07', 1, 'Kazakhstan', 'aldivina.reis.fernandes@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('50577-894', '9911', 'F', 'EDIO JUSTO BORGES', '2014-09-18', 1, 'Somalia', 'edio.justo.borges@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('07839-488', '9114', 'M', 'SOLANGE APARECIDA DO PRADO DA CRUZ', '2014-12-17', 1, 'Palestinian State', 'solange.aparecida.do.prado.da.cruz@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('74899-800', '5379', 'F', 'LUCINEIDE DE MORAES DO CARMO', '2014-06-30', 0, 'Italy', 'lucineide.de.moraes.do.carmo@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('96821-546', '0477', 'M', 'DORILDA ALVES DE CARVALHO', '2014-03-21', 0, 'Ecuador', 'dorilda.alves.de.carvalho@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('12964-234', '3468', 'F', 'JOANA ANTUNES', '2014-08-01', 1, 'The Netherlands', 'joana.antunes@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('79008-324', '4805', 'F', 'DIAMANTINA DA SILVA SOARES', '2014-09-30', 1, 'Grenada', 'diamantina.da.silva.soares@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('22470-044', '2006', 'F', 'CELESIAORMOND RIBEIRO DE CAMPOS', '2014-04-08', 1, 'Eritrea', 'celesiaormond.ribeiro.de.campos@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('43194-442', '6606', 'M', 'ROSILENE ALMEIDA DA SILVA', '2014-02-11', 1, 'Guinea-Bissau', 'rosilene.almeida.da.silva@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('43254-187', '9252', 'F', 'ADAIL BANDINELLE DE MORAES', '2014-11-14', 0, 'Cote d''Ivoire', 'adail.bandinelle.de.moraes@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('95067-903', '9277', 'M', 'KLEBER MAGALHAES FERREIRA', '2014-08-22', 1, 'China', 'kleber.magalhaes.ferreira@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('54528-565', '1997', 'F', 'ELOIDE CAVANHA', '2014-04-23', 1, 'Honduras', 'eloide.cavanha@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('68445-919', '6326', 'F', 'THANIA CRISTINA DA SILVA BARNABE', '2014-04-15', 0, 'St. Vincent & The Grenadines', 'thania.cristina.da.silva.barnabe@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('34904-140', '1947', 'F', 'BENILDE PERES DE CAMPOS', '2014-03-08', 0, 'Oman', 'benilde.peres.de.campos@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('11777-301', '8959', 'F', 'NEIZA MARIA LEITE DA SILVA', '2014-08-15', 1, 'Gambia', 'neiza.maria.leite.da.silva@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('27995-805', '2078', 'M', 'MARIA FATIMA SCHEUNEMANN MIRANDA', '2014-09-23', 1, 'Ireland', 'maria.fatima.scheunemann.miranda@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('92456-966', '1580', 'M', 'BENEDITA GAUDENCIO DA COSTA', '2014-06-24', 0, 'Equatorial Guinea', 'benedita.gaudencio.da.costa@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('58433-357', '2229', 'M', 'MARIA ELENA ALVES', '2014-07-26', 1, 'Zambia', 'maria.elena.alves@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('35219-036', '2537', 'M', 'MARIA ALVES SUTIL', '2014-05-24', 0, 'Dominican Republic', 'maria.alves.sutil@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('14327-960', '7084', 'F', 'RITA IRACI ALMEIDA DA SILVA', '2014-03-25', 0, 'Sierra Leone', 'rita.iraci.almeida.da.silva@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('11378-982', '7034', 'F', 'MIGUEL JOAQUIM SILVA', '2014-09-28', 0, 'Dominican Republic', 'miguel.joaquim.silva@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('12655-026', '2975', 'F', 'OLGA PEREIRA', '2014-08-08', 1, 'Guyana', 'olga.pereira@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('03880-140', '4617', 'F', 'LOURIVAL ROSA GUIMARAES', '2014-02-11', 1, 'Bosnia & Herzegovina', 'lourival.rosa.guimaraes@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('54847-098', '4481', 'M', 'ELZA LIMA DE SOUZA MANSANO', '2014-10-24', 1, 'South Africa', 'elza.lima.de.souza.mansano@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('49476-552', '8320', 'M', 'EUZEBIO DA SILVA CEZAR', '2014-07-11', 0, 'Namibia', 'euzebio.da.silva.cezar@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('90224-895', '9289', 'M', 'JOANA ANTUNES', '2014-07-28', 1, 'St. Kitts & Nevis', 'joana.antunes@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('71986-215', '2481', 'F', 'MARIA DE LOURDES FERNANDES DIAS', '2014-03-14', 1, 'Cyprus', 'maria.de.lourdes.fernandes.dias@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('14553-549', '7313', 'M', 'SONIA MARIA MARTINEZ PENITENTE', '2014-06-07', 1, 'Greece', 'sonia.maria.martinez.penitente@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('82944-619', '6410', 'M', 'NEUCY DE OLIVEIRA', '2014-10-05', 0, 'Vanuatu', 'neucy.de.oliveira@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('78252-201', '7188', 'F', 'LUIZA ROTTLISBERGER SILVA', '2014-01-08', 0, 'Togo', 'luiza.rottlisberger.silva@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('91566-716', '0708', 'F', 'JOAQUIM BORGES RODRIGUES', '2014-11-27', 1, 'Brunei', 'joaquim.borges.rodrigues@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('34808-731', '3356', 'M', 'ALICE FERNANDES DE OLIVEIRA', '2014-02-28', 0, 'Austria', 'alice.fernandes.de.oliveira@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('48466-366', '9243', 'M', 'RITA IRACI ALMEIDA DA SILVA', '2014-01-09', 0, 'Chile', 'rita.iraci.almeida.da.silva@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('64236-351', '8380', 'F', 'SILVIA MENDES', '2014-07-15', 0, 'Liberia', 'silvia.mendes@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('54584-198', '0996', 'M', 'SILVIO TSIPE RAIRATE', '2014-11-12', 1, 'Algeria', 'silvio.tsipe.rairate@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('53140-094', '7798', 'M', 'LOURIVAL ROSA GUIMARAES', '2014-07-31', 1, 'Greece', 'lourival.rosa.guimaraes@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('50022-856', '8674', 'F', 'MARIA HILDA MACHADO', '2014-01-07', 0, 'Norway', 'maria.hilda.machado@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('72735-065', '7250', 'F', 'MARIA ALVES SUTIL', '2014-05-28', 1, 'Equatorial Guinea', 'maria.alves.sutil@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('95757-252', '2379', 'F', 'DORILDA ALVES DE CARVALHO', '2014-05-16', 0, 'Fiji', 'dorilda.alves.de.carvalho@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('53610-790', '6035', 'M', 'GLAUBER DA COSTA ARRUDA', '2014-09-13', 1, 'Israel', 'glauber.da.costa.arruda@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('03521-704', '1430', 'F', 'DAVINA PEREIRA DE SALES', '2014-09-29', 0, 'Bangladesh', 'davina.pereira.de.sales@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('95752-207', '8302', 'M', 'LUCINEIDE DE MORAES DO CARMO', '2014-03-01', 1, 'Paraguay', 'lucineide.de.moraes.do.carmo@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('02737-794', '8967', 'F', 'LUZIA RODRIGUES DE OLIVEIRA', '2014-04-07', 0, 'Nauru', 'luzia.rodrigues.de.oliveira@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('50889-084', '6888', 'F', 'HABIB FAHED', '2014-06-14', 1, 'Germany', 'habib.fahed@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('09263-325', '8052', 'F', 'JUEL PRUDENCIO BORGES', '2014-03-26', 0, 'Afghanistan', 'juel.prudencio.borges@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('77430-392', '5126', 'F', 'JORGE TETSUO TAIRA', '2014-03-08', 1, 'Belgium', 'jorge.tetsuo.taira@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('26567-279', '5342', 'M', 'ALICE APARECIDA DOS SANTOS', '2014-07-05', 1, 'Algeria', 'alice.aparecida.dos.santos@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('30734-396', '1104', 'M', 'THANIA CRISTINA DA SILVA BARNABE', '2014-06-20', 0, 'Cameroon', 'thania.cristina.da.silva.barnabe@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('94289-683', '3216', 'M', 'CLEODETE CANOLA DE CAMPOS', '2014-03-12', 1, 'Djibouti', 'cleodete.canola.de.campos@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('42014-137', '3852', 'F', 'CRISTIANE PAES CORDOBA', '2014-03-04', 1, 'Botswana', 'cristiane.paes.cordoba@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('79591-227', '2373', 'M', 'DIEGO CESPEDES DE SOUZA', '2014-02-02', 1, 'Norway', 'diego.cespedes.de.souza@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('35884-354', '0466', 'M', 'LAURO JOSE DA SILVA', '2014-10-04', 0, 'Ethiopia', 'lauro.jose.da.silva@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('32769-552', '1080', 'M', 'SONIA MARIA MARTINEZ PENITENTE', '2014-05-17', 1, 'Albania', 'sonia.maria.martinez.penitente@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('55900-725', '0327', 'M', 'ADELSON LUIZ DA SILVA', '2014-12-19', 1, 'Honduras', 'adelson.luiz.da.silva@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('34179-425', '2708', 'M', 'LAURO JOSE DA SILVA', '2014-04-26', 1, 'India', 'lauro.jose.da.silva@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('39298-893', '1804', 'M', 'LUCINEIDE DE MORAES DO CARMO', '2014-03-24', 0, 'St. Kitts & Nevis', 'lucineide.de.moraes.do.carmo@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('02354-714', '2148', 'F', 'ALBERTO FEIZAR CARDOSO ABDALA', '2014-02-19', 0, 'Antigua & Barbuda', 'alberto.feizar.cardoso.abdala@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('09691-086', '2021', 'F', 'EUSTAQUIA PRIETO', '2014-06-28', 0, 'Ecuador', 'eustaquia.prieto@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('00662-019', '1113', 'F', 'LIDIANE DO PRADO BRITE', '2014-10-31', 0, 'Denmark', 'lidiane.do.prado.brite@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('80375-030', '6955', 'M', 'DIEGO CESPEDES DE SOUZA', '2014-02-20', 1, 'South Africa', 'diego.cespedes.de.souza@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('04372-081', '6492', 'F', 'BENEDITA GAUDENCIO DA COSTA', '2014-03-18', 1, 'Lesotho', 'benedita.gaudencio.da.costa@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('21887-734', '9590', 'M', 'ROBSON LUIZ DO NASCIMENTO PUERTAS', '2014-12-15', 1, 'Kazakhstan', 'robson.luiz.do.nascimento.puertas@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('56544-367', '6090', 'F', 'SOLANGE APARECIDA DO PRADO DA CRUZ', '2014-02-15', 1, 'Congo Democratic Republic', 'solange.aparecida.do.prado.da.cruz@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('78777-060', '9286', 'M', 'IROCIDES APARECIDA FERREIRA', '2014-07-28', 1, 'Guinea', 'irocides.aparecida.ferreira@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('51350-196', '3232', 'F', 'RONY HUDSON OLIVEIRA CANDEIRO', '2014-10-04', 0, 'United States of America', 'rony.hudson.oliveira.candeiro@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('23273-315', '3670', 'F', 'ALICE APARECIDA DOS SANTOS', '2014-02-05', 1, 'Liechtenstein', 'alice.aparecida.dos.santos@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('34278-914', '2342', 'M', 'OSVALDO PEREIRA BARBOSA', '2014-12-15', 1, 'Romania', 'osvaldo.pereira.barbosa@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('25429-977', '8009', 'F', 'JORGE TETSUO TAIRA', '2014-12-12', 0, 'Peru', 'jorge.tetsuo.taira@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('09456-176', '1648', 'F', 'ADENILTON JOSE DE MIRANDA', '2014-05-22', 1, 'Comoros', 'adenilton.jose.de.miranda@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('40886-702', '7692', 'M', 'OBADIAS MARCAL DE OLIVEIRA', '2014-11-16', 1, 'Vanuatu', 'obadias.marcal.de.oliveira@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('23663-218', '2650', 'M', 'ARISMARES SOUZA PRATES', '2014-04-17', 1, 'Korea South', 'arismares.souza.prates@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('75932-848', '4730', 'M', 'ALBERTO FEIZAR CARDOSO ABDALA', '2014-02-11', 0, 'Tajikistan', 'alberto.feizar.cardoso.abdala@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('33224-152', '5083', 'F', 'RUZINO ANTUNES DA SILVA', '2014-04-27', 1, 'Zimbabwe', 'ruzino.antunes.da.silva@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('71923-606', '1498', 'M', 'SUELY DA SILVA CAVALCANTI', '2014-07-13', 1, 'Slovakia', 'suely.da.silva.cavalcanti@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('82263-559', '2587', 'M', 'INES APARECIDA DA SILVA', '2014-03-27', 0, 'Senegal', 'ines.aparecida.da.silva@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('97944-202', '9113', 'F', 'ANDRE LUIS CASTRILLON GARCIA', '2014-05-08', 0, 'Lebanon', 'andre.luis.castrillon.garcia@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('70000-167', '5702', 'F', 'DIRCEU DE MATTOS', '2014-08-26', 1, 'Myanmar (Burma)', 'dirceu.de.mattos@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('22168-819', '3674', 'F', 'GLAUBER DA COSTA ARRUDA', '2014-05-18', 1, 'Monaco', 'glauber.da.costa.arruda@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('36962-987', '9848', 'M', 'MARCIA DA SILVA OLIVEIRA', '2014-09-27', 1, 'Panama', 'marcia.da.silva.oliveira@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('09578-019', '2336', 'F', 'MARIA ELENA ALVES', '2014-10-09', 1, 'Austria', 'maria.elena.alves@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('41906-463', '7869', 'F', 'ABILIO CAVALHEIRO', '2014-02-07', 1, 'Gambia', 'abilio.cavalheiro@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('47134-544', '6568', 'F', 'ILZA XAVIER DE LIMA ARAUJO', '2014-04-21', 0, 'Guatemala', 'ilza.xavier.de.lima.araujo@yahoo.com');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARIA FATIMA SCHEUNEMANN MIRANDA', '2014-07-09', '2014-06-30', 1, 0, 'maria.fatima.scheunemann.miranda@fb.com', 'maria.fatima.scheunemann.miranda');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MAGALI SANCHES', '2014-07-08', '2014-06-19', 1, 1, 'magali.sanches@hotmail.com', 'magali.sanches');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('NEIVA OBERGER FERREIRA', '2014-07-02', '2014-03-18', 1, 0, 'neiva.oberger.ferreira@hotmail.com', 'neiva.oberger.ferreira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ELOIR CARLOS FIRMINO', '2014-07-08', '2014-01-24', 1, 1, 'eloir.carlos.firmino@fb.com', 'eloir.carlos.firmino');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('OLGA PEREIRA', '2014-07-11', '2014-01-06', 1, 0, 'olga.pereira@gmail.com', 'olga.pereira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARCIA DA SILVA OLIVEIRA', '2014-07-07', '2014-01-29', 0, 0, 'marcia.da.silva.oliveira@hotmail.com', 'marcia.da.silva.oliveira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ALICE DE SOUZA MIRANDA', '2014-07-07', '2014-01-27', 1, 1, 'alice.de.souza.miranda@gmail.com', 'alice.de.souza.miranda');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('EDIR DIAS DE CARVALHO', '2014-07-07', '2014-06-30', 0, 1, 'edir.dias.de.carvalho@gmail.com', 'edir.dias.de.carvalho');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ADELSON LUIZ DA SILVA', '2014-07-08', '2014-04-24', 1, 1, 'adelson.luiz.da.silva@hotmail.com', 'adelson.luiz.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('VILMA VITORIA DE SOUZA MESSA', '2014-07-10', '2014-01-12', 0, 1, 'vilma.vitoria.de.souza.messa@hotmail.com', 'vilma.vitoria.de.souza.messa');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('DIAMANTINA DA SILVA SOARES', '2014-07-09', '2014-05-25', 0, 1, 'diamantina.da.silva.soares@fb.com', 'diamantina.da.silva.soares');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LUIZ FERNANDO DA SILVA AMORIM', '2014-07-08', '2014-01-23', 1, 0, 'luiz.fernando.da.silva.amorim@hotmail.com', 'luiz.fernando.da.silva.amorim');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('DIEGO CESPEDES DE SOUZA', '2014-07-03', '2014-02-10', 0, 1, 'diego.cespedes.de.souza@hotmail.com', 'diego.cespedes.de.souza');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('CELESIAORMOND RIBEIRO DE CAMPOS', '2014-07-09', '2014-06-03', 0, 1, 'celesiaormond.ribeiro.de.campos@fb.com', 'celesiaormond.ribeiro.de.campos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LUCINEIDE DE MORAES DO CARMO', '2014-07-12', '2014-03-25', 0, 1, 'lucineide.de.moraes.do.carmo@gmail.com', 'lucineide.de.moraes.do.carmo');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('SOLANGE APARECIDA DO PRADO DA CRUZ', '2014-07-04', '2014-02-07', 1, 0, 'solange.aparecida.do.prado.da.cruz@hotmail.com', 'solange.aparecida.do.prado.da.cruz');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MIGUEL JOAQUIM SILVA', '2014-07-03', '2014-02-15', 0, 0, 'miguel.joaquim.silva@fb.com', 'miguel.joaquim.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('VIOLINDO DE SOUZA', '2014-07-12', '2014-02-21', 1, 1, 'violindo.de.souza@hotmail.com', 'violindo.de.souza');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('DORILDA ALVES DE CARVALHO', '2014-07-08', '2014-01-23', 0, 0, 'dorilda.alves.de.carvalho@hotmail.com', 'dorilda.alves.de.carvalho');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JOAQUIM BORGES RODRIGUES', '2014-07-09', '2014-02-02', 0, 1, 'joaquim.borges.rodrigues@hotmail.com', 'joaquim.borges.rodrigues');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LUZIA RODRIGUES DE OLIVEIRA', '2014-07-12', '2014-05-30', 0, 1, 'luzia.rodrigues.de.oliveira@fb.com', 'luzia.rodrigues.de.oliveira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JORGE TETSUO TAIRA', '2014-07-07', '2014-01-19', 0, 0, 'jorge.tetsuo.taira@fb.com', 'jorge.tetsuo.taira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('NEIZA MARIA LEITE DA SILVA', '2014-07-05', '2014-02-01', 0, 0, 'neiza.maria.leite.da.silva@hotmail.com', 'neiza.maria.leite.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ADELSON LUIZ DA SILVA', '2014-07-04', '2014-06-25', 1, 0, 'adelson.luiz.da.silva@fb.com', 'adelson.luiz.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARCIA DA SILVA OLIVEIRA', '2014-07-03', '2014-03-13', 0, 1, 'marcia.da.silva.oliveira@fb.com', 'marcia.da.silva.oliveira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MIGUEL JOAQUIM SILVA', '2014-07-09', '2014-04-27', 1, 0, 'miguel.joaquim.silva@gmail.com', 'miguel.joaquim.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('IVANI DO NASCIMENTO VALENTIM', '2014-07-09', '2014-04-16', 0, 1, 'ivani.do.nascimento.valentim@gmail.com', 'ivani.do.nascimento.valentim');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('KLEBER MAGALHAES FERREIRA', '2014-07-06', '2014-06-30', 1, 0, 'kleber.magalhaes.ferreira@gmail.com', 'kleber.magalhaes.ferreira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARIA DE LOURDES FERNANDES DIAS', '2014-07-01', '2014-05-21', 0, 0, 'maria.de.lourdes.fernandes.dias@fb.com', 'maria.de.lourdes.fernandes.dias');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ABILIO CAVALHEIRO', '2014-07-10', '2014-01-31', 0, 0, 'abilio.cavalheiro@fb.com', 'abilio.cavalheiro');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('SUELY DA SILVA CAVALCANTI', '2014-07-03', '2014-02-27', 1, 1, 'suely.da.silva.cavalcanti@gmail.com', 'suely.da.silva.cavalcanti');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('RUZINO ANTUNES DA SILVA', '2014-07-02', '2014-05-14', 1, 1, 'ruzino.antunes.da.silva@hotmail.com', 'ruzino.antunes.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('AFONSO BARBOSA DA SILVA', '2014-07-08', '2014-02-28', 0, 1, 'afonso.barbosa.da.silva@fb.com', 'afonso.barbosa.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ZILDA MARTINS DE SOUZA', '2014-07-02', '2014-04-21', 1, 1, 'zilda.martins.de.souza@gmail.com', 'zilda.martins.de.souza');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JOSE RIBAMAR BEZERRA SA', '2014-07-08', '2014-05-10', 0, 0, 'jose.ribamar.bezerra.sa@gmail.com', 'jose.ribamar.bezerra.sa');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ELISABETE ROMERO NOBRE LEAL', '2014-07-13', '2014-01-12', 1, 0, 'elisabete.romero.nobre.leal@fb.com', 'elisabete.romero.nobre.leal');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ANTONIO INACIO RODRIGUES', '2014-07-04', '2014-04-05', 0, 0, 'antonio.inacio.rodrigues@gmail.com', 'antonio.inacio.rodrigues');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LOURIVAL ROSA GUIMARAES', '2014-07-13', '2014-01-27', 0, 0, 'lourival.rosa.guimaraes@hotmail.com', 'lourival.rosa.guimaraes');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ATAIDE DIAS DE MOURA', '2014-07-13', '2014-01-11', 1, 0, 'ataide.dias.de.moura@gmail.com', 'ataide.dias.de.moura');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LUIZA ROTTLISBERGER SILVA', '2014-07-06', '2014-03-20', 0, 1, 'luiza.rottlisberger.silva@hotmail.com', 'luiza.rottlisberger.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('CLEODETE CANOLA DE CAMPOS', '2014-07-12', '2014-02-18', 0, 1, 'cleodete.canola.de.campos@hotmail.com', 'cleodete.canola.de.campos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ZILDA MARTINS DE SOUZA', '2014-07-10', '2014-01-03', 1, 1, 'zilda.martins.de.souza@hotmail.com', 'zilda.martins.de.souza');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('CLEUSA FERREIRA MACIEL', '2014-07-01', '2014-04-08', 0, 0, 'cleusa.ferreira.maciel@fb.com', 'cleusa.ferreira.maciel');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ALCEU DOS SANTOS', '2014-07-12', '2014-06-02', 0, 0, 'alceu.dos.santos@gmail.com', 'alceu.dos.santos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ANTONIA BORGES DA SILVA', '2014-07-02', '2014-02-03', 0, 0, 'antonia.borges.da.silva@fb.com', 'antonia.borges.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ELZA LIMA DE SOUZA MANSANO', '2014-07-07', '2014-02-09', 1, 0, 'elza.lima.de.souza.mansano@gmail.com', 'elza.lima.de.souza.mansano');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('VALDOMIRO LEITE DE SA', '2014-07-02', '2014-04-18', 0, 0, 'valdomiro.leite.de.sa@gmail.com', 'valdomiro.leite.de.sa');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('HABIB FAHED', '2014-07-10', '2014-02-22', 1, 0, 'habib.fahed@gmail.com', 'habib.fahed');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('RITA IRACI ALMEIDA DA SILVA', '2014-07-02', '2014-03-10', 0, 0, 'rita.iraci.almeida.da.silva@gmail.com', 'rita.iraci.almeida.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('CARMINDA POMPEU AMORIM', '2014-07-01', '2014-01-17', 1, 1, 'carminda.pompeu.amorim@gmail.com', 'carminda.pompeu.amorim');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ANTONIA BORGES DA SILVA', '2014-07-01', '2014-04-07', 1, 0, 'antonia.borges.da.silva@gmail.com', 'antonia.borges.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ZILDA MARTINS DE SOUZA', '2014-07-04', '2014-02-10', 1, 0, 'zilda.martins.de.souza@gmail.com', 'zilda.martins.de.souza');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JOAQUIM BORGES RODRIGUES', '2014-07-13', '2014-03-07', 1, 0, 'joaquim.borges.rodrigues@fb.com', 'joaquim.borges.rodrigues');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('VILMA VITORIA DE SOUZA MESSA', '2014-07-09', '2014-01-10', 1, 0, 'vilma.vitoria.de.souza.messa@fb.com', 'vilma.vitoria.de.souza.messa');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('RUZINO ANTUNES DA SILVA', '2014-07-08', '2014-04-05', 1, 0, 'ruzino.antunes.da.silva@fb.com', 'ruzino.antunes.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('RONY HUDSON OLIVEIRA CANDEIRO', '2014-07-12', '2014-02-14', 0, 1, 'rony.hudson.oliveira.candeiro@gmail.com', 'rony.hudson.oliveira.candeiro');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARIA FATIMA SCHEUNEMANN MIRANDA', '2014-07-01', '2014-06-11', 0, 0, 'maria.fatima.scheunemann.miranda@fb.com', 'maria.fatima.scheunemann.miranda');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARIA TEREZINHA ROCHA DE SOUZA', '2014-07-02', '2014-02-17', 0, 1, 'maria.terezinha.rocha.de.souza@hotmail.com', 'maria.terezinha.rocha.de.souza');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LOURIVAL ROSA GUIMARAES', '2014-07-09', '2014-02-11', 0, 1, 'lourival.rosa.guimaraes@fb.com', 'lourival.rosa.guimaraes');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ALCEU DOS SANTOS', '2014-07-09', '2014-05-05', 1, 1, 'alceu.dos.santos@hotmail.com', 'alceu.dos.santos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARIA LOURENCO ARISTIDES', '2014-07-03', '2014-01-17', 1, 0, 'maria.lourenco.aristides@fb.com', 'maria.lourenco.aristides');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ELOIR CARLOS FIRMINO', '2014-07-09', '2014-05-06', 0, 1, 'eloir.carlos.firmino@fb.com', 'eloir.carlos.firmino');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ANDRE LUIS CASTRILLON GARCIA', '2014-07-10', '2014-06-18', 1, 1, 'andre.luis.castrillon.garcia@fb.com', 'andre.luis.castrillon.garcia');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('VIRGILIA DIAS VIEIRA', '2014-07-04', '2014-04-11', 1, 1, 'virgilia.dias.vieira@fb.com', 'virgilia.dias.vieira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ANTONIA BORGES DA SILVA', '2014-07-02', '2014-03-21', 0, 0, 'antonia.borges.da.silva@hotmail.com', 'antonia.borges.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ZILDA MARTINS DE SOUZA', '2014-07-10', '2014-05-23', 0, 1, 'zilda.martins.de.souza@hotmail.com', 'zilda.martins.de.souza');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARIA DE LOURDES FERNANDES DIAS', '2014-07-04', '2014-04-20', 1, 1, 'maria.de.lourdes.fernandes.dias@fb.com', 'maria.de.lourdes.fernandes.dias');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ELEONILDA DE LIMA RODRIGUES', '2014-07-11', '2014-03-15', 1, 1, 'eleonilda.de.lima.rodrigues@fb.com', 'eleonilda.de.lima.rodrigues');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('VIRGILIA DIAS VIEIRA', '2014-07-10', '2014-03-27', 1, 0, 'virgilia.dias.vieira@hotmail.com', 'virgilia.dias.vieira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('CRISTIANE PAES CORDOBA', '2014-07-08', '2014-02-13', 1, 1, 'cristiane.paes.cordoba@hotmail.com', 'cristiane.paes.cordoba');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('EUSTAQUIA PRIETO', '2014-07-02', '2014-06-05', 1, 0, 'eustaquia.prieto@fb.com', 'eustaquia.prieto');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('OBADIAS MARCAL DE OLIVEIRA', '2014-07-06', '2014-06-04', 0, 0, 'obadias.marcal.de.oliveira@hotmail.com', 'obadias.marcal.de.oliveira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('BENJAMIM GAUNA', '2014-07-04', '2014-04-21', 1, 0, 'benjamim.gauna@gmail.com', 'benjamim.gauna');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LUIZ FERNANDO DA SILVA AMORIM', '2014-07-04', '2014-06-22', 0, 0, 'luiz.fernando.da.silva.amorim@fb.com', 'luiz.fernando.da.silva.amorim');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ADAIL BANDINELLE DE MORAES', '2014-07-09', '2014-04-25', 0, 1, 'adail.bandinelle.de.moraes@gmail.com', 'adail.bandinelle.de.moraes');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('KLEBER MAGALHAES FERREIRA', '2014-07-11', '2014-05-27', 0, 0, 'kleber.magalhaes.ferreira@gmail.com', 'kleber.magalhaes.ferreira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LUZIA RODRIGUES DE OLIVEIRA', '2014-07-01', '2014-03-07', 0, 0, 'luzia.rodrigues.de.oliveira@gmail.com', 'luzia.rodrigues.de.oliveira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('NEIZA MARIA LEITE DA SILVA', '2014-07-12', '2014-01-15', 1, 0, 'neiza.maria.leite.da.silva@gmail.com', 'neiza.maria.leite.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('RAMAO CARDOSO', '2014-07-03', '2014-02-26', 0, 1, 'ramao.cardoso@fb.com', 'ramao.cardoso');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('INES APARECIDA DA SILVA', '2014-07-13', '2014-02-01', 1, 0, 'ines.aparecida.da.silva@fb.com', 'ines.aparecida.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('RONY HUDSON OLIVEIRA CANDEIRO', '2014-07-12', '2014-06-15', 0, 0, 'rony.hudson.oliveira.candeiro@hotmail.com', 'rony.hudson.oliveira.candeiro');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARIA ALVES SUTIL', '2014-07-03', '2014-04-01', 1, 0, 'maria.alves.sutil@gmail.com', 'maria.alves.sutil');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('IROCIDES APARECIDA FERREIRA', '2014-07-10', '2014-04-13', 1, 0, 'irocides.aparecida.ferreira@hotmail.com', 'irocides.aparecida.ferreira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('QUITERIA LOURENCO DE LIMA', '2014-07-10', '2014-03-05', 0, 1, 'quiteria.lourenco.de.lima@hotmail.com', 'quiteria.lourenco.de.lima');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('RUZINO ANTUNES DA SILVA', '2014-07-05', '2014-06-28', 0, 1, 'ruzino.antunes.da.silva@gmail.com', 'ruzino.antunes.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('CARLOS SERGIO URBANIN', '2014-07-13', '2014-04-10', 0, 1, 'carlos.sergio.urbanin@hotmail.com', 'carlos.sergio.urbanin');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('AUGUSTA ALVES DOS SANTOS', '2014-07-02', '2014-05-18', 1, 0, 'augusta.alves.dos.santos@hotmail.com', 'augusta.alves.dos.santos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('VILMA VITORIA DE SOUZA MESSA', '2014-07-11', '2014-01-15', 1, 0, 'vilma.vitoria.de.souza.messa@hotmail.com', 'vilma.vitoria.de.souza.messa');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LOURENCO DIAS', '2014-07-09', '2014-05-04', 0, 0, 'lourenco.dias@hotmail.com', 'lourenco.dias');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARIA LOURENCO ARISTIDES', '2014-07-07', '2014-03-09', 0, 1, 'maria.lourenco.aristides@hotmail.com', 'maria.lourenco.aristides');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('SUELY DA SILVA CAVALCANTI', '2014-07-06', '2014-01-09', 0, 1, 'suely.da.silva.cavalcanti@gmail.com', 'suely.da.silva.cavalcanti');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ALICE DE SOUZA MIRANDA', '2014-07-11', '2014-03-11', 0, 1, 'alice.de.souza.miranda@hotmail.com', 'alice.de.souza.miranda');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('GUIOMAR TRELHA FRANCA', '2014-07-03', '2014-02-14', 0, 1, 'guiomar.trelha.franca@hotmail.com', 'guiomar.trelha.franca');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARLENE SANTANA MARTINS', '2014-07-04', '2014-01-29', 0, 0, 'marlene.santana.martins@hotmail.com', 'marlene.santana.martins');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('NICANOR FELIZARDO DOS REIS', '2014-07-03', '2014-02-25', 1, 0, 'nicanor.felizardo.dos.reis@hotmail.com', 'nicanor.felizardo.dos.reis');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ABIGAIL DA SILVA LARA', '2014-07-09', '2014-06-08', 1, 1, 'abigail.da.silva.lara@fb.com', 'abigail.da.silva.lara');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ALIETE FRANCISCA PRATES', '2014-07-03', '2014-02-13', 1, 1, 'aliete.francisca.prates@gmail.com', 'aliete.francisca.prates');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('DIRCEU DE MATTOS', '2014-07-10', '2014-04-08', 0, 1, 'dirceu.de.mattos@fb.com', 'dirceu.de.mattos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ARISMARES SOUZA PRATES', '2014-07-06', '2014-05-27', 0, 0, 'arismares.souza.prates@hotmail.com', 'arismares.souza.prates');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('DIAMANTINA DA SILVA SOARES', '2014-07-09', '2014-03-28', 0, 1, 'diamantina.da.silva.soares@gmail.com', 'diamantina.da.silva.soares');
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-27', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-06', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-10', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-07-11', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-28', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-04', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-05', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-30', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-10', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-02', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-17', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-07-06', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-21', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-24', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-03', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-12', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-07', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-18', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-18', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-28', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-29', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-30', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-25', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-09', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-11', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-05', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-23', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-27', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-28', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-14', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-17', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-11', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-06', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-11', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-02', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-03', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-27', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-29', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-03', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-29', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-09', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-09', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-27', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-06', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-27', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-10', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-18', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-27', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-04', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-29', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-09', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-29', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-04', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-03', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-09', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-03', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-17', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-14', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-25', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-13', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-27', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-06', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-22', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-12', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-03', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-26', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-11', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-30', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-18', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-15', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-19', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-21', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-01', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-07', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-30', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-21', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-07-07', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-23', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-27', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-29', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-08', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-07', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-28', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-28', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-09', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-05', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-18', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-29', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-05', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-09', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-23', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-22', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-07-08', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-05', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-06', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-10', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-20', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-09', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-02', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-03', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
