INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('28083-368', '5321', 'F', 'SEBASTIANA BENEDITA DA COSTA', '2014-09-18', 1, 'Canada', 'sebastiana.benedita.da.costa@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('14828-044', '3360', 'M', 'VIOLINDO DE SOUZA', '2014-04-24', 0, 'Moldova', 'violindo.de.souza@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('55365-026', '2032', 'F', 'OSWALDIR GOMES', '2014-10-22', 1, 'Greece', 'oswaldir.gomes@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('82806-298', '8583', 'M', 'MARGARETH VIRGINIA DE REZENDE MEHLMANN', '2014-01-23', 0, 'Russia', 'margareth.virginia.de.rezende.mehlmann@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('49002-394', '4836', 'F', 'LUZIA RODRIGUES DE OLIVEIRA', '2014-12-18', 1, 'Finland', 'luzia.rodrigues.de.oliveira@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('49045-018', '4763', 'M', 'CLAUDIO BARBOSA DOS SANTOS', '2014-06-06', 1, 'Malta', 'claudio.barbosa.dos.santos@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('96690-606', '2472', 'M', 'MARLENE SANTANA MARTINS', '2014-04-06', 1, 'El Salvador', 'marlene.santana.martins@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('12236-685', '4792', 'M', 'RONY HUDSON OLIVEIRA CANDEIRO', '2014-08-19', 1, 'Andorra', 'rony.hudson.oliveira.candeiro@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('80489-083', '8983', 'F', 'JOAO DE LUCA', '2014-05-29', 1, 'Rwanda', 'joao.de.luca@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('88370-799', '6826', 'M', 'JOSE EVALDO DA SILVA', '2014-06-08', 1, 'Kosovo', 'jose.evaldo.da.silva@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('18819-282', '6481', 'M', 'MARIA HILDA MACHADO', '2014-05-04', 0, 'Togo', 'maria.hilda.machado@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('14117-943', '6656', 'F', 'ZILDA MARTINS DE SOUZA', '2014-10-08', 1, 'Madagascar', 'zilda.martins.de.souza@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('62194-261', '3528', 'M', 'ALCEU DOS SANTOS', '2014-02-19', 1, 'Bhutan', 'alceu.dos.santos@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('92073-649', '9913', 'M', 'ANDRE LUIS CASTRILLON GARCIA', '2014-10-29', 0, 'Nigeria', 'andre.luis.castrillon.garcia@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('57639-408', '3786', 'M', 'LAURO JOSE DA SILVA', '2014-02-05', 0, 'Norway', 'lauro.jose.da.silva@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('52567-949', '6775', 'M', 'OBADIAS MARCAL DE OLIVEIRA', '2014-06-09', 0, 'Madagascar', 'obadias.marcal.de.oliveira@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('35480-329', '1581', 'F', 'DIEGO CESPEDES DE SOUZA', '2014-09-24', 0, 'Antigua & Barbuda', 'diego.cespedes.de.souza@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('45175-808', '3686', 'F', 'ZILDA MARTINS DE SOUZA', '2014-01-03', 1, 'Denmark', 'zilda.martins.de.souza@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('33797-137', '0045', 'M', 'ZILDA MARTINS DE SOUZA', '2014-08-03', 0, 'Suriname', 'zilda.martins.de.souza@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('15597-894', '1756', 'M', 'ANTONIO INACIO RODRIGUES', '2014-09-25', 0, 'Sweden', 'antonio.inacio.rodrigues@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('70137-853', '5235', 'F', 'QUITERIA LOURENCO DE LIMA', '2014-05-18', 0, 'Australia', 'quiteria.lourenco.de.lima@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('06085-317', '1307', 'F', 'ANGELA APARECIDA BERNEGOZZE', '2014-04-13', 0, 'Congo Democratic Republic', 'angela.aparecida.bernegozze@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('72237-461', '8514', 'F', 'JOSENOTARIO MUNGO', '2014-09-05', 1, 'Malawi', 'josenotario.mungo@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('88270-206', '8609', 'F', 'JORGE TETSUO TAIRA', '2014-10-24', 0, 'Cameroon', 'jorge.tetsuo.taira@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('18754-597', '3427', 'F', 'DAVINA PEREIRA DE SALES', '2014-03-11', 0, 'Belize', 'davina.pereira.de.sales@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('24147-761', '9810', 'M', 'NEUCY DE OLIVEIRA', '2014-07-16', 0, 'Luxembourg', 'neucy.de.oliveira@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('13790-462', '7998', 'F', 'JOAO MAURILIO DA SILVA', '2014-03-18', 1, 'Switzerland', 'joao.maurilio.da.silva@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('98972-464', '7756', 'F', 'CLEUSA FERREIRA MACIEL', '2014-09-21', 1, 'Mexico', 'cleusa.ferreira.maciel@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('91023-792', '8724', 'M', 'FRANCISCA MARIA SILVA COSTA', '2014-08-07', 0, 'Serbia', 'francisca.maria.silva.costa@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('79525-629', '8682', 'F', 'EUZEBIO DA SILVA CEZAR', '2014-09-26', 1, 'Mauritania', 'euzebio.da.silva.cezar@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('67225-238', '9460', 'F', 'ELZA LIMA DE SOUZA MANSANO', '2014-06-06', 1, 'Grenada', 'elza.lima.de.souza.mansano@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('02900-342', '6317', 'M', 'EDIO JUSTO BORGES', '2014-07-23', 0, 'Venezuela', 'edio.justo.borges@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('91563-672', '1922', 'M', 'QUITERIA LOURENCO DE LIMA', '2014-06-16', 1, 'Algeria', 'quiteria.lourenco.de.lima@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('85509-820', '1949', 'F', 'BENEDITA GAUDENCIO DA COSTA', '2014-01-14', 1, 'Moldova', 'benedita.gaudencio.da.costa@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('37555-244', '1839', 'F', 'NEIZA MARIA LEITE DA SILVA', '2014-03-02', 0, 'Bahrain', 'neiza.maria.leite.da.silva@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('74562-132', '4159', 'F', 'ELOIR CARLOS FIRMINO', '2014-04-19', 1, 'Italy', 'eloir.carlos.firmino@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('05032-082', '5721', 'F', 'MARIA TEREZINHA ROCHA DE SOUZA', '2014-04-05', 1, 'Benin', 'maria.terezinha.rocha.de.souza@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('21909-336', '7033', 'M', 'ALBERTO FEIZAR CARDOSO ABDALA', '2014-10-06', 0, 'Micronesia', 'alberto.feizar.cardoso.abdala@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('22222-858', '7823', 'F', 'CLEODETE CANOLA DE CAMPOS', '2014-06-06', 0, 'Latvia', 'cleodete.canola.de.campos@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('95758-368', '9632', 'F', 'OSVALDO PEREIRA BARBOSA', '2014-10-21', 0, 'Algeria', 'osvaldo.pereira.barbosa@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('90175-536', '1009', 'M', 'ANTONIO INACIO RODRIGUES', '2014-08-21', 0, 'Mongolia', 'antonio.inacio.rodrigues@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('03650-583', '3682', 'M', 'ADAIL BANDINELLE DE MORAES', '2014-07-20', 1, 'Equatorial Guinea', 'adail.bandinelle.de.moraes@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('98509-124', '6846', 'M', 'QUITERIA LOURENCO DE LIMA', '2014-07-29', 1, 'Slovakia', 'quiteria.lourenco.de.lima@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('38882-390', '4967', 'F', 'IVANI DO NASCIMENTO VALENTIM', '2014-03-25', 0, 'Lesotho', 'ivani.do.nascimento.valentim@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('77644-959', '5076', 'M', 'JULIO APARECIDO DE SOUZA', '2014-04-06', 0, 'Indonesia', 'julio.aparecido.de.souza@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('03586-408', '3116', 'F', 'SILVIO TSIPE RAIRATE', '2014-09-30', 0, 'Madagascar', 'silvio.tsipe.rairate@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('36463-933', '6003', 'F', 'ALDEIR ALEX ALVES LIMA', '2014-12-21', 0, 'Nauru', 'aldeir.alex.alves.lima@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('95463-777', '1104', 'F', 'LUCINEIDE DE MORAES DO CARMO', '2014-04-24', 1, 'Ethiopia', 'lucineide.de.moraes.do.carmo@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('87720-040', '0201', 'F', 'JUEL PRUDENCIO BORGES', '2014-04-14', 0, 'United Kingdom', 'juel.prudencio.borges@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('81331-175', '4359', 'M', 'ELZA LIMA DE SOUZA MANSANO', '2014-01-06', 1, 'Nigeria', 'elza.lima.de.souza.mansano@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('96430-381', '8801', 'F', 'EDIR DIAS DE CARVALHO', '2014-02-11', 1, 'Macedonia', 'edir.dias.de.carvalho@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('63017-394', '7118', 'F', 'RONY HUDSON OLIVEIRA CANDEIRO', '2014-08-30', 0, 'Mongolia', 'rony.hudson.oliveira.candeiro@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('55008-448', '0986', 'F', 'MAGALI SANCHES', '2014-11-25', 0, 'Guyana', 'magali.sanches@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('51857-747', '6534', 'F', 'EDIR DIAS DE CARVALHO', '2014-07-14', 0, 'Yemen', 'edir.dias.de.carvalho@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('38793-102', '0454', 'M', 'VIRGILIA DIAS VIEIRA', '2014-01-01', 0, 'The Netherlands', 'virgilia.dias.vieira@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('62732-158', '5646', 'F', 'DELCY MARTINS DA SILVA', '2014-12-23', 1, 'Jordan', 'delcy.martins.da.silva@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('41195-768', '3564', 'F', 'ROSIMEIRE GONCALVES LOPES RAMOS', '2014-04-07', 0, 'Korea South', 'rosimeire.goncalves.lopes.ramos@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('42313-004', '0689', 'M', 'EDIO JUSTO BORGES', '2014-05-16', 1, 'Gambia', 'edio.justo.borges@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('95886-139', '6817', 'F', 'SILVIA MENDES', '2014-07-21', 1, 'Montenegro', 'silvia.mendes@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('11780-265', '0574', 'M', 'MARIA ALVES SUTIL', '2014-04-24', 0, 'Myanmar (Burma)', 'maria.alves.sutil@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('61276-204', '4819', 'F', 'JOSENOTARIO MUNGO', '2014-05-25', 1, 'Brazil', 'josenotario.mungo@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('80511-040', '1689', 'F', 'CRISTIANE PAES CORDOBA', '2014-08-27', 1, 'The Philippines', 'cristiane.paes.cordoba@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('79458-691', '6009', 'F', 'SEBASTIANA BENEDITA DA COSTA', '2014-07-08', 1, 'Germany', 'sebastiana.benedita.da.costa@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('15504-163', '2171', 'F', 'BENEDITO AMBROSIO DA COSTA', '2014-08-18', 0, 'Azerbaijan', 'benedito.ambrosio.da.costa@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('95458-630', '4061', 'M', 'IVANI DO NASCIMENTO VALENTIM', '2014-05-19', 0, 'Nauru', 'ivani.do.nascimento.valentim@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('14046-606', '4723', 'F', 'LOURIVAL ROSA GUIMARAES', '2014-11-14', 1, 'Namibia', 'lourival.rosa.guimaraes@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('05719-449', '8773', 'F', 'ALICE FERNANDES DE OLIVEIRA', '2014-08-06', 1, 'Eritrea', 'alice.fernandes.de.oliveira@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('23682-394', '6737', 'F', 'ZILMA MARQUES GONCALVES RODRIGUES', '2014-03-28', 0, 'Sudan', 'zilma.marques.goncalves.rodrigues@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('44010-040', '1886', 'F', 'GLAUBER DA COSTA ARRUDA', '2014-02-15', 0, 'Micronesia', 'glauber.da.costa.arruda@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('34069-153', '3710', 'F', 'ABIGAIL DA SILVA LARA', '2014-03-21', 1, 'Kyrgyzstan', 'abigail.da.silva.lara@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('37314-871', '7561', 'M', 'GUIOMAR TRELHA FRANCA', '2014-09-03', 1, 'Oman', 'guiomar.trelha.franca@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('48943-481', '8081', 'M', 'ATAIDE DIAS DE MOURA', '2014-04-07', 0, 'Libya', 'ataide.dias.de.moura@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('39355-966', '5445', 'F', 'AMERICO FRANCISCO DA SILVA', '2014-07-06', 0, 'Jamaica', 'americo.francisco.da.silva@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('98193-044', '9728', 'F', 'MARCONI GEORGE RIBEIRO DA SILVA', '2014-07-10', 1, 'Armenia', 'marconi.george.ribeiro.da.silva@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('10119-302', '9759', 'M', 'ALDIVINA REIS FERNANDES', '2014-09-05', 0, 'Qatar', 'aldivina.reis.fernandes@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('25381-823', '6585', 'M', 'AUGUSTA ALVES DOS SANTOS', '2014-09-19', 0, 'Fiji', 'augusta.alves.dos.santos@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('39370-969', '8228', 'M', 'JOSE NUNES PEREIRA', '2014-07-24', 1, 'Iraq', 'jose.nunes.pereira@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('79416-653', '6700', 'M', 'MARGARETH VIRGINIA DE REZENDE MEHLMANN', '2014-03-16', 0, 'Dominica', 'margareth.virginia.de.rezende.mehlmann@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('83570-407', '0938', 'M', 'AUGUSTA ALVES DOS SANTOS', '2014-10-27', 1, 'Portugal', 'augusta.alves.dos.santos@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('47763-977', '9102', 'M', 'JOANA ANTUNES', '2014-11-03', 0, 'Rwanda', 'joana.antunes@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('50763-191', '8400', 'M', 'MARCIA DA SILVA OLIVEIRA', '2014-01-04', 0, 'Serbia', 'marcia.da.silva.oliveira@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('29627-555', '4186', 'M', 'MARLENE SANTANA MARTINS', '2014-10-16', 0, 'Ghana', 'marlene.santana.martins@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('72251-524', '5821', 'M', 'BENILDE PERES DE CAMPOS', '2014-06-18', 0, 'South Sudan', 'benilde.peres.de.campos@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('17252-614', '5020', 'M', 'HABIB FAHED', '2014-09-03', 0, 'Malaysia', 'habib.fahed@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('80001-777', '3226', 'F', 'IVANI DO NASCIMENTO VALENTIM', '2014-09-06', 1, 'Bhutan', 'ivani.do.nascimento.valentim@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('31466-576', '6356', 'M', 'RUBENSMORBECK LEITE', '2014-03-20', 1, 'Cape Verde', 'rubensmorbeck.leite@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('55956-648', '1494', 'F', 'BENEDITA GAUDENCIO DA COSTA', '2014-05-29', 1, 'Guatemala', 'benedita.gaudencio.da.costa@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('75169-787', '9815', 'F', 'AUGUSTA ALVES DOS SANTOS', '2014-05-09', 1, 'Australia', 'augusta.alves.dos.santos@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('44089-232', '0801', 'F', 'JORGE TETSUO TAIRA', '2014-06-24', 1, 'Tanzania', 'jorge.tetsuo.taira@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('74020-734', '7224', 'M', 'ATAIDE DIAS DE MOURA', '2014-04-03', 1, 'Korea North', 'ataide.dias.de.moura@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('72682-196', '0155', 'F', 'JOSE RIBAMAR BEZERRA SA', '2014-10-13', 0, 'Belize', 'jose.ribamar.bezerra.sa@gmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('68469-692', '6793', 'F', 'GLAUBER DA COSTA ARRUDA', '2014-08-26', 0, 'India', 'glauber.da.costa.arruda@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('28969-367', '4928', 'F', 'ROSILENE ALMEIDA DA SILVA', '2014-01-11', 1, 'Burkina Faso', 'rosilene.almeida.da.silva@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('73460-063', '4661', 'F', 'MARIA DAIANE DE ARAUJO SOUZA', '2014-01-10', 1, 'United Kingdom', 'maria.daiane.de.araujo.souza@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('10230-773', '9294', 'F', 'JOAO MAURILIO DA SILVA', '2014-07-30', 0, 'Togo', 'joao.maurilio.da.silva@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('89046-747', '4379', 'M', 'DORILDA ALVES DE CARVALHO', '2014-12-13', 1, 'Tajikistan', 'dorilda.alves.de.carvalho@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('26122-245', '9306', 'F', 'WANDERSON COSMO DE ARAUJO', '2014-06-23', 1, 'Russia', 'wanderson.cosmo.de.araujo@yahoo.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('97490-803', '4379', 'F', 'RAMAO CARDOSO', '2014-04-19', 1, 'Tunisia', 'ramao.cardoso@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('83125-835', '1064', 'F', 'JOAO MAURILIO DA SILVA', '2014-12-05', 1, 'Kazakhstan', 'joao.maurilio.da.silva@hotmail.com');
INSERT INTO tbl_estabelecimento (cep,telefone,sexo,nome,data_nascimento,ativo,pais,email) VALUES ('37264-912', '7091', 'M', 'ALBERTO FEIZAR CARDOSO ABDALA', '2014-09-26', 1, 'Luxembourg', 'alberto.feizar.cardoso.abdala@hotmail.com');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('BENJAMIM GAUNA', '2014-07-08', '2014-01-09', 0, 1, 'benjamim.gauna@gmail.com', 'benjamim.gauna');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('CRISTIANE PAES CORDOBA', '2014-07-12', '2014-04-07', 1, 1, 'cristiane.paes.cordoba@fb.com', 'cristiane.paes.cordoba');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('THANIA CRISTINA DA SILVA BARNABE', '2014-07-11', '2014-05-16', 0, 0, 'thania.cristina.da.silva.barnabe@gmail.com', 'thania.cristina.da.silva.barnabe');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('DILMA DE SOUZA', '2014-07-13', '2014-05-31', 0, 1, 'dilma.de.souza@fb.com', 'dilma.de.souza');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ALCEU DOS SANTOS', '2014-07-05', '2014-04-11', 1, 0, 'alceu.dos.santos@fb.com', 'alceu.dos.santos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARLENE SANTANA MARTINS', '2014-07-12', '2014-02-13', 0, 0, 'marlene.santana.martins@hotmail.com', 'marlene.santana.martins');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ADAIL BANDINELLE DE MORAES', '2014-07-06', '2014-04-16', 0, 0, 'adail.bandinelle.de.moraes@fb.com', 'adail.bandinelle.de.moraes');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JOSENOTARIO MUNGO', '2014-07-10', '2014-03-27', 1, 0, 'josenotario.mungo@fb.com', 'josenotario.mungo');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('PAULO TEIXEIRA DE ABREU', '2014-07-05', '2014-04-13', 1, 0, 'paulo.teixeira.de.abreu@hotmail.com', 'paulo.teixeira.de.abreu');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LUIZ LOPES DA SILVA', '2014-07-01', '2014-06-22', 1, 1, 'luiz.lopes.da.silva@hotmail.com', 'luiz.lopes.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('DORILDA ALVES DE CARVALHO', '2014-07-13', '2014-03-04', 1, 0, 'dorilda.alves.de.carvalho@gmail.com', 'dorilda.alves.de.carvalho');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JOAO DE LUCA', '2014-07-05', '2014-01-13', 0, 1, 'joao.de.luca@hotmail.com', 'joao.de.luca');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('SUELY DA SILVA CAVALCANTI', '2014-07-06', '2014-04-05', 1, 1, 'suely.da.silva.cavalcanti@fb.com', 'suely.da.silva.cavalcanti');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LUIZ FERNANDO DA SILVA AMORIM', '2014-07-08', '2014-05-16', 0, 1, 'luiz.fernando.da.silva.amorim@fb.com', 'luiz.fernando.da.silva.amorim');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('DILMA DE SOUZA', '2014-07-09', '2014-02-17', 1, 0, 'dilma.de.souza@gmail.com', 'dilma.de.souza');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('NEIVA OBERGER FERREIRA', '2014-07-09', '2014-05-07', 0, 0, 'neiva.oberger.ferreira@gmail.com', 'neiva.oberger.ferreira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('DELCY MARTINS DA SILVA', '2014-07-10', '2014-03-05', 1, 1, 'delcy.martins.da.silva@fb.com', 'delcy.martins.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('NEIZA MARIA LEITE DA SILVA', '2014-07-02', '2014-01-18', 0, 0, 'neiza.maria.leite.da.silva@gmail.com', 'neiza.maria.leite.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('AFONSO BARBOSA DA SILVA', '2014-07-02', '2014-01-17', 1, 0, 'afonso.barbosa.da.silva@gmail.com', 'afonso.barbosa.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARIA HILDA MACHADO', '2014-07-01', '2014-05-09', 0, 1, 'maria.hilda.machado@gmail.com', 'maria.hilda.machado');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ABIGAIL DA SILVA LARA', '2014-07-09', '2014-02-19', 0, 1, 'abigail.da.silva.lara@hotmail.com', 'abigail.da.silva.lara');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARGARETH VIRGINIA DE REZENDE MEHLMANN', '2014-07-01', '2014-04-02', 0, 1, 'margareth.virginia.de.rezende.mehlmann@gmail.com', 'margareth.virginia.de.rezende.mehlmann');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('IROCIDES APARECIDA FERREIRA', '2014-07-03', '2014-02-25', 0, 0, 'irocides.aparecida.ferreira@hotmail.com', 'irocides.aparecida.ferreira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JOSENOTARIO MUNGO', '2014-07-13', '2014-01-19', 1, 0, 'josenotario.mungo@fb.com', 'josenotario.mungo');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ALDIVINA REIS FERNANDES', '2014-07-06', '2014-04-27', 1, 1, 'aldivina.reis.fernandes@fb.com', 'aldivina.reis.fernandes');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('VIOLINDO DE SOUZA', '2014-07-07', '2014-03-06', 1, 0, 'violindo.de.souza@gmail.com', 'violindo.de.souza');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LAURA SEBASTIANA GURGEL', '2014-07-09', '2014-02-03', 0, 0, 'laura.sebastiana.gurgel@hotmail.com', 'laura.sebastiana.gurgel');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARCIA DA SILVA OLIVEIRA', '2014-07-03', '2014-04-07', 0, 0, 'marcia.da.silva.oliveira@hotmail.com', 'marcia.da.silva.oliveira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('DIAMANTINA DA SILVA SOARES', '2014-07-05', '2014-04-13', 1, 1, 'diamantina.da.silva.soares@fb.com', 'diamantina.da.silva.soares');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JORGE TETSUO TAIRA', '2014-07-03', '2014-01-10', 0, 1, 'jorge.tetsuo.taira@fb.com', 'jorge.tetsuo.taira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JOAO DE LUCA', '2014-07-12', '2014-04-29', 1, 1, 'joao.de.luca@fb.com', 'joao.de.luca');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ALICE DE SOUZA MIRANDA', '2014-07-13', '2014-04-04', 1, 0, 'alice.de.souza.miranda@gmail.com', 'alice.de.souza.miranda');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('SONIA MARIA MARTINEZ PENITENTE', '2014-07-07', '2014-01-13', 0, 1, 'sonia.maria.martinez.penitente@hotmail.com', 'sonia.maria.martinez.penitente');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ELEONILDA DE LIMA RODRIGUES', '2014-07-01', '2014-05-22', 1, 1, 'eleonilda.de.lima.rodrigues@hotmail.com', 'eleonilda.de.lima.rodrigues');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ROSIMEIRE GONCALVES LOPES RAMOS', '2014-07-02', '2014-06-07', 1, 1, 'rosimeire.goncalves.lopes.ramos@hotmail.com', 'rosimeire.goncalves.lopes.ramos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('AFONSO BARBOSA DA SILVA', '2014-07-09', '2014-01-03', 1, 0, 'afonso.barbosa.da.silva@hotmail.com', 'afonso.barbosa.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('AFONSO BARBOSA DA SILVA', '2014-07-07', '2014-01-15', 0, 1, 'afonso.barbosa.da.silva@hotmail.com', 'afonso.barbosa.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARGARETH VIRGINIA DE REZENDE MEHLMANN', '2014-07-08', '2014-06-28', 0, 1, 'margareth.virginia.de.rezende.mehlmann@gmail.com', 'margareth.virginia.de.rezende.mehlmann');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LOURENCO DIAS', '2014-07-12', '2014-03-17', 0, 0, 'lourenco.dias@gmail.com', 'lourenco.dias');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARIA ELENA ALVES', '2014-07-05', '2014-04-29', 1, 0, 'maria.elena.alves@hotmail.com', 'maria.elena.alves');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('HELIO SAMBATTI', '2014-07-03', '2014-05-07', 0, 0, 'helio.sambatti@fb.com', 'helio.sambatti');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('BENJAMIM GAUNA', '2014-07-09', '2014-04-05', 1, 0, 'benjamim.gauna@fb.com', 'benjamim.gauna');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('SOLANGE APARECIDA DO PRADO DA CRUZ', '2014-07-05', '2014-02-14', 1, 0, 'solange.aparecida.do.prado.da.cruz@gmail.com', 'solange.aparecida.do.prado.da.cruz');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('TIMOTEO BATISTA LEITE', '2014-07-09', '2014-06-01', 0, 1, 'timoteo.batista.leite@fb.com', 'timoteo.batista.leite');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('NICANOR FELIZARDO DOS REIS', '2014-07-13', '2014-03-31', 1, 0, 'nicanor.felizardo.dos.reis@hotmail.com', 'nicanor.felizardo.dos.reis');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('HELIO SAMBATTI', '2014-07-08', '2014-06-24', 0, 0, 'helio.sambatti@fb.com', 'helio.sambatti');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ALCEU DOS SANTOS', '2014-07-06', '2014-01-06', 1, 0, 'alceu.dos.santos@gmail.com', 'alceu.dos.santos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('CELIA CRISTINA PEREIRA PINTO DOS SANTOS', '2014-07-13', '2014-01-27', 1, 0, 'celia.cristina.pereira.pinto.dos.santos@hotmail.com', 'celia.cristina.pereira.pinto.dos.santos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ROSIMEIRE GONCALVES LOPES RAMOS', '2014-07-06', '2014-01-02', 1, 0, 'rosimeire.goncalves.lopes.ramos@hotmail.com', 'rosimeire.goncalves.lopes.ramos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('DIEGO CESPEDES DE SOUZA', '2014-07-08', '2014-03-02', 0, 1, 'diego.cespedes.de.souza@gmail.com', 'diego.cespedes.de.souza');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LAURA SEBASTIANA GURGEL', '2014-07-03', '2014-03-28', 0, 1, 'laura.sebastiana.gurgel@hotmail.com', 'laura.sebastiana.gurgel');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LUIZA ROTTLISBERGER SILVA', '2014-07-07', '2014-03-28', 0, 0, 'luiza.rottlisberger.silva@hotmail.com', 'luiza.rottlisberger.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ROSILENE ALMEIDA DA SILVA', '2014-07-05', '2014-05-22', 1, 0, 'rosilene.almeida.da.silva@hotmail.com', 'rosilene.almeida.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MIGUEL JOAQUIM SILVA', '2014-07-03', '2014-03-08', 0, 0, 'miguel.joaquim.silva@gmail.com', 'miguel.joaquim.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LUIZ LOPES DA SILVA', '2014-07-08', '2014-02-28', 1, 1, 'luiz.lopes.da.silva@gmail.com', 'luiz.lopes.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('CORNELIO DIAS DUARTE', '2014-07-10', '2014-02-11', 1, 0, 'cornelio.dias.duarte@fb.com', 'cornelio.dias.duarte');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('RITA IRACI ALMEIDA DA SILVA', '2014-07-05', '2014-05-13', 0, 0, 'rita.iraci.almeida.da.silva@fb.com', 'rita.iraci.almeida.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('WILSON CONCEICAO DE MIRANDA', '2014-07-05', '2014-05-08', 1, 1, 'wilson.conceicao.de.miranda@hotmail.com', 'wilson.conceicao.de.miranda');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LUZIA RODRIGUES DE OLIVEIRA', '2014-07-09', '2014-03-14', 1, 1, 'luzia.rodrigues.de.oliveira@fb.com', 'luzia.rodrigues.de.oliveira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('GUIOMAR TRELHA FRANCA', '2014-07-05', '2014-03-01', 1, 1, 'guiomar.trelha.franca@hotmail.com', 'guiomar.trelha.franca');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ABIGAIL DA SILVA LARA', '2014-07-13', '2014-06-30', 0, 0, 'abigail.da.silva.lara@hotmail.com', 'abigail.da.silva.lara');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('RAMIRO VEDOVATO', '2014-07-12', '2014-02-09', 0, 1, 'ramiro.vedovato@hotmail.com', 'ramiro.vedovato');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('RONY HUDSON OLIVEIRA CANDEIRO', '2014-07-12', '2014-05-10', 0, 0, 'rony.hudson.oliveira.candeiro@gmail.com', 'rony.hudson.oliveira.candeiro');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ALICE DE SOUZA MIRANDA', '2014-07-13', '2014-02-25', 0, 0, 'alice.de.souza.miranda@fb.com', 'alice.de.souza.miranda');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARGARETH VIRGINIA DE REZENDE MEHLMANN', '2014-07-11', '2014-05-10', 0, 1, 'margareth.virginia.de.rezende.mehlmann@fb.com', 'margareth.virginia.de.rezende.mehlmann');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('SILVIA MENDES', '2014-07-07', '2014-06-26', 0, 0, 'silvia.mendes@fb.com', 'silvia.mendes');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('SEBASTIANA BENEDITA DA COSTA', '2014-07-11', '2014-02-17', 1, 1, 'sebastiana.benedita.da.costa@hotmail.com', 'sebastiana.benedita.da.costa');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('RUZINO ANTUNES DA SILVA', '2014-07-04', '2014-04-12', 0, 0, 'ruzino.antunes.da.silva@gmail.com', 'ruzino.antunes.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('JUEL PRUDENCIO BORGES', '2014-07-05', '2014-03-22', 0, 1, 'juel.prudencio.borges@gmail.com', 'juel.prudencio.borges');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('CLAUDIO BARBOSA DOS SANTOS', '2014-07-03', '2014-01-29', 1, 1, 'claudio.barbosa.dos.santos@gmail.com', 'claudio.barbosa.dos.santos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('DIAMANTINA DA SILVA SOARES', '2014-07-10', '2014-05-20', 0, 0, 'diamantina.da.silva.soares@fb.com', 'diamantina.da.silva.soares');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('RUBENSMORBECK LEITE', '2014-07-10', '2014-02-21', 1, 1, 'rubensmorbeck.leite@gmail.com', 'rubensmorbeck.leite');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ALICE DE SOUZA MIRANDA', '2014-07-10', '2014-01-23', 1, 0, 'alice.de.souza.miranda@hotmail.com', 'alice.de.souza.miranda');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('CLAUDIO BARBOSA DOS SANTOS', '2014-07-01', '2014-06-08', 1, 1, 'claudio.barbosa.dos.santos@gmail.com', 'claudio.barbosa.dos.santos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARIA LOURENCO ARISTIDES', '2014-07-09', '2014-03-23', 1, 0, 'maria.lourenco.aristides@fb.com', 'maria.lourenco.aristides');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ELOIR CARLOS FIRMINO', '2014-07-04', '2014-01-20', 0, 0, 'eloir.carlos.firmino@hotmail.com', 'eloir.carlos.firmino');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('AUGUSTA ALVES DOS SANTOS', '2014-07-13', '2014-04-05', 0, 0, 'augusta.alves.dos.santos@fb.com', 'augusta.alves.dos.santos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('DORILDA ALVES DE CARVALHO', '2014-07-05', '2014-03-10', 1, 0, 'dorilda.alves.de.carvalho@fb.com', 'dorilda.alves.de.carvalho');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('BENILDE PERES DE CAMPOS', '2014-07-02', '2014-06-01', 1, 1, 'benilde.peres.de.campos@hotmail.com', 'benilde.peres.de.campos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('CELIA CRISTINA PEREIRA PINTO DOS SANTOS', '2014-07-03', '2014-05-24', 1, 0, 'celia.cristina.pereira.pinto.dos.santos@hotmail.com', 'celia.cristina.pereira.pinto.dos.santos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('DAVINA PEREIRA DE SALES', '2014-07-12', '2014-05-09', 0, 1, 'davina.pereira.de.sales@hotmail.com', 'davina.pereira.de.sales');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('CLEUSA FERREIRA MACIEL', '2014-07-04', '2014-04-16', 0, 1, 'cleusa.ferreira.maciel@hotmail.com', 'cleusa.ferreira.maciel');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ROSILENE ALMEIDA DA SILVA', '2014-07-07', '2014-03-25', 0, 0, 'rosilene.almeida.da.silva@gmail.com', 'rosilene.almeida.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('EDIO JUSTO BORGES', '2014-07-08', '2014-03-17', 0, 1, 'edio.justo.borges@hotmail.com', 'edio.justo.borges');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('EUSTAQUIA PRIETO', '2014-07-10', '2014-03-09', 0, 0, 'eustaquia.prieto@hotmail.com', 'eustaquia.prieto');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('DAVINA PEREIRA DE SALES', '2014-07-01', '2014-03-07', 0, 1, 'davina.pereira.de.sales@hotmail.com', 'davina.pereira.de.sales');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('VALDOMIRO LEITE DE SA', '2014-07-08', '2014-03-28', 1, 0, 'valdomiro.leite.de.sa@hotmail.com', 'valdomiro.leite.de.sa');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('DAVINA PEREIRA DE SALES', '2014-07-05', '2014-02-05', 1, 0, 'davina.pereira.de.sales@gmail.com', 'davina.pereira.de.sales');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('SONIA MARIA MARTINEZ PENITENTE', '2014-07-13', '2014-04-18', 0, 1, 'sonia.maria.martinez.penitente@gmail.com', 'sonia.maria.martinez.penitente');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('BENILDE PERES DE CAMPOS', '2014-07-05', '2014-03-06', 1, 0, 'benilde.peres.de.campos@fb.com', 'benilde.peres.de.campos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ALICE APARECIDA DOS SANTOS', '2014-07-02', '2014-03-18', 1, 1, 'alice.aparecida.dos.santos@gmail.com', 'alice.aparecida.dos.santos');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ELOIR CARLOS FIRMINO', '2014-07-12', '2014-02-13', 0, 1, 'eloir.carlos.firmino@hotmail.com', 'eloir.carlos.firmino');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('PAULO TEIXEIRA DE ABREU', '2014-07-03', '2014-04-01', 0, 1, 'paulo.teixeira.de.abreu@gmail.com', 'paulo.teixeira.de.abreu');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('BENEDITA GAUDENCIO DA COSTA', '2014-07-03', '2014-01-21', 1, 1, 'benedita.gaudencio.da.costa@gmail.com', 'benedita.gaudencio.da.costa');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('LUZIA RODRIGUES DE OLIVEIRA', '2014-07-04', '2014-03-05', 0, 1, 'luzia.rodrigues.de.oliveira@fb.com', 'luzia.rodrigues.de.oliveira');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ANTONIA BORGES DA SILVA', '2014-07-02', '2014-01-14', 0, 1, 'antonia.borges.da.silva@hotmail.com', 'antonia.borges.da.silva');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('MARGARETH VIRGINIA DE REZENDE MEHLMANN', '2014-07-08', '2014-05-27', 0, 0, 'margareth.virginia.de.rezende.mehlmann@gmail.com', 'margareth.virginia.de.rezende.mehlmann');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ELEONILDA DE LIMA RODRIGUES', '2014-07-06', '2014-03-05', 0, 0, 'eleonilda.de.lima.rodrigues@gmail.com', 'eleonilda.de.lima.rodrigues');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('SILVIA MENDES', '2014-07-06', '2014-05-31', 1, 0, 'silvia.mendes@hotmail.com', 'silvia.mendes');
INSERT INTO tbl_users (nome,data_alteracao,data_criacao,bloqueado,ativo,email,username) VALUES ('ROSIMEIRE GONCALVES LOPES RAMOS', '2014-07-04', '2014-05-29', 1, 0, 'rosimeire.goncalves.lopes.ramos@fb.com', 'rosimeire.goncalves.lopes.ramos');
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-18', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-29', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-28', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-05', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-07-13', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-05', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-07-04', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-11', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-08', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-25', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-11', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-18', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-14', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-12', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-02', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-07-01', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-30', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-22', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-07-06', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-07', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-01', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-03', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-07', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-27', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-13', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-05', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-19', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-17', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-01', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-19', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-12', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-27', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-07-07', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-22', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-05', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-29', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-09', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-04', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-13', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-21', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-07-10', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-11', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-15', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-01', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-29', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-16', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-31', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-08', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-22', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-17', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-11', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-10', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-08', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-16', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-13', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-19', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-08', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-07-08', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-19', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-08', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-06', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-17', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-21', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-12', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-03', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-22', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-13', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-19', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-07-01', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-04', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-05', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-26', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-06', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-09', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-28', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-07-05', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-09', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-14', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-09', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-09', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-06-25', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-06', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-07-07', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-14', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-01-01', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-31', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-28', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-05-01', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-28', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-14', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-28', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-07-09', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-20', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-14', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-03-27', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-08', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-13', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-28', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-04-23', 0, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
INSERT INTO tbl_serial (created,active,usuario_inclusao) VALUES ('2014-02-17', 1, (SELECT nome FROM tbl_users ORDER BY RANDOM() LIMIT 1));
